import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {AddressDeliveryVerifier,addressFingerprint,buildGeocodingAddress,loadAddressVerificationConfiguration,normalizeDeliveryRange,pointInPolygon} from '../src/orders/address-delivery-verification.mjs';
import {openOrderDatabase} from '../src/orders/database.mjs';
import {OrderRepository} from '../src/orders/order-repository.mjs';
import {OrderService} from '../src/orders/order-service.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';

const recipient={residence:'Fictional Villa',street:'Test Street 7',city:'Example City',province:'Example Emirate',country:'United Arab Emirates'};
const response=(payload,{ok=true}={})=>({ok,json:async()=>payload});
const googleResult=({lat=25,lng=55,partial=false,type='ROOFTOP',city='Example City'}={})=>({status:'OK',results:[{formatted_address:'Normalized fictional address',partial_match:partial,geometry:{location:{lat,lng},location_type:type},address_components:[{long_name:city,short_name:city,types:['locality']}]}]});
const verifier=(payload,options={})=>new AddressDeliveryVerifier({apiKey:'fictional-key',range:{cities:['Example City']},fetchImpl:async()=>response(payload),clock:()=>new Date('2026-09-07T10:00:00.000Z'),...options});

test('地址只拼接有值组件且不改变原文',()=>{assert.equal(buildGeocodingAddress({...recipient,residence:'',street:'  Test Street 7  '}),'Test Street 7, Example City, Example Emirate, United Arab Emirates');assert.equal(buildGeocodingAddress({}),'');});
test('可靠定位并匹配城市白名单时可配送',async()=>{const result=await verifier(googleResult()).verify(recipient);assert.equal(result.status,'deliverable');assert.equal(result.matchBasis,'city:example city');assert.equal(result.latitudeE7,250000000);});
test('可靠定位但城市不在白名单时超出范围',async()=>{const result=await verifier(googleResult({city:'Outside City'})).verify(recipient);assert.equal(result.status,'out_of_range');assert.equal(result.matchBasis,'city:none');});
test('禁配名单优先于配送城市库，且规范化时会移出重叠城市',async()=>{const range=normalizeDeliveryRange({cities:['Example City','Dubai'],blockedCities:[' example city ','Sharjah']});assert.deepEqual(range.cities,['dubai']);assert.deepEqual(range.blockedCities,['example city','sharjah']);const result=await verifier(googleResult(),{range:{cities:['Example City'],blockedCities:['Example City']}}).verify(recipient);assert.equal(result.status,'out_of_range');assert.equal(result.matchBasis,'blocked-city:example city');});
test('多边形优先于城市白名单判断',async()=>{const range={cities:['Outside City'],polygons:[{name:'fictional-zone',points:[[24,54],[24,56],[26,56],[26,54]]}]},inside=await verifier(googleResult(),{range}).verify(recipient),outside=await verifier(googleResult({lat:28,lng:58}),{range}).verify(recipient);assert.equal(inside.status,'deliverable');assert.equal(inside.matchBasis,'polygon:fictional-zone');assert.equal(outside.status,'out_of_range');assert.equal(pointInPolygon(25,55,range.polygons[0].points),true);});
test('无结果、多个结果、partial和低可信定位均不可用',async()=>{const cases=[{status:'ZERO_RESULTS',results:[]},{status:'OK',results:[googleResult().results[0],googleResult().results[0]]},googleResult({partial:true}),googleResult({type:'APPROXIMATE'})];for(const payload of cases)assert.equal((await verifier(payload).verify(recipient)).status,'unusable');});
test('API异常与超时作为可重试失败，不误判地址',async()=>{const network=new AddressDeliveryVerifier({apiKey:'fictional-key',range:{cities:['Example City']},fetchImpl:async()=>{throw new Error('network failed');}});assert.equal((await network.verify(recipient)).status,'failed');const timeout=new AddressDeliveryVerifier({apiKey:'fictional-key',range:{cities:['Example City']},timeoutMs:5,fetchImpl:async(_url,{signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'}))))});const timed=await timeout.verify(recipient);assert.equal(timed.status,'failed');assert.match(timed.reason,/超时/);});
test('缺API或缺派送范围均明确为未配置',async()=>{assert.equal((await new AddressDeliveryVerifier({range:{cities:['Example City']}}).verify(recipient)).status,'not_configured');assert.equal((await new AddressDeliveryVerifier({apiKey:'fictional-key'}).verify(recipient)).status,'not_configured');});
test('密钥和派送范围只从本机配置读取',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'address-config-'));try{await mkdir(path.join(directory,'orders'));await writeFile(path.join(directory,'orders','delivery-zones.json'),JSON.stringify({cities:['Example City'],polygons:[{name:'fictional-zone',points:[[24,54],[24,56],[26,56]]}]}));const configuration=await loadAddressVerificationConfiguration(directory,{environment:{KDOCS_GOOGLE_GEOCODING_API_KEY:'fictional-local-key'}});assert.equal(configuration.apiKey,'fictional-local-key');assert.deepEqual(configuration.range.cities,['example city']);assert.equal(configuration.range.polygons.length,1);assert.equal(configuration.rangeFile,path.join(directory,'orders','delivery-zones.json'));}finally{await rm(directory,{recursive:true,force:true});}});
test('不同地址具有不同指纹，客户地址和密钥不进入错误内容',async()=>{assert.notEqual(addressFingerprint(recipient),addressFingerprint({...recipient,street:'Another Street'}));const secret='secret-that-must-not-leak',result=await new AddressDeliveryVerifier({apiKey:secret,range:{cities:['Example City']},fetchImpl:async()=>{throw new Error(`failure ${secret} ${recipient.street}`);}}).verify(recipient);assert.equal(JSON.stringify(result).includes(secret),false);assert.equal(JSON.stringify(result).includes(recipient.street),false);});
test('已保存校验只适用于当前订单地址，修改地址后立即失效',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'address-verification-')),database=await openOrderDatabase({databaseFile:path.join(directory,'orders.sqlite')});try{const repository=new OrderRepository(database),service=new OrderService(repository),created=service.createOrder({source:'manual',shopplus_order_no:'ADDRESS-TEST-1',customer_first_name:'Fictional',customer_last_name:'Person',customer_phone:'+000000000',customer_email:'test@example.invalid',...recipient,items:[{sku_code:'KY02',product_name_snapshot:'Fictional Product',quantity:1,unit_list_price:'100',unit_actual_price:'100',unit_cost_snapshot:'20'}]}),app=new OrderAppService({database,userDataPath:directory,addressVerifier:verifier(googleResult())});let detail=await app.verifyAddress({orderId:created.id});assert.equal(detail.addressVerification.status,'deliverable');app.updateRecipient({orderId:created.id,field:'street',value:'Changed Fictional Street',reason:'fictional correction'});detail=app.detail({id:created.id});assert.equal(detail.addressVerification.status,'not_configured');assert.equal(database.prepare('SELECT count(*) count FROM order_delivery_verifications').get().count,0);}finally{database.close();await rm(directory,{recursive:true,force:true});}});
