import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {migrateOrderDatabase} from '../src/orders/database.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';
import {WhatsAppWebClient} from '../src/orders/whatsapp-web-client.mjs';
const account='15550000001',target='15550000002',accountId='wa-phone:'+account,chatId='wa-phone:'+target;
const until=async f=>{for(let n=0;n<200;n++){if(await f())return;await new Promise(r=>setTimeout(r,5));}throw Error('condition timed out');};

test('changed customer phone only warns; explicitly linked live messages and drafts continue unchanged',async t=>{
 const f=await setup(t);f.emit(f.make('before-phone-edit'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);
 f.app.assistant.workspace.save({...f.app.assistant.workspace.state({orderId:f.one.id}),patch:{draft:'Human draft must survive phone edit'}});
 f.db.prepare('UPDATE orders SET customer_phone=?,country=? WHERE id=?').run('5550000002','United States',f.one.id);assert.equal(f.app.assistant.online.state({orderId:f.one.id}).enabled,true);
 f.db.prepare('UPDATE orders SET customer_phone=? WHERE id=?').run('+15550009999',f.one.id);assert.equal(f.app.assistant.online.state({orderId:f.one.id}).enabled,true);assert.equal(f.app.assistant.status({orderId:f.one.id}).phoneCheck.matches,false);
 f.emit(f.make('linked-chat-during-advisory'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===2);assert.equal(f.app.assistant.workspace.state({orderId:f.one.id}).values.draft,'Human draft must survive phone edit');assert.equal(f.app.assistant.online.linkPending({orderId:f.one.id,bindingRevision:1,confirmed:true}).linked,0);
 await f.app.assistant.online.targets();assert.equal(f.chat.targets.length,1);f.db.prepare('UPDATE orders SET customer_phone=? WHERE id=?').run('+'+target,f.one.id);await f.app.assistant.online.targets();assert.equal(f.chat.targets.length,1);f.emit(f.make('after-phone-corrected'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===3);
});
async function setup(t){const dir=await mkdtemp(path.join(os.tmpdir(),'wweb-live-fictional-')),db=new DatabaseSync(':memory:');migrateOrderDatabase(db);let messages=[],mediaFailure=false,releaseMedia=null,fetchFailure=false,initializations=0;const clients=[];
 const make=(id,body='Fictional <script> & 中文',type='chat',remote=target+'@c.us')=>({id:{_serialized:'false_'+remote+'_'+id,remote},timestamp:Math.floor(Date.parse('2026-09-18T01:00:01Z')/1000),body,type,fromMe:false,downloadMedia:async()=>{if(releaseMedia)await releaseMedia;if(mediaFailure)return undefined;return {mimetype:'image/png',data:'YQ=='};}});
 const chat=new WhatsAppWebClient({userDataPath:dir,reconnectDelays:[5,10],clientFactory:async()=>{const c=new EventEmitter();c.pupBrowser=new EventEmitter();c.info={wid:{_serialized:account+'@c.us'}};c.getNumberId=async n=>({_serialized:n+'@c.us'});c.getContactLidAndPhone=async ids=>ids.map(pn=>({pn,lid:'999999999999@lid'}));c.initialize=async()=>{initializations++;c.emit('authenticated');c.emit('ready');};c.destroy=async()=>{};c.getChatById=async id=>({id:{_serialized:id},fetchMessages:async({limit})=>{assert.ok(Number.isSafeInteger(limit)&&limit<=5000);if(fetchFailure)throw Error('fictional network failure');return messages.slice(-limit);}});c.sendMessage=c.getChats=()=>assert.fail('No sends or account-wide enumeration');clients.push(c);return c;}});
 const app=new OrderAppService({database:db,chatAdapter:chat,clock:()=>new Date('2026-09-18T02:00:00Z')}),one=app.drafts.create({requestId:'live-one'});app.assistant.online.start();await chat.open();await until(()=>chat.status().status==='online');
 const bind=async id=>{if(!app.detail({id}).customer.phone)db.prepare('UPDATE orders SET customer_phone=? WHERE id=?').run('+'+target,id);const c=await chat.inspect({targetPhone:target});return app.assistant.bind({orderId:id,accountId,chatId,scopeStart:'2026-09-18T00:00:00Z',endMode:'latest',candidateToken:c.token,confirmed:true});};await bind(one.id);await app.assistant.online.queue;await app.assistant.online.running;
 t.after(async()=>{await app.assistant.online.stop();await chat.close();db.close();await rm(dir,{recursive:true,force:true});});
 return {dir,db,app,chat,one,bind,make,clients,emit:m=>clients.at(-1).emit('message_create',m),setMessages:v=>messages=v,setMediaFailure:v=>mediaFailure=v,setMediaGate:v=>releaseMedia=v,setFetchFailure:v=>fetchFailure=v,get initializations(){return initializations;}};
}
test('live events receive both directions once, PN/LID aliases work, unknown chat bodies remain untouched',async t=>{const f=await setup(t);let touches=0;const foreign={id:{remote:'15550009999@c.us'},get body(){touches++;throw Error('foreign body');}};f.emit(foreign);f.emit(f.make('a'));f.emit(f.make('a'));const merchant={...f.make('b','Fictional outgoing'),fromMe:true,id:{_serialized:'true_'+target+'@c.us_b',remote:target+'@c.us'}};f.emit(merchant);f.emit(f.make('lid','Fictional LID','chat','999999999999@lid'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===3);assert.equal(touches,0);const rows=f.app.assistant.workspace.messages({orderId:f.one.id}).messages;assert.equal(rows[0].text,'Fictional <script> & 中文');assert.ok(rows.some(m=>m.direction==='merchant'));assert.equal(f.chat.status().provider,'whatsapp-web.js');assert.equal(f.chat.status().qr,null);assert.equal(f.app.assistant.online.state({orderId:f.one.id}).lastSuccessAt,'2026-09-18T02:00:00.000Z');});
test('same customer two orders remain ambiguous, explicit linking affects only chosen order and preserves drafts',async t=>{const f=await setup(t),two=f.app.drafts.create({requestId:'live-two'});await f.bind(two.id);await f.app.assistant.online.queue;for(const [id,draft] of [[f.one.id,'One human draft'],[two.id,'Two human draft']])f.app.assistant.workspace.save({...f.app.assistant.workspace.state({orderId:id}),patch:{draft}});f.emit(f.make('shared'));await until(()=>f.app.assistant.online.state({orderId:f.one.id}).pendingCount===1);assert.equal(f.app.assistant.status({orderId:f.one.id}).messageCount,0);f.app.assistant.online.linkPending({orderId:two.id,bindingRevision:1,confirmed:true});assert.equal(f.app.assistant.status({orderId:two.id}).messageCount,1);assert.equal(f.app.assistant.status({orderId:f.one.id}).messageCount,0);for(const [id,draft] of [[f.one.id,'One human draft'],[two.id,'Two human draft']])assert.equal(f.app.assistant.workspace.state({orderId:id}).values.draft,draft);assert.equal(f.app.detail({id:two.id}).customer.phone,'+'+target);});
test('failed image is saved without blocking text; manual retry updates the same message and order revision',async t=>{const f=await setup(t),image=f.make('picture','', 'image');f.setMessages([image]);f.setMediaFailure(true);f.emit(image);f.emit(f.make('after-image','Text after image'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===2);await f.chat.queue;const before=f.app.assistant.row(f.one.id).read_revision;assert.equal(f.app.assistant.workspace.messages({orderId:f.one.id}).messages.find(m=>m.id===image.id._serialized).media[0].status,'unavailable');f.setMediaFailure(false);assert.deepEqual(await f.app.assistant.online.retryMedia({orderId:f.one.id,bindingRevision:1,messageId:image.id._serialized}),{ok:true});const rows=f.app.assistant.workspace.messages({orderId:f.one.id}).messages;assert.equal(rows.length,2);assert.equal(rows.find(m=>m.id===image.id._serialized).media[0].status,'cached');assert.ok(f.app.assistant.row(f.one.id).read_revision>before);});
test('disable or rebind while attachment is in flight cannot save stale results',async t=>{const f=await setup(t);let release;f.setMediaGate(new Promise(r=>release=r));f.emit(f.make('slow','', 'image'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);f.app.assistant.online.configure({orderId:f.one.id,revision:0,enabled:false});await f.app.assistant.online.queue;release();await new Promise(r=>setTimeout(r,20));assert.equal(f.app.assistant.workspace.messages({orderId:f.one.id}).messages[0].media[0].status,'unavailable');f.emit(f.make('disabled'));await f.chat.queue;await f.app.assistant.online.queue;assert.equal(f.app.assistant.status({orderId:f.one.id}).messageCount,1);assert.throws(()=>f.app.assistant.online.linkPending({orderId:f.one.id,bindingRevision:0,confirmed:true}));});
test('restart resumes local session, temporary disconnect reconnects and supplements without touching drafts',async t=>{const f=await setup(t);f.emit(f.make('anchor'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);f.setMessages([f.make('anchor'),f.make('offline')]);const w=f.app.assistant.workspace.state({orderId:f.one.id});f.app.assistant.workspace.save({...w,patch:{draft:'Keep while offline'}});f.clients.at(-1).emit('disconnected','TIMEOUT');await until(()=>f.initializations===2&&f.chat.status().status==='online');await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===2);assert.equal(f.app.assistant.online.state({orderId:f.one.id}).gap,false);assert.equal(f.app.assistant.workspace.state({orderId:f.one.id}).values.draft,'Keep while offline');assert.deepEqual(JSON.parse(await readFile(f.chat.marker,'utf8')),{enabled:true});await f.chat.close();await f.chat.resume();await until(()=>f.initializations===3&&f.chat.status().status==='online');});
test('failed or empty recovery marks every same-customer order without dropping saved events, then clears only with an anchor',async t=>{const f=await setup(t),good=f.make('good');f.emit(good);await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);f.setMessages([good]);await f.app.assistant.online.tick();assert.equal(f.app.assistant.online.state({orderId:f.one.id}).gap,false);const two=f.app.drafts.create({requestId:'gap-live-two'});await f.bind(two.id);await until(()=>!f.app.assistant.online.running&&!f.app.assistant.online.recoverRequested);f.setFetchFailure(true);await f.app.assistant.online.tick();for(const orderId of [f.one.id,two.id]){assert.equal(f.app.assistant.online.state({orderId}).gap,true);assert.equal(f.app.assistant.history.state({orderId}).progress.complete,false);}assert.equal(f.app.assistant.status({orderId:f.one.id}).messageCount,1);assert.equal(f.app.assistant.status({orderId:two.id}).messageCount,0);f.setFetchFailure(false);f.setMessages([]);await f.app.assistant.online.tick();for(const orderId of [f.one.id,two.id])assert.equal(f.app.assistant.online.state({orderId}).gap,true);f.setMessages([good]);await f.app.assistant.online.tick();for(const orderId of [f.one.id,two.id])assert.equal(f.app.assistant.online.state({orderId}).gap,false);});
test('edit events invalidate AI context without changing source body or human draft',async t=>{const f=await setup(t),m=f.make('original');f.emit(m);await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);f.app.assistant.workspace.save({...f.app.assistant.workspace.state({orderId:f.one.id}),patch:{draft:'Human untouched'}});f.clients.at(-1).emit('message_edit',m);await until(()=>Boolean(f.app.assistant.row(f.one.id).read_issue));assert.match(f.app.assistant.row(f.one.id).read_issue,/编辑或撤回/);assert.equal(f.app.assistant.workspace.messages({orderId:f.one.id}).messages[0].text,m.body);assert.equal(f.app.assistant.workspace.state({orderId:f.one.id}).values.draft,'Human untouched');});
test('missing Chrome and unconfirmed or wrong-account target produce explicit errors without deleting sessions',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'wweb-missing-chrome-'));t.after(()=>rm(dir,{recursive:true,force:true}));const c=new WhatsAppWebClient({userDataPath:dir,chromePath:path.join(dir,'not-installed')});await assert.rejects(c.open(),/Google Chrome/);assert.equal(c.status().status,'dependency-missing');const f=await setup(t);await assert.rejects(f.chat.resolve({accountId:'other',chatId,binding:{accountId:'other',chatId}}));f.chat.restriction={accountPhone:account,targetPhone:target};await assert.rejects(f.chat.inspect({targetPhone:'15550000003'}),/授权验证范围/);});
test('platform may return LID for a phone query: only a verified PN/LID correspondence is accepted',async t=>{const f=await setup(t);f.clients.at(-1).getNumberId=async()=>({_serialized:'999999999999@lid',server:'lid'});const c=await f.chat.inspect({targetPhone:target});assert.equal(c.nativeRemote,'999999999999@lid');assert.equal(c.chatId,chatId);f.clients.at(-1).getNumberId=async()=>({_serialized:'888888888888@lid',server:'lid'});await assert.rejects(f.chat.inspect({targetPhone:target}),/核对/);});
test('PN/LID namespace change retains the old native record, reply reference and deduplicated recovery anchor',async t=>{const f=await setup(t),pn=f.make('same-native');f.emit(pn);await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);f.app.assistant.workspace.save({...f.app.assistant.workspace.state({orderId:f.one.id}),patch:{replyMessageId:pn.id._serialized,draft:'Keep reference'}});f.emit(f.make('same-native',pn.body,'chat','999999999999@lid'));await f.chat.queue;await f.app.assistant.online.queue;assert.equal(f.app.assistant.status({orderId:f.one.id}).messageCount,1);assert.equal(f.app.assistant.history.state({orderId:f.one.id}).count,1);assert.equal(f.app.assistant.workspace.state({orderId:f.one.id}).values.replyMessageId,pn.id._serialized);f.setMessages([f.make('same-native',pn.body,'chat','999999999999@lid')]);await f.app.assistant.online.tick();assert.equal(f.app.assistant.online.state({orderId:f.one.id}).gap,false);});
test('restored aliases cannot authorize another phone; paused automatic sync still permits an explicit image retry',async t=>{const f=await setup(t);const b=f.app.assistant.row(f.one.id),binding=JSON.parse(b.browser_binding);f.db.prepare('UPDATE order_assistant SET browser_binding=? WHERE order_id=?').run(JSON.stringify({...binding,aliases:[target+'@c.us','15550009999@c.us'],nativeRemote:'15550009999@c.us'}),f.one.id);await f.app.assistant.online.targets();let reads=0;f.emit({id:{remote:'15550009999@c.us'},get body(){reads++;throw Error('unauthorized body');}});const image=f.make('paused-retry','', 'image');f.setMessages([image]);f.setMediaFailure(true);f.emit(image);await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);assert.equal(reads,0);f.app.assistant.online.configure({orderId:f.one.id,revision:0,enabled:false});await f.app.assistant.online.queue;f.setMediaFailure(false);assert.deepEqual(await f.app.assistant.online.retryMedia({orderId:f.one.id,bindingRevision:1,messageId:image.id._serialized}),{ok:true});assert.equal(f.app.assistant.workspace.messages({orderId:f.one.id}).messages[0].media[0].status,'cached');assert.equal(f.app.assistant.online.state({orderId:f.one.id}).enabled,false);});

test('native network state pauses status and reconnect recovery runs; browser exit recreates retained session',async t=>{const f=await setup(t);f.emit(f.make('native-anchor'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);f.setMessages([f.make('native-anchor'),f.make('native-gap')]);f.clients.at(-1).emit('change_state','TIMEOUT');assert.equal(f.chat.status().status,'reconnecting');f.clients.at(-1).emit('change_state','CONNECTED');await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===2);assert.equal(f.chat.status().status,'online');f.clients.at(-1).pupBrowser.emit('disconnected');await until(()=>f.initializations===2&&f.chat.status().status==='online');assert.equal(await f.chat.canResume(),true);});

test('new browser generation cannot read or assign events before current account identity is verified',async t=>{const f=await setup(t);let touched=0;const m={...f.make('early'),get body(){touched++;throw Error('unverified generation body');}};f.chat.readyGeneration=0;f.emit(m);await f.chat.queue;await f.app.assistant.online.queue;assert.equal(touched,0);assert.equal(f.app.assistant.status({orderId:f.one.id}).messageCount,0);f.chat.readyGeneration=f.chat.generation;f.emit(f.make('verified'));await until(()=>f.app.assistant.status({orderId:f.one.id}).messageCount===1);});

test('exit cleanup signals only owned browser processes and is removed on normal close',async t=>{const f=await setup(t),signals=[];f.clients.at(-1).pupBrowser.process=()=>({kill:signal=>signals.push(signal)});f.chat.exitHook();assert.deepEqual(signals,['SIGTERM']);await f.chat.close();assert.equal(process.listeners('exit').includes(f.chat.exitHook),false);f.chat.exitHook();assert.deepEqual(signals,['SIGTERM']);});

test('initialization completing after close is destroyed again and cannot publish ready state',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'live-late-init-'));let release,destroyed=0;const gate=new Promise(r=>release=r),client=new EventEmitter();client.initialize=()=>gate;client.destroy=async()=>{destroyed++;};const chat=new WhatsAppWebClient({userDataPath:dir,clientFactory:async()=>client});t.after(()=>rm(dir,{recursive:true,force:true}));await chat.open();await until(()=>chat.client===client);const pending=chat.connecting;await chat.close();release();await pending;assert.equal(destroyed,2);assert.notEqual(chat.status().status,'online');assert.equal(chat.ownedClients.size,0);});

test('late initialization rejection after close also cleans up its owned browser',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'live-late-reject-'));let reject,destroyed=0;const gate=new Promise((_,r)=>reject=r),client=new EventEmitter();client.initialize=()=>gate;client.destroy=async()=>{destroyed++;};const chat=new WhatsAppWebClient({userDataPath:dir,clientFactory:async()=>client});t.after(()=>rm(dir,{recursive:true,force:true}));await chat.open();await until(()=>chat.client===client);const pending=chat.connecting;await chat.close();reject(Error('fictional late failure'));await pending;assert.equal(destroyed,2);assert.equal(chat.ownedClients.size,0);});
