import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {structuredMessage} from '../src/orders/whatsapp-structured-browser.mjs';

test('Electron preserves waiting records, previews cached attachments, recovers text on manual refresh and restarts with independent replies',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'structured-ui-fictional-')),data=path.join(dir,'data'),file=path.join(dir,'fixture.json'),out=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||'artifacts/assistant-structured-8.18/source');
 const identity={accountId:'fictional-account',chatId:'fictional-chat'},native=(suffix,type,text='')=>structuredMessage({id:'false_971500000001@c.us_'+suffix,direction:'customer',sentAt:'2026-09-13T08:00:09.000Z',type,text},identity);
 const waiting=native('waiting','ciphertext'),recovered=native('waiting','chat','Fictional recovered <b>plain text</b> & address'),image={...native('image','image'),metadata:{...native('image','image').metadata,media:[{type:'image',status:'cached',source:'attachment',dataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAABkCAIAAACO1KzYAAABVElEQVR4nO3aQQ2AMBQFwbpCHSZxgAMcgAXSAwnbSf592uz1jfO6p2/bj+njfuOO1T68mitw3BU47gocdwWOuwLHXYHjrsBxV+C4K3DcFTjuChx3BY67AsddgeOuwHFX4LgrcNwVOO6OPz6a+/4EjrsCx12B467AcVfguCtw3BU47gocdwWOuwLHXYHjrsBxV+C4K3DcFTjuChx3BY67AsddgeOu0V3cFTjuChx3BY67AsddgeOuwHFX4LgrcNwVOO4KHHcFjrsCx12B467AcVfguCtw3BU47gocdwWOu0Z3cVfguCtw3BU47gocdwWOuwLHXYHjrsBxV+C4K3DcFTjuChx3BY67AsddgeOuwHFX4LgrcNwVOO4a3cVdgeOuwHFX4LgrcNwVOO4KHHcFjrsCx12B467AcVfguCtw3BU47gocdwWOuwLHXYHjrsBxV+C4+wD2R4dq/0g24wAAAABJRU5ErkJggg=='}]}};
 let app,page;const errors=[];
 const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});
 const launch=async()=>{const exe=process.env.KDOCS_TEST_EXECUTABLE;app=await electron.launch({executablePath:exe||electronPath,args:[...(exe?[]:['.']),`--orders-test-user-data=${data}`,`--orders-test-assistant=${file}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});page=await app.firstWindow();page.setDefaultTimeout(20000);page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.getByRole('button',{name:'订单管理',exact:true}).click();};
 const open=async n=>{if(await page.getByRole('button',{name:'返回订单列表',exact:true}).isVisible())await page.getByRole('button',{name:'返回订单列表',exact:true}).click();else await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'草稿 #'+n}).click();if(!await page.locator('.order-assistant').count())await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();};
 try{
  await mkdir(out,{recursive:true});await writeFile(file,JSON.stringify({fictional:true,...identity,messages:[],historyRounds:[[[waiting,image]],[[recovered,image]]],extraction:{fields:{},items:[]}}));await launch();const one=await call('createDraft',{requestId:'structured-ui-one'}),two=await call('createDraft',{requestId:'structured-ui-two'});await open(1);
  await page.getByLabel('英文草稿 · 可编辑').fill('Human reply for first order');await page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');
  await page.getByLabel('聊天关联',{exact:true}).click();const pop=page.getByRole('group',{name:'关联本单聊天',exact:true});await pop.getByLabel('账号标识',{exact:true}).fill(identity.accountId);await pop.getByLabel('稳定聊天标识',{exact:true}).fill(identity.chatId);await pop.getByLabel('本单开始时间',{exact:true}).fill('2026-09-12T00:00');await pop.getByLabel('本单结束时间',{exact:true}).fill('2026-09-14T00:00');await pop.getByRole('button',{name:'确认关联此聊天',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'已保存客户聊天 2 条'}).waitFor();
  await page.locator('.assistant-message-body').filter({hasText:'[等待 WhatsApp 解密此消息]'}).waitFor();assert.equal((await call('assistantHistory',{orderId:one.id})).count,2);assert.match(await page.locator('.assistant-binding-summary').textContent(),/内容待核对/);assert.doesNotMatch(await page.locator('.assistant-binding-summary').textContent(),/更新失败/);
  await page.getByRole('button',{name:'查看聊天图片',exact:true}).click();await page.locator('.assistant-image-overlay').getByText('已缓存此聊天的图片附件。',{exact:true}).waitFor();assert.equal(await page.locator('.assistant-image-overlay img').evaluate(e=>e.complete&&e.naturalWidth===160),true);await page.screenshot({path:path.join(out,'structured-image-preview.png')});await page.keyboard.press('Escape');await page.locator('.assistant-image-overlay').waitFor({state:'detached'});
  await open(2);await page.getByLabel('英文草稿 · 可编辑').fill('Human reply for second order');await page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');await open(1);await page.getByRole('button',{name:'刷新聊天',exact:true}).click();await page.locator('.assistant-message-body').filter({hasText:recovered.text}).waitFor();assert.equal(await page.locator('.assistant-message-body b').count(),0);assert.equal((await call('assistantHistory',{orderId:one.id})).count,2);assert.equal((await call('assistantStatus',{orderId:two.id})).messageCount,0);assert.equal((await call('assistantWorkspace',{orderId:two.id})).values.draft,'Human reply for second order');
  for(const size of [[900,700],[1280,850],[1440,900]]){await app.evaluate(({BrowserWindow},v)=>BrowserWindow.getAllWindows()[0].setSize(...v),size);await page.locator('.assistant-message-body').filter({hasText:recovered.text}).scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,`structured-chat-${size[0]}x${size[1]}.png`)});}
  await page.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.locator('.assistant-message-body').filter({hasText:recovered.text}).waitFor();await app.close();app=null;await launch();await open(1);await page.locator('.assistant-message-body').filter({hasText:recovered.text}).waitFor();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Human reply for first order');await page.getByRole('button',{name:'查看聊天图片',exact:true}).click();await page.locator('.assistant-image-overlay').getByText('已缓存此聊天的图片附件。',{exact:true}).waitFor();await page.getByRole('button',{name:'关闭图片',exact:true}).click();const archived=(await call('assistantHistory',{orderId:one.id})).messages;assert.equal(archived.find(m=>m.id===waiting.id).incomplete,false);assert.equal(archived.find(m=>m.id===image.id).media[0].source,'attachment');await open(2);assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Human reply for second order');assert.deepEqual(errors,[]);
  await writeFile(path.join(out,'structured-ui-result.json'),JSON.stringify({result:'PASS-LOCAL',packaged:Boolean(process.env.KDOCS_TEST_EXECUTABLE),fixture:'fictional connector',waitingVisible:true,recoveryDeduplicated:true,plainTextEscaped:true,attachmentPreview:true,contentWarningSeparatedFromConnectionFailure:true,closeReopen:true,restartCache:true,independentReplies:true,sizes:['900×700','1280×850','1440×900'],realChatReads:0,realAIRequests:0,messagesSent:0},null,2));
 }catch(e){if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'structured-ui-failure.png')});throw e;}finally{await app?.close();await rm(dir,{recursive:true,force:true});}
});
