import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
const out=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||'artifacts/assistant-manual-8.16/source');
test('Electron first association reads history once, manual refresh gets new messages, reopening and restart stay idle with both replies isolated',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'assistant-manual-fictional-')),data=path.join(dir,'data'),file=path.join(dir,'fixture.json');let app,page;const errors=[];
 const old={id:'old',direction:'customer',sentAt:'2026-09-11T08:00:00Z',text:'Fictional old history'},current={id:'current',direction:'customer',sentAt:'2026-09-13T08:00:00Z',text:'Fictional current history'},next={id:'new',direction:'customer',sentAt:'2026-09-13T08:01:00Z',text:'Fictional new message only on manual refresh'};
 const fixture={fictional:true,accountId:'fictional-account',chatId:'fictional-chat',messages:[],historyRounds:[[[old],[current]],[[current,next]]],extraction:{fields:{},items:[]}};
 const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});
 async function launch(){const exe=process.env.KDOCS_TEST_EXECUTABLE;app=await electron.launch({executablePath:exe||electronPath,args:[...(exe?[]:['.']),`--orders-test-user-data=${data}`,`--orders-test-assistant=${file}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});page=await app.firstWindow();page.setDefaultTimeout(20000);page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.getByRole('button',{name:'订单管理',exact:true}).click();await page.evaluate(()=>{const native=window.setInterval;window.__messagePollTimers=[];window.setInterval=(fn,ms,...args)=>{if([3000,15000,30000].includes(ms))window.__messagePollTimers.push(ms);return native(fn,ms,...args);};});}
 async function open(n){if(await page.getByRole('button',{name:'返回订单列表',exact:true}).isVisible())await page.getByRole('button',{name:'返回订单列表',exact:true}).click();else await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'草稿 #'+n}).click();if(!await page.locator('.order-assistant').count())await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();}
 try{
  await mkdir(out,{recursive:true});await writeFile(file,JSON.stringify(fixture));await launch();const one=await call('createDraft',{requestId:'manual-native-one'});await open(1);
  await page.getByLabel('英文草稿 · 可编辑').fill('Human reply for first order');await page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');
  await page.getByLabel('聊天关联',{exact:true}).click();const pop=page.getByRole('group',{name:'关联本单聊天',exact:true});await pop.getByLabel('账号标识',{exact:true}).fill(fixture.accountId);await pop.getByLabel('稳定聊天标识',{exact:true}).fill(fixture.chatId);await pop.getByLabel('本单开始时间',{exact:true}).fill('2026-09-12T00:00');await pop.getByLabel('本单结束时间',{exact:true}).fill('2026-09-14T00:00');await pop.getByRole('button',{name:'确认关联此聊天',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'已保存客户聊天 2 条'}).waitFor();
  assert.equal((await call('assistantHistory',{orderId:one.id})).count,2);assert.equal((await call('assistantStatus',{orderId:one.id})).messageCount,1);assert.equal(await page.locator('[data-message-id="old"] .assistant-history-scope').count(),1);assert.equal(await page.locator('[data-message-id="old"]').getByRole('button',{name:'回复这条',exact:true}).count(),0);
  await page.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();await page.waitForTimeout(1200);assert.equal((await call('assistantHistory',{orderId:one.id})).count,2);assert.equal((await call('assistantOnlineSync',{orderId:one.id})).enabled,false);assert.deepEqual(await page.evaluate(()=>window.__messagePollTimers),[]);
  const two=await call('createDraft',{requestId:'manual-native-two'});await open(2);await page.getByLabel('英文草稿 · 可编辑').fill('Human reply for second order');await page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');await open(1);assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Human reply for first order');
  for(const size of [[900,700],[1280,850],[1440,900]]){await app.evaluate(({BrowserWindow},v)=>BrowserWindow.getAllWindows()[0].setSize(...v),size);await page.locator('.order-assistant').getByRole('button',{name:'助手设置',exact:true}).click();await page.getByLabel('关闭助手设置',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'开启本单在线同步',exact:true}).count(),0);await page.screenshot({path:path.join(out,`manual-settings-${size[0]}x${size[1]}.png`)});await page.getByLabel('关闭助手设置',{exact:true}).click();}
  await page.getByRole('button',{name:'刷新聊天',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'已保存客户聊天 3 条'}).waitFor();assert.equal((await call('assistantStatus',{orderId:one.id})).messageCount,2);assert.equal((await call('assistantStatus',{orderId:two.id})).messageCount,0);assert.equal((await call('assistantWorkspace',{orderId:two.id})).values.draft,'Human reply for second order');assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Human reply for first order');
  await app.close();app=null;await launch();await open(1);await page.waitForTimeout(1200);assert.equal((await call('assistantHistory',{orderId:one.id})).count,3);assert.deepEqual(await page.evaluate(()=>window.__messagePollTimers),[]);assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Human reply for first order');assert.deepEqual(errors,[]);
  await writeFile(path.join(out,'manual-history-result.json'),JSON.stringify({result:'PASS-LOCAL',packaged:Boolean(process.env.KDOCS_TEST_EXECUTABLE),firstAssociationActualButton:true,initialHistoryRead:true,oldHistoryOutsideOrderEvidence:true,manualNewMessages:true,noPollingTimers:true,noOnlineEnableButton:true,closeReopenIdle:true,restartIdle:true,bothRepliesIsolated:true,sizes:['900×700','1280×850','1440×900'],realChatReads:0,realAIRequests:0,messagesSent:0},null,2));
 }catch(e){if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'manual-history-failure.png')});throw e;}finally{await app?.close();await rm(dir,{recursive:true,force:true});}
});

test('first association progress can be stopped from the actual UI, preserves the binding and waits for manual continuation',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'assistant-first-stop-fictional-')),file=path.join(dir,'fixture.json');let app,page;
 try{
  const old={id:'stop-old',direction:'customer',sentAt:'2026-09-11T08:00:00Z',text:'Fictional old before stop'},next={id:'stop-new',direction:'customer',sentAt:'2026-09-13T08:00:00Z',text:'Fictional current after manual continuation'};
  await writeFile(file,JSON.stringify({fictional:true,accountId:'fictional-account',chatId:'fictional-chat',messages:[],historyDelayMs:1500,historyRounds:[[[old],[next]],[[old,next]]],extraction:{fields:{},items:[]}}));
  const exe=process.env.KDOCS_TEST_EXECUTABLE;app=await electron.launch({executablePath:exe||electronPath,args:[...(exe?[]:['.']),`--orders-test-user-data=${path.join(dir,'data')}`,`--orders-test-assistant=${file}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('dialog',d=>d.accept());await page.route('https://**/*',r=>r.abort());
  const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});await page.getByRole('button',{name:'订单管理',exact:true}).click();const one=await call('createDraft',{requestId:'first-stop-one'});await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'草稿 #1'}).click();await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();await page.getByLabel('聊天关联',{exact:true}).click();const pop=page.getByRole('group',{name:'关联本单聊天',exact:true});await pop.getByLabel('账号标识',{exact:true}).fill('fictional-account');await pop.getByLabel('稳定聊天标识',{exact:true}).fill('fictional-chat');await pop.getByLabel('本单开始时间',{exact:true}).fill('2026-09-12T00:00');await pop.getByLabel('本单结束时间',{exact:true}).fill('2026-09-14T00:00');await pop.getByRole('button',{name:'确认关联此聊天',exact:true}).click();
  await page.getByRole('button',{name:'停止同步',exact:true}).click({timeout:5000});await page.waitForFunction(()=>!document.querySelector('.assistant-sync-cancel'));
  const state=await call('assistantHistory',{orderId:one.id});assert.equal(state.progress.status,'cancelled');assert.ok(state.count<2);assert.equal((await call('assistantStatus',{orderId:one.id})).chat_id,'fictional-chat');await page.waitForTimeout(1700);assert.equal((await call('assistantHistory',{orderId:one.id})).count,state.count);
  await page.getByRole('button',{name:'刷新聊天',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'已保存客户聊天 2 条'}).waitFor();assert.equal((await call('assistantStatus',{orderId:one.id})).messageCount,1);
  await mkdir(out,{recursive:true});await writeFile(path.join(out,'manual-first-stop-result.json'),JSON.stringify({result:'PASS-LOCAL',actualUIStop:true,bindingRetained:true,successfulBatchesRetained:true,noBackgroundRetry:true,manualContinuation:true,realChatReads:0,realAIRequests:0,messagesSent:0},null,2));
 }catch(e){if(page&&!page.isClosed()){await mkdir(out,{recursive:true});await page.screenshot({path:path.join(out,'manual-first-stop-failure.png')});}throw e;}finally{await app?.close();await rm(dir,{recursive:true,force:true});}
});
