import test from 'node:test';import assert from 'node:assert/strict';import {_electron as electron,chromium} from 'playwright-core';import electronPath from 'electron';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {readVisibleMessages} from '../src/orders/whatsapp-browser.mjs';
const out=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||'artifacts/assistant-mature-8.11');
const pixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jfQAAAABJRU5ErkJggg==';
test('Electron final assistant controls, autosize, reply selection, bilingual edits, approved examples, history import/search, media and restart',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'assistant-experience-fictional-')),data=path.join(dir,'data'),file=path.join(dir,'fixture.json');let app,page;const errors=[];
 const fixture={fictional:true,accountId:'fictional-account',chatId:'fictional-chat',messages:[{id:'fictional-customer',direction:'customer',sentAt:'2026-09-13T08:00:00Z',text:'Full name: Avery Fictional\nStreet: Fictional address <script>window.bad=true</script>',metadata:{media:[{type:'image',status:'cached',dataUrl:pixel}]}},{id:'fictional-merchant',direction:'merchant',sentAt:'2026-09-13T08:01:00Z',text:'Please confirm your shipping phone.'}],extraction:{fields:{},items:[]},ai:{delayMs:200}};
 const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});
 const launch=async()=>{const exe=process.env.KDOCS_TEST_EXECUTABLE;app=await electron.launch({executablePath:exe||electronPath,args:[...(exe?[]:['.']),`--orders-test-user-data=${data}`,`--orders-test-assistant=${file}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'订单管理',exact:true}).click();};
 const open=async()=>{await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'草稿 #1'}).click();if(!await page.locator('.order-assistant').count())await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();};const saved=()=>page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');
 try{await mkdir(out,{recursive:true});await writeFile(file,JSON.stringify(fixture));await launch();const one=await call('createDraft',{requestId:'fictional-complete-experience'});await call('bindChat',{orderId:one.id,accountId:fixture.accountId,chatId:fixture.chatId,scopeStart:'2026-09-12T00:00:00Z',scopeEnd:'2026-09-14T00:00:00Z',confirmed:true});await call('readChat',{orderId:one.id});await open();
  await page.getByRole('button',{name:'翻译',exact:true}).click();await page.locator('.assistant-message-translation').first().waitFor();assert.equal(await page.locator('.assistant-message-translation').first().textContent(),'模拟译文：'+fixture.messages[0].text);assert.equal(await page.evaluate(()=>window.bad),undefined);
  await page.locator('[data-message-id="fictional-customer"]').getByRole('button',{name:'回复这条',exact:true}).click();assert.equal(await page.locator('[data-message-id="fictional-customer"]').getAttribute('class').then(v=>v.includes('reply-selected')),true);assert.equal(await page.getByLabel('中文想说的话').evaluate(e=>document.activeElement===e),true);assert.match(await page.locator('.assistant-reply-reference').textContent(),/Avery Fictional/);
  await page.getByLabel('中文想说的话').fill('问客户具体的收货信息');await page.getByRole('button',{name:'按意图起草',exact:true}).click();await page.locator('.assistant-draft-chinese').filter({hasText:'请确认收货地址'}).waitFor();await saved();await page.getByRole('button',{name:'保存范例',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'已保存批准范例'}).waitFor();assert.equal((await call('assistantPolicy')).values.examples.length,1);
  await page.getByLabel('英文草稿 · 可编辑').fill('Human modified English, not a promise.');assert.match(await page.locator('.assistant-draft-chinese').textContent(),/待更新/);await page.getByRole('button',{name:'更新中文对照',exact:true}).click();await page.locator('.assistant-draft-chinese').filter({hasText:'Human modified English'}).waitFor();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Human modified English, not a promise.');await saved();
  await page.getByRole('button',{name:'查看聊天图片',exact:true}).click();await page.locator('.assistant-image-overlay img').waitFor();await page.getByRole('button',{name:'关闭图片',exact:true}).click();
  const transcript=path.join(dir,'fictional-chat.txt');await writeFile(transcript,'11/09/2026, 08:00 - Merchant: Earlier order history\n13/09/2026, 08:00 - Customer: Fictional imported question <script>window.bad=true</script>');await page.getByLabel('聊天关联',{exact:true}).click();await page.getByRole('button',{name:'查看聊天历史',exact:true}).click();const history=page.getByRole('dialog',{name:'客户聊天历史',exact:true});await history.locator('summary').click();await history.getByLabel('导出文件中的我方名称').fill('Merchant');await history.getByLabel('聊天TXT文件').setInputFiles(transcript);await history.getByRole('button',{name:'导入聊天文件',exact:true}).click();await history.locator('.assistant-action-feedback').filter({hasText:'文件记录已导入'}).waitFor();await history.getByLabel('搜索聊天历史').fill('Earlier');await history.getByRole('button',{name:'搜索',exact:true}).click();await history.locator('.assistant-message-body').filter({hasText:'Earlier order history'}).waitFor();assert.equal((await call('assistantStatus',{orderId:one.id})).messageCount,2);await page.screenshot({path:path.join(out,'history-import-search.png')});await history.getByRole('button',{name:'关闭',exact:true}).click();
  await page.locator('.order-assistant').getByRole('button',{name:'助手设置',exact:true}).click();await page.getByRole('button',{name:'流程与缓存设置',exact:true}).click();const policy=page.getByRole('dialog',{name:'流程与缓存设置',exact:true});await policy.getByLabel('步骤名称 1').fill('先核对需求');await policy.getByLabel('聊天译文缓存',{exact:true}).selectOption('90');await policy.getByRole('button',{name:'保存设置',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'流程与缓存设置已保存'}).waitFor();assert.equal((await call('assistantPolicy')).values.retentionDays,90);
  const heights=[];for(const [width,height] of [[900,700],[1280,850],[1440,900]]){await app.evaluate(({BrowserWindow},s)=>BrowserWindow.getAllWindows()[0].setSize(s.width,s.height),{width,height});await page.locator('.assistant-chat-card').scrollIntoViewIfNeeded();const controls=await page.locator('.assistant-toolbar').evaluate(e=>[...e.querySelectorAll('button')].map(n=>{const r=n.getBoundingClientRect();return {y:r.y,bottom:r.bottom,font:getComputedStyle(n).fontSize,right:r.right,left:r.left};}));assert.equal(controls.length,4);assert.ok(Math.max(...controls.map(r=>r.y))-Math.min(...controls.map(r=>r.y))<10,JSON.stringify(controls));assert.ok(controls.every(r=>r.font==='14px'),JSON.stringify(controls));for(let n=1;n<controls.length;n++)assert.ok(controls[n].left>=controls[n-1].right-1,JSON.stringify(controls));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
   const handle=page.getByRole('slider',{name:'聊天区高度'});await handle.focus();await handle.press('End');assert.equal(await page.locator('.assistant-chat-scroll').evaluate(e=>Math.round(e.getBoundingClientRect().height)),1600);await handle.press('Home');await handle.press('ArrowDown');assert.equal(await page.locator('.assistant-chat-scroll').evaluate(e=>Math.round(e.getBoundingClientRect().height)),280);await page.evaluate(()=>{const a=document.querySelector('.order-assistant');a.scrollTop=0;document.querySelector('.assistant-chat-card').scrollIntoView({block:'start'});});await page.waitForTimeout(120);await page.screenshot({path:path.join(out,`chat-${width}x${height}.png`)});
   const intent=page.getByLabel('中文想说的话'),english=page.getByLabel('英文草稿 · 可编辑');await intent.fill('短句');await english.fill('Short');await page.waitForTimeout(70);const short=await intent.evaluate(e=>e.offsetHeight);await intent.fill(Array.from({length:35},(_,n)=>`第${n+1}行：需要核对客户提供的完整资料。`).join('\n'));await english.fill(Array.from({length:30},(_,n)=>`Line ${n+1}: Fictional text with uncertain details, not a commitment.`).join('\n'));await page.waitForTimeout(100);const long=await intent.evaluate(e=>({height:e.offsetHeight,scroll:e.scrollHeight,client:e.clientHeight})),eng=await english.evaluate(e=>({height:e.offsetHeight,scroll:e.scrollHeight,client:e.clientHeight}));assert.ok(long.height>short+400,JSON.stringify({short,long}));assert.ok(long.scroll<=long.client+2,JSON.stringify(long));assert.ok(eng.scroll<=eng.client+2,JSON.stringify(eng));heights.push({width,short,long,english:eng});await intent.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`long-input-${width}x${height}.png`)});await intent.fill('重新缩短');await english.fill('Saved final English');await page.waitForTimeout(80);assert.ok(await intent.evaluate(e=>e.offsetHeight)<long.height);await page.getByRole('button',{name:'更新中文对照',exact:true}).click();await page.locator('.assistant-draft-chinese').filter({hasText:'Saved final English'}).waitFor();await saved();await page.waitForFunction(()=>!document.querySelector('[data-ai-purpose="translate-draft"]').disabled);await english.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`reply-${width}x${height}.png`)});
  }
  await app.close();app=null;await launch();await open();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Saved final English');assert.match(await page.locator('.assistant-draft-chinese').textContent(),/Saved final English/);assert.equal(await page.locator('.assistant-chat-scroll').evaluate(e=>Math.round(e.getBoundingClientRect().height)),280);assert.equal((await call('assistantPolicy')).values.retentionDays,90);assert.equal((await call('assistantPolicy')).values.examples.length,1);assert.equal((await call('assistantHistory',{orderId:one.id,query:'Earlier'})).messages.length,1);assert.deepEqual(errors,[]);await writeFile(path.join(out,'experience-result.json'),JSON.stringify({result:'PASS-LOCAL',packaged:Boolean(process.env.KDOCS_TEST_EXECUTABLE),controlsSameRow:true,font14:true,autosizeGrowShrinkResize:true,replySelectionFeedback:true,bilingualEditInvalidation:true,approvedExamples:true,historyImportSearch:true,historyDidNotBroadenOrder:true,mediaPreview:true,restart:true,realAIRequests:0,realChatReads:0,heights},null,2));
 }catch(e){if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'experience-failure.png')});throw e;}finally{await app?.close();await rm(dir,{recursive:true,force:true});}
});
test('actual browser DOM reads and persists image thumbnail without remote URLs and keeps 20-message verification limit',async()=>{const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();await page.setContent(`<main id="main"><div data-testid="conversation-panel-body"><div data-id="image-native"><i data-icon="tail-in"></i><div data-pre-plain-text="[16:00, 2026年9月13日] Fictional:"><span>Fictional caption</span><div data-testid="image-thumb"><img src="${pixel}"></div></div></div></div></main>`);await page.locator('img').evaluate(async i=>{await i.decode();});const scope={accountId:'fictional-account',chatId:'fictional-chat',from:'2026-09-13T08:00:00Z',to:'2026-09-13T08:01:00Z',timeZone:'Asia/Shanghai'};const messages=await readVisibleMessages(page,scope);assert.equal(messages[0].metadata.media[0].status,'cached');assert.match(messages[0].metadata.media[0].dataUrl,/^data:image\/jpeg;base64,/);assert.equal(messages[0].text,'Fictional caption');await mkdir(out,{recursive:true});await writeFile(path.join(out,'image-dom-result.json'),JSON.stringify({result:'PASS-LOCAL',realDOM:true,realWhatsApp:false,cachedThumbnail:true,originalFullImage:false,realChatReads:0},null,2));}finally{await browser.close();}});
