import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import path from 'node:path';import os from 'node:os';
const out=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||'artifacts/assistant-history-once-8.17/source');
test('Electron completed/current/next stages fold without losing current, separated settings and compact confirmation preserve failure input',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'history-once-ui-fictional-')),data=path.join(dir,'data'),file=path.join(dir,'fixture.json');let app,page,db;const errors=[];
 const fields={fullName:'Fictional Customer',phone:'+971500000000',email:'fictional@example.invalid',country:'United Arab Emirates',province:'Dubai',city:'Dubai',street:'Fictional Street 12',residence:'Room 34'};
 try{
  await mkdir(out,{recursive:true});await mkdir(path.join(data,'state'),{recursive:true});await writeFile(path.join(data,'state/baseline.json'),JSON.stringify({versionAt:'fictional',products:[['商品编号','来源商品名称','成本'],['KY02','Fictional Product','10']]}));await writeFile(file,JSON.stringify({fictional:true,accountId:'fictional-account',chatId:'fictional-chat',messages:[],extraction:{fields:{},items:[]}}));
  const exe=process.env.KDOCS_TEST_EXECUTABLE;app=await electron.launch({executablePath:exe||electronPath,args:[...(exe?[]:['.']),`--orders-test-user-data=${data}`,`--orders-test-assistant=${file}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('https://**/*',r=>r.abort());await page.getByRole('button',{name:'订单管理',exact:true}).click();
  const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});
  const one=await call('createDraft',{requestId:'once-ui-one'}),two=await call('createDraft',{requestId:'once-ui-two'});await call('saveDraft',{orderId:one.id,fields:{fullName:fields.fullName},items:[{sku:'KY02',quantity:2,price:'25',discount:'0'}]});
  const open=async n=>{if(await page.getByRole('button',{name:'返回订单列表',exact:true}).isVisible())await page.getByRole('button',{name:'返回订单列表',exact:true}).click();else await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'草稿 #'+n}).click();if(!await page.locator('.order-assistant').count())await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.locator('.assistant-stage-strip').waitFor();};await open(1);
  assert.equal(await page.locator('.assistant-stage-previous .assistant-stage-number').textContent(),'1');assert.equal(await page.locator('.assistant-stage-previous .assistant-stage-tick').textContent(),'✓');assert.equal(await page.locator('.assistant-stage-current .assistant-stage-number').textContent(),'2');assert.match(await page.locator('.assistant-stage-current').textContent(),/收货/);
  const sizes=[];for(const size of [[900,700],[1280,850],[1440,900]]){
   await app.evaluate(({BrowserWindow},v)=>BrowserWindow.getAllWindows()[0].setSize(...v),size);await page.evaluate(()=>{const a=document.querySelector('.order-assistant');a.scrollTop=0;if(innerWidth>=1200)window.scrollTo(0,0);else document.querySelector('.assistant-heading').scrollIntoView({block:'center'});});await page.waitForTimeout(120);if(size[0]>=1200)assert.equal(await page.locator('.assistant-heading').evaluate(e=>e.getBoundingClientRect().top>=document.querySelector('.order-detail-page-head').getBoundingClientRect().bottom),true);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('.assistant-stage-previous').isVisible(),true);assert.equal(await page.locator('.assistant-stage-current').isVisible(),true);assert.equal(await page.locator('.assistant-stage-current').evaluate(e=>getComputedStyle(e).fontSize),'14px');
   await page.screenshot({path:path.join(out,`once-stage-${size[0]}x${size[1]}.png`)});
   await page.locator('.order-assistant').getByRole('button',{name:'助手设置',exact:true}).click();const shortcuts=page.locator('.assistant-settings-shortcuts');await shortcuts.getByRole('button',{name:'打开完整设置',exact:true}).waitFor();const geometry=await shortcuts.evaluate(e=>[...e.querySelectorAll('button')].map(n=>{const r=n.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom};}));assert.equal(geometry.length,2);assert.ok(geometry[1].top>=geometry[0].bottom+10||geometry[1].left>=geometry[0].right+10,JSON.stringify(geometry));await page.screenshot({path:path.join(out,`once-settings-${size[0]}x${size[1]}.png`)});await shortcuts.getByRole('button',{name:'打开完整设置',exact:true}).scrollIntoViewIfNeeded();assert.equal(await shortcuts.getByRole('button',{name:'打开完整设置',exact:true}).evaluate(e=>{const r=e.getBoundingClientRect(),p=e.closest('.assistant-settings-popover').getBoundingClientRect();return r.top>=p.top&&r.bottom<=Math.min(p.bottom,innerHeight);}),true);await page.screenshot({path:path.join(out,`once-settings-actions-${size[0]}x${size[1]}.png`)});await page.getByLabel('关闭助手设置',{exact:true}).click();sizes.push({size,settingsGeometry:geometry});
  }
  await page.locator('.assistant-stage-strip').evaluate(e=>{e.style.flex='none';e.style.width='270px';});await page.waitForFunction(()=>document.querySelector('.assistant-stage-more')?.hidden===false);assert.equal(await page.locator('.assistant-stage-next').isVisible(),false);assert.equal(await page.locator('.assistant-stage-current').isVisible(),true);await page.getByRole('button',{name:'查看后续阶段',exact:true}).click();await page.getByRole('dialog',{name:'订单阶段与提醒',exact:true}).locator('[data-stage-id]').first().waitFor();assert.equal(await page.getByRole('dialog',{name:'订单阶段与提醒',exact:true}).locator('[data-stage-id]').count(),8);await page.getByRole('dialog',{name:'订单阶段与提醒',exact:true}).getByRole('button',{name:'关闭',exact:true}).click();await page.locator('.assistant-stage-strip').evaluate(e=>{e.style.flex='';e.style.width='';});
  const row=page.locator('.customer-confirmation-row');assert.match(await row.textContent(),/客户确认\s*待确认/);assert.equal(await row.locator('input,textarea').count(),0);await row.getByRole('button',{name:'登记确认',exact:true}).click();let dialog=page.getByRole('dialog',{name:'登记客户确认',exact:true});await dialog.getByRole('button',{name:'确认并进入履约',exact:true}).click();await dialog.getByRole('alert').filter({hasText:'依据'}).waitFor();await dialog.getByLabel('客户确认依据').fill('Fictional accepted order');await dialog.getByRole('button',{name:'确认并进入履约',exact:true}).click();await dialog.getByRole('alert').filter({hasText:'缺少'}).waitFor();assert.equal(await dialog.getByLabel('客户确认依据').inputValue(),'Fictional accepted order');await page.screenshot({path:path.join(out,'once-confirmation-dialog.png')});await dialog.getByLabel('关闭客户确认').click();assert.equal((await call('detail',one.id)).confirmed,false);
  await call('saveDraft',{orderId:one.id,fields,items:[{sku:'KY02',quantity:2,price:'25',discount:'0'}]});await open(1);assert.equal(await page.locator('.assistant-stage-previous .assistant-stage-number').textContent(),'2');assert.equal(await page.locator('.assistant-stage-current .assistant-stage-number').textContent(),'3');
  await page.locator('.customer-confirmation-row').getByRole('button',{name:'登记确认',exact:true}).click();dialog=page.getByRole('dialog',{name:'登记客户确认',exact:true});await dialog.getByLabel('客户确认方式').selectOption('其他方式');await dialog.getByLabel('客户确认依据').fill('Fictional phone confirmation: two KY02 at AED 25 and full delivery details');db=new DatabaseSync(path.join(data,'orders/orders.sqlite'));db.exec("CREATE TRIGGER once_confirm_fail BEFORE UPDATE ON orders BEGIN SELECT RAISE(ABORT,'fictional confirmation failure'); END");await dialog.getByRole('button',{name:'确认并进入履约',exact:true}).click();await dialog.getByRole('alert').filter({hasText:'fictional confirmation failure'}).waitFor();assert.match(await dialog.getByLabel('客户确认依据').inputValue(),/Fictional phone confirmation/);assert.equal((await call('detail',one.id)).confirmed,false);db.exec('DROP TRIGGER once_confirm_fail');db.close();db=null;await dialog.getByRole('button',{name:'确认并进入履约',exact:true}).click();await page.getByRole('heading',{name:'聊单 #1',exact:true}).waitFor();await page.screenshot({path:path.join(out,'once-confirmation-saved.png')});assert.match((await call('detail',one.id)).confirmationNote,/其他方式/);assert.equal((await call('detail',two.id)).confirmed,false);await page.locator('.customer-confirmation-row').getByRole('button',{name:'查看依据',exact:true}).click();await page.getByRole('dialog',{name:'客户确认依据',exact:true}).getByText(/Fictional phone confirmation/).waitFor();await page.keyboard.press('Escape');await page.locator('.customer-confirmation-dialog').waitFor({state:'detached'});assert.equal(await page.locator('.customer-confirmation-dialog').count(),0);assert.deepEqual(errors,[]);
  await writeFile(path.join(out,'history-once-ui-result.json'),JSON.stringify({result:'PASS-LOCAL',packaged:Boolean(exe),sizes,completedTick:true,currentAlwaysVisible:true,nextFoldAndFullDialog:true,progressionNumbers:true,font14:true,settingsGapAtLeast10:true,compactConfirmation:true,invalidAndFailedConfirmationPreservesInput:true,explicitSource:true,secondOrderUnchanged:true,realChatReads:0,realAIRequests:0,messagesSent:0},null,2));
 }catch(e){if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'history-once-ui-failure.png')});throw e;}finally{db?.close();await app?.close();await rm(dir,{recursive:true,force:true});}
});
