import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import {mkdtemp,writeFile,mkdir,rm} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';
import {DatabaseSync} from 'node:sqlite';
const out=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||'artifacts/assistant-s23-8.10');
test('Electron AI bubbles/cache, selected reply, proactive/translation/regeneration, edit/switch races and restart',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'assistant-ai-fictional-')),data=path.join(dir,'data'),fixtureFile=path.join(dir,'fixture.json');let app,page;const errors=[];
 const fixture={fictional:true,accountId:'fictional-account',chatId:'fictional-chat',messages:[{id:'question',direction:'customer',sentAt:'2026-09-12T08:00:00.000Z',text:'AED 25 each? Not accepted. <script>window.bad=true</script>'},{id:'answer',direction:'merchant',sentAt:'2026-09-12T08:01:00.000Z',text:'Please confirm your address.'}],extraction:{fields:{},items:[]},ai:{delayMs:500}};
 const launch=async()=>{const exe=process.env.KDOCS_TEST_EXECUTABLE;app=await electron.launch({executablePath:exe||electronPath,args:[...(exe?[]:['.']),`--orders-test-user-data=${data}`,`--orders-test-assistant=${fixtureFile}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'订单管理',exact:true}).click();};
 const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});
 const open=async label=>{if(await page.getByRole('button',{name:'返回订单列表'}).isVisible())await page.getByRole('button',{name:'返回订单列表'}).click();else await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:label}).click();if(!await page.locator('.order-assistant').count())await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();};
 const saved=()=>page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');
 try{
  await mkdir(out,{recursive:true});await writeFile(fixtureFile,JSON.stringify(fixture));await launch();const one=await call('createDraft',{requestId:'fictional-ai-ui-one'}),two=await call('createDraft',{requestId:'fictional-ai-ui-two'});
  await call('bindChat',{orderId:one.id,...fixture,scopeStart:'2026-09-12T00:00:00.000Z',scopeEnd:'2026-09-13T00:00:00.000Z',confirmed:true});await call('readChat',{orderId:one.id});await open('草稿 #1');
  await page.getByLabel('显示中文译文').check();assert.equal(await page.locator('.assistant-message-translation').count(),0);await page.getByRole('button',{name:'翻译',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'本次生成 2 条'}).waitFor();assert.equal(await page.locator('.assistant-message-body').first().textContent(),fixture.messages[0].text);assert.equal(await page.evaluate(()=>window.bad),undefined);assert.equal(await page.locator('.assistant-message-translation').count(),2);
  await page.getByRole('button',{name:'翻译',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'本次生成 0 条'}).waitFor();
  await page.locator('[data-message-id="question"]').getByRole('button').click();await page.getByRole('button',{name:'AI 拟回复',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="英文草稿 · 可编辑"]').value.startsWith('Fictional AI draft'));
  await page.getByRole('button',{name:'主动联系',exact:true}).click();await page.getByLabel('中文想说的话').fill('仅核对地址');await page.getByRole('button',{name:'转成英文',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'AI 草稿请核对'}).waitFor();await saved();
  await page.getByRole('button',{name:'重新生成',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').fill('Human edit while response waits');await page.locator('.assistant-action-feedback').filter({hasText:/已丢弃|变化/}).waitFor();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Human edit while response waits');await saved();
  await page.getByRole('button',{name:'重新生成',exact:true}).click();await page.getByRole('button',{name:'返回订单列表'}).click();await open('草稿 #2');await page.getByLabel('英文草稿 · 可编辑').fill('Second order only');await page.waitForTimeout(650);assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Second order only');await saved();assert.equal((await call('assistantWorkspace',{orderId:one.id})).values.draft,'Human edit while response waits');
  await open('草稿 #1');await page.getByRole('button',{name:'重新生成',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'AI 草稿请核对'}).waitFor();await saved();
  // Same binding confirmation must keep messages, translations and revision.
  const before=await call('assistantStatus',{orderId:one.id});await call('bindChat',{orderId:one.id,...fixture,scopeStart:'2026-09-12T00:00:00.000Z',scopeEnd:'2026-09-13T00:00:00.000Z',confirmed:true});const after=await call('assistantStatus',{orderId:one.id});assert.equal(after.binding_revision,before.binding_revision);assert.equal(after.messageCount,2);
  for(const [width,height] of [[900,700],[1280,850],[1440,900]]){await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(size.width,size.height),{width,height});await page.locator('.assistant-chat-card').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const controls=await page.locator('.assistant-view-controls').evaluate(e=>[...e.children].map(n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));for(let n=1;n<controls.length;n++)assert.ok(controls[n].x>=controls[n-1].right-1||controls[n].y>=controls[n-1].bottom-1,JSON.stringify(controls));await page.screenshot({path:path.join(out,`ai-chat-${width}x${height}.png`)});await page.getByLabel('英文草稿 · 可编辑').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`ai-reply-${width}x${height}.png`)});}
  await app.close();app=null;await launch();await open('草稿 #1');await page.locator('.assistant-message-translation').filter({hasText:'模拟译文'}).first().waitFor();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Fictional AI draft. Please confirm the address.');await open('草稿 #2');assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Second order only');assert.deepEqual(errors,[]);
  const deferred=await page.evaluate(async id=>{
   const {AssistantPanel}=await import('./assistant-panel.js');const api=async(method,payload)=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;};const detail=await api('detail',id);let count=0,started,release;const reached=new Promise(r=>started=r),gate=new Promise(r=>release=r);
   const panel=new AssistantPanel(async(method,payload)=>{const value=await api(method,payload);if(method==='assistantWorkspace'){if(++count===1)return {...value,capabilities:{translation:false,replyGeneration:false},capabilityNote:'checking local configuration'};if(count===2){started();await gate;}}return value;},()=>{});panel.open=true;panel.attach(detail,document.getElementById('order-detail-content'));await reached;const initiallyDisabled=panel.aside.querySelector('[data-ai-purpose="reply"]').disabled;const input=panel.aside.querySelector('[aria-label="中文想说的话"]');input.value='Human input during local configuration wait';input.dispatchEvent(new Event('input',{bubbles:true}));await panel.flushCurrent();release();
   for(let n=0;n<300&&panel.aside.querySelector('[data-ai-purpose="reply"]').disabled;n++)await new Promise(requestAnimationFrame);
   const enabled=!panel.aside.querySelector('[data-ai-purpose="reply"]').disabled,preserved=panel.session.values.intent===input.value&&input.value==='Human input during local configuration wait';await panel.flushCurrent();return {initiallyDisabled,enabled,preserved};
  },two.id);assert.deepEqual(deferred,{initiallyDisabled:true,enabled:true,preserved:true});
  await writeFile(path.join(out,'ai-ui-result.json'),JSON.stringify({result:'PASS-LOCAL',packaged:Boolean(process.env.KDOCS_TEST_EXECUTABLE),gateway:'fictional simulation; no API or keychain validation',realAIRequests:0,realChatReads:0,translationCache:true,originalEscaped:true,editableGeneratedDraft:true,editAndSwitchRaces:true,repeatBinding:true,restart:true,deferredConfiguration:true,sizes:['900x700','1280x850','1440x900']},null,2));
 }catch(e){if(page&&!page.isClosed()){await page.screenshot({path:path.join(out,'ai-ui-failure.png')});console.error(await page.locator('.assistant-action-feedback').textContent());}throw e;}finally{await app?.close();await rm(dir,{recursive:true,force:true});}
});

test('Electron literal translations ignore history gaps; phone mismatch only shows an inline advisory, caches/drafts survive restart',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'assistant-fix-822-')),data=path.join(dir,'data'),file=path.join(dir,'fixture.json');let app,page;
 const fixture={fictional:true,accountId:'fictional-account',chatId:'wa-phone:971500000002',messages:[{id:'english',direction:'customer',sentAt:'2026-09-12T08:00:00.000Z',text:'Please confirm the address.'},{id:'quoted',direction:'merchant',sentAt:'2026-09-12T08:01:00.000Z',text:'Discount is ten percent.'},{id:'arabic',direction:'customer',sentAt:'2026-09-12T08:02:00.000Z',text:'هل يمكنك تأكيد العنوان؟'},{id:'french',direction:'customer',sentAt:'2026-09-12T08:03:00.000Z',text:'Merci de confirmer votre adresse.'},{id:'picture',direction:'customer',sentAt:'2026-09-12T08:04:00.000Z',text:'[图片]'}],extraction:{fields:{},items:[]},ai:{delayMs:50}};
 const launch=async()=>{const exe=process.env.KDOCS_TEST_EXECUTABLE;app=await electron.launch({executablePath:exe||electronPath,args:[...(exe?[]:['.']),'--orders-test-user-data='+data,'--orders-test-assistant='+file],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});page=await app.firstWindow();page.setDefaultTimeout(15000);await page.getByRole('button',{name:'订单管理',exact:true}).click();page.on('dialog',d=>d.accept());};
 const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});
 const open=async()=>{const back=page.getByRole('button',{name:'返回订单列表',exact:true});if(await back.isVisible())await back.click();else await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'草稿 #1'}).click();if(!await page.locator('.order-assistant').count())await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();};
 const editDb=fn=>{const db=new DatabaseSync(path.join(data,'orders','orders.sqlite'),{timeout:5000});try{fn(db);}finally{db.close();}};
 try{
  await mkdir(out,{recursive:true});await writeFile(file,JSON.stringify(fixture));await launch();const one=await call('createDraft',{requestId:'fix-822-ui-one'});await call('saveDraft',{orderId:one.id,fields:{phone:'0500000002',country:'United Arab Emirates'}});
  await call('bindChat',{orderId:one.id,...fixture,scopeStart:'2026-09-12T00:00:00Z',scopeEnd:'2026-09-13T00:00:00Z',confirmed:true});await call('readChat',{orderId:one.id});
  editDb(db=>{db.prepare('UPDATE order_assistant SET read_issue=? WHERE order_id=?').run('本单含未完整同步的非文字、引用或编辑内容；请在 WhatsApp 核对',one.id);db.prepare('UPDATE order_chat_messages SET metadata=? WHERE order_id=? AND message_id=?').run(JSON.stringify({incomplete:true,messageType:'chat'}),one.id,'quoted');db.prepare('INSERT INTO assistant_chat_archive VALUES(?,?,?,?,?,?,?)').run(fixture.accountId,fixture.chatId,'old','customer','2026-09-01T08:00:00.000Z','Older English message','{}');});
  editDb(db=>db.prepare('UPDATE orders SET customer_phone=? WHERE id=?').run('0500000999',one.id));
  await open();assert.equal(await page.getByRole('button',{name:'翻译',exact:true}).isDisabled(),false);await page.getByRole('button',{name:'翻译',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'本次生成 5 条'}).waitFor();assert.equal(await page.locator('.assistant-message-translation').count(),5);assert.match(await page.locator('.assistant-action-feedback').textContent(),/跳过 1 条/);assert.equal(await page.locator('[data-message-id="picture"] .assistant-message-translation').count(),0);assert.equal(await page.locator('[data-message-id="quoted"] .assistant-message-translation').count(),1);assert.equal(await page.locator('[data-message-id="old"] .assistant-message-translation').count(),1);
  await page.getByRole('button',{name:'翻译',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'本次生成 0 条'}).waitFor();await page.getByLabel('英文草稿 · 可编辑').fill('Human English draft preserved');await page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');
  const advisory=page.getByRole('button',{name:'核对客户电话',exact:true});await advisory.waitFor();assert.equal(await advisory.evaluate(e=>getComputedStyle(e).color),'rgb(180, 35, 24)');assert.equal(await page.locator('.assistant-phone-warning').count(),0);assert.equal(await page.getByRole('button',{name:'翻译',exact:true}).isDisabled(),false);assert.equal(await page.getByRole('button',{name:'复制并去 WhatsApp',exact:true}).isDisabled(),false);
  const number=await page.locator('.assistant-person strong').boundingBox(),icon=await advisory.boundingBox();assert.ok(Math.abs(number.y+number.height/2-icon.y-icon.height/2)<3);assert.ok(icon.x>=number.x+number.width);const height=await page.locator('.assistant-identity').evaluate(e=>e.offsetHeight);await advisory.hover();await page.getByRole('tooltip').waitFor();assert.match(await page.getByRole('tooltip').textContent(),/0500000999/);assert.match(await page.getByRole('tooltip').textContent(),/971500000002/);assert.equal(await page.locator('.assistant-identity').evaluate(e=>e.offsetHeight),height);await page.screenshot({path:path.join(out,'phone-advisory.png')});await page.keyboard.press('Escape');assert.equal(await page.getByRole('tooltip').count(),0);
  const state=await call('assistantWorkspace',{orderId:one.id});const copied=await call('copyAssistantReply',{orderId:one.id,revision:state.revision,bindingRevision:state.bindingRevision});assert.equal(copied.copied,true);await app.close();app=null;await launch();await open();await page.getByRole('button',{name:'核对客户电话',exact:true}).waitFor();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Human English draft preserved');
  editDb(db=>db.prepare('UPDATE orders SET customer_phone=? WHERE id=?').run('+971 50 000 0002',one.id));await open();assert.equal(await page.locator('.assistant-phone-hint').count(),0);assert.equal((await call('assistantStatus',{orderId:one.id})).phoneCheck.matches,true);await page.locator('.assistant-message-translation').first().waitFor();assert.equal(await page.locator('.assistant-message-translation').count(),5);await page.screenshot({path:path.join(out,'literal-translation-restored.png')});
  await writeFile(path.join(out,'phone-translation-result.json'),JSON.stringify({result:'PASS-FICTIONAL',packaged:Boolean(process.env.KDOCS_TEST_EXECUTABLE),nationalPhoneMatched:true,phoneMismatchAdvisoryOnly:true,translationAndCopyAvailableDuringMismatch:true,arabicAndFrenchBodiesTranslated:true,inlineIconWithoutExtraRow:true,literalTranslationDespiteIncompleteHistory:true,quotedBodyTranslated:true,visibleOlderMessageTranslated:true,placeholderSkipped:true,cacheReused:true,restartDraftCachePreserved:true,realAIRequests:0,realMessagesSent:0,formalOrdersModified:0},null,2));
 }finally{await app?.close();await rm(dir,{recursive:true,force:true});}
});
