import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {openOrderDatabase,orderDatabasePath} from '../src/orders/database.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';
const evidence=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||'artifacts/assistant-ui-s1');
test('S1 Electron messages, pagination, isolated replies, clipboard, failure recovery, concurrency and quit/restart',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'assistant-s1-fictional-')),data=path.join(dir,'data'),settingsFile=path.join(dir,'settings.json');let app,db,page;const errors=[];
 const launch=async()=>{app=await electron.launch({executablePath:process.env.KDOCS_TEST_EXECUTABLE||electronPath,args:[...(process.env.KDOCS_TEST_EXECUTABLE?[]:['.']),`--orders-test-user-data=${data}`,`--orders-test-settings=${settingsFile}`],env:{...process.env,NODE_ENV:'test'},cwd:path.resolve('.')});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{console.log('dialog',d.type());void d.accept();});await page.getByRole('button',{name:'订单管理',exact:true}).click();};
 const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});
 const open=async label=>{await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:label}).click();if(!await page.locator('.order-assistant').count())await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();};
 const saved=async()=>{await page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');};
 try{
  await mkdir(evidence,{recursive:true});await writeFile(settingsFile,JSON.stringify({key:'fictional-s1-key-only'}));db=await openOrderDatabase({userDataPath:data});const service=new OrderAppService({database:db}),one=service.drafts.create({requestId:'s1-fictional-one'}),two=service.drafts.create({requestId:'s1-fictional-two'});
  for(const order of [one,two])db.prepare('UPDATE order_assistant SET binding_revision=1,account_id=?,chat_id=?,scope_start=?,scope_end=? WHERE order_id=?').run('fictional','fictional','2026-09-12T00:00:00Z','2026-09-13T00:00:00Z',order.id);
  for(let n=0;n<165;n++)db.prepare('INSERT INTO order_chat_messages(order_id,binding_revision,message_id,direction,sent_at,body) VALUES(?,1,?,?,?,?)').run(one.id,'m'+String(n).padStart(3,'0'),n%2?'merchant':'customer','2026-09-12T08:00:00Z',n===164?'<script>window.bad=true</script> & "Fictional"':'Fictional message '+n);
  db.close();db=null;await launch();await open('草稿 #1');
  assert.equal(await page.locator('.assistant-message').count(),80);assert.equal(await page.locator('.assistant-message-body').last().textContent(),'<script>window.bad=true</script> & "Fictional"');assert.equal(await page.evaluate(()=>window.bad),undefined);
  await page.getByRole('button',{name:'加载较早的聊天记录'}).click();await page.waitForFunction(()=>document.querySelectorAll('.assistant-message').length===160);await page.getByRole('button',{name:'加载较早的聊天记录'}).click();await page.waitForFunction(()=>document.querySelectorAll('.assistant-message').length===165);assert.equal(new Set(await page.locator('.assistant-message').evaluateAll(es=>es.map(e=>e.dataset.messageId))).size,165);
  await page.locator('[data-message-id="m000"]').getByRole('button').click();assert.match(await page.locator('.assistant-reply-reference').textContent(),/Fictional message 0/);
  await page.getByLabel('中文想说的话').fill('请核对虚构地址');await page.getByLabel('英文草稿 · 可编辑').fill('Please confirm the fictional address.');await page.getByLabel('回复语气').selectOption('brief');await page.getByRole('button',{name:'主动联系',exact:true}).click();await saved();
  const first=await call('assistantWorkspace',{orderId:one.id});assert.equal(first.values.replyMessageId,'m000');assert.equal(first.values.mode,'proactive');assert.equal(first.values.tone,'brief');
  const originalClipboard=await app.evaluate(({clipboard})=>clipboard.readText());await page.getByRole('button',{name:'复制并去 WhatsApp'}).click();await page.getByText('英文草稿已复制（测试环境未打开外部聊天）。',{exact:true}).waitFor();assert.equal(await app.evaluate(({clipboard})=>clipboard.readText()),first.values.draft);await app.evaluate(({clipboard},text)=>clipboard.writeText(text),originalClipboard);
  for(const [width,height] of [[900,700],[1280,850],[1440,900]]){
   await app.evaluate(({BrowserWindow},{width,height})=>BrowserWindow.getAllWindows()[0].setSize(width,height),{width,height});await page.locator('.assistant-chat-card').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
   const geometry=await page.evaluate(()=>{const b=label=>[...document.querySelectorAll('button,summary')].find(e=>e.textContent===label)?.getBoundingClientRect(),refresh=b('刷新聊天'),binding=b('聊天关联');return {refresh:refresh.x,binding:binding.x};});assert.ok(geometry.refresh<geometry.binding);
   await page.screenshot({path:path.join(evidence,`s1-chat-${width}x${height}.png`)});await page.locator('.order-assistant').getByRole('button',{name:'助手设置',exact:true}).click();await page.getByLabel('API 密钥',{exact:true}).waitFor();
   const sizes=await page.getByLabel('API 密钥',{exact:true}).evaluate(e=>({key:e.getBoundingClientRect().width,model:document.querySelector('[aria-label="模型"]').getBoundingClientRect().width}));assert.equal(sizes.key,sizes.model);await page.screenshot({path:path.join(evidence,`s1-settings-${width}x${height}.png`)});await page.locator('.order-assistant').getByRole('button',{name:'助手设置',exact:true}).click();
   await page.getByText('聊天关联',{exact:true}).click();await page.screenshot({path:path.join(evidence,`s1-binding-${width}x${height}.png`)});await page.getByText('聊天关联',{exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(evidence,`s1-reply-${width}x${height}.png`)});
  }

  await app.evaluate(({clipboard})=>{globalThis.restoreClipboardWrite=clipboard.writeText;clipboard.writeText=()=>{throw Error('Fictional clipboard failure');};});await page.getByRole('button',{name:'复制并去 WhatsApp'}).click();await page.locator('.assistant-action-feedback').filter({hasText:'复制失败'}).waitFor();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),first.values.draft);await app.evaluate(({clipboard})=>{clipboard.writeText=globalThis.restoreClipboardWrite;delete globalThis.restoreClipboardWrite;});
  await page.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),first.values.draft);
  await page.getByRole('button',{name:'返回订单列表'}).click();await open('草稿 #2');assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'');assert.equal(await page.locator('.assistant-message').count(),0);await page.getByLabel('英文草稿 · 可编辑').fill('Second order only');await page.getByRole('button',{name:'返回订单列表'}).click();await open('草稿 #1');assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),first.values.draft);
  db=new DatabaseSync(orderDatabasePath(data));db.exec("CREATE TRIGGER fail_reply BEFORE UPDATE ON order_assistant_workspace BEGIN SELECT RAISE(ABORT,'Fictional save failure'); END");await page.getByLabel('英文草稿 · 可编辑').fill('Keep after failure');await page.locator('.assistant-save-state.is-error').waitFor();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Keep after failure');assert.equal((await call('assistantWorkspace',{orderId:one.id})).values.draft,first.values.draft);
  await app.evaluate(({app})=>{setTimeout(()=>app.quit(),0);});await page.waitForTimeout(200);assert.equal((await call('assistantWorkspace',{orderId:one.id})).values.draft,first.values.draft);assert.equal(page.isClosed(),false);
  await page.getByRole('button',{name:'返回订单列表'}).click();assert.equal(await page.getByLabel('英文草稿 · 可编辑').isVisible(),true);db.exec('DROP TRIGGER fail_reply');db.close();db=null;await page.getByRole('button',{name:'重试保存'}).click();await saved();assert.equal((await call('assistantWorkspace',{orderId:one.id})).values.draft,'Keep after failure');
  const concurrent=await call('assistantWorkspace',{orderId:one.id});await call('saveAssistantWorkspace',{...concurrent,patch:{draft:'Other window wins'}});await page.getByLabel('英文草稿 · 可编辑').fill('Unsaved conflicting text');await page.locator('.assistant-save-state.is-error').waitFor();assert.equal((await call('assistantWorkspace',{orderId:one.id})).values.draft,'Other window wins');assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Unsaved conflicting text');await page.getByRole('button',{name:'重新载入保存版本'}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="英文草稿 · 可编辑"]').value==='Other window wins');
  await page.getByLabel('英文草稿 · 可编辑').fill('Saved immediately before quit');await app.evaluate(({app})=>{setTimeout(()=>app.quit(),0);});await app.waitForEvent('close');app=null;await launch();await open('草稿 #1');assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Saved immediately before quit');assert.equal((await call('assistantWorkspace',{orderId:two.id})).values.draft,'Second order only');assert.deepEqual(errors,[]);
  const race=await page.evaluate(async({one,two})=>{
   const {AssistantPanel}=await import('./assistant-panel.js');
   const api=async(method,payload)=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;};
   const a=await api('detail',one),b=await api('detail',two),root=document.getElementById('order-detail-content');let releaseOld,oldStarted;
   const started=new Promise(r=>oldStarted=r),oldGate=new Promise(r=>releaseOld=r);
   const panel=new AssistantPanel(async(method,payload)=>{const result=await api(method,payload);if(method==='assistantStatus'&&payload.orderId===one){oldStarted();await oldGate;}return result;},()=>{});panel.open=true;panel.attach(a,root);await started;panel.attach(b,root);
   const ready=async(predicate)=>{for(let n=0;n<300;n++){if(predicate())return;await new Promise(requestAnimationFrame);}throw Error('Race UI did not settle');};
   await ready(()=>panel.session?.orderId===two);releaseOld();await new Promise(r=>setTimeout(r,50));const isolated=panel.session.orderId===two&&panel.messages.length===0;
   let releaseSnapshot,snapshotStarted;const reached=new Promise(r=>snapshotStarted=r),gate=new Promise(r=>releaseSnapshot=r);panel.call=async(method,payload)=>{const result=await api(method,payload);if(method==='assistantWorkspace'){snapshotStarted();await gate;}return result;};
   const reload=panel.load(b,panel.aside,panel.epoch);await reached;panel.changed(panel.session,'intent','New input while old snapshot waits');await panel.flush(panel.session);releaseSnapshot();await reload;
   const preserved=panel.aside.querySelector('[aria-label="中文想说的话"]').value==='New input while old snapshot waits';await panel.flushCurrent();return {isolated,preserved};
  },{one:one.id,two:two.id});assert.deepEqual(race,{isolated:true,preserved:true});
  await writeFile(path.join(evidence,'workspace-result.json'),JSON.stringify({result:'PASS-LOCAL',realAIRequests:0,realChatReads:0,messages:165,sizes:['900x700','1280x850','1440x900'],clipboard:true,saveFailure:true,concurrentRevision:true,quitRestart:true},null,2));
 }catch(error){console.error(error);if(page&&!page.isClosed())console.error(await page.locator('.assistant-action-feedback').textContent());if(page&&!page.isClosed())await page.screenshot({path:path.join(evidence,'workspace-failure.png')});throw error;}finally{db?.close();if(app){let timer;try{await Promise.race([app.close(),new Promise(resolve=>{timer=setTimeout(()=>{app.process().kill('SIGKILL');resolve();},5000);})]);}finally{clearTimeout(timer);}}await rm(dir,{recursive:true,force:true});}
});
