import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {migrateOrderDatabase} from '../src/orders/database.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';
function setup(t){const database=new DatabaseSync(':memory:');migrateOrderDatabase(database);t.after(()=>database.close());const app=new OrderAppService({database,clock:()=>new Date('2026-09-17T08:00:00Z'),chatAdapter:{mode:'browser',resolve:async p=>({accountId:p.accountId,chatId:p.chatId,binding:p})},extractor:async()=>assert.fail('Incomplete history must not request AI'),aiGateway:{configuration:async()=>assert.fail('Incomplete history must not resolve model configuration'),complete:async()=>assert.fail('Incomplete history must not request AI')}});const order=app.drafts.create({requestId:'once-one'});return {app,database,order,bind:()=>app.assistant.bind({orderId:order.id,accountId:'fictional-account',chatId:'fictional-chat',scopeStart:'2026-09-12T00:00:00Z',scopeEnd:'2026-09-14T00:00:00Z',confirmed:true})};}
const message=(id,sentAt='2026-09-13T08:00:00Z',incomplete=false)=>({id,direction:'customer',sentAt,text:incomplete?'[非文字消息，请在 WhatsApp 查看]':'Fictional text '+id,metadata:{incomplete,note:incomplete?'附件未同步':null}});
test('incomplete media is visible in history and blocks order extraction instead of inventing complete context',async t=>{const f=setup(t);await f.bind();const b=f.app.assistant.row(f.order.id);f.app.assistant.history.save(b,[message('media',undefined,true),message('adjacent')],{complete:false});f.app.assistant.history.apply({orderId:f.order.id});const state=f.app.assistant.history.state({orderId:f.order.id});assert.equal(state.count,2);assert.equal(state.messages.find(m=>m.id==='media').incomplete,true);assert.equal(state.messages.find(m=>m.id==='media').syncNote,'附件未同步');assert.equal(f.app.assistant.workspace.messages({orderId:f.order.id,includeHistory:true}).messages.find(m=>m.id==='media').incomplete,true);await assert.rejects(f.app.assistant.extract({orderId:f.order.id}),/未完整同步/);const w=f.app.assistant.workspace.state({orderId:f.order.id});const saved=f.app.assistant.workspace.save({...w,patch:{intent:'Fictional ask for address',mode:'proactive'}});await assert.rejects(f.app.assistant.ai.generate({orderId:f.order.id,revision:saved.revision,bindingRevision:saved.bindingRevision,purpose:'compose'}),/未完整同步/);assert.equal(f.app.assistant.status({orderId:f.order.id}).messageCount,2);});
test('old incomplete attachments remain history only and do not block complete order-range text',async t=>{const f=setup(t);await f.bind();f.app.assistant.history.save(f.app.assistant.row(f.order.id),[message('old-media','2026-09-11T08:00:00Z',true),message('current')],{complete:false});f.app.assistant.history.apply({orderId:f.order.id});assert.equal(f.app.assistant.status({orderId:f.order.id}).read_issue,null);assert.equal(f.app.assistant.status({orderId:f.order.id}).messageCount,1);assert.equal(f.app.assistant.history.state({orderId:f.order.id}).count,2);});
test('a newly detected incomplete flag upgrades existing history and linked context without disappearing on a later reread',async t=>{const f=setup(t);await f.bind();const b=f.app.assistant.row(f.order.id),m=message('existing');f.app.assistant.history.save(b,[m],{complete:false});f.app.assistant.history.apply({orderId:f.order.id});f.database.prepare('UPDATE order_assistant SET result=? WHERE order_id=?').run(JSON.stringify({fields:{},items:[],conflicts:[]}),f.order.id);const prior=f.app.assistant.row(f.order.id).read_revision;f.app.assistant.history.save(b,[{...m,metadata:{incomplete:true,note:'引用附件待核对'}}],{complete:false});f.app.assistant.history.apply({orderId:f.order.id});assert.match(f.app.assistant.status({orderId:f.order.id}).read_issue,/未完整同步/);assert.equal(f.app.assistant.row(f.order.id).read_revision,prior+1);assert.equal(f.app.assistant.row(f.order.id).result,null);assert.equal(f.app.assistant.workspace.messages({orderId:f.order.id,includeHistory:true}).messages[0].incomplete,true);f.app.assistant.history.save(b,[m],{complete:false});assert.equal(f.app.assistant.history.state({orderId:f.order.id}).messages[0].incomplete,true);});
test('a large one-operation read retains batches on disk failure and a manual retry deduplicates all 250 records',async t=>{const f=setup(t);await f.bind();f.database.exec("CREATE TRIGGER history_once_fail BEFORE INSERT ON assistant_chat_archive WHEN NEW.message_id='row-100' BEGIN SELECT RAISE(ABORT,'fictional archive disk failure'); END");f.app.assistant.chat.readHistory=async({onBatch})=>{for(let i=0;i<250;i++)await onBatch([message('row-'+i)],{complete:false,historyConsent:true,earliestId:'row-'+i});};await assert.rejects(f.app.assistant.history.refresh({orderId:f.order.id,historyConsent:true}),/fictional archive disk failure/);assert.equal(f.app.assistant.history.state({orderId:f.order.id}).count,100);assert.equal(f.app.assistant.history.state({orderId:f.order.id}).progress.status,'failed');f.database.exec('DROP TRIGGER history_once_fail');await f.app.assistant.history.refresh({orderId:f.order.id});assert.equal(f.app.assistant.history.state({orderId:f.order.id}).count,250);assert.equal(f.app.assistant.status({orderId:f.order.id}).messageCount,250);assert.equal(f.app.assistant.history.state({orderId:f.order.id}).progress.complete,false);assert.equal(f.app.assistant.online.timer,null);});

test('direct browser history synchronization cannot bypass the first history consent',async t=>{const f=setup(t);await f.bind();let reads=0;f.app.assistant.chat.readHistory=async()=>reads++;await assert.rejects(f.app.assistant.history.sync({orderId:f.order.id}),/确认读取范围/);assert.equal(reads,0);await f.app.assistant.history.sync({orderId:f.order.id,historyConsent:true});assert.equal(reads,1);});
