import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {DatabaseSync} from 'node:sqlite';import {_electron as electron} from 'playwright-core';import electronPath from 'electron';
const out=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||'artifacts/assistant-refresh-8.14/source');
test('Electron refresh integrates customer history with scoped replies, phone identity, stage goals, tab spacing, failure retention and restart',async()=>{
 const temp=await mkdtemp(path.join(os.tmpdir(),'assistant-refresh-fictional-')),data=path.join(temp,'data'),file=path.join(temp,'fixture.json');let app,page,db;const errors=[];
 const msg=(id,date='2026-09-13',text='Fictional '+id)=>({id,direction:'customer',sentAt:date+'T08:00:00.000Z',text});const current=msg('current'),old=Array.from({length:105},(_,n)=>msg('old-'+String(n).padStart(3,'0'),'2026-09-11')),latest=msg('latest','2026-09-14'),good=msg('good-before-failure','2026-09-14');
 const fixture={fictional:true,accountId:'wa-phone:971500000003',chatId:'wa-phone:971500000001',messages:[current],historyRounds:[[[current],old],[[current,latest]],[[good],[{...msg('invalid'),id:''}]],Array.from({length:10},()=>[current,latest,good])],historyDelayMs:500,extraction:{fields:{},items:[]},ai:{}};
 const call=(method,payload)=>page.evaluate(async({method,payload})=>{const r=await window.inventoryApp.orders[method](payload);if(!r.ok)throw Error(r.error.message);return r.data;},{method,payload});
 const launch=async()=>{const exe=process.env.KDOCS_TEST_EXECUTABLE;app=await electron.launch({executablePath:exe||electronPath,args:[...(exe?[]:['.']),`--orders-test-user-data=${data}`,`--orders-test-assistant=${file}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('https://**/*',r=>r.abort());await page.getByRole('button',{name:'订单管理',exact:true}).click();};
 const open=async()=>{await page.getByRole('button',{name:'订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'草稿 #1'}).click();await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();};
 try{await mkdir(out,{recursive:true});await writeFile(file,JSON.stringify(fixture));await launch();let one=await call('createDraft',{requestId:'refresh-ui-one'});await call('saveDraft',{orderId:one.id,fields:{fullName:'Fictional Recipient',phone:'+971500000001'},items:[{sku:'KY02',quantity:1,price:'25',discount:'0'}]});await call('bindChat',{orderId:one.id,accountId:fixture.accountId,chatId:fixture.chatId,scopeStart:'2026-09-12T00:00:00Z',scopeEnd:'2026-09-15T00:00:00Z',confirmed:true});const two=await call('createDraft',{requestId:'refresh-ui-two'});await open();assert.equal(await page.locator('.assistant-person strong').textContent(),'+971500000001');assert.match(await page.locator('.assistant-stage-current').textContent(),/确认收货地址/);assert.match(await page.locator('.assistant-stage-next').textContent(),/核对地址配送范围/);
 await page.getByLabel('英文草稿 · 可编辑').fill('Keep fictional human English');await page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');
 await page.getByRole('button',{name:'刷新聊天',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'已保存客户聊天 106 条'}).waitFor();assert.equal((await call('assistantStatus',{orderId:one.id})).messageCount,1);assert.equal((await call('assistantStatus',{orderId:two.id})).messageCount,0);assert.equal(await page.locator('.assistant-message').count(),80);await page.getByRole('button',{name:'加载较早的聊天记录',exact:true}).click();assert.equal(await page.locator('.assistant-message').count(),106);assert.equal(await page.locator('[data-message-id="old-000"] .assistant-history-scope').count(),1);assert.equal(await page.locator('[data-message-id="old-000"]').getByRole('button',{name:'回复这条'}).count(),0);assert.equal(await page.locator('[data-message-id="current"]').getByRole('button',{name:'回复这条'}).count(),1);
 const sizes=[];for(const size of [[900,700],[1280,850],[1440,900]]){await app.evaluate(({BrowserWindow},v)=>BrowserWindow.getAllWindows()[0].setSize(...v),size);await page.evaluate(()=>{document.querySelector('.order-assistant').scrollTop=0;document.querySelector('.assistant-heading').scrollIntoView({block:'center'});});await page.waitForTimeout(100);const geometry=await page.locator('.assistant-toolbar').evaluate(e=>{const tabs=[...e.querySelectorAll('.assistant-tab')],b=[...tabs,e.querySelector('.assistant-translation-toggle'),e.querySelector('[data-translation-action]')];return {positions:b.map(n=>{const r=n.getBoundingClientRect();return {left:r.left,right:r.right,center:r.y+r.height/2,font:getComputedStyle(n).fontSize,bg:getComputedStyle(n).backgroundColor};}),gaps:tabs.slice(1).map((n,i)=>n.getBoundingClientRect().left-tabs[i].getBoundingClientRect().right),overflows:document.documentElement.scrollWidth>innerWidth};});assert.ok(geometry.gaps.every(n=>n>=12));assert.equal(geometry.overflows,false);assert.ok(Math.max(...geometry.positions.map(r=>r.center))-Math.min(...geometry.positions.map(r=>r.center))<2);assert.ok(geometry.positions.slice(0,3).every(r=>r.font==='14px'&&!['rgba(0, 0, 0, 0)','transparent'].includes(r.bg)));assert.ok(!['rgba(0, 0, 0, 0)','transparent'].includes(geometry.positions.at(-1).bg));const goals=await page.locator('.assistant-stage-strip').evaluate(e=>[...e.querySelectorAll('button')].map(n=>({text:n.textContent,title:n.title,height:n.getBoundingClientRect().height})));assert.ok(goals.every(n=>n.height<=55));await page.screenshot({path:path.join(out,`refresh-${size[0]}x${size[1]}.png`)});sizes.push({size,geometry,goals});}
 await page.getByRole('button',{name:'刷新聊天',exact:true}).click();await page.locator('.assistant-action-feedback').filter({hasText:'已保存客户聊天 107 条'}).waitFor();assert.equal((await call('assistantStatus',{orderId:one.id})).messageCount,2);assert.equal(await page.locator('[data-message-id="latest"]').count(),1);
 await page.getByRole('button',{name:'刷新聊天',exact:true}).click();await page.locator('.assistant-action-feedback[role=alert]').filter({hasText:'历史消息校验失败'}).waitFor();const history=await call('assistantHistory',{orderId:one.id});assert.equal(history.count,108);assert.equal(history.progress.status,'failed');assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Keep fictional human English');assert.equal((await call('assistantStatus',{orderId:one.id})).messageCount,2);assert.equal(await page.locator('[data-message-id="good-before-failure"]').count(),1);
 await page.getByRole('button',{name:'刷新聊天',exact:true}).click();await page.getByRole('button',{name:'停止同步',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.assistant-sync-cancel'));assert.equal((await call('assistantHistory',{orderId:one.id})).progress.status,'cancelled');assert.equal((await call('assistantHistory',{orderId:one.id})).count,108);
 const state=await call('assistantWorkspace',{orderId:one.id});await page.getByRole('button',{name:'刷新聊天',exact:true}).click();await page.getByRole('button',{name:'返回订单列表',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'草稿 #2'}).click();if(!await page.locator('.order-assistant').count())await page.getByRole('button',{name:'订单助手',exact:true}).click();await page.getByLabel('英文草稿 · 可编辑').waitFor();await page.getByLabel('英文草稿 · 可编辑').fill('Fictional second order reply');await page.waitForFunction(()=>document.querySelector('.assistant-save-state')?.textContent==='已保存');await page.waitForTimeout(750);assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),'Fictional second order reply');assert.equal(await page.locator('.assistant-person strong').textContent(),'待关联聊天');assert.equal((await call('assistantStatus',{orderId:two.id})).messageCount,0);assert.equal((await call('assistantWorkspace',{orderId:one.id})).values.draft,state.values.draft);await app.close();app=null;await launch();await open();assert.equal(await page.getByLabel('英文草稿 · 可编辑').inputValue(),state.values.draft);assert.equal((await call('assistantHistory',{orderId:one.id})).count,108);assert.equal(await page.locator('.assistant-person strong').textContent(),'+971500000001');assert.deepEqual(errors,[]);await writeFile(path.join(out,'refresh-result.json'),JSON.stringify({result:'PASS-LOCAL',packaged:Boolean(process.env.KDOCS_TEST_EXECUTABLE),sizes,phoneIsAssociatedChatNotReceiver:true,fullSavedHistoryPaginated:true,historyOutsideOrderNotQuoted:true,latestAndDedup:true,partialFailureRetained:true,stopButtonCancels:true,humanReplyPreserved:true,orderIsolation:true,asyncSwitchReturnIgnored:true,restart:true,realAIRequests:0,realChatReads:0,messagesSent:0},null,2));
 }catch(e){if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'refresh-failure.png'),fullPage:true});throw e;}finally{db?.close();await app?.close();await rm(temp,{recursive:true,force:true});}
});
