import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {DatabaseSync} from 'node:sqlite';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {WhatsAppStructuredBrowser} from '../src/orders/whatsapp-structured-browser.mjs';
import {migrateOrderDatabase} from '../src/orders/database.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';
const out=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||'artifacts/assistant-structured-8.18/source');
async function fixture(t,options={}){
 const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage();await page.route('**/*',r=>r.fulfill({status:200,contentType:'text/html',body:'<main id="main"><header>Fictional customer</header><div data-id="false_971500000001@c.us_visible">Fictional waiting layout has no DOM time prefix</div></main>'}));await page.goto('https://web.whatsapp.com/');
 await page.evaluate(options=>{
  const pn='971500000001@c.us',lid='123456789012345@lid',wid=s=>({_serialized:s,toString:()=>s});
  window.fixture={page:options.pages||60,loads:0,peer:0,recovery:0,downloads:0,bodyReads:0,foreign:false};
  const message=(n,i)=>{const id={id:`p${n}-${i}`,remote:pn,fromMe:false,toString:()=>`false_${pn}_p${n}-${i}`};return {id,type:'chat',t:1789286400+n*60+i,get body(){window.fixture.bodyReads++;return 'Fictional native '+n+' '+i;}};};
  const chat={id:wid(lid),msgs:{getModelsArray:()=>window.rawMessages,...(options.loadState?{msgLoadState:{noEarlierMsgs:false,contextLoaded:true,isLoadingEarlierMsgs:false,isRepairingMsgHistory:options.repairing===true}}:{})},noEarlierMsgs:false,endOfHistoryTransfer:false,endOfHistoryTransferType:1};
  window.rawMessages=Array.from({length:4},(_,i)=>message(window.fixture.page,i));
  if(options.shortIds){document.querySelector('#main header').textContent='+971 50 000 0001';document.querySelector('#main [data-id]').setAttribute('data-id',window.rawMessages[0].id.id);}
  if(options.waiting){window.rawMessages.push({id:{remote:pn,fromMe:false,toString:()=>`false_${pn}_waiting`},type:'ciphertext',t:1789286420,body:''});}
  if(options.image){window.rawMessages.push({id:{remote:pn,fromMe:false,toString:()=>`false_${pn}_image`},type:'image',t:1789286430,body:'',mimetype:'image/png',size:68,mediaData:{mediaStage:'RESOLVED'}});}
  const modules={WAWebUserPrefsMeUser:{getMaybeMePnUser:()=>wid(window.fixture.foreign?'971500000008@c.us':'971500000009@c.us')},WAWebWidFactory:{createWid:wid},WAWebApiContact:{getPhoneNumber:()=>wid(pn),getCurrentLid:()=>wid(lid)},WAWebCollections:{Chat:{get:id=>[pn,lid].includes(id?._serialized||id)?chat:null}},WAWebChatLoadMessages:{loadEarlierMsgs:async()=>{window.fixture.loads++;if(options.stalled)return [];if(--window.fixture.page>=1){const rows=Array.from({length:4},(_,i)=>message(window.fixture.page,i));window.rawMessages.push(...rows);return rows;}if(options.loadState)chat.msgs.msgLoadState.noEarlierMsgs=true;else {chat.noEarlierMsgs=true;chat.endOfHistoryTransfer=true;}return [];}},WAWebSendNonMessageDataRequest:{sendPeerDataOperationRequest:async(type,payload)=>{if(type!==3||payload.chatId!==chat.id)throw Error('Wrong protocol target');window.fixture.peer++;if(options.delayed)setTimeout(()=>{window.rawMessages.push(message(0,0));},120);}},WAWebNonMessageDataRequestPlaceholderMessageResendUtils:{handlePlaceholderMsgsSeen:async(rows)=>{window.fixture.recovery++;if(options.decrypt)for(const m of rows){m.type='chat';m.body='Fictional recovered body';}}},WAWebDownloadManager:{downloadManager:{downloadAndMaybeDecrypt:async()=>{window.fixture.downloads++;return Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aQioAAAAASUVORK5CYII='),c=>c.charCodeAt(0)).buffer;}}}};
  window.require=name=>{if(!modules[name])throw Error('Fictional missing module '+name);return modules[name];};
 },options);
 const connector=new WhatsAppStructuredBrowser({page,limits:{waitMs:options.delayed?50:5,stalls:options.delayed?6:2,deadlineMs:10000}}),current=await connector.currentIdentity();
 return {page,connector,current};
}
test('structured real-browser fixture loads 60 store pages despite missing DOM timestamps, recovers waiting text and downloads bytes once',async t=>{
 const f=await fixture(t,{waiting:true,decrypt:true,image:true}),database=new DatabaseSync(':memory:');migrateOrderDatabase(database);t.after(()=>database.close());const app=new OrderAppService({database,chatAdapter:f.connector}),one=app.drafts.create({requestId:'native-store-one'});
 // Candidate selection is still required by the existing association contract.
 const candidate=await f.connector.inspect();await app.assistant.bind({orderId:one.id,accountId:candidate.accountId,chatId:candidate.chatId,candidateToken:candidate.token,scopeStart:'2026-09-13T00:00:00Z',scopeEnd:'2026-09-14T00:00:00Z',confirmed:true,historyConsent:true});
 const state=app.assistant.history.state({orderId:one.id,limit:200});assert.equal(state.count,242);assert.equal(state.progress.complete,false);assert.equal(state.progress.status,'web-top-verified');assert.equal(state.progress.boundary.noEarlierMsgs,true);assert.equal(app.assistant.history.state({orderId:one.id,query:'Fictional recovered'}).messages[0].text,'Fictional recovered body');assert.equal(app.assistant.history.state({orderId:one.id,query:'Fictional recovered'}).messages[0].incomplete,false);assert.equal(app.assistant.history.state({orderId:one.id,query:'[图片]'}).messages[0].media[0].source,'attachment');assert.equal(new Set(state.messages.map(m=>m.id)).size,state.messages.length);
 await app.assistant.history.refresh({orderId:one.id});assert.equal(app.assistant.history.state({orderId:one.id}).count,242);assert.equal(await f.page.evaluate(()=>window.fixture.downloads),1);assert.equal(app.assistant.online.timer,null);
 await mkdir(out,{recursive:true});await writeFile(path.join(out,'structured-store-result.json'),JSON.stringify({result:'PASS-LOCAL',realWhatsApp:false,actualBrowser:true,storePages:60,records:242,DOMTimestampRequired:false,nativeDecryptionUpgrade:true,attachmentByteDownload:true,repeatedRefreshDownloads:1,manualOnly:true,accountCompletenessClaimed:false},null,2));
});
test('stalled native loading requests only the selected target once, waits for delayed history and never claims complete',async t=>{const f=await fixture(t,{pages:1,stalled:true,delayed:true});const ids=new Set();let terminal;await f.connector.readHistory({...f.current,binding:f.current,onBatch:async(rows,p)=>{rows.forEach(m=>ids.add(m.id));terminal=p;}});assert.equal(ids.size,5);assert.equal(await f.page.evaluate(()=>window.fixture.peer),1);assert.equal(terminal.complete,false);assert.equal(terminal.status,'coverage-unverified');});
test('native account/target changes reject bodies and cancelled operations preserve the first checkpoint',async t=>{const f=await fixture(t,{pages:3});let cancelled=false,batches=0,last;await f.connector.readHistory({...f.current,binding:f.current,cancelled:()=>cancelled,onBatch:async(rows,p)=>{if(rows.length){batches++;cancelled=true;}last=p;}});assert.equal(batches,1);assert.equal(last.status,'cancelled');await f.page.evaluate(()=>{window.fixture.foreign=true;window.fixture.bodyReads=0;});await assert.rejects(f.connector.readHistory({...f.current,binding:f.current,onBatch:async()=>assert.fail('Foreign batch')}),/关联不符/);assert.equal(await f.page.evaluate(()=>window.fixture.bodyReads),0);});
test('account switch after a native snapshot discards the checkpoint even when visible chat identifiers stay unchanged',async t=>{const f=await fixture(t,{pages:1}),operation=f.connector.operation.bind(f.connector);f.connector.operation=async input=>{const result=await operation(input);if(input.op==='snapshot')await f.page.evaluate(()=>window.fixture.foreign=true);return result;};await assert.rejects(f.connector.readHistory({...f.current,binding:f.current,onBatch:async()=>assert.fail('Switched-account checkpoint must not be saved')}),/账号或聊天已切换/);});
test('short DOM IDs require native PN/LID membership and preserve guarded history loading',async t=>{const f=await fixture(t,{pages:3,shortIds:true}),ids=new Set();await f.connector.readHistory({...f.current,binding:f.current,onBatch:async rows=>rows.forEach(m=>ids.add(m.id))});assert.equal(ids.size,12);assert.equal(f.current.nativeRemote,'123456789012345@lid');await f.page.evaluate(()=>{window.fixture.bodyReads=0;document.querySelector('#main [data-id]').setAttribute('data-id','unknown-other-chat');});await assert.rejects(f.connector.currentIdentity(),e=>e.code==='WHATSAPP_TARGET_CHANGED');assert.equal(await f.page.evaluate(()=>window.fixture.bodyReads),0);});
test('short ID captions cannot authorize unknown native namespaces or an unverified phone',async t=>{const f=await fixture(t,{pages:1,shortIds:true});await f.page.evaluate(()=>{window.fixture.bodyReads=0;window.rawMessages[0].id.remote='971500000008@c.us';});await assert.rejects(f.connector.currentIdentity(),e=>e.code==='WHATSAPP_TARGET_CHANGED');assert.equal(await f.page.evaluate(()=>window.fixture.bodyReads),0);await f.page.evaluate(()=>{window.rawMessages[0].id.remote='971500000001@c.us';document.querySelector('#main header').textContent='Fictional unknown name';});await assert.rejects(f.connector.currentIdentity(),e=>e.code==='WHATSAPP_TARGET_UNVERIFIED');assert.equal(await f.page.evaluate(()=>window.fixture.bodyReads),0);});

test('native message load state proves only the loaded web top, never phone transfer completion',async t=>{const f=await fixture(t,{pages:1,shortIds:true,loadState:true});let last;await f.connector.readHistory({...f.current,binding:f.current,onBatch:async(_,p)=>last=p});assert.equal(last.status,'web-top-verified');assert.equal(last.boundary.webTopLoaded,true);assert.equal(last.boundary.endOfHistoryTransfer,false);assert.equal(last.complete,false);});
test('repairing message history cannot be reported as a verified web top',async t=>{const f=await fixture(t,{pages:1,shortIds:true,loadState:true,repairing:true});let last;await f.connector.readHistory({...f.current,binding:f.current,onBatch:async(_,p)=>last=p});assert.equal(last.status,'coverage-unverified');assert.equal(last.boundary.webTopLoaded,false);assert.equal(last.complete,false);});
