import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron,chromium} from 'playwright-core';
import ExcelJS from 'exceljs';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

const columns=[['订单信息基础信息','订单号','orderNo'],['订单信息基础信息','子订单 ID','subOrderId'],['订单信息基础信息','创建时间','createdAt'],['订单信息基础信息','订单状态','orderStatus'],['订单信息基础信息','货币单位','currency'],['订单信息基础信息','订单总价','orderTotal'],['订单信息基础信息','商品总价','productTotal'],['收货信息','名(firstName)','firstName'],['收货信息','姓(lastName)','lastName'],['收货信息','联系电话','phone'],['收货信息','联系邮箱','email'],['收货信息','国家','country'],['收货信息','省/州','province'],['收货信息','城市','city'],['收货信息','街道','street'],['商品信息','商品SKU','productSku'],['商品信息','商品名称','productName'],['商品信息','商品售价','unitPrice'],['商品信息','售出数量','quantity'],['商品信息','商品支付状态','paymentStatus'],['商品信息','商品配送状态','fulfillmentStatus']];
const data={orderNo:'MISSING-COST-FICTIONAL',subOrderId:'MISSING-COST-SUB',createdAt:'2026-09-12 12:00:00',orderStatus:'待发货',currency:'AED',orderTotal:'25',productTotal:'25',firstName:'Fictional',lastName:'Customer',phone:'+000000083',email:'missing-cost@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Fictional Street',productSku:'KY999',productName:'KY999 Fictional Product',unitPrice:'25',quantity:'1',paymentStatus:'paid',fulfillmentStatus:'pending'};
const delay=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));

async function makeWorkbook(file){const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Fictional Orders');let start=1;for(const group of [...new Set(columns.map(row=>row[0]))]){const count=columns.filter(row=>row[0]===group).length;sheet.mergeCells(1,start,1,start+count-1);sheet.getCell(1,start).value=group;start+=count;}columns.forEach((row,index)=>sheet.getCell(2,index+1).value=row[1]);columns.forEach((column,index)=>sheet.getCell(3,index+1).value=data[column[2]]??'');await workbook.xlsx.writeFile(file);}
async function localUrl(userData){for(let attempt=0;attempt<200;attempt++){const files=await readdir(path.join(userData,'logs')).catch(()=>[]),entries=[];for(const file of files.filter(name=>name.startsWith('startup-')).sort()){const text=await readFile(path.join(userData,'logs',file),'utf8').catch(()=>'');for(const line of text.split('\n').filter(Boolean))try{entries.push(JSON.parse(line));}catch{}}const started=entries.filter(entry=>entry.message==='本地管理页面已启动').at(-1);if(started){const token=(await readFile(path.join(userData,'local-web-token'),'utf8')).trim();return `http://127.0.0.1:${started.metrics.port}/?token=${token}`;}await delay(100);}throw new Error('打包应用没有启动本地管理页面');}

test('打包版缺失成本可明确留空后导入且不写0',async()=>{const packaged=path.resolve(process.env.KDOCS_PACKAGED_APP||'');if(!process.env.KDOCS_PACKAGED_APP)throw new Error('缺少KDOCS_PACKAGED_APP');const directory=await mkdtemp(path.join(os.tmpdir(),'kdocs-missing-cost-')),userData=path.join(directory,'user-data'),file=path.join(directory,'fictional-missing-cost.xlsx'),artifactDirectory=process.env.KDOCS_TEST_ARTIFACT_DIRECTORY;let application,browser,page;try{await makeWorkbook(file);const executable=path.join(packaged,'Contents','MacOS',path.basename(packaged,'.app'));application=await electron.launch({executablePath:executable,args:[`--isolated-user-data=${userData}`],cwd:path.dirname(packaged),env:{...process.env,NODE_ENV:'production'}});const url=await localUrl(userData);browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1280,height:800}});await page.goto(url,{waitUntil:'networkidle'});await page.getByRole('button',{name:'订单管理',exact:true}).click();const chooserPromise=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入ShopPlus Excel',exact:true}).first().click();const chooser=await chooserPromise;await chooser.setFiles(file);await page.getByText(/1 条商品缺少成本/).waitFor();assert.equal(await page.locator('#preview-filename').textContent(),'fictional-missing-cost.xlsx');assert.equal(await page.locator('input[data-field="costAed"]').inputValue(),'');assert.equal(await page.locator('[data-confirm-missing-cost]').count(),1);if(artifactDirectory){await mkdir(artifactDirectory,{recursive:true});await page.screenshot({path:path.join(artifactDirectory,'missing-cost-review-production.png'),fullPage:true});}const review=page.locator('.review-checks');await review.locator('[data-confirm-review]').check();await review.locator('[data-confirm-missing-cost]').check();await review.getByRole('button',{name:'保存核对',exact:true}).click();await page.getByText('准备导入 1 个订单',{exact:true}).waitFor();await page.getByRole('button',{name:'确认导入',exact:true}).click();await page.locator('#import-confirm-dialog').getByRole('button',{name:'确认导入',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:'MISSING-COST-FICTIONAL'}).waitFor();await page.close();page=null;await application.close();application=null;const database=new DatabaseSync(path.join(userData,'orders','orders.sqlite'),{readOnly:true}),stored=database.prepare('SELECT unit_cost_snapshot,needs_review FROM order_items').get();database.close();assert.equal(stored.unit_cost_snapshot,null);assert.equal(stored.needs_review,1);console.log('MISSING_COST_IMPORT={"orders":1,"items":1,"nullCosts":1,"zeroCosts":0}');}finally{await page?.close().catch(()=>{});await browser?.close().catch(()=>{});await application?.close().catch(()=>{});await rm(directory,{recursive:true,force:true});}});
