import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron,chromium} from 'playwright-core';
import electronPath from 'electron';
import ExcelJS from 'exceljs';
import * as XLSX from 'xlsx';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

const columns=[['订单信息基础信息','订单号','orderNo'],['订单信息基础信息','子订单 ID','subOrderId'],['订单信息基础信息','创建时间','createdAt'],['订单信息基础信息','订单状态','orderStatus'],['订单信息基础信息','货币单位','currency'],['订单信息基础信息','订单总价','orderTotal'],['订单信息基础信息','商品总价','productTotal'],['订单信息基础信息','优惠金额','discountAmount'],['订单信息基础信息','物流费用','customerShippingFee'],['订单信息基础信息','支付方式','paymentMethod'],['收货信息','名(firstName)','firstName'],['收货信息','姓(lastName)','lastName'],['收货信息','姓名','fullName'],['收货信息','联系电话','phone'],['收货信息','联系邮箱','email'],['收货信息','国家','country'],['收货信息','省/州','province'],['收货信息','城市','city'],['收货信息','街道','street'],['收货信息','寓所','residence'],['商品信息','商品SKU','productSku'],['商品信息','商品名称','productName'],['商品信息','商品售价','unitPrice'],['商品信息','售出数量','quantity'],['商品信息','商品支付状态','paymentStatus'],['商品信息','商品配送状态','fulfillmentStatus']];

const fictionalData=orderNo=>({orderNo,subOrderId:`SUB-${orderNo}`,createdAt:'2026-09-12 12:00:00',orderStatus:'待发货',currency:'AED',orderTotal:'25',productTotal:'25',discountAmount:'0',customerShippingFee:'0',paymentMethod:'COD',firstName:'Fictional',lastName:'Customer',fullName:'Fictional Customer',phone:'+000 000 008',email:'browser-file@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Fictional Street, Unit "A"',residence:'Fictional Residence',productSku:'KY02',productName:'KY02 Fictional',unitPrice:'25',quantity:'1',paymentStatus:'paid',fulfillmentStatus:'pending'});
async function makeOrderFile(file,extension,orderNo){const data=fictionalData(orderNo);if(extension==='xlsx'){const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Fictional Orders');let start=1;for(const group of [...new Set(columns.map(row=>row[0]))]){const count=columns.filter(row=>row[0]===group).length;sheet.mergeCells(1,start,1,start+count-1);sheet.getCell(1,start).value=group;start+=count;}columns.forEach((row,index)=>sheet.getCell(2,index+1).value=row[1]);columns.forEach((column,index)=>sheet.getCell(3,index+1).value=data[column[2]]??'');await workbook.xlsx.writeFile(file);return;}let previous='',groupRow=columns.map(([group])=>{const value=group===previous?'':group;previous=group;return value;}),sheet=XLSX.utils.aoa_to_sheet([groupRow,columns.map(row=>row[1]),columns.map(row=>data[row[2]]??'')]),workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,sheet,'Fictional Orders');await writeFile(file,XLSX.write(workbook,{bookType:extension,type:'buffer'}));}

test('浏览器文件选择器支持xlsx、xls、csv的取消、重选、预览和导入',async()=>{
  const directory=await mkdtemp(path.join(os.tmpdir(),'browser-order-file-picker-')),userData=path.join(directory,'user-data'),urlFile=path.join(directory,'url.txt'),formats=['xlsx','xls','csv'],files=[];let application,browser;
  try{
    await mkdir(path.join(userData,'state'),{recursive:true});
    for(const extension of formats){const orderNo=`BROWSER-${extension.toUpperCase()}-FICTIONAL`,file=path.join(directory,`fictional-shopplus.${extension}`);await makeOrderFile(file,extension,orderNo);files.push({extension,file,orderNo});}
    await writeFile(path.join(userData,'state','baseline.json'),JSON.stringify({versionAt:'fictional',products:[['商品编号','来源商品名称','成本'],['KY02','Fictional','5']]}));
    const packaged=process.env.KDOCS_PACKAGED_APP,production=process.env.KDOCS_PRODUCTION_IMPORT==='1',executablePath=packaged?path.join(packaged,'Contents/MacOS',path.basename(packaged,'.app')):electronPath,args=production?[`--isolated-user-data=${userData}`]:packaged?[`--orders-test-user-data=${userData}`,'--orders-test-browser-workspace',`--orders-test-browser-url-file=${urlFile}`]:['.',`--orders-test-user-data=${userData}`,'--orders-test-browser-workspace',`--orders-test-browser-url-file=${urlFile}`];
    application=await electron.launch({executablePath,args,cwd:packaged?path.dirname(packaged):path.resolve('.'),env:{...process.env,NODE_ENV:production?'production':'test'}});
    let url='';for(let i=0;i<150&&!url;i++){await new Promise(resolve=>setTimeout(resolve,100));if(production){const logFiles=await readdir(path.join(userData,'logs')).catch(()=>[]);for(const file of logFiles.filter(name=>name.startsWith('startup-'))){const entries=(await readFile(path.join(userData,'logs',file),'utf8')).split('\n').filter(Boolean).flatMap(line=>{try{return [JSON.parse(line)];}catch{return [];}}),started=entries.find(entry=>entry.message==='本地管理页面已启动');if(started){const token=(await readFile(path.join(userData,'local-web-token'),'utf8')).trim();url=`http://127.0.0.1:${started.metrics.port}/?token=${token}`;break;}}}else url=await readFile(urlFile,'utf8').catch(()=>'');}
    assert.match(url,/^http:\/\/127\.0\.0\.1:\d+\/\?token=/);browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:800}});await page.goto(url,{waitUntil:'networkidle'});await page.getByRole('button',{name:'订单管理',exact:true}).click();const importButton=page.getByRole('button',{name:'导入ShopPlus Excel',exact:true}).first();
    let chooserPromise=page.waitForEvent('filechooser');await importButton.click();let chooser=await chooserPromise;assert.equal(await importButton.isDisabled(),true);await chooser.setFiles([]);await page.waitForFunction(()=>!document.querySelector('#orders-import').disabled);
    for(const {file,orderNo} of files){chooserPromise=page.waitForEvent('filechooser');await importButton.click();chooser=await chooserPromise;await chooser.setFiles(file);await page.getByText('准备导入 1 个订单',{exact:true}).waitFor();assert.equal((await readdir(path.join(userData,'state'))).filter(name=>name.startsWith('.shopplus-')).length,1);await page.getByRole('button',{name:'确认导入',exact:true}).click();await page.locator('#import-confirm-dialog').getByRole('button',{name:'确认导入',exact:true}).click();await page.locator('#orders-table-body tr').filter({hasText:orderNo}).waitFor();assert.equal((await readdir(path.join(userData,'state'))).some(name=>name.startsWith('.shopplus-')),false);}
    const result={message:await page.locator('#orders-error-message').textContent(),rows:await page.locator('#orders-table-body').innerText()};assert.match(result.message,/成功导入 1 个订单/,JSON.stringify(result));for(const {orderNo} of files)assert.match(result.rows,new RegExp(orderNo),JSON.stringify(result));
    if(!production){await browser.close();browser=null;await application.close();application=null;await rm(urlFile,{force:true});application=await electron.launch({executablePath,args,cwd:packaged?path.dirname(packaged):path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});let restarted='';for(let n=0;n<150&&!restarted;n++){restarted=await readFile(urlFile,'utf8').catch(()=>'');if(!restarted)await new Promise(r=>setTimeout(r,100));}assert.ok(restarted);browser=await chromium.launch({headless:true});const restoredPage=await browser.newPage();await restoredPage.goto(restarted);await restoredPage.getByRole('button',{name:'订单管理',exact:true}).click();await restoredPage.getByRole('button',{name:'订单列表',exact:true}).click();for(const {orderNo} of files)await restoredPage.locator('#orders-table-body tr').filter({hasText:orderNo}).waitFor();}
    const artifactDirectory=process.env.KDOCS_TEST_ARTIFACT_DIRECTORY;if(artifactDirectory){await mkdir(artifactDirectory,{recursive:true});await (browser.contexts()[0].pages()[0]).screenshot({path:path.join(artifactDirectory,production?'import-formats-production-complete.png':'import-formats-complete.png'),fullPage:true});}
  }finally{await browser?.close();await application?.close();await rm(directory,{recursive:true,force:true});}
});
