import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import {mkdtemp,mkdir,copyFile,readdir,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import {openOrderDatabase} from '../src/orders/database.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';
import {formatAed} from '../src/orders/package-report.mjs';

const requiredEnvironment=name=>{const value=process.env[name];if(!value)throw new Error(`缺少隔离验收环境参数：${name}`);return path.resolve(value);};
async function launch(userData,excelFile){return electron.launch({executablePath:electronPath,args:['.',`--orders-test-user-data=${userData}`,`--orders-test-excel=${excelFile}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});}

test('Electron 44在隔离数据库完成真实ShopPlus导入、原文TXT、收件确认、重启和重复保护',async()=>{const excelFile=requiredEnvironment('REAL_SHOPPLUS_XLSX'),baselineFile=requiredEnvironment('REAL_COST_BASELINE'),sourceHash=createHash('sha256').update(await readFile(excelFile)).digest('hex'),directory=await mkdtemp(path.join(os.tmpdir(),'real-orders-isolated-')),userData=path.join(directory,'isolated-user-data');let app,database,uiFullNameConfirmed=0;await mkdir(path.join(userData,'state'),{recursive:true});await copyFile(baselineFile,path.join(userData,'state','baseline.json'));
  try{
    app=await launch(userData,excelFile);let page=await app.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.getByRole('button',{name:'导入ShopPlus Excel'}).first().click();await page.waitForFunction(()=>document.querySelector('#pv-orders')?.textContent==='10');assert.equal(await page.locator('#pv-items').textContent(),'11');assert.equal(await page.locator('#pv-multi').textContent(),'1');assert.equal(await page.locator('#pv-blocked').textContent(),'0');assert.equal(await page.locator('#pv-duplicate').textContent(),'0');while(await page.locator('.review-checks').count()){const review=page.locator('.review-checks').first();for(const checkbox of await review.getByRole('checkbox').all())await checkbox.check();await review.getByRole('button',{name:'保存核对'}).click();await page.waitForTimeout(50);}
    await page.getByText('准备导入 10 个订单').waitFor();await page.getByRole('button',{name:'确认导入'}).click();await page.locator('#import-confirm-dialog').getByRole('button',{name:'确认导入'}).click();await page.waitForFunction(()=>document.querySelectorAll('#orders-table-body tr').length===10);const multi=page.locator('#orders-table-body tr').filter({hasText:'2 件'});await multi.click();const packageCount=await page.locator('.fulfillment-package').count();await page.getByRole('button',{name:'确认订单'}).click();await page.locator('.fulfillment-package').first().getByRole('button',{name:'预览TXT'}).click();await page.locator('#txt-preview-dialog').waitFor({state:'visible'});assert.ok((await page.locator('#txt-preview-content').textContent()).length>100);await page.keyboard.press('Escape');await page.keyboard.press('Escape');const rows=page.locator('#orders-table-body tr');for(let index=0;index<await rows.count();index++){await rows.nth(index).click();const confirmation=page.locator('.recipient-full-name button');if(await confirmation.count()){const orderConfirmation=page.getByRole('button',{name:'确认订单'});if(await orderConfirmation.count())await orderConfirmation.click();await page.locator('.fulfillment-package').first().getByRole('button',{name:'预览TXT'}).click();await page.getByRole('button',{name:'使用原始Full name作为Name'}).click();await page.getByRole('button',{name:'保存TXT'}).waitFor({state:'visible'});await page.keyboard.press('Escape');uiFullNameConfirmed++;await page.keyboard.press('Escape');break;}await page.keyboard.press('Escape');}assert.equal(uiFullNameConfirmed,1);await app.close();app=null;
    app=await launch(userData,excelFile);page=await app.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.waitForFunction(()=>document.querySelector('#sum-total')?.textContent==='10');await page.getByRole('button',{name:'导入ShopPlus Excel'}).first().click();await page.waitForFunction(()=>document.querySelector('#pv-duplicate')?.textContent==='10');assert.equal(await page.locator('#commit-orders').isDisabled(),true);await app.close();app=null;
    database=await openOrderDatabase({userDataPath:userData});const orderCount=Number(database.prepare('SELECT count(*) count FROM orders').get().count),itemCount=Number(database.prepare('SELECT count(*) count FROM order_items').get().count),packages=database.prepare('SELECT * FROM packages ORDER BY order_id,series_code').all(),records=database.prepare('SELECT * FROM orders ORDER BY created_at,id').all(),present=value=>Boolean(String(value??'').trim()),rawImmediateReady=records.filter(record=>[record.customer_last_name,record.customer_first_name,record.customer_phone,record.customer_email,record.country,record.province,record.city,record.street].every(present)).length,rawFullNameEligible=records.filter(record=>!present(record.customer_first_name)&&present(record.customer_full_name)&&[record.customer_last_name,record.customer_phone,record.customer_email,record.country,record.province,record.city,record.street].every(present)).length,rawProvinceBlocked=records.filter(record=>!present(record.province)).length,appService=new OrderAppService({database,userDataPath:userData});let checkedTxt=0,originalConsistent=0,partitionCorrect=0,amountConsistent=0,blocked=0,residenceWarnings=0;
    for(const order of records){appService.confirmOrder({orderId:order.id,note:'isolated acceptance'});const record=database.prepare('SELECT * FROM orders WHERE id=?').get(order.id),orderPackages=database.prepare('SELECT * FROM packages WHERE order_id=?').all(order.id),allItems=database.prepare('SELECT * FROM order_items WHERE order_id=?').all(order.id);for(const parcel of orderPackages){let report=appService.previewPackageTxt({packageId:parcel.id});if(report.warnings?.some(warning=>warning.code==='RESIDENCE_MISSING'))residenceWarnings++;if(report.problems?.some(problem=>problem.code==='FULL_NAME_CONFIRMATION_REQUIRED')){appService.confirmFullNameAsName({orderId:order.id});report=appService.previewPackageTxt({packageId:parcel.id});}if(!report.ok){assert.ok(report.problems.some(problem=>problem.field==='province'));blocked++;continue;}checkedTxt++;const override=database.prepare("SELECT override_value FROM order_recipient_overrides WHERE order_id=? AND field_name='firstName'").get(order.id)?.override_value,effectiveFields=[record.customer_last_name,record.customer_first_name||override,record.customer_phone,record.customer_email,record.country,record.province,record.city,record.street],items=allItems.filter(item=>item.package_id===parcel.id),details=report.content.split('Order Price Details：\n\n')[1].trim().split('\n');if(effectiveFields.every(value=>report.content.includes(String(value))))originalConsistent++;if(details.length===items.length&&items.every(item=>details.includes(`${item.sku_code}      AED${formatAed(item.unit_actual_price)} x ${item.quantity}`)))partitionCorrect++;if(report.totalFils===items.reduce((sum,item)=>sum+Number(item.line_revenue),0))amountConsistent++;}}
    const fullNameConfirmations=Number(database.prepare("SELECT count(*) count FROM order_recipient_overrides WHERE override_kind='full_name_confirmation'").get().count),automaticBackups=(await readdir(path.join(userData,'orders','automatic-backups'))).filter(name=>name.endsWith('.sqlite')).length,auditText=JSON.stringify(database.prepare("SELECT event_type,old_value,new_value,note FROM order_events WHERE event_type LIKE 'recipient_%'").all()),auditLeaksCustomerValue=records.flatMap(record=>[record.customer_first_name,record.customer_last_name,record.customer_full_name,record.customer_phone,record.customer_email,record.country,record.province,record.city,record.street,record.residence]).filter(present).some(value=>auditText.includes(String(value))),safeStats={orders:orderCount,items:itemCount,multiItemOrders:Number(database.prepare('SELECT count(*) count FROM (SELECT order_id FROM order_items GROUP BY order_id HAVING count(*)>1)').get().count),packages:packages.length,multiSeriesOrders:Number(database.prepare('SELECT count(*) count FROM (SELECT order_id FROM packages GROUP BY order_id HAVING count(*)>1)').get().count),uiMultiOrderPackages:packageCount,rawImmediateReady,rawFullNameEligible,rawProvinceBlocked,uiFullNameConfirmed,fullNameConfirmations,residenceWarnings,txtChecked:checkedTxt,txtOriginalConsistent:originalConsistent,txtPartitionCorrect:partitionCorrect,txtAmountConsistent:amountConsistent,txtBlocked:blocked,automaticBackups};assert.deepEqual({orders:orderCount,items:itemCount},{orders:10,items:11});assert.equal(rawImmediateReady,7);assert.equal(rawFullNameEligible,2);assert.equal(rawProvinceBlocked,1);assert.equal(fullNameConfirmations,2);assert.equal(residenceWarnings,6);assert.equal(checkedTxt,9);assert.equal(blocked,1);assert.equal(originalConsistent,checkedTxt);assert.equal(partitionCorrect,checkedTxt);assert.equal(amountConsistent,checkedTxt);assert.equal(checkedTxt+blocked,packages.length);assert.ok(automaticBackups>=1);assert.equal(auditLeaksCustomerValue,false);assert.equal(createHash('sha256').update(await readFile(excelFile)).digest('hex'),sourceHash);console.log(`REAL_ACCEPTANCE_STATS=${JSON.stringify(safeStats)}`);
  }finally{if(database)database.close();if(app)await app.close().catch(()=>{});await rm(directory,{recursive:true,force:true});}
});
