import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import ExcelJS from 'exceljs';
import {mkdtemp,mkdir,writeFile,readFile,access,readdir,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {openOrderDatabase} from '../src/orders/database.mjs';
import {OrderRepository} from '../src/orders/order-repository.mjs';
import {OrderService} from '../src/orders/order-service.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';

const columns=[['订单信息基础信息','订单号','orderNo'],['订单信息基础信息','子订单 ID','subOrderId'],['订单信息基础信息','创建时间','createdAt'],['订单信息基础信息','订单状态','orderStatus'],['订单信息基础信息','货币单位','currency'],['订单信息基础信息','订单总价','orderTotal'],['订单信息基础信息','商品总价','productTotal'],['订单信息基础信息','优惠金额','discountAmount'],['订单信息基础信息','物流费用','customerShippingFee'],['订单信息基础信息','支付方式','paymentMethod'],['收货信息','名(firstName)','firstName'],['收货信息','姓(lastName)','lastName'],['收货信息','姓名','fullName'],['收货信息','联系电话','phone'],['收货信息','联系邮箱','email'],['收货信息','国家','country'],['收货信息','省/州','province'],['收货信息','城市','city'],['收货信息','街道','street'],['收货信息','寓所','residence'],['商品信息','商品SKU','productSku'],['商品信息','商品名称','productName'],['商品信息','商品售价','unitPrice'],['商品信息','售出数量','quantity'],['商品信息','商品支付状态','paymentStatus'],['商品信息','商品配送状态','fulfillmentStatus']];
const base={orderNo:'E2E-FICTIONAL-1',createdAt:'2026-08-31 12:00:00',orderStatus:'待发货',currency:'AED',orderTotal:'180',productTotal:'180',discountAmount:'0',customerShippingFee:'0',paymentMethod:'COD',firstName:'Fictional',lastName:'Person',fullName:'Fictional Person',phone:'+000 000 001',email:'ui@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Fictional Street',residence:'Fictional Residence',quantity:'1',paymentStatus:'paid',fulfillmentStatus:'pending'};
async function makeExcel(file){const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Fictional Orders');let start=1;for(const group of [...new Set(columns.map(row=>row[0]))]){const count=columns.filter(row=>row[0]===group).length;sheet.mergeCells(1,start,1,start+count-1);sheet.getCell(1,start).value=group;start+=count;}columns.forEach((row,index)=>sheet.getCell(2,index+1).value=row[1]);const rows=[{...base,subOrderId:'SUB-YB-1',productSku:'YB45',productName:'YB45 Fictional Product',unitPrice:'60'},{...base,subOrderId:'SUB-YB-2',productSku:'YB40',productName:'YB40 Fictional Product',unitPrice:'40'},{...base,subOrderId:'SUB-KY',productSku:'KY02',productName:'KY02 Fictional Product',unitPrice:'80'}];rows.forEach((row,r)=>columns.forEach((column,c)=>sheet.getCell(r+3,c+1).value=row[column[2]]??''));
  await book.xlsx.writeFile(file);}
async function launch(userData,options={}){const packaged=process.env.KDOCS_TEST_EXECUTABLE;const args=[...(packaged?[]:['.']),`--orders-test-user-data=${userData}`,'--orders-test-address-deliverable'];for(const [key,flag] of [['excelFile','--orders-test-excel='],['saveDirectory','--orders-test-save-directory='],['dataDirectory','--orders-test-data-directory='],['restoreFile','--orders-test-restore-file=']])if(options[key])args.push(flag+options[key]);if(options.cancelSave)args.push('--orders-test-cancel-save');if(options.cancelDataSave)args.push('--orders-test-cancel-data-save');return electron.launch({executablePath:packaged||electronPath,args,cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});}
const fictionalOrder=(orderNo,{status='unshipped',cost='20.00'}={})=>({source:'manual',shopplus_order_no:orderNo,shopplus_created_at:'2026-09-01T08:00:00.000Z',currency:'AED',order_status:'fictional',delivery_status:status,payment_method:'COD',customer_first_name:'Fictional',customer_last_name:'Person',customer_full_name:'Fictional Person',customer_phone:'+000 000 002',customer_email:'fictional@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Fictional Street',residence:'Fictional Residence',items:[{sku_code:'YB17',product_name_snapshot:'YB17 Fictional Product',quantity:1,unit_list_price:'50',unit_actual_price:'50',unit_cost_snapshot:cost,cost_source:'fictional'}]});
const acceptDialogs=page=>page.on('dialog',async dialog=>{await dialog.accept(dialog.type()==='prompt'?'fictional reason':undefined);});
async function confirmDeliverable(page){await page.getByRole('button',{name:'可配送',exact:true}).click();const dialog=page.locator('#address-confirm-dialog');await dialog.getByRole('heading',{name:'确认地址可配送'}).waitFor();await dialog.getByRole('button',{name:'确认可配送'}).click();await page.getByText('✅ 已确认可配送').waitFor();}
async function openOrder(page,orderNo){await page.getByRole('button',{name:'订单管理'}).click();
  await page.getByRole('button',{name:'订单列表'}).click();
  await page.locator('#order-search').fill(orderNo);const row=page.locator('#orders-table-body tr').filter({hasText:orderNo});
  await row.waitFor();
  await row.click();
  await page.getByRole('heading',{name:'客户信息'}).waitFor();}
const current=(page,name)=>page.locator('.status-step.current',{hasText:name});

test('Electron 44完成导入、双包裹状态、报单、费用、利润和重启持久化',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'electron-orders-ui-')),userData=path.join(directory,'user-data'),saveDirectory=path.join(directory,'reports'),excelFile=path.join(directory,'orders.xlsx');let app;try{await mkdir(path.join(userData,'state'),{recursive:true});
  await mkdir(saveDirectory,{recursive:true});
  await makeExcel(excelFile);
  await writeFile(path.join(userData,'state','baseline.json'),JSON.stringify({versionAt:'fictional',products:[['商品编号','来源商品名称','成本'],['YB45','Fictional','20'],['YB40','Fictional','10'],['KY02','Fictional','20']]}));app=await launch(userData,{excelFile,saveDirectory});let page=await app.firstWindow();acceptDialogs(page);
  await page.getByRole('button',{name:'订单管理'}).click();
  await page.getByRole('button',{name:'导入ShopPlus Excel'}).first().click();
  await page.getByText('准备导入 1 个订单').waitFor();
  await page.getByRole('button',{name:'确认导入'}).click();
  await page.locator('#import-confirm-dialog').getByRole('button',{name:'确认导入'}).click();
  await page.locator('#orders-table-body tr').click();assert.equal(await page.locator('.profit-package-carousel').count(),1);await page.getByText('共 2 个包裹',{exact:true}).waitFor();
  await page.locator('#order-detail-status').getByRole('button',{name:'待确认',exact:true}).click();
  await page.waitForTimeout(800);
  assert.equal(await page.locator('#orders-error').evaluate(element=>element.classList.contains('hidden')),true,JSON.stringify({error:await page.locator('#orders-error-message').textContent(),status:await page.locator('#order-detail-status').innerText()}));
  await page.locator('#order-detail-status').getByRole('button',{name:'待报单',exact:true}).waitFor();
  await confirmDeliverable(page);const reportCard=page.locator('.order-report-card'),headingBox=await reportCard.getByRole('heading',{name:'报单',exact:true}).boundingBox(),buttonBox=await reportCard.getByRole('button',{name:'生成报单'}).boundingBox();assert.ok(headingBox&&buttonBox&&Math.abs((headingBox.y+headingBox.height/2)-(buttonBox.y+buttonBox.height/2))<4);assert.match(await reportCard.innerText(),/客户确认\s+已确认 ✓/);assert.match(await reportCard.innerText(),/商品信息\s+✅ 完整/);assert.match(await reportCard.innerText(),/包裹信息\s+共 2 个/);await reportCard.getByRole('button',{name:'生成报单'}).click();await page.getByRole('button',{name:'下载TXT'}).click();await page.locator('#order-detail-status').getByRole('button',{name:'待收货',exact:true}).waitFor();await page.getByLabel('当前操作包裹').selectOption({label:'YB包裹'});
  await page.locator('#order-detail-status').getByRole('button',{name:'待收货',exact:true}).click();
  await page.getByLabel('YB实际物流费AED').fill('5');
  await page.locator('.shipping-registration').getByRole('button',{name:'确定',exact:true}).click();
  await page.getByLabel('当前操作包裹').selectOption({label:'KY包裹'});
  await page.getByRole('button',{name:'拒单',exact:true}).click();
  await page.getByLabel('原因 / 备注').fill('fictional refusal');
  await page.locator('#package-outcome-dialog').getByRole('button',{name:'确认',exact:true}).click();
  await page.waitForTimeout(800);
  assert.equal(await page.locator('#orders-error').evaluate(element=>element.classList.contains('hidden')),true,await page.locator('#orders-error-message').textContent());
  assert.equal(await page.getByLabel('KY实际物流费AED').count(),1,JSON.stringify(await page.locator('.profit-package-carousel').allInnerTexts()));
  await page.getByLabel('KY实际物流费AED').fill('2');
  await page.locator('.shipping-registration').getByRole('button',{name:'确定',exact:true}).click();
  await page.getByText('AED 63.00').first().waitFor();assert.match(await readFile(path.join(saveDirectory,'E2E-FICTIONAL-1_8.31-1.txt'),'utf8'),/YB45[\s\S]*YB40[\s\S]*KY02/);
  await app.close();app=await launch(userData);page=await app.firstWindow();
  await openOrder(page,'E2E-FICTIONAL-1');
  await page.getByText('AED 63.00').first().waitFor();}finally{if(app)await app.close().catch(()=>{});
  await rm(directory,{recursive:true,force:true});}});

test('Electron 44显示取消、费用待确认和成本不完整',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'electron-orders-states-')),userData=path.join(directory,'data');let app,database;try{database=await openOrderDatabase({userDataPath:userData});const service=new OrderService(new OrderRepository(database));service.createOrder(fictionalOrder('CANCEL',{status:'cancelled_before_outbound'}));service.createOrder(fictionalOrder('WAIT',{status:'signed'}));const missing=service.createOrder(fictionalOrder('MISSING',{status:'signed',cost:null}));service.confirmPackageFee(missing.packages[0].id,{actual_fee:'5',reason:'fictional',resolution_status:'signed'});database.close();database=null;app=await launch(userData);let page=await app.firstWindow();
  await openOrder(page,'CANCEL');
  await page.locator('#order-detail-page .profit-metrics').getByText(/AED 0\.00（RMB 0\.00）/).waitFor();
  await page.keyboard.press('Escape');
  await openOrder(page,'WAIT');
  assert.equal(await page.getByLabel('YB实际物流费AED').inputValue(),'');
  await page.keyboard.press('Escape');
  await openOrder(page,'MISSING');
  await page.locator('.profit-metrics').getByText('缺失',{exact:true}).waitFor();}finally{if(database)database.close();if(app)await app.close().catch(()=>{});
  await rm(directory,{recursive:true,force:true});}});

test('Electron 44完成单包裹逐级流转、地址校验和包裹优惠',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'electron-workflow-')),userData=path.join(directory,'data'),reports=path.join(directory,'reports');let app,database;try{await mkdir(reports);database=await openOrderDatabase({userDataPath:userData});new OrderService(new OrderRepository(database)).createOrder(fictionalOrder('WORKFLOW'));database.close();database=null;app=await launch(userData,{saveDirectory:reports});const page=await app.firstWindow();acceptDialogs(page);
  await openOrder(page,'WORKFLOW');assert.equal((await page.locator('.recipient-table-row').filter({hasText:'电话'}).innerText()).includes(' '),false);
  await page.locator('#order-detail-status').getByRole('button',{name:'待确认',exact:true}).click();
  await page.locator('#order-detail-status').getByRole('button',{name:'待报单',exact:true}).waitFor();
  await confirmDeliverable(page);
  await page.locator('.order-report-card').getByRole('button',{name:'生成报单'}).click();await page.getByRole('button',{name:'下载TXT'}).click();await page.locator('#order-detail-status').getByRole('button',{name:'待收货',exact:true}).waitFor();
  await page.getByLabel('YB17优惠数值').fill('10');
  await page.locator('.profit-discount-row').getByRole('button',{name:'确定'}).click();
  await page.locator('#order-detail-page').getByText('AED 40.00',{exact:true}).first().waitFor();
  await page.locator('#order-detail-status').getByRole('button',{name:'待收货',exact:true}).click();
  assert.equal(await page.getByLabel('YB实际物流费AED').inputValue(),'');}finally{if(database)database.close();if(app)await app.close().catch(()=>{});
  await rm(directory,{recursive:true,force:true});}});

test('Electron 44完成虚构数据备份、恢复、重启和利润Excel导出',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'electron-data-')),userData=path.join(directory,'data'),exports=path.join(directory,'exports');let app,database;try{await mkdir(exports);database=await openOrderDatabase({userDataPath:userData});const service=new OrderService(new OrderRepository(database)),created=service.createOrder(fictionalOrder('BACKUP',{status:'signed'}));service.confirmPackageFee(created.packages[0].id,{actual_fee:'5',reason:'fictional',resolution_status:'signed'});new OrderAppService({database,userDataPath:userData}).recordRemittance({orderId:created.id,amountAed:'25.00',registeredAt:'2026-09-02'});database.close();database=null;app=await launch(userData,{dataDirectory:exports});let page=await app.firstWindow();
  await page.getByRole('button',{name:'订单管理'}).click();
  await page.getByRole('button',{name:'数据管理'}).click();
  await page.getByRole('button',{name:'创建订单备份'}).click();const backup=path.join(exports,'orders-backup-test.sqlite');
  await page.getByText('订单备份已创建：orders-backup-test.sqlite').waitFor();
  await access(backup);
  await page.getByRole('button',{name:'利润登记'}).click();
  await page.getByRole('button',{name:'导出当前筛选 Excel'}).click();const output=path.join(exports,'profit-export-test.xlsx');
  await page.getByText('利润表已导出：profit-export-test.xlsx（1 行）').waitFor();
  await access(output);
  await app.close();app=await launch(userData,{restoreFile:backup});page=await app.firstWindow();
  await page.getByRole('button',{name:'订单管理'}).click();
  await page.getByRole('button',{name:'数据管理'}).click();
  await page.getByRole('button',{name:'选择备份并恢复'}).click();
  await page.getByRole('checkbox',{name:/我已理解/}).check();
  await page.getByRole('button',{name:'确认恢复'}).click();
  await page.getByText('恢复完成：1 个订单，1 条商品明细').waitFor();const workbook=new ExcelJS.Workbook();
  await workbook.xlsx.readFile(output);assert.equal(typeof workbook.getWorksheet('利润明细').getCell('G2').value,'number');assert.ok((await readdir(path.join(userData,'orders','automatic-backups'))).length>=1);}finally{if(database)database.close();if(app)await app.close().catch(()=>{});
  await rm(directory,{recursive:true,force:true});}});

test('Electron 44完成Full name确认、Residence单次提示、Province补全、恢复和TXT',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'electron-recipient-')),userData=path.join(directory,'data'),reports=path.join(directory,'reports');let app,database;try{await mkdir(reports);database=await openOrderDatabase({userDataPath:userData});const service=new OrderService(new OrderRepository(database)),created=service.createOrder(fictionalOrder('RECIPIENT'));database.prepare('UPDATE orders SET customer_first_name=NULL,customer_full_name=?,province=NULL,residence=NULL WHERE id=?').run('Fictional Full Name Preserved',created.id);database.close();database=null;app=await launch(userData,{saveDirectory:reports});const page=await app.firstWindow();acceptDialogs(page);
  await openOrder(page,'RECIPIENT');assert.equal(await page.getByText('Residence未提供，请确认Street中已有足够的详细地址。',{exact:true}).count(),1);
  await page.getByRole('button',{name:'确认使用原始Full name'}).click();
  await page.getByRole('button',{name:'编辑客户信息'}).click();
  await page.getByLabel('选择收件资料字段').selectOption('province');
  await page.getByLabel('省人工值').fill('Fictional Manual Province');
  await page.getByLabel('省修改原因').fill('fictional correction');
  await page.getByRole('button',{name:'保存修改'}).click();
  await page.locator('.order-report-card').getByText('不完整',{exact:true}).waitFor();
  assert.equal(await page.locator('.order-report-card').getByRole('button',{name:'生成报单'}).isDisabled(),true);
  await page.locator('.recipient-table-row').filter({hasText:'省'}).getByText('已修改').waitFor();
  await page.locator('.recipient-table-row').filter({hasText:'省'}).getByRole('button',{name:'已修改'}).click();
  await page.getByRole('button',{name:'恢复聊单原值'}).click();
  await page.getByRole('button',{name:'编辑客户信息'}).click();
  await page.getByLabel('选择收件资料字段').selectOption('province');
  await page.getByLabel('省人工值').fill('Fictional Manual Province');
  await page.getByLabel('省修改原因').fill('fictional correction');
  await page.getByRole('button',{name:'保存修改'}).click();
  await page.locator('#order-detail-status').getByRole('button',{name:'待确认',exact:true}).click();
  await page.locator('#order-detail-status').getByRole('button',{name:'待报单',exact:true}).waitFor();
  await confirmDeliverable(page);
  await page.locator('.order-report-card').getByRole('button',{name:'生成报单'}).click();
  await page.getByRole('button',{name:'下载TXT'}).click();const txt=await readFile(path.join(reports,'RECIPIENT_9.1-1.txt'),'utf8');assert.match(txt,/Name: Fictional Full Name Preserved/);assert.match(txt,/\nResidence:\n/);assert.match(txt,/Province: Fictional Manual Province/);}finally{if(database)database.close();if(app)await app.close().catch(()=>{});
  await rm(directory,{recursive:true,force:true});}});
