import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {openOrderDatabase} from '../src/orders/database.mjs';
import {OrderRepository} from '../src/orders/order-repository.mjs';
import {OrderService,allocatePackageDiscount} from '../src/orders/order-service.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';
import {packageReportReadiness} from '../src/orders/report-readiness.mjs';

const item=(sku,quantity=1,overrides={})=>({sku_code:sku,product_name_snapshot:`${sku} Fictional Long Product Title`,quantity,unit_list_price:'100.00',unit_actual_price:'100.00',unit_cost_snapshot:'20.00',cost_source:'fictional',...overrides});
test('旧人工配送记录不能放行缺失详细地址，核对记录持久有效，空Street不可确认',async()=>{
  const f=await fixture();try{
    f.repository.saveAddressVerification({orderId:f.created.id,status:'matched',at:new Date().toISOString(),eventId:'legacy-address-check'});
    assert.equal(f.app.detail({id:f.created.id}).addressVerification.status,'unusable');
    f.app.recordAddressVerification({orderId:f.created.id,status:'matched',detailConfirmed:true});
    const reopenedService=new OrderAppService({database:f.database,userDataPath:f.directory});
    assert.equal(reopenedService.detail({id:f.created.id}).addressVerification.status,'deliverable');
    f.database.prepare('UPDATE orders SET street=? WHERE id=?').run('',f.created.id);
    assert.equal(f.app.detail({id:f.created.id}).addressVerification.status,'unusable');
    assert.throws(()=>f.app.recordAddressVerification({orderId:f.created.id,status:'matched',detailConfirmed:true}),/补全Street/);
    assert.equal(f.app.previewPackageTxt({orderId:f.created.id}).ok,false);
  }finally{await f.close();}
});
const input=(overrides={})=>({source:'manual',shopplus_order_no:'FINAL-UI-1',currency:'AED',order_status:'待发货',delivery_status:'unshipped',payment_method:'COD',shopplus_created_at:'2026-09-07T10:20:30.000Z',customer_first_name:'Fictional',customer_last_name:'Person',customer_full_name:'Fictional Person',customer_phone:'+000 000 000',customer_email:'fictional@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Example Street',residence:'',items:[item('YB45'),item('YB40'),item('KY02')],...overrides});
async function fixture(overrides={}){const directory=await mkdtemp(path.join(os.tmpdir(),'final-order-workspace-')),file=path.join(directory,'orders.sqlite'),database=await openOrderDatabase({databaseFile:file}),repository=new OrderRepository(database),service=new OrderService(repository),addressVerifier={configured:true,configurationStatus:()=>({status:'ready',reason:null}),verify:async recipient=>({status:'deliverable',normalizedAddress:'Normalized fictional address',latitudeE7:250000000,longitudeE7:550000000,matchBasis:'city:example city',addressFingerprint:(await import('../src/orders/address-delivery-verification.mjs')).addressFingerprint(recipient),checkedAt:'2026-09-07T10:00:00.000Z'})},app=new OrderAppService({database,userDataPath:directory,addressVerifier}),created=service.createOrder(input(overrides));return {directory,file,database,repository,service,app,created,close:async()=>{try{database.close();}catch{}await rm(directory,{recursive:true,force:true});}};}
const pending=(app,orderId,packageId)=>{app.confirmOrder({orderId});app.updatePackageStatus({packageId,status:'outbound_processing'});app.updatePackageStatus({packageId,status:'shipped_pending'});};

test('状态按确认、待发货、待收货、最终结果流转，更正和审计完整',async()=>{const f=await fixture({items:[item('YB45')]});try{const id=f.created.packages[0].id;assert.throws(()=>f.app.updatePackageStatus({packageId:id,status:'signed'}),/确认后/);f.app.confirmOrder({orderId:f.created.id});f.app.updatePackageStatus({packageId:id,status:'shipped_pending'});assert.throws(()=>f.app.updatePackageStatus({packageId:id,status:'refused'}),/必须填写备注/);let detail=f.app.updatePackageStatus({packageId:id,status:'signed'});assert.equal(detail.trackingStatus,'signed');assert.throws(()=>f.app.updatePackageStatus({packageId:id,status:'refused',note:'not allowed'}),/继续推进最终/);assert.throws(()=>f.app.correctPackageStatus({packageId:id,status:'refused'}),/原因/);detail=f.app.correctPackageStatus({packageId:id,status:'refused',reason:'fictional courier correction'});assert.equal(detail.trackingStatus,'refused');const events=f.database.prepare("SELECT event_type,old_value,new_value,note FROM order_events WHERE package_id=? AND event_type LIKE 'package_status_%' ORDER BY event_time,id").all(id);assert.deepEqual(events.map(row=>row.new_value),['shipped_pending','signed','refused']);assert.equal(JSON.stringify(events).includes(f.created.customer_phone),false);}finally{await f.close();}});
test('多包裹操作只改当前包裹，整体状态不提前完成',async()=>{const f=await fixture();try{const yb=f.created.packages.find(row=>row.series_code==='YB'),ky=f.created.packages.find(row=>row.series_code==='KY');f.app.confirmOrder({orderId:f.created.id});for(const parcel of [yb,ky]){f.app.updatePackageStatus({packageId:parcel.id,status:'outbound_processing'});f.app.updatePackageStatus({packageId:parcel.id,status:'shipped_pending'});}let detail=f.app.updatePackageStatus({packageId:yb.id,status:'signed'});assert.equal(detail.trackingStatus,'partial_complete');assert.equal(detail.packages.find(row=>row.id===ky.id).status,'shipped_pending');detail=f.app.updatePackageStatus({packageId:ky.id,status:'refused',note:'fictional refusal'});assert.equal(detail.trackingStatus,'completed_mixed');}finally{await f.close();}});
test('包裹优惠精确分摊，保留原始金额快照并完整回滚',async()=>{const f=await fixture({items:[item('YB45',2),item('YB40',1)]});try{const id=f.created.packages[0].id,source=f.database.prepare('SELECT id,source_line_revenue,line_gross FROM order_items ORDER BY item_sequence').all();assert.deepEqual(allocatePackageDiscount(source.map(row=>({...row,quantity:row.id===source[0].id?2:1})),301n).reduce((sum,value)=>sum+value,0n),301n);let detail=f.app.updatePackageDiscount({packageId:id,discountAed:'3.01',reason:'fictional campaign'});assert.equal(detail.packages[0].discountFils,301);assert.equal(detail.packages[0].saleFils,30000);assert.equal(detail.packages[0].dealFils,29699);assert.deepEqual(f.database.prepare('SELECT source_line_revenue FROM order_items ORDER BY item_sequence').all().map(row=>row.source_line_revenue),source.map(row=>row.source_line_revenue));const before=f.database.prepare('SELECT line_revenue,manual_discount FROM order_items ORDER BY item_sequence').all();f.database.exec("CREATE TRIGGER reject_package_discount BEFORE INSERT ON order_events WHEN NEW.event_type='package_discount_updated' BEGIN SELECT RAISE(ABORT,'fictional discount rollback'); END");assert.throws(()=>f.app.updatePackageDiscount({packageId:id,discountAed:'2.01',reason:'fictional rollback'}),/fictional discount rollback/);assert.deepEqual(f.database.prepare('SELECT line_revenue,manual_discount FROM order_items ORDER BY item_sequence').all(),before);}finally{await f.close();}});
test('利润按包裹计算：签收、拒单、NULL、0费用和总利润',async()=>{const f=await fixture();try{const yb=f.created.packages.find(row=>row.series_code==='YB'),ky=f.created.packages.find(row=>row.series_code==='KY');f.app.confirmOrder({orderId:f.created.id});for(const parcel of [yb,ky]){f.app.updatePackageStatus({packageId:parcel.id,status:'outbound_processing'});f.app.updatePackageStatus({packageId:parcel.id,status:'shipped_pending'});}let detail=f.app.updatePackageStatus({packageId:yb.id,status:'signed'});assert.equal(detail.packages.find(row=>row.id===yb.id).profitStatus,'waiting_fee');assert.equal(detail.totalProfitFils,null);detail=f.app.confirmPackageFee({packageId:yb.id,amountAed:'5.00',reason:'fictional invoice'});assert.equal(detail.packages.find(row=>row.id===yb.id).packageProfitFils,15500);assert.equal(detail.totalProfitFils,null);f.app.updatePackageStatus({packageId:ky.id,status:'refused',note:'fictional refusal'});detail=f.app.confirmPackageFee({packageId:ky.id,amountAed:'0',reason:'fictional zero invoice'});assert.equal(detail.packages.find(row=>row.id===ky.id).packageProfitFils,0);assert.equal(detail.totalProfitFils,15500);f.database.close();f.database=await openOrderDatabase({databaseFile:f.file});f.app=new OrderAppService({database:f.database,userDataPath:f.directory,addressVerifier:f.app.addressVerifier});assert.equal(f.app.detail({id:f.created.id}).totalProfitFils,15500);}finally{await f.close();}});
test('报单七项校验各自阻断，Residence缺失必须明确核对详细地址',async()=>{const f=await fixture();try{let detail=f.app.detail({id:f.created.id}),parcel=detail.packages[0];assert.equal(detail.report.readiness.checks.length,7);assert.equal(detail.report.readiness.checks.find(row=>row.key==='address').ok,false);assert.equal(detail.report.readiness.checks.find(row=>row.key==='confirmation').ok,false);let recipient=detail.report.readiness.checks.find(row=>row.key==='recipient');assert.equal(recipient.ok,false);assert.equal(recipient.blocking,true);assert.match(recipient.text,/Residence缺失.*Street/);await f.app.verifyAddress({orderId:f.created.id});f.app.confirmOrder({orderId:f.created.id});assert.equal(f.app.previewPackageTxt({packageId:parcel.id}).ok,false);assert.throws(()=>f.app.recordAddressVerification({orderId:f.created.id,status:'matched'}),/明确确认/);f.app.recordAddressVerification({orderId:f.created.id,status:'matched',detailConfirmed:true});detail=f.app.detail({id:f.created.id});recipient=detail.report.readiness.checks.find(row=>row.key==='recipient');assert.equal(recipient.ok,true);assert.equal(detail.report.readiness.ok,true);const report=f.app.previewPackageTxt({packageId:parcel.id});assert.ok(report.ok&&report.token);assert.match(report.filename,/FINAL-UI-1_9\.7-1\.txt/);assert.match(report.content,/YB45/);assert.match(report.content,/YB40/);assert.match(report.content,/KY02/);assert.equal(report.content.includes('系列包裹'),false);assert.equal(report.totalFils,30000);const sameReport=f.app.previewPackageTxt({packageId:detail.packages[1].id});assert.equal(sameReport.filename,report.filename);const oldToken=sameReport.token;f.app.updateRecipient({orderId:f.created.id,field:'street',value:'Updated Fictional Street',reason:'fictional update'});assert.throws(()=>f.app.reportForSave(oldToken),/失效/);assert.equal(f.app.detail({id:f.created.id}).addressVerification.status,'unusable');assert.equal(f.app.previewPackageTxt({orderId:f.created.id}).ok,false);}finally{await f.close();}});
test('报单编号按订单日期顺序持久分配且重启后不变化',async()=>{const f=await fixture();try{const second=f.service.createOrder(input({shopplus_order_no:'FINAL-UI-2',shopplus_created_at:'2026-09-07T11:20:30.000Z'}));assert.equal(f.database.prepare('SELECT report_number FROM orders WHERE id=?').get(f.created.id).report_number,'9.7-1');assert.equal(f.database.prepare('SELECT report_number FROM orders WHERE id=?').get(second.id).report_number,'9.7-2');f.database.close();f.database=await openOrderDatabase({databaseFile:f.file});assert.deepEqual(f.database.prepare('SELECT report_number FROM orders ORDER BY report_sequence').all().map(row=>row.report_number),['9.7-1','9.7-2']);}finally{await f.close();}});
test('报单六项门禁能分别阻止客户、地址、确认、商品、分包和金额异常',()=>{const baseOrder={address_detail_confirmed:true,order_confirmed:1,customer_last_name:'Fictional',customer_first_name:'Person',customer_phone:'+000000000',customer_email:'fictional@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Example Street'},baseParcel={id:'p1',series_code:'YB'},baseItem={package_id:'p1',sku_code:'YB45',quantity:1,unit_actual_price:10000,line_revenue:10000,line_gross:10000,manual_discount:0,actual_price_confirmed:1},cases=[['recipient',{order:{...baseOrder,customer_phone:''}}],['address',{addressStatus:'out_of_range'}],['confirmation',{order:{...baseOrder,order_confirmed:0}}],['products',{items:[{...baseItem,sku_code:''}]}],['package',{items:[{...baseItem,package_id:'other'}]}],['price',{items:[{...baseItem,actual_price_confirmed:0}]}]];for(const [key,changes] of cases){const result=packageReportReadiness({order:changes.order||baseOrder,parcel:baseParcel,items:changes.items||[baseItem],addressStatus:changes.addressStatus||'deliverable'});assert.equal(result.ok,false,key);assert.equal(result.checks.find(check=>check.key===key).ok,false,key);}const valid=packageReportReadiness({order:baseOrder,parcel:baseParcel,items:[baseItem],addressStatus:'deliverable'});assert.equal(valid.ok,true);assert.deepEqual(valid.checks.map(row=>row.key),['recipient','address','confirmation','products','package','price']);});
