import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import {mkdir,mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

const waitFor=async(check,{timeout=15000,interval=100}={})=>{
 const until=Date.now()+timeout;let result;
 while(Date.now()<until){try{result=await check();if(result)return result;}catch{}await new Promise(resolve=>setTimeout(resolve,interval));}
 throw new Error('Timed out waiting for fictional ShopPlus product inventory state');
};

test('商品库存页仅在明确操作后读取全部已上架有货目录，并把规则收纳到标题问号',async()=>{
 const directory=await mkdtemp(path.join(os.tmpdir(),'inventory-shopplus-products-'));let application;
 try{
  application=await electron.launch({executablePath:process.env.KDOCS_TEST_EXECUTABLE||electronPath,args:[...(process.env.KDOCS_TEST_EXECUTABLE?[]:['.']),`--orders-test-user-data=${directory}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});
  const page=await application.firstWindow({timeout:30000});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await application.evaluate(({ipcMain})=>{
   const smallImage='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9hK3sAAAAASUVORK5CYII=';
   globalThis.__inventoryPilotCalls=0;globalThis.__inventoryPilotScopes=[];globalThis.__inventoryPilotRefreshCalls=0;globalThis.__inventoryPilotMediaCalls=0;globalThis.__inventoryPilotSourcePricingCalls=0;globalThis.__inventoryPilotReconciliationCalls=0;globalThis.__inventoryPilotMappingCatalogCalls=0;globalThis.__inventoryPilotMappingCatalog=[];globalThis.__inventoryPilotMappingCatalogRun=null;globalThis.__inventoryPilotReconciliation=null;globalThis.__inventoryPilotMediaRun=null;globalThis.__inventoryPilotSourcePricingRun=null;globalThis.__inventoryPilotRefreshRun=null;
   globalThis.__inventoryPilotProducts=[];globalThis.__inventoryPilotLastTarget=2;
   globalThis.__inventoryPilotStatus={configured:true,productTest:null};
   const view=()=>({products:globalThis.__inventoryPilotProducts,archivedProducts:[],mappingCatalog:globalThis.__inventoryPilotMappingCatalog,mappingCatalogRun:globalThis.__inventoryPilotMappingCatalogRun,reconciliation:globalThis.__inventoryPilotReconciliation,listingHistory:[{at:'2026-09-26T11:00:00.000Z',remoteProductId:'fictional-stock-small',type:'variant_inventory',afterStockQuantity:20,result:'verified'}],limit:100,defaultTarget:2,imageMaxBytes:500*1024,canCollect:true,lastRun:globalThis.__inventoryPilotProducts.length?{at:'2026-09-25T10:00:00.000Z',target:globalThis.__inventoryPilotLastTarget,captured:globalThis.__inventoryPilotProducts.length,added:2,skippedOutOfStock:1,imageManualReview:globalThis.__inventoryPilotProducts.filter(product=>product.image?.status==='manual_review').length,limit:100}:null,refreshRun:globalThis.__inventoryPilotRefreshRun,mediaRun:globalThis.__inventoryPilotMediaRun,sourcePricingRun:globalThis.__inventoryPilotSourcePricingRun,batch:{status:'ready',captured:globalThis.__inventoryPilotProducts.length}});
   ipcMain.removeHandler('orders:shopplus-product-catalog');
   ipcMain.handle('orders:shopplus-product-catalog',async()=>({ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus}}));
   ipcMain.removeHandler('orders:sync-shopplus-products');
   ipcMain.handle('orders:sync-shopplus-products',async(_event,payload)=>{
    globalThis.__inventoryPilotCalls++;globalThis.__inventoryPilotScopes.push(payload?.scope||null);globalThis.__inventoryPilotLastTarget=payload?.scope==='published-in-stock'?'published-in-stock':payload?.target||2;
    globalThis.__inventoryPilotStatus={configured:true,productTest:{status:'verified',at:'2026-09-25T10:00:00.000Z',message:'已通过虚构 ShopPlus 商品读取验证'}};
    globalThis.__inventoryPilotProducts=[
     {remoteProductId:'fictional-stock-small',productNumber:'SP-KY40-BLK-000001',sourceSpu:'KY40-BLK',name:'KY40 黑色（虚构）',sourceName:'KY40 黑色（虚构）',websitePriceAed:300,stockQuantity:20,publishStatus:1,variants:[{id:'fictional-variant-black',stockQuantity:20}],sourcePricing:{status:'matched',method:'商品编号精确匹配',sourceStock:'有货'},floorPriceAed:180,description:'<h2>KY40 产品介绍</h2><p>轻便&nbsp;<strong>耐用</strong></p><ul><li>适合日常使用</li><br><br><li>库存以网站为准</li></ul><script>不得显示</script>',image:{status:'cached',dataUrl:smallImage,byteLength:499*1024,mimeType:'image/png'}},
     {remoteProductId:'fictional-stock-large',productNumber:'SP-KY40-WHT-000002',sourceSpu:'KY40-WHT',name:'KY40 白色（虚构）',sourceName:'KY40 白色（虚构）',websitePriceAed:320,stockQuantity:8,variants:[{id:'fictional-variant-white',stockQuantity:8}],floorPriceAed:null,description:'虚构大图产品介绍',image:{status:'manual_review',dataUrl:null,byteLength:500*1024,reviewReason:'图片达到或超过 500 KiB，未缓存，待人工确认'}}
    ];
    globalThis.__inventoryPilotMappingCatalog=globalThis.__inventoryPilotProducts.map(product=>({...product,stockKnown:true}));globalThis.__inventoryPilotMappingCatalogRun={at:'2026-09-26T10:05:00.000Z',captured:2,listed:2,unlisted:0,outOfStock:0};
    return {ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus,collected:true}};
   });
   ipcMain.removeHandler('orders:sync-shopplus-mapping-catalog');
   ipcMain.handle('orders:sync-shopplus-mapping-catalog',async()=>{globalThis.__inventoryPilotMappingCatalogCalls++;await new Promise(resolve=>setTimeout(resolve,220));if(globalThis.__inventoryPilotMappingCatalogFailure)throw new Error('虚构网站目录暂时不可读取');globalThis.__inventoryPilotMappingCatalog=[...globalThis.__inventoryPilotProducts.map(product=>({...product,stockKnown:true})),{remoteProductId:'fictional-unlisted',productNumber:'SP-UNLISTED-000003',sourceSpu:'037',name:'037（虚构下架）',sourceName:'037（虚构下架）',websitePriceAed:265,stockKnown:true,stockQuantity:0,publishStatus:0,variants:[{id:'fictional-variant-unlisted',stockQuantity:0}]}];globalThis.__inventoryPilotMappingCatalogRun={at:'2026-09-26T10:05:00.000Z',captured:3,listed:2,unlisted:1,outOfStock:1};return {ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus,synced:true}};});
   ipcMain.removeHandler('orders:refresh-shopplus-products');
   ipcMain.handle('orders:refresh-shopplus-products',async()=>{
    globalThis.__inventoryPilotRefreshCalls++;const first=globalThis.__inventoryPilotProducts[0];first.websitePriceAed=301;first.refresh={status:'refreshed',at:'2026-09-26T10:30:00.000Z'};globalThis.__inventoryPilotRefreshRun={at:'2026-09-26T10:30:00.000Z',received:2,pages:1,totalCount:2,requestedProducts:2,refreshed:2,missing:0};return {ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus,refreshed:true}};
   });
   ipcMain.removeHandler('orders:sync-shopplus-product-media');
   ipcMain.handle('orders:sync-shopplus-product-media',async()=>{
    globalThis.__inventoryPilotMediaCalls++;
    const first=globalThis.__inventoryPilotProducts[0],second=globalThis.__inventoryPilotProducts[1];
    first.images=[first.image,{status:'cached',dataUrl:smallImage,byteLength:400*1024,mimeType:'image/png'},{status:'manual_review',dataUrl:null,byteLength:500*1024,reviewReason:'图片达到或超过 500 KiB，未缓存，待人工确认'}];first.image=first.images[0];first.media={status:'completed',sourceImageCount:3,cachedImageCount:2,manualReviewImageCount:1,unavailableImageCount:0};
    second.images=[second.image];second.media={status:'completed',sourceImageCount:1,cachedImageCount:0,manualReviewImageCount:1,unavailableImageCount:0};
    globalThis.__inventoryPilotMediaRun={sourceImages:4,cachedImages:2,manualReviewImages:2,unavailableImages:0};
    return {ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus,collected:true}};
   });
   ipcMain.removeHandler('orders:integrate-shopplus-source-pricing');
   ipcMain.handle('orders:integrate-shopplus-source-pricing',async()=>{
    globalThis.__inventoryPilotSourcePricingCalls++;
    const [first,second]=globalThis.__inventoryPilotProducts;
    first.costPriceAed=100;first.suggestedPriceAed=200;first.sourcePricing={status:'matched',method:'商品编号精确匹配',sourceBusinessId:first.productNumber,sourceName:'虚构来源黑色'};
    second.costPriceAed=120;second.suggestedPriceAed=240;second.sourcePricing={status:'matched',method:'商品名称唯一精确匹配',sourceBusinessId:'FIC-WHITE',sourceName:second.sourceName};
    globalThis.__inventoryPilotSourcePricingRun={at:'2026-09-26T10:00:00.000Z',sourceUpdatedAt:'2026-09-26T09:30:00.000Z',sourceCount:2,matched:2,updated:2,unmatched:0,blank:0};
    return {ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus,sourcePricing:true}};
   });
   ipcMain.removeHandler('orders:reconcile-shopplus-source-data');
   ipcMain.handle('orders:reconcile-shopplus-source-data',async()=>{globalThis.__inventoryPilotReconciliationCalls++;globalThis.__inventoryPilotReconciliation={status:'pending',at:'2026-09-27T10:00:00.000Z',summary:{mapped:1,changed:1,sourceChanged:1,websiteChanged:1,conflicts:1,sourceMissing:0,websiteMissing:0,newSource:0,removedSource:0,firstBaseline:true},rows:[{remoteProductId:'fictional-stock-small',name:'KY40 黑色（虚构）',source:{costPriceAed:110,suggestedPriceAed:220,sourceStock:'无货'},website:{websitePriceAed:333,stockKnown:true,stockQuantity:0,publishStatus:0,variants:[{id:'fictional-variant-black',stockQuantity:0}]},before:{source:{costPriceAed:100,suggestedPriceAed:200,sourceStock:'有货'},website:{websitePriceAed:300,stockKnown:true,stockQuantity:20,publishStatus:1}},changes:['来源成本发生变化','网站库存数量发生变化','状态不一致：来源无货，但网站仍上架且有库存']} ]};return {ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus,reconciled:true}};});
   ipcMain.removeHandler('orders:apply-shopplus-source-reconciliation');
   ipcMain.handle('orders:apply-shopplus-source-reconciliation',async()=>{globalThis.__inventoryPilotReconciliation={...globalThis.__inventoryPilotReconciliation,status:'applied',appliedAt:'2026-09-27T10:01:00.000Z'};return {ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus,applied:true}};});
   ipcMain.removeHandler('inventory:local');
   ipcMain.handle('inventory:local',async()=>({ok:true,data:{updatedAt:'2026-09-26T10:00:00.000Z',latestCollection:{capturedAt:'2026-09-26T09:55:00.000Z',products:[{sourceName:'KY40 黑色来源资料'},{sourceName:'KY40 白色来源资料'},{sourceName:'尚未编号的虚构来源资料'}]},current:{capturedAt:'2026-09-26T09:55:00.000Z',savedAt:'2026-09-26T10:00:00.000Z',products:[{businessId:'SP-KY40-BLK-000001',sourceName:'KY40 黑色（虚构）',cost:'100',suggestedPrice:'200',stock:'有货'}]}}}));
   globalThis.__sourceLoginState='idle';globalThis.__sourceLoginCalls=0;globalThis.__sourceSyncCalls=0;
   ipcMain.removeHandler('kdocs:login');
   ipcMain.handle('kdocs:login',async()=>{globalThis.__sourceLoginCalls++;globalThis.__sourceLoginState='awaiting_login';return {ok:true,data:{state:'awaiting_login',browserName:'虚构 Chrome',keptOpen:true}};});
   ipcMain.removeHandler('kdocs:login-status');
   ipcMain.handle('kdocs:login-status',async()=>({ok:true,data:{state:globalThis.__sourceLoginState,browserName:'虚构 Chrome',keptOpen:globalThis.__sourceLoginState==='ready'||globalThis.__sourceLoginState==='awaiting_login'}}));
   ipcMain.removeHandler('source:sync-local');
   ipcMain.handle('source:sync-local',async event=>{globalThis.__sourceSyncCalls++;event.sender.send('app:progress',{stage:'KDocs采集',message:'已扫描 86/200 行',currentRow:86,endRow:200});await new Promise(resolve=>setTimeout(resolve,180));event.sender.send('app:progress',{stage:'完成',message:'✅ 已完成 200 条来源资料'});return {ok:true,data:{action:'complete',mapping:{rows:[]}}};});
   globalThis.__mappingStatusCalls=0;globalThis.__mappingSaveCalls=0;
   let mappingRows=[
    {sourceKey:'MODEL:KY40-BLK',sourceName:'KY40 黑色来源资料',businessId:'SP-KY40-BLK-000001',status:'待确认',note:'第一轮候选（网站编号唯一一致）：KY40 黑色（虚构）；待人工复核'},
    {sourceKey:'MODEL:KY40-WHT',sourceName:'KY40 白色来源资料',businessId:'SP-KY40-WHT-000002',status:'待确认',note:'第一轮候选（网站编号唯一一致）：KY40 白色（虚构）；待人工复核'},
    {sourceKey:'MODEL:UNASSIGNED',sourceName:'尚未编号的虚构来源资料',businessId:'',status:'待编号',note:'没有可确认的网站商品编号'}
   ];
   const mappingReply=()=>({status:'pending',summary:{total:mappingRows.length,automatic:mappingRows.filter(row=>row.status==='正常').length,needsConfirmation:mappingRows.filter(row=>row.status==='待确认').length,pendingNumber:mappingRows.filter(row=>row.status==='待编号').length},mapping:{rows:mappingRows,review:mappingRows.filter(row=>row.status!=='正常')}});
   ipcMain.removeHandler('mapping:status');
   ipcMain.handle('mapping:status',async()=>{globalThis.__mappingStatusCalls++;return {ok:true,data:mappingReply()};});
   ipcMain.removeHandler('sync:mapping');
   ipcMain.handle('sync:mapping',async(_event,payload)=>{globalThis.__mappingSaveCalls++;const answers=new Map((payload?.answers||[]).map(row=>[row.sourceKey,{businessId:String(row.businessId||''),action:String(row.action||'')} ]));mappingRows=mappingRows.map(row=>{if(!answers.has(row.sourceKey))return row;const answer=answers.get(row.sourceKey),businessId=answer.businessId;if(answer.action==='ignore')return {...row,businessId:'',status:'本机已忽略',note:`${row.note}；虚构本机重复项已忽略`};if(answer.action==='restore')return {...row,businessId:'',status:'待编号',note:`${row.note}；虚构本机恢复核对`};if(!businessId)return {...row,businessId:'',status:'待编号',note:`${row.note}；虚构本机确认已取消`};return {...row,businessId,status:'正常',note:`${row.note}${row.status==='正常'&&row.businessId!==businessId?'；虚构本机确认已更正':'；虚构本机确认'}`};});return {ok:true,data:globalThis.__mappingSaveCalls===1?{action:'complete',result:{ok:true}}:mappingReply()};});
   ipcMain.removeHandler('orders:update-shopplus-product');
   ipcMain.handle('orders:update-shopplus-product',async(_event,payload)=>{
    const product=globalThis.__inventoryPilotProducts.find(item=>item.remoteProductId===payload.remoteProductId);if(!product)return {ok:false,error:{message:'找不到虚构商品'}};
    product.name=payload.name;product.floorPriceAed=payload.floorPrice===''?null:Number(payload.floorPrice);product.description=payload.description;return {ok:true,data:{catalog:view(),status:globalThis.__inventoryPilotStatus}};
   });
  });
  const frame=page.frameLocator('iframe.confirmed-frame');
  await frame.getByRole('button',{name:'商品库存',exact:true}).click();
  await frame.locator('#ui011-inventory').waitFor();
  const bridgeState=await frame.locator('#ui011-inventory').evaluate(()=>({selfPilot:typeof window.shopPlusProductPilot?.catalog,parentPilot:typeof window.parent?.shopPlusProductPilot?.catalog,selfInventory:typeof window.inventoryApp?.status,parentInventory:typeof window.parent?.inventoryApp?.status}));
  assert.deepEqual(bridgeState,{selfPilot:'undefined',parentPilot:'function',selfInventory:'undefined',parentInventory:'function'});
  assert.equal(await frame.locator('#ui011-connection-label').textContent(),'ShopPlus 商品读取待验证');
  await frame.locator('#ui011-page-help').click();
  await frame.locator('#ui011-popover').waitFor({state:'visible'});
  assert.match(await frame.locator('#ui011-popover').textContent()||'',/网站库存大于等于 2/);
  assert.match(await frame.locator('#ui011-popover').textContent()||'',/不再有 100 款截断/);
  assert.match(await frame.locator('#ui011-popover').textContent()||'',/500 KiB/);
  await frame.locator('#ui011-close-popover').click();
  await frame.locator('#ui011-product-manager').click();
  const manager=frame.locator('dialog.shared-dialog').filter({hasText:'采集与更新商品'});
  await manager.waitFor({state:'visible'});
  assert.equal(await manager.locator('#ui011-manager-refresh').isDisabled(),true,'未采集商品前不能伪造网站资料更新');
  assert.match(await manager.textContent()||'',/上架／下架请进入“来源资料”/);
  await manager.locator('#ui011-manager-collect').click();
  await waitFor(async()=>await frame.locator('#ui011-rows tr').count()===2);
  assert.equal(await application.evaluate(()=>globalThis.__inventoryPilotCalls),1,'仅通过明确按钮触发一次虚构商品读取');
  assert.deepEqual(await application.evaluate(()=>globalThis.__inventoryPilotScopes),['published-in-stock']);
  await manager.locator('#ui011-manager-close').click();
  assert.equal(await frame.locator('#ui011-connection-label').textContent(),'ShopPlus 商品读取已验证');
  assert.deepEqual(await frame.locator('#ui011-inventory thead th').allTextContents(),['序号','商品名称','网站售价（AED）','网站库存','上架状态','操作']);
  assert.deepEqual(await frame.locator('#ui011-rows tr').allTextContents(),['1KY40 黑色（虚构）AED 300.00有库存 · 20已上架商品操作','2KY40 白色（虚构）AED 320.00有库存 · 8待同步商品操作']);
  assert.equal(await frame.locator('#ui011-product-manager').innerText(),'采集与更新商品','顶部入口明确用于全量采集与刷新已有资料');
  assert.equal(await frame.locator('#ui011-rows tr').first().getByRole('button',{name:'商品操作',exact:true}).count(),1,'单商品操作不再与顶部批量入口同名');
  const actionDialog=frame.locator('dialog.shared-dialog').filter({hasText:'商品操作 · KY40 黑色（虚构）'});
  await frame.locator('#ui011-rows tr').first().getByRole('button',{name:'商品操作',exact:true}).click();
  await actionDialog.waitFor({state:'visible'});
  assert.match(await actionDialog.textContent()||'',/进入详情（调整库存）/,'单商品入口保留详情及库存调整路径');
  await actionDialog.getByRole('button',{name:'关闭',exact:true}).click();
  assert.equal(await frame.locator('#ui011-page-summary').textContent(),'本页第 1–2 项 · 共 2 项');
  assert.equal(await frame.locator('#ui011-page-current').textContent(),'1 / 1');
  assert.equal(await frame.locator('#ui011-page-prev').isDisabled(),true,'两款试采集结果只有一页，上一页不可伪装为可用');
  assert.equal(await frame.locator('#ui011-page-next').isDisabled(),true,'两款试采集结果只有一页，下一页不可伪装为可用');
  await frame.locator('#ui011-sort').selectOption('price-desc');
  assert.match(await frame.locator('#ui011-rows tr').first().textContent()||'',/^1KY40 白色（虚构）AED 320\.00/,'底部排序真实改变当前两款虚构商品的显示顺序');
  await frame.locator('#ui011-sort').selectOption('captured');
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.isVisible())?.setContentSize(1440,1000));
  await page.waitForTimeout(180);
  await frame.locator('#ui011-source-library').click();
  await frame.locator('#ui-source-library').waitFor();
  assert.deepEqual(await frame.locator('#ui-source-library header .actions button').allTextContents(),['← 返回商品库存','查看来源表']);
  assert.equal(await frame.locator('#source-workflow li').count(),6,'来源资料页按六步展示顺序与操作');
  assert.equal(await frame.locator('#source-source-snapshot').evaluate(node=>node.open),false,'详细快照卡默认收起');
  assert.equal(await frame.locator('#source-mapping-card').evaluate(node=>node.open),false,'人工对应卡默认收起');
  if(process.env.KDOCS_COLLAPSED_CARDS_SCREENSHOT){await mkdir(path.dirname(process.env.KDOCS_COLLAPSED_CARDS_SCREENSHOT),{recursive:true});await page.screenshot({path:process.env.KDOCS_COLLAPSED_CARDS_SCREENSHOT});}
  await frame.locator('#source-mapping-card > summary').click();
  assert.equal(await frame.locator('#source-mapping-card').evaluate(node=>node.open),true,'点击标题可展开人工对应卡');
  assert.equal(await frame.locator('#source-login-check').isDisabled(),true,'未打开受控登录窗口时不能检测登录状态');
  assert.equal(await frame.locator('#source-sync').isDisabled(),true,'未登录时同步入口必须锁定，而不是无反馈点击');
  assert.equal(await frame.getByRole('button',{name:'读取网站最新资料并生成差异',exact:true}).isDisabled(),true,'本次未同步来源资料时不能跳过前置步骤读取网站');
  assert.match(await frame.locator('#source-sync-progress').textContent()||'',/下一步：点击“登录来源资料”/,'页面明确告诉用户下一步，而不是让用户猜测');
  await waitFor(async()=>await frame.locator('#source-mapping-table tbody tr').count()===2);
  assert.equal(await application.evaluate(()=>globalThis.__mappingStatusCalls),1,'进入来源资料页即只读加载本机映射候选，不要求再次同步');
  assert.match(await frame.locator('#source-mapping-summary').textContent()||'',/3 条来源资料 · 2 条系统建议待确认（不占用商品） · 1 条待选择/);
  assert.match(await frame.locator('#source-mapping-table tbody tr').first().textContent()||'',/KY40 黑色来源资料/);
  assert.match(await frame.locator('#source-mapping-table tbody tr').first().textContent()||'',/KY40 黑色（虚构）/,'候选行同时显示网站商品名称');
  assert.match(await frame.locator('#source-mapping-table tbody tr').first().textContent()||'',/ShopPlus 商品 ID：fictional-stock-small/);
  assert.match(await frame.locator('#source-mapping-table tbody tr').first().textContent()||'',/规格 ID：fictional-variant-black/);
  assert.equal(await frame.locator('#source-mapping-table tbody tr').first().getByRole('link',{name:'打开商品后台'}).getAttribute('href'),'https://portal.shoplus.net/admin/products/fictional-stock-small');
  await application.evaluate(({ipcMain})=>{globalThis.__shopPlusOpenCalls=[];ipcMain.removeHandler('shopplus:open-product');ipcMain.handle('shopplus:open-product',async(_event,payload)=>{globalThis.__shopPlusOpenCalls.push(payload?.remoteProductId);return {ok:true,data:{opened:true,url:`https://portal.shoplus.net/admin/products/${payload?.remoteProductId}`}};});});
  await frame.locator('#source-mapping-table tbody tr').first().getByRole('link',{name:'打开商品后台'}).click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__shopPlusOpenCalls.length)===1);
  assert.deepEqual(await application.evaluate(()=>globalThis.__shopPlusOpenCalls),['fictional-stock-small'],'商品后台入口只把已采集的 ShopPlus 商品 ID 交给受控外部浏览器入口');
  assert.doesNotMatch(await frame.locator('#source-mapping-table').textContent()||'',/SP-KY40-BLK-000001/,'本机追踪键不再显示为网站编号或人工输入项');
  assert.equal(await frame.getByRole('button',{name:'保存本机确认结果',exact:true}).isDisabled(),true,'未明确确认前不能保存候选');
  assert.equal(await frame.locator('#source-mapping-table-wrap').count(),1,'来源核对表使用自身滚动容器，避免破坏整页布局');
  if(process.env.KDOCS_SOURCE_MAPPING_SCREENSHOT){await mkdir(path.dirname(process.env.KDOCS_SOURCE_MAPPING_SCREENSHOT),{recursive:true});await page.screenshot({path:process.env.KDOCS_SOURCE_MAPPING_SCREENSHOT});}
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.isVisible())?.setContentSize(820,640));
  await page.waitForTimeout(180);
  const mappingNarrow=await frame.locator('.mapping-table-wrap').evaluate(node=>({clientWidth:node.clientWidth,scrollWidth:node.scrollWidth}));
  assert.ok(mappingNarrow.scrollWidth>mappingNarrow.clientWidth,`窄窗口通过候选表自身横向滚动保持字段独立：${JSON.stringify(mappingNarrow)}`);
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.isVisible())?.setContentSize(1280,820));
  await page.waitForTimeout(180);
  await frame.locator('#source-mapping-filter').selectOption('all');
  assert.equal(await frame.locator('#source-mapping-table tbody tr').count(),3,'全部筛选展示待编号来源资料');
  await frame.locator('#source-mapping-filter').selectOption('candidate');
  const firstCandidate=frame.locator('#source-mapping-table tbody tr').first();
  await firstCandidate.getByRole('button',{name:'确认对应',exact:true}).click();
  assert.equal(await application.evaluate(()=>globalThis.__mappingSaveCalls),0,'单条确认先保持为待保存决定，不会立即写入');
  await frame.getByRole('button',{name:'保存本机确认结果',exact:true}).click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__mappingSaveCalls)===1);
  await waitFor(async()=>await application.evaluate(()=>globalThis.__mappingStatusCalls)>=2);
  assert.equal(await frame.locator('#source-mapping-table tbody tr').count(),1,'完成回执后必须回读映射，并保留当前待确认候选');
  assert.match(await frame.locator('#source-mapping-table tbody tr').first().textContent()||'',/KY40 白色来源资料/,'未点击确认的另一候选保存后仍保持待确认');
  assert.match(await frame.locator('#source-mapping-summary').textContent()||'',/3 条来源资料/,'保存接口只返回完成结果时，页面仍从本机重新读取完整映射，不会误报没有候选');
  await frame.locator('#source-mapping-table tbody tr').first().getByRole('button',{name:'不对应',exact:true}).click();
  assert.match(await frame.locator('#source-mapping-table tbody').textContent()||'',/没有符合当前筛选条件/,'标记不对应后该候选从待确认列表移除，等待另选商品');
  await frame.getByRole('button',{name:'保存本机确认结果',exact:true}).click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__mappingSaveCalls)===2);
  await frame.locator('#source-mapping-filter').selectOption('unassigned');
  const unassigned=frame.locator('#source-mapping-table tbody tr').filter({hasText:'KY40 白色来源资料'});
  await unassigned.getByRole('button',{name:'选择网站商品',exact:true}).click();
  const picker=frame.locator('dialog.mapping-candidate-dialog');await picker.waitFor({state:'visible'});
  assert.equal(await picker.getByRole('searchbox',{name:'搜索已采集网站商品'}).count(),1,'候选面板提供独立搜索');
  assert.match(await picker.textContent()||'',/系统推荐.*其他备选/,'候选面板分为系统推荐和其他备选两部分');
  assert.match(await picker.locator('.mapping-candidate.is-recommended').textContent()||'',/KY40 白色（虚构）/,'系统将网站标识精确一致的商品置顶推荐');
  if(process.env.KDOCS_CANDIDATE_PICKER_SCREENSHOT){await mkdir(path.dirname(process.env.KDOCS_CANDIDATE_PICKER_SCREENSHOT),{recursive:true});await page.screenshot({path:process.env.KDOCS_CANDIDATE_PICKER_SCREENSHOT});}
  await picker.getByRole('searchbox',{name:'搜索已采集网站商品'}).fill('fictional-stock-small');
  assert.match(await picker.locator('.mapping-candidate-list').textContent()||'',/KY40 黑色（虚构）/,'搜索可命中已采集商品 ID，不删除旧商品');
  await picker.getByRole('searchbox',{name:'搜索已采集网站商品'}).fill('KY40-WHT');
  await picker.locator('.mapping-candidate.is-recommended').click();
  await picker.getByRole('button',{name:'选择并标记确认',exact:true}).click();
  await frame.getByRole('button',{name:'保存本机确认结果',exact:true}).click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__mappingSaveCalls)===3);
  await frame.locator('#source-mapping-filter').selectOption('confirmed');
  const savedMapping=frame.locator('#source-mapping-table tbody tr').filter({hasText:'KY40 黑色来源资料'});
  await savedMapping.getByRole('button',{name:'更正对应',exact:true}).click();
  const correctionPicker=frame.locator('dialog.mapping-candidate-dialog');await correctionPicker.waitFor({state:'visible'});
  assert.equal(await correctionPicker.getByRole('searchbox',{name:'搜索已采集网站商品'}).count(),1,'旧已确认关系更正也使用可搜索选择器');
  await correctionPicker.getByRole('button',{name:'取消',exact:true}).click();
  await savedMapping.getByRole('button',{name:'取消确认',exact:true}).click();
  assert.equal(await frame.getByRole('button',{name:'保存本机确认结果',exact:true}).isDisabled(),false,'取消已保存关系只标记为待保存，不会立即写入');
  await frame.getByRole('button',{name:'保存本机确认结果',exact:true}).click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__mappingSaveCalls)===4);
  await frame.locator('#source-mapping-filter').selectOption('all');
  const duplicateRow=frame.locator('#source-mapping-table tbody tr').filter({hasText:'尚未编号的虚构来源资料'});
  await duplicateRow.getByRole('button',{name:'本机忽略重复项',exact:true}).click();
  const ignoreDialog=frame.locator('dialog.shared-dialog').filter({hasText:'本机忽略重复来源资料'});await ignoreDialog.waitFor({state:'visible'});
  assert.match(await ignoreDialog.textContent()||'',/不会删除或编辑来源资料/,'重复项处理明确说明只在本机进行');
  await ignoreDialog.getByRole('button',{name:'仅本机忽略',exact:true}).click();
  await frame.getByRole('button',{name:'保存本机确认结果',exact:true}).click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__mappingSaveCalls)===5);
  await frame.locator('#source-mapping-filter').selectOption('ignored');
  const ignoredRow=frame.locator('#source-mapping-table tbody tr').filter({hasText:'尚未编号的虚构来源资料'});
  assert.equal(await ignoredRow.count(),1,'本机忽略项可单独查看，而不是删除来源资料');
  await ignoredRow.getByRole('button',{name:'恢复核对',exact:true}).click();
  await frame.getByRole('button',{name:'保存本机确认结果',exact:true}).click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__mappingSaveCalls)===6);
  await frame.locator('#source-mapping-filter').selectOption('unassigned');
  assert.equal(await frame.locator('#source-mapping-table tbody tr').filter({hasText:'尚未编号的虚构来源资料'}).count(),1,'恢复后来源资料重新进入待选择列表');
  assert.equal(await application.evaluate(()=>globalThis.__sourceSyncCalls),0,'浏览和保存本机映射不会重新读取来源资料');
  assert.equal(await frame.locator('#source-sync').isDisabled(),true,'未登录时同步按钮保持锁定');
  assert.match(await frame.locator('#source-login-state').textContent()||'',/尚未打开/);
  await frame.locator('#source-login').click();
  assert.equal(await application.evaluate(()=>globalThis.__sourceLoginCalls),1,'登录只打开受控窗口，不读取来源资料');
  assert.match(await frame.locator('#source-login-state').textContent()||'',/二维码刷新/);
  assert.equal(await frame.locator('#source-sync').isDisabled(),true,'等待扫码时不能提前同步');
  await frame.locator('#source-login-check').click();
  assert.equal(await application.evaluate(()=>globalThis.__sourceSyncCalls),0,'等待扫码时检测不会启动同步');
  await application.evaluate(()=>{globalThis.__sourceLoginState='ready';});
  await frame.locator('#source-login-check').click();
  assert.match(await frame.locator('#source-login-state').textContent()||'',/登录已确认/);
  assert.equal(await frame.locator('#source-sync').isDisabled(),false,'检测确认登录后才解锁同步');
  const syncClick=frame.locator('#source-sync').click();
  await waitFor(async()=>/86\/200 行/.test(await frame.locator('#source-sync-progress').textContent()||''));
  assert.equal(await frame.locator('#source-login').isDisabled(),true,'同步中锁定登录入口，避免改变同步前提');
  assert.equal(await frame.locator('#source-login-check').isDisabled(),true,'同步中锁定登录检测，避免改变同步前提');
  await syncClick;
  assert.equal(await application.evaluate(()=>globalThis.__sourceSyncCalls),1,'登录确认后仍须用户明确点击才开始来源同步');
  await waitFor(async()=>!(await frame.locator('#source-sync').isDisabled()));
  assert.equal(await frame.locator('#source-source-snapshot').evaluate(node=>node.open),true,'来源同步完成后自动展开来源快照');
  assert.match(await frame.locator('#source-source-snapshot-table').textContent()||'',/当前显示 3 个来源商品；来源表原始资料 3 行（应为 199 行，异常）/,'来源快照表尾应区分筛选后的来源商品数与原始资料行数，并明确提示总行数异常');
  if(process.env.KDOCS_SOURCE_SNAPSHOT_SCREENSHOT){await mkdir(path.dirname(process.env.KDOCS_SOURCE_SNAPSHOT_SCREENSHOT),{recursive:true});await frame.locator('#source-source-snapshot').scrollIntoViewIfNeeded();await page.screenshot({path:process.env.KDOCS_SOURCE_SNAPSHOT_SCREENSHOT});}
  assert.equal(await frame.locator('#source-website-sync').isDisabled(),false,'来源快照完成后才解锁网站产品快照');
  const websiteSyncClick=frame.locator('#source-website-sync').click();
  await waitFor(async()=>await frame.locator('#source-website-sync').isDisabled());
  assert.equal(await frame.locator('#source-website-sync').innerText(),'正在同步网站产品…','同步中按钮须明确说明正在进行');
  assert.match(await frame.locator('#source-website-sync-state').textContent()||'',/正在同步网站产品到本机/,'同步中状态须保留在第四步内');
  if(process.env.KDOCS_WEBSITE_SYNC_SCREENSHOT){await mkdir(path.dirname(process.env.KDOCS_WEBSITE_SYNC_SCREENSHOT),{recursive:true});await page.screenshot({path:process.env.KDOCS_WEBSITE_SYNC_SCREENSHOT});}
  await websiteSyncClick;
  await waitFor(async()=>await application.evaluate(()=>globalThis.__inventoryPilotMappingCatalogCalls)===1);
  await waitFor(async()=>/已同步 ✓/.test(await frame.locator('#source-website-sync-state').textContent()||''));
  assert.equal(await frame.locator('#source-website-snapshot').evaluate(node=>node.open),true,'网站同步完成后自动展开网站快照');
  assert.match(await frame.locator('#source-website-snapshot-table').textContent()||'',/037（虚构下架）/,'网站本机快照包含下架、无货商品');
  assert.match(await frame.locator('#source-website-snapshot-table').textContent()||'',/网站标识.*ShopPlus 商品 ID.*规格 ID/,'网站快照应分开显示网站标识、商品 ID 和规格 ID');
  assert.match(await frame.locator('#source-website-snapshot-table').textContent()||'',/037.*fictional-unlisted.*fictional-variant-unlisted/,'三个网站识别字段应分别展示，不与商品名称混淆');
  if(process.env.KDOCS_WEBSITE_SNAPSHOT_SCREENSHOT){await mkdir(path.dirname(process.env.KDOCS_WEBSITE_SNAPSHOT_SCREENSHOT),{recursive:true});await frame.locator('#source-website-snapshot').scrollIntoViewIfNeeded();await page.screenshot({path:process.env.KDOCS_WEBSITE_SNAPSHOT_SCREENSHOT});}
  assert.equal(await frame.locator('#source-website-sync').innerText(),'重新同步网站产品','成功后按钮应明确可再次刷新');
  assert.match(await frame.locator('#source-website-sync-state').textContent()||'',/已同步 ✓/,'成功后须在第四步明确显示已同步');
  await application.evaluate(()=>{globalThis.__inventoryPilotMappingCatalogFailure=true;});
  await frame.getByRole('button',{name:'重新同步网站产品',exact:true}).click();
  await waitFor(async()=>/同步失败，可重试/.test(await frame.locator('#source-website-sync-state').textContent()||''));
  assert.equal(await frame.locator('#source-website-sync').innerText(),'重试同步网站产品','失败后必须明确可重试，而不是误称已同步');
  assert.equal(await frame.locator('#source-website-sync').isDisabled(),false,'失败结束后允许用户明确重试');
  await application.evaluate(()=>{globalThis.__inventoryPilotMappingCatalogFailure=false;});
  await frame.locator('#source-mapping-jump').click();
  assert.equal(await frame.locator('#source-mapping-card').evaluate(node=>node.open),true,'查看对应关系会展开对应卡片');
  assert.equal(await frame.getByRole('button',{name:'读取网站最新资料并生成差异',exact:true}).isDisabled(),false,'两份当前快照与映射可用后才解锁变化核对');
  assert.match(await frame.locator('#source-sync-progress').textContent()||'',/读取已确认映射商品/);
  await frame.getByRole('button',{name:'读取网站最新资料并生成差异',exact:true}).click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__inventoryPilotReconciliationCalls)===1);
  assert.equal(await frame.locator('#source-reconciliation-card').evaluate(node=>node.open),true,'读取变化后自动展开变化核对卡片');
  assert.match(await frame.locator('#source-reconciliation').textContent()||'',/来源成本发生变化/,'来源成本、建议售价和有货状态先以差异显示');
  assert.match(await frame.locator('#source-reconciliation').textContent()||'',/网站库存数量发生变化/,'网站售价、库存和上架状态先以差异显示');
  assert.match(await frame.locator('#source-reconciliation').textContent()||'',/状态不一致/,'来源无货与网站库存仍分列，并提示冲突');
  await frame.getByRole('button',{name:'确认更新本机平台资料',exact:true}).click();
  const reconciliationDialog=frame.locator('dialog.shared-dialog').filter({hasText:'确认更新本机平台资料'});await reconciliationDialog.waitFor({state:'visible'});
  await reconciliationDialog.getByRole('button',{name:'确认更新本机资料',exact:true}).click();
  await waitFor(async()=>/已于/.test(await frame.locator('#source-reconciliation').textContent()||''));
  await frame.locator('#source-back').click();
  await frame.locator('#ui011-inventory').waitFor();
  assert.equal(await frame.getByText('Must Not Be Collected',{exact:true}).count(),0);
  assert.equal(await frame.getByText('无货',{exact:true}).count(),0);
  assert.equal(await frame.locator('#ui011-overview-photo img').count(),1,'小于 500 KiB 的主图可作为缩略图显示');
  assert.equal(await frame.locator('#ui011-edit').count(),0,'库存概览不提供编辑入口，编辑只在产品详情页进行');
  assert.equal(await frame.locator('.product-images-button').count(),0,'库存页不提供添加、删除或管理商品图片的入口');
  const preview=await frame.locator('#ui011-overview-photo').evaluate(node=>{const image=node.querySelector('img');if(!image)throw new Error('missing fictional product image');const style=getComputedStyle(image),rect=node.getBoundingClientRect();return {width:rect.width,height:rect.height,objectFit:style.objectFit};});
  assert.ok(Math.abs(preview.width-preview.height)<2,'商品概览预览框保持正方形');
  assert.equal(preview.objectFit,'contain','商品图片完整显示，不裁切填满预览框');
  assert.match(await frame.locator('#ui011-product-number').textContent()||'',/SP-KY40-BLK-000001/);
  assert.deepEqual(await frame.locator('.overview-grid label').allTextContents(),['成本价（AED）','建议售价（AED）','底价设置（AED）','库存数量']);
  assert.deepEqual(await frame.locator('.overview-grid').evaluate(grid=>({label:getComputedStyle(grid.querySelector('label')).fontSize,value:getComputedStyle(grid.querySelector('strong')).fontSize})),{label:'11px',value:'14px'},'商品概览资料字段字号保持可读');
  await frame.locator('#ui011-rows tr').nth(1).click();
  await frame.getByText('图片待人工确认',{exact:true}).waitFor();
  assert.equal(await frame.locator('#ui011-overview-photo img').count(),0,'达到 500 KiB 的图片不能显示为缓存缩略图');
  assert.match(await frame.locator('#ui011-review-copy').textContent()||'',/500 KiB/);
  await frame.locator('#ui011-connection-help').click();
  assert.match(await frame.locator('#ui011-popover').textContent()||'',/已保存 2 款/);
  assert.match(await frame.locator('#ui011-popover').textContent()||'',/图片待确认/);
  await frame.locator('#ui011-close-popover').click();
  await frame.locator('#ui011-rows tr').first().click();
  await frame.locator('#ui011-full-details').click();
  await frame.locator('#ui032').waitFor();
  assert.equal(await frame.locator('#ui032 .page-head h1').textContent(),'KY40 黑色（虚构）');
  assert.equal(await frame.locator('#ui032 .crumb > #u32-back').count(),1,'返回库存作为面包屑的第一个层级入口');
  assert.equal(await frame.locator('#ui032 .page-head .actions #u32-back').count(),0,'返回库存不再混在右侧编辑动作中');
  assert.deepEqual(await frame.locator('#ui032 .page-head .actions > *').evaluateAll(nodes=>nodes.filter(node=>getComputedStyle(node).display!=='none').map(node=>node.id)),['u32-availability-status','u32-adjust-inventory','u32-listing','u32-edit'],'非编辑状态保留库存状态、明确变体库存调整、受控上下架和本机资料编辑');
  const [crumbBox,backBox,headBox]=await Promise.all([frame.locator('#ui032 .crumb').boundingBox(),frame.locator('#u32-back').boundingBox(),frame.locator('#ui032 .page-head').boundingBox()]);
  if(!crumbBox||!backBox||!headBox)throw new Error('产品详情的面包屑、返回入口与标题必须存在');
  assert.ok(Math.abs(crumbBox.x-backBox.x)<2,'返回入口从页面左上面包屑起点对齐');
  assert.ok(backBox.y+backBox.height<=headBox.y,'返回入口位于标题和资料之前');
  if(process.env.KDOCS_PRODUCT_DETAIL_SCREENSHOT){await mkdir(path.dirname(process.env.KDOCS_PRODUCT_DETAIL_SCREENSHOT),{recursive:true});await page.screenshot({path:process.env.KDOCS_PRODUCT_DETAIL_SCREENSHOT});}
  assert.match(await frame.locator('#ui032 .left-info').textContent()||'',/SP-KY40-BLK-000001/);
  assert.equal(await frame.locator('#u32-hero img').count(),1,'已缓存的小图会在真实产品详情中显示');
  assert.equal(await frame.locator('#u32-details textarea').inputValue(),'KY40 产品介绍\n轻便 耐用\n• 适合日常使用\n• 库存以网站为准');
  assert.deepEqual(await frame.locator('#ui032 .source-item').allTextContents(),['成本价—商品编号精确匹配','建议售价—商品编号精确匹配','网站库存20 件ShopPlus 只读','来源状态有货来源资料 · 只读','网站上架已上架ShopPlus 回读'],'详情将来源有货、网站库存和网站上架状态分开显示');
  assert.match(await frame.locator('#u32-listing-history').textContent()||'',/已更新网站变体库存至 20，并已回读确认/,'详情显示该商品最近一次已回读确认的调整记录');
  const detailHero=await frame.locator('#u32-hero').evaluate(node=>{const image=node.querySelector('img');if(!image)throw new Error('missing fictional detail image');const rect=node.getBoundingClientRect(),style=getComputedStyle(image);return {width:rect.width,height:rect.height,objectFit:style.objectFit};});
  assert.ok(detailHero.width>=238&&detailHero.width<=242&&detailHero.height>=238&&detailHero.height<=242,`产品详情主图放大为清晰可读的 240px 正方形预览：${JSON.stringify(detailHero)}`);
  assert.ok(Math.abs(detailHero.width-detailHero.height)<2);assert.equal(detailHero.objectFit,'contain');
  assert.equal(await frame.locator('#u32-collect-media').isVisible(),true,'旧主图记录提供明确的图片补采入口');
  await frame.locator('#u32-collect-media').click();
  await waitFor(async()=>await frame.locator('#ui032 .thumbs .thumb').count()===3);
  assert.equal(await application.evaluate(()=>globalThis.__inventoryPilotMediaCalls),1,'补采只由明确按钮触发一次');
  assert.equal(await frame.locator('#u32-collect-media').isHidden(),true,'网站图片列表已读取后不再重复显示补采入口');
  assert.match(await frame.locator('#ui032 .gallery-note').textContent()||'',/网站返回 3 张；已缓存 2 张，1 张待确认/);
  assert.equal(await frame.locator('#ui032 .thumbs .thumb.active').count(),1);
  await frame.locator('#u32-gallery-next').click();
  assert.equal(await frame.locator('#ui032 .thumbs .thumb.active').evaluate(node=>[...node.parentElement.children].indexOf(node)),1,'右箭头切换到下一张缩略图');
  await frame.locator('#u32-gallery-next').click();
  assert.match(await frame.locator('#u32-hero').textContent()||'',/500 KiB/,'达到限制的图片不伪造显示，保留人工确认说明');
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.isVisible())?.setContentSize(820,640));
  await page.waitForTimeout(180);
  const narrowDetailHero=await frame.locator('#u32-hero').evaluate(node=>{const rect=node.getBoundingClientRect();return {width:rect.width,height:rect.height};});
  assert.ok(narrowDetailHero.width>=238&&narrowDetailHero.width<=242&&narrowDetailHero.height>=238&&narrowDetailHero.height<=242,`窄窗口详情主图仍维持 240px 完整显示预览：${JSON.stringify(narrowDetailHero)}`);
  const narrowBreadcrumb=await frame.locator('#ui032 .crumb').evaluate(node=>({clientWidth:node.clientWidth,scrollWidth:node.scrollWidth}));
  assert.ok(narrowBreadcrumb.scrollWidth<=narrowBreadcrumb.clientWidth,`820×640 面包屑返回入口不横向溢出：${JSON.stringify(narrowBreadcrumb)}`);
  assert.equal(await frame.locator('#u32-availability-status').textContent(),'有库存 · 可人工介绍','聊单可介绍状态收为顶部简洁标签');
  assert.equal(await frame.locator('#u32-availability-status').evaluate(node=>node.classList.contains('is-in')),true);
  assert.equal(await frame.locator('#ui032 .availability').count(),0,'底部重复的聊单状态卡片已移除');
  assert.equal(await frame.locator('.product-images-button').count(),0,'ShopPlus 试采集详情不会混入旧的本机图片库入口');
  await frame.locator('#u32-back').click();
  await frame.locator('#ui011-inventory').waitFor();
  assert.equal(await frame.locator('#ui011-rows tr').count(),2,'返回库存后仍保留同一批虚构试采集记录');
  await frame.locator('#ui011-product-manager').click();
  const refreshManager=frame.locator('dialog.shared-dialog').filter({hasText:'采集与更新商品'});
  await refreshManager.locator('#ui011-manager-refresh').click();
  await waitFor(async()=>await application.evaluate(()=>globalThis.__inventoryPilotRefreshCalls)===1);
  assert.match(await refreshManager.locator('output').textContent()||'',/已更新 2 款/,'明确点击后才执行已采集商品资料更新');
  assert.match(await frame.locator('#ui011-rows tr').first().textContent()||'',/AED 301\.00/,'网站售价更新显示在已采集商品列表');
  await refreshManager.locator('#ui011-manager-close').click();
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.isVisible())?.setContentSize(1280,820));
  await page.waitForTimeout(180);
  const wide=await frame.locator('#ui011-inventory .table-wrap').evaluate(node=>({clientWidth:node.clientWidth,scrollWidth:node.scrollWidth}));assert.ok(wide.scrollWidth<=wide.clientWidth,'1280×820 应直接显示五列');
  const overviewLayout=await frame.locator('#ui011-inventory .overview').evaluate(node=>{const parent=node.parentElement,action=node.querySelector('.overview-actions'),main=node.closest('.main');if(!parent||!action||!main)throw new Error('missing inventory overview layout');const overview=node.getBoundingClientRect(),workspace=parent.getBoundingClientRect(),actionRect=action.getBoundingClientRect(),mainRect=main.getBoundingClientRect();return {viewport:window.innerHeight,mainHeight:mainRect.height,mainScrollHeight:main.scrollHeight,workspaceTop:workspace.top,workspaceHeight:workspace.height,overviewWidth:overview.width,overviewBottom:overview.bottom,workspaceBottom:workspace.bottom,buttonGap:overview.bottom-actionRect.bottom};});
  assert.ok(overviewLayout.overviewWidth>=338&&overviewLayout.overviewWidth<=342,`1280×820 商品概览卡片扩展为 340px：${JSON.stringify(overviewLayout)}`);
  assert.ok(Math.abs(overviewLayout.overviewBottom-overviewLayout.workspaceBottom)<2,'概览外层卡片随工作区延伸到底部');
  assert.ok(overviewLayout.buttonGap>=24,`详情操作按钮保持在紧凑信息区下方，不被拉到卡片底边：${JSON.stringify(overviewLayout)}`);
  const listLayout=await frame.locator('#ui011-inventory .list-card').evaluate(node=>{const footer=node.querySelector('.list-footer');const rows=[...node.querySelectorAll('#ui011-rows tr')];if(!footer||rows.length!==2)throw new Error('missing inventory list footer or rows');const card=node.getBoundingClientRect(),footerRect=footer.getBoundingClientRect();return {cardBottom:card.bottom,footerBottom:footerRect.bottom,rowHeights:rows.map(row=>row.getBoundingClientRect().height)};});
  assert.ok(Math.abs(listLayout.cardBottom-listLayout.footerBottom)<2,'列表底部功能行贴合卡片底部而非占用行内空间');
  assert.ok(Math.abs(listLayout.rowHeights[0]-listLayout.rowHeights[1])<2,`两款试采集商品在列表可用高度中均匀分布：${JSON.stringify(listLayout)}`);
  if(process.env.KDOCS_INVENTORY_SOURCE_PRICING_SCREENSHOT){await mkdir(path.dirname(process.env.KDOCS_INVENTORY_SOURCE_PRICING_SCREENSHOT),{recursive:true});await page.mouse.move(2,2);await page.screenshot({path:process.env.KDOCS_INVENTORY_SOURCE_PRICING_SCREENSHOT});}
  await page.screenshot({path:path.join(directory,'inventory-1280x820.png')});
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.isVisible())?.setContentSize(820,640));
  await page.waitForTimeout(180);
  const narrow=await frame.locator('#ui011-inventory .table-wrap').evaluate(node=>({clientWidth:node.clientWidth,scrollWidth:node.scrollWidth}));assert.ok(narrow.scrollWidth>narrow.clientWidth,'820×640 应通过表格横向滚动保持五列独立');
  await page.screenshot({path:path.join(directory,'inventory-820x640.png')});
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.isVisible())?.setContentSize(1280,820));
  assert.deepEqual(await application.evaluate(()=>globalThis.__inventoryPilotScopes),['published-in-stock'],'全量采集范围只能由明确按钮传入');
  assert.deepEqual(errors,[]);
 }finally{
  try{application?.process().kill('SIGKILL');}catch{}
  await application?.close().catch(()=>{});
  await rm(directory,{recursive:true,force:true,maxRetries:3,retryDelay:150}).catch(()=>{});
 }
});
