import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {randomUUID} from 'node:crypto';import {ManualChat} from '../src/manual-chat.mjs';import {WhatsAppWebClient} from '../src/orders/whatsapp-web-client.mjs';
async function setup(t){const directory=await mkdtemp(path.join(os.tmpdir(),'manual-chat-'));t.after(()=>rm(directory,{recursive:true,force:true}));const calls=[];let failAt=-1;const adapter={status:()=>({status:'online'}),resolve:async value=>value,read:async()=>[],verifyManualTarget:async()=>{},sendVerified:async(_b,part)=>{calls.push(part);if(calls.length===failAt)throw Error('fixture timeout');return {id:'message-'+calls.length};}};const service=new ManualChat({adapter,directory});service.bindings.set('binding',{accountId:'wa-phone:971500000001',chatId:'wa-phone:971500000002',binding:{}});return {service,adapter,directory,calls,fail:n=>failAt=n,payload:()=>({token:'binding',requestId:randomUUID(),text:'Hello 😊 https://example.com/send-check',images:[]})};}
test('manual send preserves text, emoji and links and accepts verified images and files',async t=>{const f=await setup(t);await assert.rejects(f.service.send({...f.payload(),token:'missing'}),/关联/);await assert.rejects(f.service.send({...f.payload(),images:['file:///private/data']}),/附件/);assert.equal(f.calls.length,0);const p={...f.payload(),chinese:'do not send',images:['data:image/jpeg;base64,eA=='],attachments:[{name:'acceptance.txt',mimetype:'text/plain',dataUrl:'data:text/plain;base64,aGVsbG8='}]};const r=await f.service.send(p);assert.equal(r.status,'sent');assert.equal(f.calls[0].text,p.text);assert.deepEqual(f.calls.slice(1).map(part=>({name:part.attachment.name,mimetype:part.attachment.mimetype,kind:part.attachment.kind})),[{name:'reply-image-1.jpg',mimetype:'image/jpeg',kind:'image'},{name:'acceptance.txt',mimetype:'text/plain',kind:'file'}]);});
test('double clicks and a reloaded identical draft do not duplicate a recent send',async t=>{const f=await setup(t),p=f.payload();const results=await Promise.all([f.service.send(p),f.service.send(p)]);assert.equal(f.calls.length,1);assert.equal(results[0].requestId,results[1].requestId);await f.service.send({...p,requestId:randomUUID()});assert.equal(f.calls.length,1);await assert.rejects(f.service.send({...p,text:'changed'}),/内容已变化/);});
test('partial timeout keeps durable unknown state and never retries after restart',async t=>{const f=await setup(t);f.fail(2);const p={...f.payload(),images:['data:image/jpeg;base64,eA==']};const r=await f.service.send(p);assert.equal(r.status,'unknown');assert.equal(r.parts[0].status,'sent');assert.equal(r.parts[1].status,'unknown');assert.equal(f.calls.length,2);const next=new ManualChat({adapter:f.adapter,directory:f.directory});next.bindings=f.service.bindings;await assert.rejects(next.send({...p,requestId:randomUUID()}),/待核实/);assert.equal((await next.send(p)).status,'unknown');assert.equal(f.calls.length,2);});
test('a reply target is fingerprinted and attached only to the first outbound part',async t=>{const f=await setup(t),replyToMessageId='false_971500000002@c.us_fixture-source',payload={...f.payload(),replyToMessageId,attachments:[{name:'fixture.txt',mimetype:'text/plain',dataUrl:'data:text/plain;base64,eA=='}]};const result=await f.service.send(payload);assert.equal(result.status,'sent');assert.equal(result.replyToMessageId,replyToMessageId);assert.equal(f.calls[0].replyToMessageId,replyToMessageId);assert.equal(f.calls[1].replyToMessageId,undefined);await f.service.send({...payload,requestId:randomUUID()});assert.equal(f.calls.length,2);});
test('live adapter rechecks identity and sends text, images and files with verified receipt IDs',async()=>{const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'}),sent=[];a.state={status:'online'};a.accountId='wa-phone:971500000001';a.generation=2;a.client={getChatById:async()=>({id:{_serialized:'971500000002@lid'}}),sendMessage:async(remote,content,options)=>{assert.equal(remote,'971500000002@c.us');sent.push({content,options});return {id:{_serialized:`true_971500000002@lid_fixture-${sent.length}`}};}};const b={accountId:a.accountId,chatId:'wa-phone:971500000002',binding:{accountId:a.accountId,chatId:'wa-phone:971500000002',aliases:['971500000002@c.us','971500000002@lid']}};assert.match((await a.sendVerified(b,{text:'Hello 😊 https://example.com'})).id,/fixture-1$/);assert.match((await a.sendVerified(b,{attachment:{name:'photo.png',kind:'image',dataUrl:'data:image/png;base64,eA=='}})).id,/fixture-2$/);assert.match((await a.sendVerified(b,{attachment:{name:'acceptance.txt',kind:'file',dataUrl:'data:text/plain;base64,aGVsbG8='}})).id,/fixture-3$/);assert.equal(sent[0].content,'Hello 😊 https://example.com');assert.deepEqual(sent[0].options,{sendSeen:false,waitUntilMsgSent:true});assert.equal(sent[1].content.mimetype,'image/png');assert.equal(sent[1].content.filename,'photo.png');assert.deepEqual(sent[1].options,{sendSeen:false,waitUntilMsgSent:true});assert.equal(sent[2].content.mimetype,'text/plain');assert.equal(sent[2].content.filename,'acceptance.txt');assert.deepEqual(sent[2].options,{sendSeen:false,waitUntilMsgSent:true,sendMediaAsDocument:true});a.accountId='wa-phone:971500000003';await assert.rejects(a.sendVerified(b,{text:'Hello'}),/核对/);});
test('send accepts a structured outbound LID receipt whose opaque message key contains underscores',async()=>{const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'}),pn='971500000002@c.us',lid='42424242424242@lid',opaque='fixture_key_with_underscores',receiptId=`true_${lid}_${opaque}`;a.state={status:'online'};a.accountId='wa-phone:971500000001';a.generation=2;a.client={getChatById:async()=>({id:{_serialized:pn}}),sendMessage:async()=>({id:{fromMe:true,remote:{_serialized:lid},id:opaque},fromMe:true})};const binding={accountId:a.accountId,chatId:'wa-phone:971500000002',binding:{accountId:a.accountId,chatId:'wa-phone:971500000002',aliases:[pn]}};assert.equal((await a.sendVerified(binding,{text:'Verified receipt'})).id,receiptId);});
test('send rejects a malformed outbound receipt even after the target chat was verified',async()=>{const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'}),pn='971500000002@c.us';a.state={status:'online'};a.accountId='wa-phone:971500000001';a.generation=2;a.client={getChatById:async()=>({id:{_serialized:pn},fetchMessages:async()=>[]}),sendMessage:async()=>({id:{_serialized:'invalid-receipt'}})};const binding={accountId:a.accountId,chatId:'wa-phone:971500000002',binding:{accountId:a.accountId,chatId:'wa-phone:971500000002',aliases:[pn]}};await assert.rejects(a.sendVerified(binding,{text:'Blocked'}),/回执身份无法核对/);});
test('quoted replies verify the source belongs to the selected chat before dispatch',async()=>{const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'}),pn='971500000002@c.us',quote=`false_${pn}_fixture-source`,sent=[];a.state={status:'online'};a.accountId='wa-phone:971500000001';a.generation=2;a.client={getChatById:async()=>({id:{_serialized:pn}}),getMessageById:async id=>({id:{_serialized:id}}),sendMessage:async(_remote,_content,options)=>{sent.push(options);return {id:{_serialized:`true_${pn}_fixture-reply`}};}};const binding={accountId:a.accountId,chatId:'wa-phone:971500000002',binding:{accountId:a.accountId,chatId:'wa-phone:971500000002',aliases:[pn]}};await a.sendVerified(binding,{text:'Reply',replyToMessageId:quote});assert.equal(sent[0].quotedMessageId,quote);await assert.rejects(a.sendVerified(binding,{text:'Wrong target',replyToMessageId:'false_971500000003@c.us_other'}),/不属于当前/);assert.equal(sent.length,1);});
test('inbox restores a verified phone number, WhatsApp profile image and message owner for current LID chats',async()=>{const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'});a.state={status:'online'};a.accountId='wa-phone:971500000001';const remote='124242424242424@lid';a.client={getChats:async()=>[{id:{_serialized:remote},name:'',timestamp:1710000000,lastMessage:{timestamp:1710000000,body:'Hello',fromMe:false},getContact:async()=>({pushname:'',name:'',getProfilePicUrl:async()=> 'https://example.invalid/whatsapp-profile.jpg'})}],getContactLidAndPhone:async ids=>{assert.deepEqual(ids,[remote]);return [{lid:remote,pn:'971500000002@c.us'}];}};const page=await a.inbox();assert.equal(page.total,1);assert.equal(page.items[0].phone,'971500000002');assert.equal(page.items[0].chatId,'wa-phone:971500000002');assert.equal(page.items[0].preview,'Hello');assert.equal(page.items[0].avatarUrl,'https://example.invalid/whatsapp-profile.jpg');assert.equal(page.items[0].direction,'customer');});
test('verified source reads expose all retrieved rows for local retention, separate from the visible 20',async()=>{
 const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'}),accountId='wa-phone:971500000001',chatId='wa-phone:971500000002',remote='971500000002@c.us';
 const source=Array.from({length:37},(_,index)=>({id:{_serialized:`false_${remote}_${index}`,remote},fromMe:false,timestamp:1710000000+index,type:'chat',body:`Actual ${index}`}));
 let requested=0;a.state={status:'online'};a.accountId=accountId;a.client={getContactLidAndPhone:async()=>[],getChatById:async()=>({id:{_serialized:remote},fetchMessages:async({limit})=>{requested=limit;return source;}})};
 const binding={accountId,chatId,aliases:[remote],nativeRemote:remote},result=await a.recent({accountId,chatId,binding,limit:20,archive:true});
 assert.equal(requested,500);assert.equal(result.messages.length,20);assert.equal(result.archiveMessages.length,37);
});
test('one malformed older source row does not hide the other verified messages',async()=>{
 const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'}),accountId='wa-phone:971500000001',chatId='wa-phone:971500000002',remote='971500000002@c.us';
 const good={id:{_serialized:`false_${remote}_good`,remote},fromMe:false,timestamp:1710000000,type:'chat',body:'Actual message'},bad={...good,id:{_serialized:'unverified-id',remote}};
 a.state={status:'online'};a.accountId=accountId;a.client={getContactLidAndPhone:async()=>[],getChatById:async()=>({id:{_serialized:remote},fetchMessages:async()=>[bad,good]})};
 const binding={accountId,chatId,aliases:[remote],nativeRemote:remote},result=await a.recent({accountId,chatId,binding,limit:20,archive:true});
 assert.deepEqual(result.messages.map(row=>row.text),['Actual message']);assert.match(result.archiveIssue,/1 条消息/);
});
test('verified sticker and GIF attachments keep their real type and become displayable local media',async()=>{const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'}),remote='971500000002@c.us',target={accountId:'wa-phone:971500000001',chatId:'wa-phone:971500000002',aliases:new Set([remote])},make=(id,type,mimetype)=>({id:{_serialized:`false_${remote}_${id}`,remote},fromMe:false,timestamp:1710000000,type,body:'',downloadMedia:async()=>({mimetype,data:'R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=='})});const sticker=make('sticker','sticker','image/webp');sticker.downloadMedia=async()=>({mimetype:'image/webp',data:'UklGRiIAAABXRUJQVlA4IBYAAADQAQCdASoBAAEAAUAmJaQAA3AA/vuUAAA='});const first=a.normalize(sticker,target);assert.equal(first.text,'[贴纸]');assert.equal(first.metadata.media[0].status,'unavailable');const cached=await a.downloadImage(sticker,target,0,{manual:true,emit:false});assert.equal(cached.metadata.media[0].type,'sticker');assert.equal(cached.metadata.media[0].status,'cached');assert.match(cached.metadata.media[0].dataUrl,/^data:image\/webp;base64,/);const gif=make('gif','gif','image/gif');const gifCached=await a.downloadImage(gif,target,0,{manual:true,emit:false});assert.equal(gifCached.text,'[GIF 动图]');assert.equal(gifCached.metadata.media[0].type,'gif');assert.match(gifCached.metadata.media[0].dataUrl,/^data:image\/gif;base64,/);});
test('a verified workbench chat caches a safe attachment even without online order sync',async()=>{const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'}),accountId='wa-phone:971500000001',chatId='wa-phone:971500000002',remote='971500000002@c.us',message={id:{_serialized:`false_${remote}_media`,remote},fromMe:false,timestamp:1710000000,type:'unknown',hasMedia:true,body:'',downloadMedia:async()=>({mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='})};a.state={status:'online'};a.accountId=accountId;a.client={getContactLidAndPhone:async()=>[],getChatById:async()=>({id:{_serialized:remote},fetchMessages:async()=>[message]})};const binding={accountId,chatId,aliases:[remote],nativeRemote:remote};const first=await a.recent({accountId,chatId,binding,limit:20});assert.equal(a.targets.length,0);assert.equal(first.messages[0].metadata.messageType,'image');assert.equal(first.messages[0].metadata.media[0].status,'unavailable');const visible=await a.retryMedia({accountId,chatId,binding,messageId:first.messages[0].id});assert.equal(visible.metadata.media[0].status,'cached');assert.match(visible.metadata.media[0].dataUrl,/^data:image\/png;base64,/);const next=await a.recent({accountId,chatId,binding,limit:20});assert.equal(next.messages[0].metadata.media[0].status,'cached');});
test('phone history retains customer, known manual, explicit AI and unknown merchant identities',async t=>{
 const f=await setup(t);await f.service.send(f.payload());
 f.adapter.read=async()=>[{id:'customer',direction:'customer',text:'Hi'},{id:'message-1',direction:'merchant',text:'Hello 😊'},{id:'ai',direction:'merchant',sender:'AI自动发送',text:'Reply'},{id:'unknown',direction:'merchant',text:'Earlier reply'}];
 const rows=await f.service.history({token:'binding'});assert.deepEqual(rows.map(row=>row.sender),['客户','人工发送','AI自动发送','我方发送']);
});
test('visible media reads one verified message only after the workbench requests it',async t=>{
 const f=await setup(t);let input;f.adapter.retryMedia=async value=>{input=value;return {id:'image-1',direction:'customer',text:'[图片]',metadata:{messageType:'image',media:[{type:'image',status:'cached',dataUrl:'data:image/png;base64,eA=='}]}};};
 const row=await f.service.media({token:'binding',messageId:' image-1 '});assert.equal(input.messageId,'image-1');assert.equal(input.chatId,'wa-phone:971500000002');assert.equal(input.force,false);assert.equal(row.sender,'客户');await f.service.media({token:'binding',messageId:'image-1',force:true});assert.equal(input.force,true);await assert.rejects(f.service.media({token:'binding',messageId:''}),/标识/);
});
