import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {randomUUID} from 'node:crypto';import {ManualChat} from '../src/manual-chat.mjs';import {WhatsAppWebClient} from '../src/orders/whatsapp-web-client.mjs';
async function setup(t){const directory=await mkdtemp(path.join(os.tmpdir(),'manual-chat-'));t.after(()=>rm(directory,{recursive:true,force:true}));const calls=[];let failAt=-1;const adapter={status:()=>({status:'online'}),resolve:async value=>value,read:async()=>[],verifyManualTarget:async()=>{},sendVerified:async(_b,part)=>{calls.push(part);if(calls.length===failAt)throw Error('fixture timeout');return {id:'message-'+calls.length};}};const service=new ManualChat({adapter,directory});service.bindings.set('binding',{accountId:'wa-phone:971500000001',chatId:'wa-phone:971500000002',binding:{}});return {service,adapter,directory,calls,fail:n=>failAt=n,payload:()=>({token:'binding',requestId:randomUUID(),text:'Hello 😊',images:[]})};}
test('manual send requires a verified recipient; only explicit English and images are sent',async t=>{const f=await setup(t);await assert.rejects(f.service.send({...f.payload(),token:'missing'}),/关联/);await assert.rejects(f.service.send({...f.payload(),images:['file:///private/data']}),/图片/);assert.equal(f.calls.length,0);const p={...f.payload(),chinese:'do not send',images:['data:image/jpeg;base64,eA==']};const r=await f.service.send(p);assert.equal(r.status,'sent');assert.deepEqual(f.calls,[{text:'Hello 😊'},{image:'data:image/jpeg;base64,eA==',imageIndex:0}]);});
test('double clicks and a reloaded identical draft do not duplicate a recent send',async t=>{const f=await setup(t),p=f.payload();const results=await Promise.all([f.service.send(p),f.service.send(p)]);assert.equal(f.calls.length,1);assert.equal(results[0].requestId,results[1].requestId);await f.service.send({...p,requestId:randomUUID()});assert.equal(f.calls.length,1);await assert.rejects(f.service.send({...p,text:'changed'}),/内容已变化/);});
test('partial timeout keeps durable unknown state and never retries after restart',async t=>{const f=await setup(t);f.fail(2);const p={...f.payload(),images:['data:image/jpeg;base64,eA==']};const r=await f.service.send(p);assert.equal(r.status,'unknown');assert.equal(r.parts[0].status,'sent');assert.equal(r.parts[1].status,'unknown');assert.equal(f.calls.length,2);const next=new ManualChat({adapter:f.adapter,directory:f.directory});next.bindings=f.service.bindings;await assert.rejects(next.send({...p,requestId:randomUUID()}),/待核实/);assert.equal((await next.send(p)).status,'unknown');assert.equal(f.calls.length,2);});
test('live adapter rechecks identity and verifies send receipts without marking chats seen',async()=>{const a=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'});a.state={status:'online'};a.accountId='wa-phone:971500000001';a.generation=2;a.client={getChatById:async()=>({id:{_serialized:'971500000002@lid'}}),sendMessage:async(remote,text,options)=>{assert.equal(remote,'971500000002@c.us');assert.equal(text,'Hello');assert.deepEqual(options,{sendSeen:false,waitUntilMsgSent:true});return {fromMe:true,id:{_serialized:'true_971500000002@lid_fixture'}};}};const b={accountId:a.accountId,chatId:'wa-phone:971500000002',binding:{accountId:a.accountId,chatId:'wa-phone:971500000002',aliases:['971500000002@c.us','971500000002@lid']}};assert.equal((await a.sendVerified(b,{text:'Hello'})).id,'true_971500000002@lid_fixture');a.accountId='wa-phone:971500000003';await assert.rejects(a.sendVerified(b,{text:'Hello'}),/核对/);});
test('phone history retains customer, known manual, explicit AI and unknown merchant identities',async t=>{
 const f=await setup(t);await f.service.send(f.payload());
 f.adapter.read=async()=>[{id:'customer',direction:'customer',text:'Hi'},{id:'message-1',direction:'merchant',text:'Hello 😊'},{id:'ai',direction:'merchant',sender:'AI自动发送',text:'Reply'},{id:'unknown',direction:'merchant',text:'Earlier reply'}];
 const rows=await f.service.history({token:'binding'});assert.deepEqual(rows.map(row=>row.sender),['客户','人工发送','AI自动发送','我方发送']);
});
