import test from 'node:test';
import assert from 'node:assert/strict';
import {WhatsAppWebClient} from '../src/orders/whatsapp-web-client.mjs';

const accountId='wa-phone:971500000001',chatId='wa-phone:971500000002',remote='971500000002@c.us';
const binding={accountId,chatId,identityVerified:true,aliases:[remote],nativeRemote:remote};
const image=(index,downloadMedia=async()=>({mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='}),messageRemote=remote)=>({id:{_serialized:`false_${messageRemote}_image-${index}`,remote:messageRemote},fromMe:false,timestamp:1710000000,type:'image',hasMedia:true,body:'',downloadMedia});
function adapter(messages,{lidAliases=[]}={}){const client=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'});client.state={status:'online'};client.accountId=accountId;client.generation=1;const limits=[],lookups=[];client.client={getContactLidAndPhone:async()=>lidAliases.map(lid=>({pn:remote,lid})),getChatById:async()=>({id:{_serialized:remote},fetchMessages:async({limit})=>{limits.push(limit);return [messages.at(-1)];}}),getMessageById:async id=>{lookups.push(id);return messages.find(row=>row.id._serialized===id)||null;}};return {client,limits,lookups};}

test('a requested older image uses its direct ID lookup without depending on a recent-message probe',async()=>{const rows=Array.from({length:50},(_,index)=>image(index)),{client,limits}=adapter(rows);const result=await client.retryMedia({...binding,binding,messageId:rows[0].id._serialized});assert.equal(result.metadata.media[0].status,'cached');assert.deepEqual(limits,[]);assert.equal(result.id,rows[0].id._serialized);});

test('an older image can use its verified native ID even if the recent-message request is unavailable',async()=>{const old=image(100),{client,limits}=adapter([old]);client.client.getChatById=async()=>{throw Error('fictional recent-history interruption');};const result=await client.retryMedia({...binding,binding,messageId:old.id._serialized});assert.equal(result.metadata.media[0].status,'cached');assert.deepEqual(limits,[]);});

test('a stored LID image retries the same opaque ID through the current verified PN without scanning history',async()=>{const lid='124242424242424@lid',row=image('legacy_key_with_underscores'),stored=`false_${lid}_image-legacy_key_with_underscores`,{client,limits,lookups}=adapter([row]);const result=await client.retryMedia({...binding,binding,messageId:stored});assert.equal(result.id,row.id._serialized);assert.deepEqual(lookups,[row.id._serialized]);assert.deepEqual(limits,[]);});

test('a PN record can retry its same opaque ID through the current verified LID alias',async()=>{const lid='124242424242424@lid',row=image('same_key_with_underscores',undefined,lid),stored=`false_${remote}_image-same_key_with_underscores`,{client,limits,lookups}=adapter([row],{lidAliases:[lid]});const result=await client.retryMedia({...binding,binding,messageId:stored});assert.equal(result.id,row.id._serialized);assert.deepEqual(lookups,[stored,row.id._serialized]);assert.deepEqual(limits,[]);});

test('a current LID record retries PN only after the same current LID ID is absent',async()=>{const lid='124242424242424@lid',row=image('current_lid_key'),stored=`false_${lid}_image-current_lid_key`,{client,lookups}=adapter([row],{lidAliases:[lid]});await client.retryMedia({...binding,binding,messageId:stored});assert.deepEqual(lookups,[stored,row.id._serialized]);});

test('malformed message IDs and foreign responses stop before any unrelated media is read',async()=>{const row=image('safe'),foreign=image('safe',undefined,'971500000003@c.us'),{client,lookups,limits}=adapter([row]);await assert.rejects(client.retryMedia({...binding,binding,messageId:'t'}),error=>error?.code==='WHATSAPP_MEDIA_IDENTITY');assert.deepEqual(lookups,[]);client.client.getMessageById=async id=>{lookups.push(id);return foreign;};await assert.rejects(client.retryMedia({...binding,binding,messageId:row.id._serialized}),error=>error?.code==='WHATSAPP_MEDIA_IDENTITY');assert.deepEqual(limits,[]);});

test('unverified chats and more than two current LID aliases cannot widen a media lookup',async()=>{const row=image('bounded'),lids=['111111111111111@lid','222222222222222@lid','333333333333333@lid','444444444444444@lid'],{client,lookups}=adapter([],{lidAliases:lids});await assert.rejects(client.retryMedia({...binding,binding,identityVerified:false,messageId:row.id._serialized}),error=>error?.code==='WHATSAPP_MEDIA_IDENTITY');assert.deepEqual(lookups,[]);await assert.rejects(client.retryMedia({...binding,binding,messageId:row.id._serialized}),error=>error?.code==='WHATSAPP_MEDIA_NOT_FOUND');assert.equal(lookups.length,3);assert.deepEqual(lookups,[row.id._serialized,`false_${lids[0]}_image-bounded`,`false_${lids[1]}_image-bounded`]);});

test('a failed direct lookup reports the old-image stage without probing the newest message',async()=>{const old=image('old'),latest=image('latest'),{client,limits}=adapter([old,latest]);client.client.getMessageById=async()=>{throw Error('fictional ID lookup unavailable');};await assert.rejects(client.retryMedia({...binding,binding,messageId:old.id._serialized}),error=>error?.code==='WHATSAPP_MEDIA_LOOKUP_UNAVAILABLE'&&/历史图片/.test(error.message));assert.deepEqual(limits,[]);});

test('the transport accepts a 1.2 MB image, rejects one over 16 MB, and keeps its cache bounded',async()=>{const payload=Buffer.alloc(1_200_000,7).toString('base64'),big=Buffer.alloc(16*1024*1024+1,8).toString('base64'),rows=[image(1,async()=>({mimetype:'image/png',data:payload})),image(2,async()=>({mimetype:'image/png',data:big}))],{client}=adapter(rows);const ok=await client.retryMedia({...binding,binding,messageId:rows[0].id._serialized});assert.equal(ok.metadata.media[0].status,'cached');assert.ok(client.mediaCacheBytes<48*1024*1024);await assert.rejects(client.retryMedia({...binding,binding,messageId:rows[1].id._serialized}),/16 MB/);assert.equal(client.mediaCache.size,1);});

test('image requests use at most two downloads',async()=>{let active=0,maximum=0;const starts=[],releases=[];const rows=Array.from({length:4},(_,index)=>image(index,async()=>{active++;maximum=Math.max(maximum,active);starts.push(index);await new Promise(resolve=>releases.push(()=>{active--;resolve();}));return {mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='};}));const {client}=adapter(rows);const requests=rows.map(row=>client.retryMedia({...binding,binding,messageId:row.id._serialized}));await new Promise(resolve=>setTimeout(resolve,30));assert.equal(maximum,2);assert.equal(starts.length,2);releases.splice(0).forEach(release=>release());await new Promise(resolve=>setTimeout(resolve,30));assert.equal(maximum,2);assert.equal(starts.length,4);releases.splice(0).forEach(release=>release());await Promise.all(requests);assert.equal(client.mediaCache.size,4);});

test('connection change rejects queued images and discards late downloads',async()=>{const releases=[],rows=Array.from({length:3},(_,index)=>image(index,async()=>new Promise(resolve=>releases.push(()=>resolve({mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='})))));const {client}=adapter(rows);const first=client.retryMedia({...binding,binding,messageId:rows[0].id._serialized}),second=client.retryMedia({...binding,binding,messageId:rows[1].id._serialized}),queued=client.retryMedia({...binding,binding,messageId:rows[2].id._serialized});const rejection=assert.rejects(queued,/连接已变化/);await new Promise(resolve=>setTimeout(resolve,20));assert.equal(releases.length,2);client.generation++;client.cancelQueuedMedia('WhatsApp 连接已变化，请重新打开图片');await rejection;releases.splice(0).forEach(release=>release());assert.deepEqual(await Promise.all([first,second]),[null,null]);assert.equal(client.mediaCache.size,0);});

test('reopening an image uses memory unless a decode failure forces a fresh download',async()=>{let downloads=0;const row=image(5,async()=>{downloads++;return {mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='};}),{client}=adapter([row]);for(let index=0;index<2;index++)assert.equal((await client.retryMedia({...binding,binding,messageId:row.id._serialized})).metadata.media[0].status,'cached');assert.equal(downloads,1);assert.equal((await client.retryMedia({...binding,binding,messageId:row.id._serialized,force:true})).metadata.media[0].status,'cached');assert.equal(downloads,2);});

test('three large images evict the oldest cached payload before exceeding 48 MB',async()=>{const payload=Buffer.alloc(14*1024*1024,9).toString('base64'),rows=Array.from({length:3},(_,index)=>image(index,async()=>({mimetype:'image/png',data:payload}))),{client}=adapter(rows);for(const row of rows)await client.retryMedia({...binding,binding,messageId:row.id._serialized});assert.ok(client.mediaCacheBytes<=48*1024*1024);assert.equal(client.mediaCache.size,2);assert.equal(client.mediaCache.has(accountId+':'+rows[0].id._serialized),false);});
