import test from 'node:test';
import assert from 'node:assert/strict';
import {WhatsAppWebClient} from '../src/orders/whatsapp-web-client.mjs';

const accountId='wa-phone:971500000001',chatId='wa-phone:971500000002',remote='971500000002@c.us';
const binding={accountId,chatId,aliases:[remote],nativeRemote:remote};
const image=(index,downloadMedia=async()=>({mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='}))=>({id:{_serialized:`false_${remote}_image-${index}`,remote},fromMe:false,timestamp:1710000000+index,type:'image',hasMedia:true,body:'',downloadMedia});
function adapter(messages){const client=new WhatsAppWebClient({userDataPath:'/tmp/fictional-unused'});client.state={status:'online'};client.accountId=accountId;client.generation=1;const limits=[];client.client={getContactLidAndPhone:async()=>[],getChatById:async()=>({id:{_serialized:remote},fetchMessages:async({limit})=>{limits.push(limit);return [messages.at(-1)];}}),getMessageById:async id=>messages.find(row=>row.id._serialized===id)||null};return {client,limits};}

test('a requested older image uses direct ID lookup and only a one-row identity probe',async()=>{const rows=Array.from({length:50},(_,index)=>image(index)),{client,limits}=adapter(rows);const result=await client.retryMedia({...binding,binding,messageId:rows[0].id._serialized});assert.equal(result.metadata.media[0].status,'cached');assert.deepEqual(limits,[1]);assert.equal(result.id,rows[0].id._serialized);});

test('the transport accepts a 1.2 MB image, rejects one over 16 MB, and keeps its cache bounded',async()=>{const payload=Buffer.alloc(1_200_000,7).toString('base64'),big=Buffer.alloc(16*1024*1024+1,8).toString('base64'),rows=[image(1,async()=>({mimetype:'image/png',data:payload})),image(2,async()=>({mimetype:'image/png',data:big}))],{client}=adapter(rows);const ok=await client.retryMedia({...binding,binding,messageId:rows[0].id._serialized});assert.equal(ok.metadata.media[0].status,'cached');assert.ok(client.mediaCacheBytes<48*1024*1024);await assert.rejects(client.retryMedia({...binding,binding,messageId:rows[1].id._serialized}),/16 MB/);assert.equal(client.mediaCache.size,1);});

test('image requests use at most two downloads',async()=>{let active=0,maximum=0;const starts=[],releases=[];const rows=Array.from({length:4},(_,index)=>image(index,async()=>{active++;maximum=Math.max(maximum,active);starts.push(index);await new Promise(resolve=>releases.push(()=>{active--;resolve();}));return {mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='};}));const {client}=adapter(rows);const requests=rows.map(row=>client.retryMedia({...binding,binding,messageId:row.id._serialized}));await new Promise(resolve=>setTimeout(resolve,30));assert.equal(maximum,2);assert.equal(starts.length,2);releases.splice(0).forEach(release=>release());await new Promise(resolve=>setTimeout(resolve,30));assert.equal(maximum,2);assert.equal(starts.length,4);releases.splice(0).forEach(release=>release());await Promise.all(requests);assert.equal(client.mediaCache.size,4);});

test('connection change rejects queued images and discards late downloads',async()=>{const releases=[],rows=Array.from({length:3},(_,index)=>image(index,async()=>new Promise(resolve=>releases.push(()=>resolve({mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='})))));const {client}=adapter(rows);const first=client.retryMedia({...binding,binding,messageId:rows[0].id._serialized}),second=client.retryMedia({...binding,binding,messageId:rows[1].id._serialized}),queued=client.retryMedia({...binding,binding,messageId:rows[2].id._serialized});const rejection=assert.rejects(queued,/连接已变化/);await new Promise(resolve=>setTimeout(resolve,20));assert.equal(releases.length,2);client.generation++;client.cancelQueuedMedia('WhatsApp 连接已变化，请重新打开图片');await rejection;releases.splice(0).forEach(release=>release());assert.deepEqual(await Promise.all([first,second]),[null,null]);assert.equal(client.mediaCache.size,0);});

test('reopening an image uses memory unless a decode failure forces a fresh download',async()=>{let downloads=0;const row=image(5,async()=>{downloads++;return {mimetype:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JkXQAAAAASUVORK5CYII='};}),{client}=adapter([row]);for(let index=0;index<2;index++)assert.equal((await client.retryMedia({...binding,binding,messageId:row.id._serialized})).metadata.media[0].status,'cached');assert.equal(downloads,1);assert.equal((await client.retryMedia({...binding,binding,messageId:row.id._serialized,force:true})).metadata.media[0].status,'cached');assert.equal(downloads,2);});

test('three large images evict the oldest cached payload before exceeding 48 MB',async()=>{const payload=Buffer.alloc(14*1024*1024,9).toString('base64'),rows=Array.from({length:3},(_,index)=>image(index,async()=>({mimetype:'image/png',data:payload}))),{client}=adapter(rows);for(const row of rows)await client.retryMedia({...binding,binding,messageId:row.id._serialized});assert.ok(client.mediaCacheBytes<=48*1024*1024);assert.equal(client.mediaCache.size,2);assert.equal(client.mediaCache.has(accountId+':'+rows[0].id._serialized),false);});
