import test from 'node:test';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {openOrderDatabase} from '../src/orders/database.mjs';
import {createCostCatalog} from '../src/orders/cost-catalog.mjs';
import {OrderAppService,displayPhone,maskPhone} from '../src/orders/order-app-service.mjs';

const columns=[
  ['订单信息基础信息','订单号','orderNo'],['订单信息基础信息','子订单 ID','subOrderId'],['订单信息基础信息','创建时间','createdAt'],['订单信息基础信息','订单状态','orderStatus'],['订单信息基础信息','货币单位','currency'],['订单信息基础信息','订单总价','orderTotal'],['订单信息基础信息','商品总价','productTotal'],['订单信息基础信息','优惠金额','discountAmount'],['订单信息基础信息','物流费用','customerShippingFee'],['订单信息基础信息','支付方式','paymentMethod'],
  ['收货信息','姓名','fullName'],['收货信息','联系电话','phone'],['收货信息','联系邮箱','email'],['收货信息','国家','country'],['收货信息','省/州','province'],['收货信息','城市','city'],['收货信息','街道','street'],['收货信息','寓所','residence'],['收货信息','邮编','postalCode'],['收货信息','门牌号','doorNumber'],
  ['商品信息','商品SKU','productSku'],['商品信息','商品名称','productName'],['商品信息','商品售价','unitPrice'],['商品信息','售出数量','quantity'],['商品信息','商品支付状态','paymentStatus'],['商品信息','商品配送状态','fulfillmentStatus']
];
const fictional=(overrides={})=>({orderNo:'UI-ORDER-1',subOrderId:'UI-SUB-1',createdAt:'2026-08-31 10:00:00',orderStatus:'待发货',currency:'AED',orderTotal:'99.00',productTotal:'100.00',discountAmount:'1.00',customerShippingFee:'0',paymentMethod:'COD',fullName:'Fictional Recipient',phone:'+971500000001',email:'fictional@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Example Street',residence:'Example Residence',postalCode:'00000',doorNumber:'A-1',productSku:'KY02',productName:'KY02 Very Long Fictional Product Name For Interface Testing',unitPrice:'100.00',quantity:'1',paymentStatus:'paid',fulfillmentStatus:'pending',...overrides});
async function workbook(file,rows){const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Orders');let start=1;for(const group of [...new Set(columns.map(value=>value[0]))]){const count=columns.filter(value=>value[0]===group).length;sheet.mergeCells(1,start,1,start+count-1);sheet.getCell(1,start).value=group;start+=count;}columns.forEach((value,index)=>sheet.getCell(2,index+1).value=value[1]);rows.forEach((data,row)=>columns.forEach((value,column)=>sheet.getCell(row+3,column+1).value=data[value[2]]??''));await book.xlsx.writeFile(file);}
async function fixture(rows=[fictional()]){const directory=await mkdtemp(path.join(os.tmpdir(),'order-app-ui-')),file=path.join(directory,'fictional.xlsx');await workbook(file,rows);const database=await openOrderDatabase({databaseFile:path.join(directory,'orders.sqlite')}),catalog=createCostCatalog([{businessId:'KY02',sourceName:'KY02 Fictional',cost:'20'}]),service=new OrderAppService({database,userDataPath:directory,costCatalogLoader:async()=>catalog,tokenFactory:()=>`token-${Math.random()}`});return {directory,file,database,service,close:async()=>{database.close();await rm(directory,{recursive:true,force:true});}};}

test('订单预览只返回脱敏电话和必要列表字段，不泄露完整客户资料或路径',async()=>{const f=await fixture();try{const preview=await f.service.previewFile(f.file,{originalFilename:'订单列表_虚构.xlsx'}),serialized=JSON.stringify(preview);assert.equal(preview.filename,'订单列表_虚构.xlsx');assert.equal(preview.summary.validOrders,1);assert.match(preview.orders[0].phoneMasked,/\*/);assert.equal(preview.orders[0].city,'城市已记录');assert.equal('shipping' in preview.orders[0],false);assert.equal(serialized.includes('Fictional Recipient'),false);assert.equal(serialized.includes('fictional@example.invalid'),false);assert.equal(serialized.includes('Example City'),false);assert.equal(serialized.includes(f.directory),false);}finally{await f.close();}});
test('核对优惠后使用服务端预览令牌导入，业务列表显示完整电话且利润导出继续脱敏',async()=>{const f=await fixture();try{let preview=await f.service.previewFile(f.file),order=preview.orders[0];assert.equal(order.needsReview,true);assert.throws(()=>f.service.commit({token:preview.token}),error=>error.code==='SHOPPLUS_REVIEW_REQUIRED');preview=f.service.review({token:preview.token,orderNo:order.orderNo,confirmed:true,discountConfirmed:true,items:order.items.map(item=>({sourceRow:item.sourceRow,businessCode:item.businessCode,costAed:'20.00'}))});assert.equal(preview.orders[0].reviewConfirmed,true);const result=await f.service.commit({token:preview.token});assert.equal(result.imported,1);assert.equal(f.service.summary().total,1);const list=f.service.list({search:'UI-ORDER',searchType:'order'});assert.equal(list.length,1);assert.equal(list[0].phone,'+971500000001');assert.notEqual(list[0].phoneMasked,list[0].phone);assert.equal(list[0].city,'城市已记录');const detail=f.service.detail({id:list[0].id});assert.equal(detail.customer.fullName,'Fictional Recipient');assert.equal(detail.customer.phone,'+971500000001');assert.equal(detail.items[0].costFils,2000);assert.equal(detail.packages[0].shippingFeeConfirmed,false);assert.equal(detail.profitStatus,'pending');assert.notEqual(f.service.profitReport({}).rows[0].phoneMasked,list[0].phone);}finally{await f.close();}});
test('缺号缺成本不能用0代替，商品编号补全前不能确认核对',async()=>{const f=await fixture([fictional({productSku:'',productName:'Fictional Product Without Code'})]);try{const preview=await f.service.previewFile(f.file),order=preview.orders[0];assert.equal(order.items[0].costFils,null);assert.throws(()=>f.service.review({token:preview.token,orderNo:order.orderNo,confirmed:true,missingCostConfirmed:true,discountConfirmed:true,items:[]}),/商品编号/);const revised=f.service.review({token:preview.token,orderNo:order.orderNo,confirmed:true,discountConfirmed:true,items:[{sourceRow:order.items[0].sourceRow,businessCode:'Z99',costAed:'12.50'}]});assert.equal(revised.orders[0].items[0].costFils,1250);}finally{await f.close();}});
test('库存尚无成本时必须明确确认后才可按NULL导入',async()=>{const f=await fixture();try{f.service.costCatalogLoader=async()=>createCostCatalog([]);let preview=await f.service.previewFile(f.file),order=preview.orders[0];assert.equal(order.items[0].costFils,null);assert.throws(()=>f.service.review({token:preview.token,orderNo:order.orderNo,confirmed:true,discountConfirmed:true,items:[]}),/成本暂时留空/);preview=f.service.review({token:preview.token,orderNo:order.orderNo,confirmed:true,missingCostConfirmed:true,discountConfirmed:true,items:[{sourceRow:order.items[0].sourceRow,businessCode:order.items[0].businessCode,costAed:''}]});assert.equal(preview.orders[0].reviewConfirmed,true);const result=await f.service.commit({token:preview.token});assert.equal(result.imported,1);const stored=f.database.prepare('SELECT unit_cost_snapshot,needs_review FROM order_items').get();assert.equal(stored.unit_cost_snapshot,null);assert.equal(stored.needs_review,1);}finally{await f.close();}});
test('预览令牌失效、错误筛选和不支持的文件类型都会被拒绝',async()=>{const f=await fixture();try{const first=await f.service.previewFile(f.file);await f.service.previewFile(f.file);assert.throws(()=>f.service.commit({token:first.token}),error=>error.code==='SHOPPLUS_PREVIEW_EXPIRED');assert.throws(()=>f.service.list({searchType:'sql'}),error=>error.code==='ORDERS_INVALID_ARGUMENT');await assert.rejects(()=>f.service.previewFile(path.join(f.directory,'orders.ods')),error=>error.code==='SHOPPLUS_FILE_TYPE_UNSUPPORTED');}finally{await f.close();}});
test('电话脱敏保留少量识别位',()=>{assert.equal(maskPhone('+971500000001'),'+97********01');assert.equal(maskPhone('1234'),'1***');});
test('订单列表电话删除普通空格、连续空格、制表符和不换行空格',()=>{for(const [input,expected] of [['+971 55 123 4567','+971551234567'],['+971551234567','+971551234567'],['055 123 4567','0551234567'],['+971   55  123   4567','+971551234567'],['+971\u00a055\u00a0123\u00a04567','+971551234567'],['+971\t55\t123\t4567','+971551234567']])assert.equal(displayPhone(input),expected);});
test('电话搜索兼容带空格和不带空格输入且固定序号可搜索',async()=>{const f=await fixture([fictional({discountAmount:'0',orderTotal:'100',phone:'+971 55 123 4567'})]);try{const preview=await f.service.previewFile(f.file);await f.service.commit({token:preview.token});const compact=f.service.list({search:'+971551234567',searchType:'phone'}),spaced=f.service.list({search:'+971 55 123 4567',searchType:'phone'});assert.equal(compact.length,1);assert.equal(spaced.length,1);assert.equal(compact[0].phone,'+971551234567');assert.equal(f.service.list({search:String(compact[0].sequence),searchType:'sequence'})[0].id,compact[0].id);}finally{await f.close();}});
test('核对不单卖商品时保留注释成本原文和业务标记',async()=>{const f=await fixture();try{f.service.costCatalogLoader=async()=>createCostCatalog([{businessId:'KY02',cost:'20(不单卖)'}]);let preview=await f.service.previewFile(f.file),order=preview.orders[0];assert.equal(order.items[0].costNote,'不单卖');preview=f.service.review({token:preview.token,orderNo:order.orderNo,confirmed:true,discountConfirmed:true,items:[{sourceRow:order.items[0].sourceRow,businessCode:'KY02',costAed:'20.00'}]});await f.service.commit({token:preview.token});const item=f.database.prepare('SELECT cost_raw_text,cost_note,not_sold_separately FROM order_items').get();assert.deepEqual({...item},{cost_raw_text:'20(不单卖)',cost_note:'不单卖',not_sold_separately:1});}finally{await f.close();}});
test('订单搜索、筛选和排序不会改变固定序号',async()=>{const f=await fixture([fictional({discountAmount:'0',orderTotal:'100'})]);try{const preview=await f.service.previewFile(f.file);await f.service.commit({token:preview.token});const rows=f.service.list({search:'UI-ORDER',searchType:'order'}),sequence=rows[0].sequence;assert.equal(rows.length,1);assert.deepEqual(rows[0].products,[{code:'KY02',quantity:1}]);assert.equal(rows[0].createdAt,'2026-08-31 10:00:00');assert.equal(f.service.list({search:'000001',searchType:'phone'})[0].sequence,sequence);assert.equal(f.service.list({search:'KY02',searchType:'sku'})[0].sequence,sequence);assert.equal(f.service.list({status:'unshipped'})[0].sequence,sequence);assert.equal(f.service.list({review:'no',sort:'oldest'})[0].sequence,sequence);assert.equal(f.service.list({review:'yes'}).length,0);}finally{await f.close();}});
