import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,mkdir,readdir,writeFile,access,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {openOrderDatabase,orderDatabasePath,migrateOrderDatabase} from '../src/orders/database.mjs';
import {ORDER_MIGRATIONS,CURRENT_ORDER_SCHEMA_VERSION} from '../src/orders/migrations/index.mjs';
import {OrderRepository} from '../src/orders/order-repository.mjs';
import {OrderService} from '../src/orders/order-service.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';
import {createVerifiedBackup,validateOrderDatabaseFile,createAutomaticBackup,automaticBackupDirectory,replaceDatabaseAtomically,finalizeDatabaseReplacement,rollbackDatabaseReplacement,cleanupAutomaticBackups} from '../src/orders/order-data-protection.mjs';

const order=(number)=>({source:'manual',shopplus_order_no:number,currency:'AED',delivery_status:'unshipped',customer_first_name:'Test',customer_last_name:'Customer',items:[{sku_code:'KY02',product_name_snapshot:'Fictional Product',quantity:1,unit_list_price:'10',unit_actual_price:'10',unit_cost_snapshot:'2'}]});
async function fixture(){const directory=await mkdtemp(path.join(os.tmpdir(),'order-protection-')),database=await openOrderDatabase({userDataPath:directory}),service=new OrderService(new OrderRepository(database));return {directory,database,service,close:async()=>{try{database.close();}catch{}await rm(directory,{recursive:true,force:true});}};}

test('WAL状态下手动备份完整且可被重新打开',async()=>{const f=await fixture();try{f.service.createOrder(order('BACKUP-1'));f.database.prepare("INSERT INTO order_data_audit(id,event_type,event_time) VALUES('wal-row','test','2026-09-02')").run();const file=path.join(f.directory,'manual.sqlite'),result=await createVerifiedBackup(f.database,file,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION}),verified=validateOrderDatabaseFile(file,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION}),copy=new DatabaseSync(file,{readOnly:true});try{assert.equal(result.integrity,'ok');assert.equal(verified.orderCount,1);assert.equal(verified.itemCount,1);assert.equal(copy.prepare('PRAGMA integrity_check').get().integrity_check,'ok');const names=copy.prepare("SELECT lower(name) name FROM sqlite_master WHERE type='table'").all().map(row=>row.name).join(',');assert.equal(/oauth|cookie|token|kdocs|google/.test(names),false);}finally{copy.close();}}finally{await f.close();}});

test('备份恢复保留固定序号并正确回退订单',async()=>{const f=await fixture();try{const original=f.service.createOrder(order('RESTORE-OLD')),sequence=original.fixed_sequence;const backup=path.join(f.directory,'restore.sqlite');await createVerifiedBackup(f.database,backup,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION});f.service.createOrder(order('RESTORE-NEW'));assert.equal(f.database.prepare('SELECT count(*) count FROM orders').get().count,2);f.database.close();const replacement=await replaceDatabaseAtomically({databaseFile:orderDatabasePath(f.directory),sourceFile:backup,maxVersion:CURRENT_ORDER_SCHEMA_VERSION});await finalizeDatabaseReplacement(replacement.rollbackFile);f.database=await openOrderDatabase({userDataPath:f.directory,skipMigrationBackup:true});assert.equal(f.database.prepare('SELECT count(*) count FROM orders').get().count,1);assert.equal(f.database.prepare("SELECT fixed_sequence FROM orders WHERE shopplus_order_no='RESTORE-OLD'").get().fixed_sequence,sequence);assert.equal(f.database.prepare("SELECT count(*) count FROM orders WHERE shopplus_order_no='RESTORE-NEW'").get().count,0);}finally{await f.close();}});

test('替换后重连失败可使用安全回滚文件恢复原数据',async()=>{const f=await fixture();try{f.service.createOrder(order('ROLLBACK-OLD'));const backup=path.join(f.directory,'rollback-source.sqlite');await createVerifiedBackup(f.database,backup,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION});f.service.createOrder(order('ROLLBACK-CURRENT'));f.database.close();const replacement=await replaceDatabaseAtomically({databaseFile:orderDatabasePath(f.directory),sourceFile:backup,maxVersion:CURRENT_ORDER_SCHEMA_VERSION});await rollbackDatabaseReplacement({databaseFile:orderDatabasePath(f.directory),rollbackFile:replacement.rollbackFile});f.database=await openOrderDatabase({userDataPath:f.directory,skipMigrationBackup:true});assert.equal(f.database.prepare('SELECT count(*) count FROM orders').get().count,2);assert.equal(f.database.prepare("SELECT count(*) count FROM orders WHERE shopplus_order_no='ROLLBACK-CURRENT'").get().count,1);}finally{await f.close();}});

test('损坏文件、非订单SQLite、不完整结构、伪造迁移签名和高版本数据库被拒绝且当前数据不变',async()=>{const f=await fixture();try{f.service.createOrder(order('SAFE-CURRENT'));const corrupt=path.join(f.directory,'corrupt.sqlite'),other=path.join(f.directory,'other.sqlite'),incomplete=path.join(f.directory,'incomplete.sqlite'),forged=path.join(f.directory,'forged.sqlite'),newer=path.join(f.directory,'newer.sqlite');await writeFile(corrupt,'not sqlite');const ordinary=new DatabaseSync(other);ordinary.exec('CREATE TABLE notes(value TEXT)');ordinary.close();await createVerifiedBackup(f.database,incomplete,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION});const missing=new DatabaseSync(incomplete);missing.exec('DROP TABLE order_recipient_overrides');missing.close();await createVerifiedBackup(f.database,forged,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION});const fake=new DatabaseSync(forged);fake.prepare('UPDATE schema_migrations SET name=? WHERE version=1').run('unrelated_database');fake.close();await createVerifiedBackup(f.database,newer,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION});const high=new DatabaseSync(newer);high.prepare('INSERT INTO schema_migrations(version,name,applied_at) VALUES(999,?,?)').run('future','2026-09-02');high.close();for(const [file,code] of [[corrupt,'ORDER_BACKUP_CORRUPT'],[other,'ORDER_BACKUP_WRONG_DATABASE'],[incomplete,'ORDER_BACKUP_WRONG_DATABASE'],[forged,'ORDER_BACKUP_WRONG_DATABASE'],[newer,'ORDER_BACKUP_NEWER_VERSION']])assert.throws(()=>validateOrderDatabaseFile(file,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION}),error=>error.code===code);await assert.rejects(()=>replaceDatabaseAtomically({databaseFile:orderDatabasePath(f.directory),sourceFile:corrupt,maxVersion:CURRENT_ORDER_SCHEMA_VERSION}),error=>error.code==='ORDER_BACKUP_CORRUPT');assert.equal(f.database.prepare('SELECT count(*) count FROM orders').get().count,1);}finally{await f.close();}});

test('自动备份仅保留最近10份且不清理手动备份',async()=>{const f=await fixture();try{f.service.createOrder(order('RETENTION-1'));const base=Date.UTC(2026,8,2,0,0,0);for(let index=0;index<12;index++)await createAutomaticBackup(f.database,{userDataPath:f.directory,reason:'before_import',clock:()=>new Date(base+index*1000),maxVersion:CURRENT_ORDER_SCHEMA_VERSION});const directory=automaticBackupDirectory(f.directory),manual=path.join(directory,'orders-backup-manual.sqlite');await createVerifiedBackup(f.database,manual,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION});await cleanupAutomaticBackups(directory,{limit:10,maxVersion:CURRENT_ORDER_SCHEMA_VERSION});const names=await readdir(directory);assert.equal(names.filter(name=>name.startsWith('automatic-orders-backup-')).length,10);await access(manual);}finally{await f.close();}});

test('正式导入的自动备份失败时不进入数据写入',async()=>{const f=await fixture();try{let called=0;const app=new OrderAppService({database:f.database,userDataPath:f.directory,beforeCommit:async()=>{called++;throw new Error('fictional backup failure');}}),token='preview-token-safe';app.previews.set(token,{preview:{orders:[],summary:{blockingErrors:0}},reviewed:new Set(),createdAt:Date.now(),committing:false});await assert.rejects(()=>app.commit({token}),/fictional backup failure/);assert.equal(called,1);assert.equal(f.database.prepare('SELECT count(*) count FROM orders').get().count,0);assert.equal(f.database.prepare('SELECT count(*) count FROM import_batches').get().count,0);}finally{await f.close();}});

test('执行结构迁移前自动创建可验证的旧版备份',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'order-migration-backup-')),file=orderDatabasePath(directory);await mkdir(path.dirname(file),{recursive:true});let database=new DatabaseSync(file);try{migrateOrderDatabase(database,ORDER_MIGRATIONS.slice(0,1));database.close();database=await openOrderDatabase({userDataPath:directory});const names=await readdir(automaticBackupDirectory(directory));assert.equal(names.length,1);assert.equal(validateOrderDatabaseFile(path.join(automaticBackupDirectory(directory),names[0]),{maxVersion:CURRENT_ORDER_SCHEMA_VERSION}).schemaVersion,1);}finally{try{database.close();}catch{}await rm(directory,{recursive:true,force:true});}});
