import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {classifySeries,groupItemsBySeries} from '../src/orders/series-classifier.mjs';
import {classifyDeliveryZone} from '../src/orders/delivery-zone-classifier.mjs';
import {allocateShippingFee,moneyToFils} from '../src/orders/profit-calculation.mjs';
import {convertAedFilsToRmbFen,FinancialRuleRepository} from '../src/orders/financial-rules.mjs';
import {openOrderDatabase,migrateOrderDatabase} from '../src/orders/database.mjs';
import {migration001} from '../src/orders/migrations/001-initial.mjs';
import {ORDER_MIGRATIONS} from '../src/orders/migrations/index.mjs';
import {OrderRepository} from '../src/orders/order-repository.mjs';
import {OrderService} from '../src/orders/order-service.mjs';

const baseItem=(sku,overrides={})=>({sku_code:sku,product_name_snapshot:`测试商品${sku||'未知'}`,quantity:1,unit_list_price:'100.00',unit_actual_price:'100.00',unit_cost_snapshot:'20.00',cost_source:'test-fixture',...overrides});
async function fixture({at='2026-08-31T08:00:00.000Z'}={}){
  const directory=await mkdtemp(path.join(tmpdir(),'kdocs-orders-')),file=path.join(directory,'orders.sqlite'),resource={database:await openOrderDatabase({databaseFile:file})},clock={now:at};
  resource.repository=new OrderRepository(resource.database);resource.rules=new FinancialRuleRepository(resource.database);resource.service=new OrderService(resource.repository,{clock:()=>new Date(clock.now),rules:resource.rules});
  resource.close=async()=>{try{resource.database.close();}catch(error){if(error.code!=='ERR_INVALID_STATE')throw error;}await rm(directory,{recursive:true,force:true});};return {...resource,directory,file,clock,resource};
}
const create=(f,overrides={})=>f.resource.service.createOrder({source:'manual',city:'Dubai',delivery_status:'signed',items:[baseItem('KY02')],...overrides});

test('商品系列按前缀分包并保留纯数字前导零',()=>{
  assert.equal(groupItemsBySeries([baseItem('KY02'),baseItem(' ky40 ')]).length,1);assert.deepEqual(groupItemsBySeries([baseItem('KY02'),baseItem('YB17')]).map(value=>value.seriesCode),['KY','YB']);
  const numeric=groupItemsBySeries([baseItem('026'),baseItem('031')]);assert.equal(numeric[0].seriesCode,'NUMERIC');assert.deepEqual(numeric[0].items.map(value=>value.normalizedSku),['026','031']);assert.equal(classifySeries('Z01').seriesCode,'Z');
});
test('空SKU和异常SKU独立标记人工检查',()=>{assert.equal(classifySeries('').needsReview,true);assert.equal(classifySeries('-123').seriesCode,'UNCLASSIFIED:-123');assert.equal(groupItemsBySeries([baseItem(''),baseItem('')]).length,2);});

for(const [place,expected] of [['Dubai','urban'],['  dUbAi  ','urban'],['Sharjah','urban'],['Ajman','remote'],['Abu Dhabi','remote'],['Ras Al Khaimah','remote'],['Ras-Al-Khaimah','remote'],['Umm Al Quwain','remote'],['Al Ain','remote'],['Fujairah','remote']])
  test(`${place.trim()}配送区域识别为${expected}`,()=>assert.equal(classifyDeliveryZone({city:place}).zone,expected));
test('Al Ain优先于Abu Dhabi省份且仍归remote',()=>{const value=classifyDeliveryZone({city:'Al Ain',province:'Abu Dhabi'});assert.equal(value.zone,'remote');assert.equal(value.matchedPlace,'Al Ain');});
test('city无法识别时参考province，仍无法识别则unclassified',()=>{assert.equal(classifyDeliveryZone({city:'Unknown',province:'Dubai'}).zone,'urban');assert.equal(classifyDeliveryZone({city:'Unknown',province:'Unknown'}).zone,'unclassified');});
test('允许明确人工指定区域但拒绝模糊值',()=>{assert.equal(classifyDeliveryZone({city:'Unknown',override:'remote'}).source,'manual');assert.throws(()=>classifyDeliveryZone({override:'near dubai'}),/只能是urban或remote/);});
test('人工指定配送区域会写入事件历史',async()=>{const f=await fixture();try{const order=create(f,{city:'Unknown',delivery_zone_override:'urban'});assert.equal(order.packages[0].delivery_zone,'urban');assert.ok(order.events.some(event=>event.event_type==='delivery_zone_overridden'&&event.new_value==='urban'));}finally{await f.close();}});

for(const [city,status] of [['Dubai','signed'],['Sharjah','signed'],['Ajman','signed'],['Dubai','refused']])test(`${city} ${status}不自动套用固定费用`,async()=>{const f=await fixture();try{const order=create(f,{city,delivery_status:status}),p=order.packages[0];assert.equal(p.shipping_fee,null);assert.equal(p.delivery_fee,0);assert.equal(p.handling_fee,0);assert.equal(p.shipping_fee_finalized,0);assert.equal(order.projected_profit,null);assert.equal(order.realized_profit,null);assert.equal(order.profit_status,'pending');}finally{await f.close();}});
test('未识别地区不影响变量实际费用流程',async()=>{const f=await fixture();try{const order=create(f,{city:'Unknown'}),p=order.packages[0];assert.equal(p.delivery_zone,'unclassified');assert.equal(p.shipping_fee_finalized,0);assert.equal(order.profit_status,'pending');assert.equal(order.realized_profit,null);}finally{await f.close();}});
test('签收和拒收的费用录入规则相同',async()=>{const f=await fixture();try{const signed=create(f,{shopplus_order_no:'SAME-1'}),refused=create(f,{shopplus_order_no:'SAME-2',delivery_status:'refused'});for(const order of [signed,refused]){assert.equal(order.packages[0].shipping_fee_finalized,0);assert.equal(order.realized_profit,null);}}finally{await f.close();}});
test('出库前取消费用和利润均为0',async()=>{const f=await fixture();try{const order=create(f,{city:'Unknown',delivery_status:'cancelled_before_outbound'});assert.equal(order.packages[0].shipping_fee,0);assert.equal(order.realized_profit,0);assert.equal(order.profit_status,'final');}finally{await f.close();}});
test('出库后取消费用也待快递确认',async()=>{const f=await fixture();try{const order=create(f,{city:'Unknown',delivery_status:'cancelled_after_outbound'});assert.equal(order.packages[0].shipping_fee,null);assert.equal(order.packages[0].shipping_fee_finalized,0);assert.equal(order.realized_profit,null);assert.equal(order.profit_status,'pending');}finally{await f.close();}});
test('费用争议不能生成最终费用或利润',async()=>{const f=await fixture();try{const order=create(f,{delivery_status:'fee_dispute',fee_dispute_note:'fictional test dispute'});assert.equal(order.packages[0].shipping_fee_finalized,0);assert.equal(order.realized_profit,null);assert.equal(order.profit_status,'pending');}finally{await f.close();}});
test('实际运费未知时不用0运费生成虚假预计利润',async()=>{const f=await fixture();try{const order=create(f,{delivery_status:'outbound_processing'});assert.equal(order.projected_profit,null);assert.equal(order.realized_profit,null);assert.equal(order.profit_status,'pending');}finally{await f.close();}});
test('人工免除费用要求原因、保存快照并记录事件',async()=>{const f=await fixture();try{const order=create(f,{delivery_status:'fee_dispute'}),packageId=order.packages[0].id;assert.throws(()=>f.resource.service.overridePackageFee(packageId,{actual_fee:'0',reason:'',resolution_status:'signed'}),/必须填写/);
    assert.throws(()=>f.resource.service.overridePackageFee(packageId,{actual_fee:'-1',reason:'fictional invalid fee',resolution_status:'signed'}),/不能为负数/);
    const updated=f.resource.service.overridePackageFee(packageId,{actual_fee:'0',reason:'fictional warehouse waiver',resolution_status:'signed'}),p=updated.packages[0];assert.equal(p.fee_overridden,1);assert.equal(p.fee_confirmation_source,'manual_adjustment');assert.equal(p.shipping_fee,0);assert.equal(p.fee_override_reason,'fictional warehouse waiver');assert.ok(updated.events.some(event=>event.event_type==='package_fee_overridden'&&event.note==='fictional warehouse waiver'));
  }finally{await f.close();}});
test('未知地区的争议包裹在快递确认实际费用后可以结算',async()=>{const f=await fixture();try{const order=create(f,{city:'Unknown',delivery_status:'fee_dispute'}),updated=f.resource.service.confirmPackageFee(order.packages[0].id,{actual_fee:'5',reason:'fictional confirmed actual fee',resolution_status:'refused'}),pkg=updated.packages[0];assert.equal(pkg.fee_overridden,0);assert.equal(pkg.fee_confirmation_source,'courier');assert.equal(pkg.fee_confirmation_note,'fictional confirmed actual fee');assert.ok(pkg.fee_confirmed_at);assert.ok(updated.events.some(event=>event.event_type==='package_fee_confirmed'));assert.equal(updated.realized_profit,-500);assert.equal(updated.profit_status,'final');}finally{await f.close();}});
test('出库费可暂不拆分，如果拆分则组成必须等于快递确认总费用',async()=>{const f=await fixture();try{const order=create(f);assert.throws(()=>f.resource.service.confirmPackageFee(order.packages[0].id,{actual_fee:'47',delivery_fee:'45',handling_fee:'1',reason:'fictional invalid split',resolution_status:'signed'}),/组成之和/);const updated=f.resource.service.confirmPackageFee(order.packages[0].id,{actual_fee:'47',delivery_fee:'45',handling_fee:'2',reason:'fictional courier breakdown',resolution_status:'signed'}),pkg=updated.packages[0];assert.equal(pkg.delivery_fee,4500);assert.equal(pkg.handling_fee,200);assert.equal(pkg.shipping_fee,4700);}finally{await f.close();}});

test('同系列多商品只录入一个包裹实际费用并精确分摊',async()=>{const f=await fixture();try{const order=create(f,{items:[baseItem('KY02',{unit_actual_price:'100'}),baseItem('KY40',{unit_actual_price:'300'})]}),updated=f.resource.service.confirmPackageFee(order.packages[0].id,{actual_fee:'47',reason:'fictional courier invoice',resolution_status:'signed'});assert.equal(updated.packages.length,1);assert.equal(updated.packages[0].shipping_fee,4700);assert.deepEqual(updated.items.map(item=>item.realized_allocated_shipping_fee),[1175,3525]);assert.equal(updated.items.reduce((sum,item)=>sum+item.realized_allocated_shipping_fee,0),4700);}finally{await f.close();}});
test('KY和YB两个包裹必须分别确认实际费用',async()=>{const f=await fixture();try{let order=create(f,{items:[baseItem('KY02'),baseItem('YB17')]});assert.equal(order.packages.length,2);assert.equal(order.realized_profit,null);for(const pkg of order.packages)order=f.resource.service.confirmPackageFee(pkg.id,{actual_fee:'47',reason:'fictional courier invoice',resolution_status:'signed'});assert.equal(order.packages.reduce((sum,p)=>sum+p.shipping_fee,0),9400);assert.equal(order.profit_status,'final');}finally{await f.close();}});
test('分摊存在尾差时最后一条承担且总额严格一致',()=>{const allocations=allocateShippingFee([{lineRevenueFils:333n},{lineRevenueFils:333n},{lineRevenueFils:334n}],100n);assert.deepEqual(allocations,[33n,33n,34n]);});
test('签收确认实际费用后利润等于收入减成本减费用',async()=>{const f=await fixture();try{const order=create(f),updated=f.resource.service.confirmPackageFee(order.packages[0].id,{actual_fee:'47',reason:'fictional courier invoice',resolution_status:'signed'});assert.equal(updated.realized_profit,3300);}finally{await f.close();}});
test('拒签和出库后取消确认费用后不计收入及商品成本',async()=>{const f=await fixture();try{let refused=create(f,{shopplus_order_no:'R1',delivery_status:'refused',items:[baseItem('KY02',{unit_actual_price:'500',unit_cost_snapshot:'300'})]});refused=f.resource.service.confirmPackageFee(refused.packages[0].id,{actual_fee:'5',reason:'fictional courier invoice',resolution_status:'refused'});assert.equal(refused.realized_profit,-500);
    let after=create(f,{shopplus_order_no:'R2',delivery_status:'cancelled_after_outbound',items:[baseItem('YB17',{unit_actual_price:'500',unit_cost_snapshot:'300'})]});after=f.resource.service.confirmPackageFee(after.packages[0].id,{actual_fee:'7.25',reason:'fictional courier invoice',resolution_status:'cancelled_after_outbound'});assert.equal(after.realized_profit,-725);
  }finally{await f.close();}});
test('混合状态包裹在各自确认费用后汇总',async()=>{const f=await fixture();try{let order=create(f,{items:[baseItem('KY02',{package_status:'signed'}),baseItem('YB17',{package_status:'refused'})]});for(const pkg of order.packages)order=f.resource.service.confirmPackageFee(pkg.id,{actual_fee:'5',reason:'fictional courier invoice',resolution_status:pkg.series_code==='KY'?'signed':'refused'});assert.equal(order.realized_profit,7000);assert.equal(order.profit_status,'final');}finally{await f.close();}});
test('待派送订单运费未知时利润待确认',async()=>{const f=await fixture();try{const order=create(f,{delivery_status:'shipped_pending'});assert.equal(order.projected_profit,null);assert.equal(order.realized_profit,null);assert.equal(order.profit_status,'pending');}finally{await f.close();}});
test('签收商品缺少成本时利润不完整，但拒签不把缺失成本当销售成本',async()=>{const f=await fixture();try{let signed=create(f,{shopplus_order_no:'M1',items:[baseItem('KY02',{unit_cost_snapshot:null})]});signed=f.resource.service.confirmPackageFee(signed.packages[0].id,{actual_fee:'5',reason:'fictional courier invoice',resolution_status:'signed'});assert.equal(signed.realized_profit,null);assert.equal(signed.profit_status,'incomplete');
    let refused=create(f,{shopplus_order_no:'M2',delivery_status:'refused',items:[baseItem('YB17',{unit_cost_snapshot:null})]});refused=f.resource.service.confirmPackageFee(refused.packages[0].id,{actual_fee:'5',reason:'fictional courier invoice',resolution_status:'refused'});assert.equal(refused.realized_profit,-500);assert.equal(refused.profit_status,'final');
  }finally{await f.close();}});

test('正式汇率1.8按整数精度计算人民币结算',async()=>{const f=await fixture();try{let order=create(f);order=f.resource.service.confirmPackageFee(order.packages[0].id,{actual_fee:'47',reason:'fictional courier invoice',resolution_status:'signed'});assert.equal(order.exchange_rate_scaled,1800000);assert.equal(order.exchange_rate_scale,1000000);assert.equal(order.realized_profit,3300);assert.equal(order.realized_rmb_settlement,5940);assert.equal(convertAedFilsToRmbFen(-500n,{rate_scaled:1800000,scale:1000000}),-900n);}finally{await f.close();}});
test('人民币换算按整数半入规则处理正负尾差',()=>{assert.equal(convertAedFilsToRmbFen(1n,{rate_scaled:1750000,scale:1000000}),2n);assert.equal(convertAedFilsToRmbFen(-1n,{rate_scaled:1750000,scale:1000000}),-2n);});
test('没有有效汇率时保留AED利润并把人民币结算标为待确认',async()=>{const f=await fixture();try{f.resource.database.prepare("UPDATE exchange_rate_rules SET is_enabled=0 WHERE currency_pair='AED/CNY'").run();let order=create(f);order=f.resource.service.confirmPackageFee(order.packages[0].id,{actual_fee:'47',reason:'fictional courier invoice',resolution_status:'signed'});assert.equal(order.realized_profit,3300);assert.equal(order.realized_rmb_settlement,null);assert.equal(order.rmb_settlement_status,'pending');}finally{await f.close();}});
test('修改默认汇率不会改变历史订单汇率和人民币结算快照',async()=>{const f=await fixture();try{let old=create(f,{shopplus_order_no:'FX-OLD'});old=f.resource.service.confirmPackageFee(old.packages[0].id,{actual_fee:'47',reason:'fictional courier invoice',resolution_status:'signed'});f.resource.rules.createExchangeRate({id:'fx-v2',version:'v2',rate_scaled:2000000,scale:1000000,effective_from:'2026-09-01T00:00:00.000Z',created_at:'2026-08-31T09:00:00.000Z'});f.clock.now='2026-09-02T00:00:00.000Z';f.resource.service=new OrderService(f.resource.repository,{clock:()=>new Date(f.clock.now),rules:f.resource.rules});let current=create(f,{shopplus_order_no:'FX-NEW'});current=f.resource.service.confirmPackageFee(current.packages[0].id,{actual_fee:'47',reason:'fictional courier invoice',resolution_status:'signed'});
    const persisted=f.resource.repository.getOrder(old.id);assert.equal(persisted.exchange_rate_scaled,1800000);assert.equal(persisted.realized_rmb_settlement,5940);assert.equal(current.exchange_rate_scaled,2000000);assert.equal(current.realized_rmb_settlement,6600);
  }finally{await f.close();}});
test('新费用版本不会让历史变量费用包裹自动结算',async()=>{const f=await fixture();try{const pending=create(f,{shopplus_order_no:'FEE-OLD',delivery_status:'shipped_pending'}),p=pending.packages[0],created='2026-08-31T09:00:00.000Z';f.resource.rules.createFeeRuleSet({id:'fee-v3',version:'v3',effective_from:'2026-09-01T00:00:00.000Z',is_enabled:1,created_at:created,fee_mode:'fixed_rules'},[{id:'fee-v3-urban-signed',delivery_zone:'urban',package_status:'signed',delivery_fee:6200,handling_fee:0,total_fee:6200,created_at:created}]);
    f.resource.database.prepare("UPDATE fee_rule_sets SET is_enabled=0 WHERE id='fee-rules-variable-actual-v2'").run();f.clock.now='2026-09-02T00:00:00.000Z';f.resource.service=new OrderService(f.resource.repository,{clock:()=>new Date(f.clock.now),rules:f.resource.rules});const oldPending=f.resource.service.updatePackageStatus(p.id,'signed'),newOrder=create(f,{shopplus_order_no:'FEE-NEW'});assert.equal(oldPending.packages[0].shipping_fee_finalized,0);assert.equal(oldPending.packages[0].fee_rule_version,'variable-actual-v2');assert.equal(newOrder.packages[0].shipping_fee,6200);assert.equal(newOrder.packages[0].fee_rule_version,'v3');
  }finally{await f.close();}});
test('已发布费用和汇率版本的金额不可原地修改',async()=>{const f=await fixture();try{assert.throws(()=>f.resource.database.prepare("UPDATE fee_rules SET total_fee=9999 WHERE id='fee-urban-signed-v1'").run(),/immutable/);assert.throws(()=>f.resource.database.prepare("UPDATE exchange_rate_rules SET rate_scaled=999999 WHERE id='aed-cny-2026-08-31-v1'").run(),/immutable/);}finally{await f.close();}});

test('成本快照、客户原名、数据库重开和重复订单号约束均有效',async()=>{const f=await fixture();try{const item=baseItem('KY02',{unit_cost_snapshot:'20'}),order=create(f,{shopplus_order_no:'PERSIST-1',customer_full_name:'  Test  Customer  ',items:[item]});item.unit_cost_snapshot='99';assert.equal(f.resource.repository.getOrder(order.id).items[0].unit_cost_snapshot,2000);assert.throws(()=>create(f,{shopplus_order_no:'PERSIST-1'}),/UNIQUE constraint failed/);
    f.resource.database.close();f.resource.database=await openOrderDatabase({databaseFile:f.file});f.resource.repository=new OrderRepository(f.resource.database);assert.equal(f.resource.repository.getOrder(order.id).customer_full_name,'  Test  Customer  ');assert.equal((await stat(f.file)).mode&0o777,0o600);
  }finally{await f.close();}});

test('版本1数据库安全升级到变量费用版本并隔离旧50/22语义',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'kdocs-v1-upgrade-')),file=path.join(directory,'orders.sqlite'),db=new DatabaseSync(file);try{db.exec('PRAGMA foreign_keys=ON');migrateOrderDatabase(db,[migration001]);
    db.prepare(`INSERT INTO orders(id,source,currency,order_status,payment_status,fulfillment_status,delivery_status,discount_amount,profit_status,total_profit,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run('o1','manual','AED','new','unknown','unfulfilled','cancelled_before_shipping',0,'final',3000,'2026-08-30','2026-08-30');
    db.prepare(`INSERT INTO packages(id,order_id,series_code,package_status,shipping_fee,shipping_fee_finalized,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run('p1','o1','KY','signed',5000,1,'2026-08-30','2026-08-30');
    db.prepare(`INSERT INTO packages(id,order_id,series_code,package_status,shipping_fee,shipping_fee_finalized,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run('p2','o1','YB','refused',2200,1,'2026-08-30','2026-08-30');
    db.prepare(`INSERT INTO packages(id,order_id,series_code,package_status,shipping_fee,shipping_fee_finalized,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run('p3','o1','NUMERIC','cancelled_before_shipping',0,1,'2026-08-30','2026-08-30');
    db.prepare(`INSERT INTO order_items(id,order_id,sku_code,product_name_snapshot,quantity,unit_list_price,unit_actual_price,unit_cost_snapshot,package_id,allocated_shipping_fee,line_revenue,line_cost,line_profit,needs_review,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run('i1','o1','KY02','Fictional Product',1,10000,10000,2000,'p1',5000,10000,2000,3000,0,'2026-08-30','2026-08-30');
    db.prepare(`INSERT INTO order_items(id,order_id,sku_code,product_name_snapshot,quantity,unit_list_price,unit_actual_price,unit_cost_snapshot,package_id,allocated_shipping_fee,line_revenue,line_cost,line_profit,needs_review,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run('i2','o1','YB17','Fictional Product 2',1,10000,10000,2000,'p2',2200,10000,2000,5800,0,'2026-08-30','2026-08-30');
    db.prepare(`INSERT INTO order_items(id,order_id,sku_code,product_name_snapshot,quantity,unit_list_price,unit_actual_price,unit_cost_snapshot,package_id,allocated_shipping_fee,line_revenue,line_cost,line_profit,needs_review,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run('i3','o1','026','Fictional Product 3',1,10000,10000,2000,'p3',0,10000,2000,8000,0,'2026-08-30','2026-08-30');
    db.prepare(`INSERT INTO order_events(id,order_id,package_id,event_type,event_time) VALUES(?,?,?,?,?)`).run('e1','o1','p1','created','2026-08-30');migrateOrderDatabase(db);
    const order=db.prepare('SELECT * FROM orders WHERE id=?').get('o1'),pkg=db.prepare('SELECT * FROM packages WHERE id=?').get('p1'),refused=db.prepare('SELECT * FROM packages WHERE id=?').get('p2'),cancelled=db.prepare('SELECT * FROM packages WHERE id=?').get('p3'),item=db.prepare('SELECT * FROM order_items WHERE id=?').get('i1');assert.equal(order.legacy_total_profit,3000);assert.equal(order.total_profit,null);assert.equal(order.profit_status,'incomplete');assert.equal(order.delivery_status,'cancelled_before_outbound');assert.equal(order.order_confirmed,0);assert.equal(order.order_confirmed_at,null);assert.equal(pkg.legacy_shipping_fee,5000);assert.equal(pkg.shipping_fee,null);assert.equal(pkg.shipping_fee_finalized,0);assert.equal(pkg.status_updated_at,'2026-08-30');assert.equal(pkg.fee_rule_version,'variable-actual-v2');assert.equal(refused.legacy_shipping_fee,2200);assert.equal(refused.shipping_fee,null);assert.equal(refused.shipping_fee_finalized,0);assert.equal(cancelled.package_status,'cancelled_before_outbound');assert.equal(cancelled.shipping_fee_finalized,1);assert.match(pkg.fee_dispute_note,/requires review/);assert.equal(item.legacy_line_profit,3000);assert.equal(item.source_line_revenue,10000);assert.equal(item.manual_discount,null);assert.equal(db.prepare('SELECT count(*) count FROM order_items').get().count,3);assert.equal(db.prepare('SELECT count(*) count FROM order_events').get().count,1);
  }finally{db.close();await rm(directory,{recursive:true,force:true});}});
test('数据库迁移重复运行不会重复破坏数据',async()=>{const f=await fixture();try{create(f);const first=migrateOrderDatabase(f.resource.database),second=migrateOrderDatabase(f.resource.database);assert.deepEqual(second,first);assert.equal(first.length,ORDER_MIGRATIONS.length);assert.equal(f.resource.database.prepare('SELECT count(*) count FROM orders').get().count,1);}finally{await f.close();}});
test('旧订单按创建时间稳定回填固定序号且唯一',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'kdocs-sequence-upgrade-')),file=path.join(directory,'orders.sqlite'),database=new DatabaseSync(file);try{database.exec('PRAGMA foreign_keys=ON');migrateOrderDatabase(database,ORDER_MIGRATIONS.slice(0,11));const service=new OrderService(new OrderRepository(database),{clock:()=>new Date('2026-09-01T00:00:00.000Z')});const later=service.createOrder({source:'manual',shopplus_order_no:'SEQ-LATER',shopplus_created_at:'2026-08-02T00:00:00.000Z',city:'Dubai',items:[baseItem('KY02')]}),tieB=service.createOrder({source:'manual',shopplus_order_no:'SEQ-TIE-B',shopplus_created_at:'2026-08-01T00:00:00.000Z',city:'Dubai',items:[baseItem('YB17')]}),tieA=service.createOrder({source:'manual',shopplus_order_no:'SEQ-TIE-A',shopplus_created_at:'2026-08-01T00:00:00.000Z',city:'Dubai',items:[baseItem('Z01')]});migrateOrderDatabase(database);const rows=database.prepare('SELECT id,fixed_sequence FROM orders ORDER BY fixed_sequence').all();assert.deepEqual(rows.map(row=>row.id),[tieA.id,tieB.id,later.id].sort((left,right)=>{const dates=new Map([[later.id,'2026-08-02'],[tieA.id,'2026-08-01'],[tieB.id,'2026-08-01']]);return dates.get(left).localeCompare(dates.get(right))||left.localeCompare(right);}));assert.deepEqual(rows.map(row=>row.fixed_sequence),[1,2,3]);assert.throws(()=>database.prepare('UPDATE orders SET fixed_sequence=1 WHERE fixed_sequence=2').run(),/UNIQUE/);}finally{database.close();await rm(directory,{recursive:true,force:true});}});
test('新订单固定序号只递增且删除后不复用',async()=>{const f=await fixture();try{const first=create(f,{shopplus_order_no:'SEQ-NEW-1'}),second=create(f,{shopplus_order_no:'SEQ-NEW-2'});assert.deepEqual([first.fixed_sequence,second.fixed_sequence],[1,2]);f.resource.database.prepare('DELETE FROM orders WHERE id=?').run(second.id);const third=create(f,{shopplus_order_no:'SEQ-NEW-3'});assert.equal(third.fixed_sequence,3);f.resource.database.close();f.resource.database=await openOrderDatabase({databaseFile:f.file});assert.equal(f.resource.database.prepare('SELECT fixed_sequence FROM orders WHERE id=?').get(third.id).fixed_sequence,3);}finally{await f.close();}});
test('迁移失败会完整回滚DDL和版本记录',async()=>{const f=await fixture();try{const broken={version:999,name:'broken',statements:['CREATE TABLE must_rollback(id INTEGER)','THIS IS NOT SQL']};assert.throws(()=>migrateOrderDatabase(f.resource.database,[broken]));assert.equal(f.resource.database.prepare("SELECT count(*) count FROM sqlite_master WHERE type='table' AND name='must_rollback'").get().count,0);assert.equal(f.resource.database.prepare('SELECT count(*) count FROM schema_migrations WHERE version=999').get().count,0);}finally{await f.close();}});
test('金额只能用字符串或整数fils，避免浮点误差',()=>{assert.equal(moneyToFils('0.01'),1n);assert.throws(()=>moneyToFils(0.1),/不能使用JavaScript浮点数/);});
