import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import electronPath from 'electron';
import {mkdir,mkdtemp,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {openOrderDatabase} from '../src/orders/database.mjs';
import {OrderRepository} from '../src/orders/order-repository.mjs';
import {OrderService} from '../src/orders/order-service.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';

const packageInfo=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8'));
const input={source:'manual',shopplus_order_no:'DETAIL-FULFILLMENT-001',shopplus_created_at:'2026-09-28T08:00:00.000Z',currency:'AED',order_status:'fictional',delivery_status:'unshipped',payment_method:'COD',customer_first_name:'Fulfillment',customer_last_name:'Audit',customer_full_name:'Fulfillment Audit',customer_phone:'+000 000 013',customer_email:'fulfillment@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'13 Fictional Street',residence:'Unit 13',items:[{sku_code:'FULFILL13',product_name_snapshot:'Fictional fulfillment product',quantity:1,unit_list_price:'100',unit_actual_price:'100',unit_cost_snapshot:'20',cost_source:'fictional'}]};

test('订单详情可登记客户确认，并按包裹完成运输、已收货、运费和本机回款登记',async()=>{
  const directory=await mkdtemp(path.join(os.tmpdir(),'order-detail-fulfillment-')),userData=path.join(directory,'data'),artifacts=path.resolve(process.env.KDOCS_TEST_ARTIFACT_DIRECTORY||`artifacts/order-detail-fulfillment-${packageInfo.version}`);let application,database;
  try{
    await mkdir(artifacts,{recursive:true});database=await openOrderDatabase({userDataPath:userData});const service=new OrderService(new OrderRepository(database)),created=service.createOrder(input);database.close();database=null;
    const executable=process.env.KDOCS_TEST_EXECUTABLE;application=await electron.launch({executablePath:executable||electronPath,args:[...(executable?[]:['.']),`--orders-test-user-data=${userData}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});const page=await application.firstWindow();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',error=>errors.push(error.message));const frame=page.frameLocator('iframe.confirmed-frame');
    await frame.getByRole('button',{name:'订单管理',exact:true}).click();const table=frame.locator('.ob-rows tr').filter({hasText:'DETAIL-FULFILLMENT-001'});await table.getByRole('button',{name:'订单详情',exact:true}).click();const root=frame.locator('#ui008-order-detail');await root.getByRole('heading',{name:'DETAIL-FULFILLMENT-001',exact:true}).waitFor();
    await root.getByRole('button',{name:'待确认',exact:true}).click();const confirmationDialog=root.locator('.ob-fulfillment-dialog');await confirmationDialog.getByRole('heading',{name:'确认客户订单',exact:true}).waitFor();await confirmationDialog.getByLabel('客户确认依据或备注').fill('fictional customer explicitly confirmed order and delivery details');await confirmationDialog.getByRole('button',{name:'确认客户订单',exact:true}).click();await root.getByText('已确认',{exact:true}).waitFor();assert.equal(await root.locator('.ob-status-complete').filter({hasText:'已确认'}).count(),1,'客户确认后显示灰色已确认');
    await root.getByRole('button',{name:'标记出库中',exact:true}).click();await root.getByText('出库中 · 实际物流费 待登记',{exact:true}).waitFor();
    await root.getByRole('button',{name:'标记运输中',exact:true}).click();await root.getByText('运输中 · 实际物流费 待登记',{exact:true}).waitFor();
    await root.getByRole('button',{name:'确认已收货',exact:true}).click();const receiptDialog=root.locator('.ob-fulfillment-dialog');await receiptDialog.getByRole('heading',{name:'确认已收货',exact:true}).waitFor();await receiptDialog.getByRole('button',{name:'取消',exact:true}).click();assert.equal(await root.getByRole('button',{name:'确认已收货',exact:true}).count(),1,'取消确认不改变待收货状态');
    await root.getByRole('button',{name:'确认已收货',exact:true}).click();await root.locator('.ob-fulfillment-dialog').getByRole('button',{name:'确认',exact:true}).click();await root.getByText('已签收 · 实际物流费 待登记',{exact:true}).waitFor();
    await root.getByRole('button',{name:'登记实际物流费',exact:true}).click();const feeDialog=root.locator('.ob-fulfillment-dialog');await feeDialog.getByLabel('实际物流费（AED）').fill('5.25');await feeDialog.getByRole('button',{name:'确认',exact:true}).click();await root.getByText('已签收 · 实际物流费 AED 5.25',{exact:true}).waitFor();
    await root.getByRole('button',{name:'登记净回款',exact:true}).click();const remittanceDialog=root.locator('.ob-fulfillment-dialog');await remittanceDialog.getByLabel('净回款（CNY）').fill('320.00');await remittanceDialog.getByLabel('回款日期').fill('2026-09-28');await remittanceDialog.getByRole('button',{name:'确认',exact:true}).click();await root.getByText('已登记净回款：CNY ¥320.00 · 2026-09-28',{exact:true}).waitFor();
    const detail=await page.evaluate(orderId=>window.inventoryApp.orders.detail(orderId),created.id);assert.equal(detail.ok,true);assert.equal(detail.data.packages[0].status,'signed');assert.equal(detail.data.packages[0].shippingFeeFils,525);assert.equal(detail.data.packages[0].shippingFeeConfirmed,true);assert.equal(detail.data.remittance.amountFils,32000);assert.equal(detail.data.remittance.registeredAt.slice(0,10),'2026-09-28');
    await root.locator('.ob-settlement-card').scrollIntoViewIfNeeded();await page.waitForTimeout(180);await page.screenshot({path:path.join(artifacts,'order-detail-fulfillment-1280x820.png')});assert.deepEqual(errors,[],'履约操作没有页面错误');
  }finally{if(database)database.close();if(application){await application.close().catch(()=>{});try{if(application.process().exitCode===null)application.process().kill('SIGKILL');}catch{}}await rm(directory,{recursive:true,force:true});}
});

test('订单详情拒收必须填写依据，并可安排只记录在本机的后续跟进',async()=>{
  const directory=await mkdtemp(path.join(os.tmpdir(),'order-detail-refusal-')),userData=path.join(directory,'data');let application,database;
  try{
    database=await openOrderDatabase({userDataPath:userData});const service=new OrderService(new OrderRepository(database)),app=new OrderAppService({database,userDataPath:userData}),created=service.createOrder({...input,shopplus_order_no:'DETAIL-REFUSAL-001'});app.confirmOrder({orderId:created.id,note:'fictional confirmed order'});app.updatePackageStatus({packageId:created.packages[0].id,status:'outbound_processing'});app.updatePackageStatus({packageId:created.packages[0].id,status:'shipped_pending'});database.close();database=null;
    const executable=process.env.KDOCS_TEST_EXECUTABLE;application=await electron.launch({executablePath:executable||electronPath,args:[...(executable?[]:['.']),`--orders-test-user-data=${userData}`],cwd:path.resolve('.'),env:{...process.env,NODE_ENV:'test'}});const page=await application.firstWindow();page.setDefaultTimeout(15000);const frame=page.frameLocator('iframe.confirmed-frame');await frame.getByRole('button',{name:'订单管理',exact:true}).click();const table=frame.locator('.ob-rows tr').filter({hasText:'DETAIL-REFUSAL-001'});await table.getByRole('button',{name:'订单详情',exact:true}).click();const root=frame.locator('#ui008-order-detail');await root.getByRole('heading',{name:'DETAIL-REFUSAL-001',exact:true}).waitFor();
    await root.getByRole('button',{name:'登记拒收／拒单',exact:true}).click();const refusalDialog=root.locator('.ob-fulfillment-dialog');await refusalDialog.getByRole('heading',{name:'登记拒收／拒单',exact:true}).waitFor();await refusalDialog.getByRole('button',{name:'确认',exact:true}).click();await refusalDialog.getByText('拒单、联系不上或取消必须填写备注',{exact:true}).waitFor();await refusalDialog.getByLabel('拒收／拒单原因（必填）').fill('fictional customer refused delivery');await refusalDialog.getByRole('button',{name:'确认',exact:true}).click();await root.getByRole('button',{name:'待跟进',exact:true}).waitFor();const refusedStatus=root.locator('.ob-status-complete').filter({hasText:'已拒收'});await refusedStatus.waitFor();assert.equal(await refusedStatus.evaluate(element=>getComputedStyle(element).backgroundColor),'rgb(222, 219, 226)','已完成状态使用灰色完成态');
    await root.getByRole('button',{name:'待跟进',exact:true}).click();const followup=root.locator('[data-order-followup]');await followup.getByRole('button',{name:'拒单询问',exact:true}).click();const followupDialog=root.locator('.ob-fulfillment-dialog');await followupDialog.getByRole('heading',{name:'安排拒单询问',exact:true}).waitFor();await followupDialog.getByLabel('下次跟进时间').fill('2099-01-01T10:00');await followupDialog.getByLabel('跟进备注或依据（必填）').fill('fictional refusal follow-up');await followupDialog.getByRole('button',{name:'保存本机提醒',exact:true}).click();await followup.getByText(/已安排下次跟进：2099-01-01/).waitFor();
    const detail=await page.evaluate(orderId=>window.inventoryApp.orders.detail(orderId),created.id);assert.equal(detail.ok,true);assert.equal(detail.data.packages[0].status,'refused');assert.equal(detail.data.confirmed,true);await page.screenshot({path:path.resolve(`artifacts/order-detail-refusal-${packageInfo.version}.png`)});
  }finally{if(database)database.close();if(application){await application.close().catch(()=>{});try{if(application.process().exitCode===null)application.process().kill('SIGKILL');}catch{}}await rm(directory,{recursive:true,force:true});}
});
