import test from 'node:test';
import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright-core';
import ExcelJS from 'exceljs';
import {DatabaseSync} from 'node:sqlite';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdir,writeFile,readFile,readdir,rename,access,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {openOrderDatabase,orderDatabasePath,migrateOrderDatabase} from '../src/orders/database.mjs';
import {ORDER_MIGRATIONS,CURRENT_ORDER_SCHEMA_VERSION} from '../src/orders/migrations/index.mjs';
import {OrderRepository} from '../src/orders/order-repository.mjs';
import {OrderService} from '../src/orders/order-service.mjs';
import {validateOrderDatabaseFile} from '../src/orders/order-data-protection.mjs';

const execute=promisify(execFile);
const appPath=path.resolve(required('PACKAGED_APP_PATH'));
const acceptanceRoot=validatedAcceptanceRoot(required('PACKAGED_ACCEPTANCE_ROOT'));
const oldAppPath=process.env.PACKAGED_OLD_APP_PATH?path.resolve(process.env.PACKAGED_OLD_APP_PATH):null;
const oldAppVersion=process.env.PACKAGED_OLD_APP_VERSION||'0.1.9';
const executable=path.join(appPath,'Contents','MacOS','KDocs 库存同步');
const columns=[
  ['订单信息基础信息','订单号','orderNo'],['订单信息基础信息','子订单 ID','subOrderId'],['订单信息基础信息','创建时间','createdAt'],['订单信息基础信息','订单状态','orderStatus'],['订单信息基础信息','货币单位','currency'],['订单信息基础信息','订单总价','orderTotal'],['订单信息基础信息','商品总价','productTotal'],['订单信息基础信息','优惠金额','discountAmount'],['订单信息基础信息','物流费用','customerShippingFee'],['订单信息基础信息','支付方式','paymentMethod'],
  ['收货信息','名(firstName)','firstName'],['收货信息','姓(lastName)','lastName'],['收货信息','姓名','fullName'],['收货信息','联系电话','phone'],['收货信息','联系邮箱','email'],['收货信息','国家','country'],['收货信息','省/州','province'],['收货信息','城市','city'],['收货信息','街道','street'],['收货信息','寓所','residence'],
  ['商品信息','商品SKU','productSku'],['商品信息','商品名称','productName'],['商品信息','商品售价','unitPrice'],['商品信息','售出数量','quantity'],['商品信息','商品支付状态','paymentStatus'],['商品信息','商品配送状态','fulfillmentStatus']
];

function required(name){const value=process.env[name];if(!value)throw new Error(`Missing ${name}`);return value;}
function validatedAcceptanceRoot(value){const resolved=path.resolve(value),underTemp=['/tmp',os.tmpdir()].some(root=>{const relative=path.relative(root,resolved);return Boolean(relative)&&!relative.startsWith('..')&&!path.isAbsolute(relative);});if(!path.basename(resolved).startsWith('kdocs-packaged-acceptance.')||!underTemp)throw new Error('PACKAGED_ACCEPTANCE_ROOT must be a dedicated kdocs-packaged-acceptance.* temporary directory');return resolved;}
const packageCard=(page,series)=>page.locator('.package-profit-card').filter({hasText:`${series}系列`});
const reportCard=(page,series)=>page.locator('.report-packages article').filter({hasText:`${series}系列`});
const current=(page,name)=>page.locator('.status-step.current',{hasText:name});
const acceptDialogs=page=>page.on('dialog',dialog=>dialog.accept());
async function launch(userData,{excelFile,saveDirectory,dataDirectory,restoreFile}={}){
  const args=[`--orders-test-user-data=${userData}`,'--orders-test-address-deliverable'];
  if(excelFile)args.push(`--orders-test-excel=${excelFile}`);
  if(saveDirectory)args.push(`--orders-test-save-directory=${saveDirectory}`);
  if(dataDirectory)args.push(`--orders-test-data-directory=${dataDirectory}`);
  if(restoreFile)args.push(`--orders-test-restore-file=${restoreFile}`);
  const application=await electron.launch({executablePath:executable,args,env:{...process.env,NODE_ENV:'test'}});
  const identity=await application.evaluate(({app,Menu})=>({packaged:app.isPackaged,version:app.getVersion(),name:app.getName(),userData:app.getPath('userData'),menuItems:Menu.getApplicationMenu()?.items.length||0}));
  assert.deepEqual({...identity,menuItems:undefined},{packaged:true,version:'0.1.13',name:'KDocs Inventory Sync',userData:path.resolve(userData),menuItems:undefined});assert.ok(identity.menuItems>0);
  assert.equal(application.process().spawnfile,executable);
  assert.equal(executable.includes('node_modules'),false);
  return application;
}
async function launchInstalledVersion(bundle,userData,version){const binary=path.join(bundle,'Contents','MacOS','KDocs 库存同步'),application=await electron.launch({executablePath:binary,args:[`--orders-test-user-data=${userData}`],env:{...process.env,NODE_ENV:'test'}}),identity=await application.evaluate(({app})=>({packaged:app.isPackaged,version:app.getVersion(),userData:app.getPath('userData')}));assert.deepEqual(identity,{packaged:true,version,userData:path.resolve(userData)});return application;}

async function makeExcel(file){
  const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Fictional Orders');let start=1;
  for(const group of [...new Set(columns.map(value=>value[0]))]){const count=columns.filter(value=>value[0]===group).length;sheet.mergeCells(1,start,1,start+count-1);sheet.getCell(1,start).value=group;start+=count;}
  columns.forEach((value,index)=>{sheet.getCell(2,index+1).value=value[1];});
  const base={orderNo:'PACKAGED-CLEAN-1',createdAt:'2026-09-02 12:00:00',orderStatus:'待发货',currency:'AED',orderTotal:'180',productTotal:'180',discountAmount:'0',customerShippingFee:'0',paymentMethod:'COD',firstName:'',lastName:'Fictional Surname',fullName:'Fictional Full Name Preserved',phone:'+00000000001',email:'packaged@example.invalid',country:'Example Country',province:'',city:'Example City',street:'Example Street',residence:'',quantity:'1',paymentStatus:'paid',fulfillmentStatus:'pending'};
  const rows=[{...base,subOrderId:'PACKAGED-KY',productSku:'KY02',productName:'KY02 Packaged Fictional Product',unitPrice:'100'},{...base,subOrderId:'PACKAGED-Z',productSku:'Z01',productName:'Z01 Packaged Fictional Product',unitPrice:'80'}];
  rows.forEach((row,rowIndex)=>columns.forEach((value,column)=>{sheet.getCell(rowIndex+3,column+1).value=row[value[2]]??'';}));
  await workbook.xlsx.writeFile(file);
}

const manualOrder=(orderNo,overrides={})=>({source:'manual',shopplus_order_no:orderNo,currency:'AED',delivery_status:'unshipped',customer_first_name:'Fictional',customer_last_name:'Recipient',customer_full_name:'Fictional Recipient',customer_phone:'+00000000002',customer_email:'upgrade@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Example Street',residence:'Example Residence',items:[{sku_code:'YB17',product_name_snapshot:'YB17 Fictional Product',quantity:1,unit_list_price:'50',unit_actual_price:'50',unit_cost_snapshot:'15'}],...overrides});
const responsiveOrderNo=`PACKAGED-RESPONSIVE-${'ORDER'.repeat(28)}`;
const responsiveOrder=()=>manualOrder(responsiveOrderNo,{customer_first_name:null,customer_last_name:'اختبار',customer_full_name:'اسم خيالي كامل للاختبار',customer_email:`fictional.${'mailbox'.repeat(22)}@example.invalid`,province:null,street:`${'Fictional-Unbroken-English-Address-'.repeat(12)} شارع اختباري طويل للغاية`,residence:null,items:[{sku_code:'KY02',product_name_snapshot:`KY02 ${'Very Long Fictional Product '.repeat(10)}`,quantity:1,unit_list_price:'100',unit_actual_price:'100',unit_cost_snapshot:'20'},{sku_code:'YB17',product_name_snapshot:'YB17 Fictional Product',quantity:1,unit_list_price:'60',unit_actual_price:'60',unit_cost_snapshot:'15'},{sku_code:'Z01',product_name_snapshot:'Z01 Fictional Product',quantity:1,unit_list_price:'50',unit_actual_price:'50',unit_cost_snapshot:'10'}]});

async function packagedDialogGeometry(page){return page.evaluate(()=>{const dialog=document.querySelector('#order-detail-dialog'),content=document.querySelector('#order-detail-content'),close=document.querySelector('#order-detail-close'),footer=document.querySelector('.detail-modal-actions'),grid=document.querySelector('.detail-workspace'),rect=element=>{const box=element.getBoundingClientRect();return {left:box.left,right:box.right,top:box.top,bottom:box.bottom};},dialogRect=dialog.getBoundingClientRect();return {width:innerWidth,height:innerHeight,dialog:rect(dialog),close:rect(close),footer:rect(footer),dialogScroll:[dialog.scrollWidth,dialog.clientWidth],contentScroll:[content.scrollWidth,content.clientWidth,content.scrollLeft,content.scrollHeight,content.clientHeight],columns:getComputedStyle(grid).gridTemplateColumns.split(' ').length,background:getComputedStyle(document.body).overflow,overflowing:[...dialog.querySelectorAll('*')].filter(element=>!element.matches('input,select,textarea')&&element.scrollWidth>element.clientWidth+1).length,clipped:[...dialog.querySelectorAll('h2,h3,.detail-field,.detail-section,.recipient-row,.fulfillment-package,.modal-actions,button,input,select')].filter(element=>element.getClientRects().length&&(element.getBoundingClientRect().left<dialogRect.left-.5||element.getBoundingClientRect().right>dialogRect.right+.5)).length};});}
function assertPackagedDialog(result,columns){assert.ok(result.dialog.left>=15.5&&result.dialog.right<=result.width-15.5);assert.ok(result.dialog.top>=15.5&&result.dialog.bottom<=result.height-15.5);assert.deepEqual(result.dialogScroll,[result.dialogScroll[1],result.dialogScroll[1]]);assert.equal(result.contentScroll[0],result.contentScroll[1]);assert.equal(result.contentScroll[2],0);assert.ok(result.contentScroll[3]>result.contentScroll[4]);assert.equal(result.columns,columns);assert.equal(result.background,'hidden');assert.equal(result.overflowing,0);assert.equal(result.clipped,0);for(const part of [result.close,result.footer])assert.ok(part.left>=result.dialog.left&&part.right<=result.dialog.right&&part.top>=result.dialog.top&&part.bottom<=result.dialog.bottom);}
async function packagedOrderListGeometry(page,row){return page.evaluate(element=>{const wrap=document.querySelector('.order-list-wrap'),table=document.querySelector('.order-list-table'),head=table.querySelector('thead'),cells=[...element.querySelectorAll('td')];return {page:[document.documentElement.scrollWidth,document.documentElement.clientWidth],wrap:[wrap.scrollWidth,wrap.clientWidth],table:[table.scrollWidth,wrap.clientWidth],headVisible:getComputedStyle(head).display!=='none',labels:cells.map(cell=>cell.dataset.label),stacks:cells.slice(7).map(cell=>cell.querySelectorAll('.cell-stack span').length)};},await row.elementHandle());}
async function packagedOrderSurfaceVisual(page,{panel,surface,header,cell}){return page.evaluate(selectors=>{const style=selector=>getComputedStyle(document.querySelector(selector)),panelStyle=style(selectors.panel),surfaceStyle=style(selectors.surface),headerStyle=style(selectors.header),cellStyle=style(selectors.cell),shell=document.querySelector('.shell').getBoundingClientRect();return {shellWidth:Math.round(shell.width),pageFits:document.documentElement.scrollWidth===document.documentElement.clientWidth,panel:[panelStyle.backgroundColor,panelStyle.borderRadius,panelStyle.boxShadow,panelStyle.paddingTop],surface:[surfaceStyle.backgroundColor,surfaceStyle.borderRadius,surfaceStyle.borderTopWidth],header:[headerStyle.color,headerStyle.fontSize,headerStyle.fontWeight],cell:[cellStyle.color,cellStyle.fontSize,cellStyle.lineHeight]};}, {panel,surface,header,cell});}

test('packaged App completes clean install, business flow, persistence, restore and reinstall',async()=>{
  const root=path.join(acceptanceRoot,'clean'),userData=path.join(root,'user-data'),outputs=path.join(root,'outputs'),excelFile=path.join(root,'fictional-orders.xlsx');let application,database;
  await mkdir(path.join(userData,'state'),{recursive:true});await mkdir(outputs,{recursive:true});await makeExcel(excelFile);await writeFile(path.join(userData,'state','baseline.json'),JSON.stringify({versionAt:'packaged-fictional',products:[['商品编号','来源商品名称','成本'],['KY02','KY02 Fictional','20'],['Z01','Z01 Fictional','10']]}));
  try{
    application=await launch(userData,{excelFile,saveDirectory:outputs,dataDirectory:outputs});let page=await application.firstWindow();acceptDialogs(page);await page.waitForLoadState('domcontentloaded');assert.equal(await page.title(),'KDocs 库存同步');await page.getByText('检查并同步库存').waitFor();await page.getByRole('button',{name:'订单管理'}).click();await page.waitForFunction(()=>document.querySelector('#sum-total')?.textContent==='0');await page.getByRole('button',{name:'导入ShopPlus Excel'}).first().click();await page.waitForFunction(()=>document.querySelector('#pv-orders')?.textContent==='1');assert.equal(await page.locator('#pv-items').textContent(),'2');await page.getByText('准备导入 1 个订单').waitFor();await page.getByRole('button',{name:'确认导入'}).click();await page.locator('#import-confirm-dialog').getByRole('button',{name:'确认导入'}).click();await page.locator('#orders-table-body tr').click();assert.equal(await page.locator('.package-profit-card').count(),2);await current(page,'待确认').click();
    await page.getByRole('button',{name:'确认使用原始Full name'}).click();await page.getByRole('button',{name:'编辑收件资料'}).click();await page.getByLabel('选择收件资料字段').selectOption('province');await page.getByLabel('省人工值').fill('Fictional Confirmed Province');await page.getByLabel('省修改原因').fill('fictional packaged acceptance');await page.getByRole('button',{name:'保存修改'}).click();await page.getByText('Residence未提供，请确认Street中已有足够的详细地址。',{exact:true}).waitFor();await page.getByRole('button',{name:'校验地址'}).click();await page.getByText('✅ 地址可配送').waitFor();
    for(const series of ['KY','Z']){await page.getByLabel('当前操作包裹').selectOption({label:`${series}包裹`});await current(page,'待发货').click();await current(page,'出库中').click();await page.getByRole('button',{name:'签收',exact:true}).click();}
    for(const [series,fee] of [['KY','5.00'],['Z','2.00']]){const card=packageCard(page,series);await card.getByLabel(`${series}实际物流费`).fill(fee);await card.getByLabel(`${series}费用备注`).fill('fictional courier confirmation');await card.getByRole('button',{name:'保存物流费'}).click();await reportCard(page,series).getByRole('button',{name:'生成报单'}).click();await page.getByRole('button',{name:'下载TXT'}).click();}
    await page.getByText('AED 143.00').first().waitFor();await page.keyboard.press('Escape');await page.getByRole('button',{name:'利润登记'}).click();await page.locator('#profit-total').getByText('AED 143.00').waitFor();await page.getByRole('button',{name:'导出当前筛选 Excel'}).click();await page.getByText('利润表已导出：profit-export-test.xlsx（2 行）').waitFor();await page.getByRole('button',{name:'数据管理'}).click();await page.getByRole('button',{name:'创建订单备份'}).click();await page.getByText('订单备份已创建：orders-backup-test.sqlite').waitFor();await application.close();application=null;
    const txtFiles=(await readdir(outputs)).filter(value=>value.endsWith('.txt')).sort();assert.deepEqual(txtFiles,['PACKAGED-CLEAN-1_KY.txt','PACKAGED-CLEAN-1_Z.txt']);for(const file of txtFiles){const content=await readFile(path.join(outputs,file),'utf8');assert.match(content,/\nResidence:\n/);assert.match(content,/Province: Fictional Confirmed Province/);assert.equal(content.includes('undefined'),false);}const workbook=new ExcelJS.Workbook();await workbook.xlsx.readFile(path.join(outputs,'profit-export-test.xlsx'));assert.equal(workbook.getWorksheet('利润明细').rowCount,3);assert.equal(typeof workbook.getWorksheet('利润明细').getCell('H2').value,'number');assert.equal(workbook.getWorksheet('利润明细').getCell('A2').value,1);assert.equal(workbook.getWorksheet('汇总').getCell('B6').value,143);
    application=await launch(userData);page=await application.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.waitForFunction(()=>document.querySelector('#sum-total')?.textContent==='1');await page.getByRole('button',{name:'订单列表'}).click();await page.locator('#orders-table-body tr').click();await page.locator('.recipient-table').getByText('Fictional Full Name Preserved',{exact:true}).waitFor();await page.locator('.recipient-table').getByText('Fictional Confirmed Province',{exact:true}).waitFor();await page.getByText('AED 143.00').first().waitFor();await application.close();application=null;
    database=await openOrderDatabase({userDataPath:userData});new OrderService(new OrderRepository(database)).createOrder(manualOrder('PACKAGED-EXTRA'));database.close();database=null;application=await launch(userData,{restoreFile:path.join(outputs,'orders-backup-test.sqlite')});page=await application.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.getByRole('button',{name:'数据管理'}).click();await page.getByRole('button',{name:'选择备份并恢复'}).click();await page.getByRole('checkbox',{name:/我已理解/}).check();await page.getByRole('button',{name:'确认恢复'}).click();await page.getByText('恢复完成：1 个订单，2 条商品明细').waitFor();await application.close();application=null;
    database=await openOrderDatabase({userDataPath:userData,skipMigrationBackup:true});assert.equal(database.prepare('SELECT count(*) count FROM orders').get().count,1);assert.equal(database.prepare('SELECT count(*) count FROM order_items').get().count,2);assert.equal(database.prepare('SELECT realized_profit FROM orders').get().realized_profit,14300);assert.equal(database.prepare('SELECT count(*) count FROM order_recipient_overrides').get().count,2);database.close();database=null;
    const installed=path.join(root,'isolated-install','KDocs 库存同步.app');await mkdir(path.dirname(installed),{recursive:true});await execute('/usr/bin/ditto',[appPath,installed]);application=await launchInstalledVersion(installed,userData,'0.1.13');page=await application.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.waitForFunction(()=>document.querySelector('#sum-total')?.textContent==='1');await application.close();application=null;assert.equal(orderDatabasePath(userData).startsWith(installed),false);await access(orderDatabasePath(userData));
    const log=await readFile(path.join(userData,'logs',`startup-${new Date().toISOString().slice(0,10)}.jsonl`),'utf8');assert.match(log,/"packaged":true/);assert.ok(log.includes(path.resolve(userData)));
  }finally{if(database)database.close();if(application)await application.close().catch(()=>{});}
});

test('packaged App safely upgrades a version 7 database and preserves financial snapshots',async()=>{
  const root=path.join(acceptanceRoot,'upgrade'),userData=path.join(root,'user-data'),file=orderDatabasePath(userData);let database,application;await mkdir(path.dirname(file),{recursive:true});database=new DatabaseSync(file);database.exec('PRAGMA foreign_keys=ON');migrateOrderDatabase(database,ORDER_MIGRATIONS.slice(0,7));const at='2026-09-02T00:00:00.000Z';database.prepare('INSERT INTO import_batches(id,source,original_filename,file_sha256,status,total_rows,valid_orders,imported_orders,skipped_orders,failed_orders,warning_count,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('fictional-batch','shopplus_excel','fictional.xlsx','a'.repeat(64),'completed',3,2,2,0,0,0,at,at);let service=new OrderService(new OrderRepository(database)),multi=service.createOrder({source:'shopplus_excel',shopplus_order_no:'UPGRADE-MULTI',currency:'AED',delivery_status:'unshipped',customer_first_name:'Upgrade',customer_last_name:'Recipient',customer_full_name:'Upgrade Recipient',customer_phone:'+00000000003',customer_email:'upgrade-multi@example.invalid',country:'Example Country',province:null,city:'Example City',street:'Example Street',residence:null,import_batch_id:'fictional-batch',source_file_name:'fictional.xlsx',source_file_sha256:'a'.repeat(64),imported_at:at,items:[{sku_code:'KY02',product_name_snapshot:'KY02 Upgrade Fictional',quantity:1,unit_list_price:'100',unit_actual_price:'100',unit_cost_snapshot:'20'},{sku_code:'Z01',product_name_snapshot:'Z01 Upgrade Fictional',quantity:1,unit_list_price:'80',unit_actual_price:'80',unit_cost_snapshot:'10'}]});service.confirmPackageFee(multi.packages.find(value=>value.series_code==='KY').id,{actual_fee:'5',reason:'fictional historic courier fee',resolution_status:'signed'});let final=service.createOrder(manualOrder('UPGRADE-FINAL',{delivery_status:'signed',import_batch_id:'fictional-batch',source:'shopplus_excel',source_file_name:'fictional.xlsx',source_file_sha256:'a'.repeat(64),imported_at:at}));service.confirmPackageFee(final.packages[0].id,{actual_fee:'6',reason:'fictional historic courier fee',resolution_status:'signed'});const before={orders:database.prepare('SELECT count(*) count FROM orders').get().count,items:database.prepare('SELECT count(*) count FROM order_items').get().count,costs:database.prepare('SELECT unit_cost_snapshot FROM order_items ORDER BY order_id,item_sequence').all().map(value=>value.unit_cost_snapshot),fees:database.prepare('SELECT shipping_fee FROM packages ORDER BY order_id,series_code').all().map(value=>value.shipping_fee),finalProfit:database.prepare('SELECT realized_profit FROM orders WHERE id=?').get(final.id).realized_profit,raw:database.prepare('SELECT customer_first_name,customer_last_name,province FROM orders WHERE id=?').get(multi.id)};assert.equal(Math.max(...database.prepare('SELECT version FROM schema_migrations').all().map(value=>value.version)),7);database.close();database=null;
  try{
    application=await launch(userData);let page=await application.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.waitForFunction(()=>document.querySelector('#sum-total')?.textContent==='2');await page.getByRole('button',{name:'订单列表'}).click();await page.locator('#orders-table-body tr').filter({hasText:'UPGRADE-MULTI'}).click();await page.getByRole('button',{name:'编辑收件资料'}).click();await page.getByLabel('选择收件资料字段').selectOption('province');await page.getByLabel('省人工值').fill('Fictional Upgraded Province');await page.getByLabel('省修改原因').fill('fictional upgrade acceptance');await page.getByRole('button',{name:'保存修改'}).click();await page.locator('.recipient-table').getByText('Fictional Upgraded Province',{exact:true}).waitFor();await application.close();application=null;
    database=new DatabaseSync(file);const after={orders:database.prepare('SELECT count(*) count FROM orders').get().count,items:database.prepare('SELECT count(*) count FROM order_items').get().count,costs:database.prepare('SELECT unit_cost_snapshot FROM order_items ORDER BY order_id,item_sequence').all().map(value=>value.unit_cost_snapshot),fees:database.prepare('SELECT shipping_fee FROM packages ORDER BY order_id,series_code').all().map(value=>value.shipping_fee),finalProfit:database.prepare('SELECT realized_profit FROM orders WHERE id=?').get(final.id).realized_profit,raw:database.prepare('SELECT customer_first_name,customer_last_name,province FROM orders WHERE id=?').get(multi.id)};assert.deepEqual(after,before);assert.equal(database.prepare('SELECT max(version) version FROM schema_migrations').get().version,CURRENT_ORDER_SCHEMA_VERSION);assert.equal(database.prepare('SELECT override_value FROM order_recipient_overrides WHERE order_id=? AND field_name=?').get(multi.id,'province').override_value,'Fictional Upgraded Province');database.close();database=null;
    const backupDirectory=path.join(userData,'orders','automatic-backups'),backups=(await readdir(backupDirectory)).filter(value=>value.endsWith('.sqlite'));assert.equal(backups.length,1);assert.equal(validateOrderDatabaseFile(path.join(backupDirectory,backups[0]),{maxVersion:CURRENT_ORDER_SCHEMA_VERSION}).schemaVersion,7);
    application=await launch(userData);page=await application.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.waitForFunction(()=>document.querySelector('#sum-total')?.textContent==='2');await application.close();application=null;assert.equal((await readdir(backupDirectory)).filter(value=>value.endsWith('.sqlite')).length,1);database=new DatabaseSync(file);assert.equal(database.prepare('SELECT count(*) count FROM schema_migrations').get().count,CURRENT_ORDER_SCHEMA_VERSION);assert.equal(database.prepare('SELECT count(*) count FROM order_recipient_overrides').get().count,1);database.close();database=null;
  }finally{if(database)database.close();if(application)await application.close().catch(()=>{});}
});

test('packaged App keeps the responsive order dialog inside four viewport sizes',async()=>{
  const root=path.join(acceptanceRoot,'responsive'),userData=path.join(root,'user-data');let database,application;
  try{
    database=await openOrderDatabase({userDataPath:userData});const service=new OrderService(new OrderRepository(database));service.createOrder(responsiveOrder());database.close();database=null;
    application=await launch(userData);const page=await application.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.setViewportSize({width:1440,height:900});await page.locator('.recent-order:not(.recent-order-header)').waitFor();const overviewVisual=await packagedOrderSurfaceVisual(page,{panel:'#overview-recent',surface:'.recent-orders-table',header:'.recent-order-header .recent-order-cell',cell:'.recent-order:not(.recent-order-header) .recent-order-cell'});assert.ok(overviewVisual.shellWidth>=1300);assert.equal(overviewVisual.pageFits,true);await page.getByRole('button',{name:'订单列表'}).click();await page.locator('#orders-table-body tr').waitFor();assert.deepEqual(await packagedOrderSurfaceVisual(page,{panel:'.order-list-panel',surface:'.order-list-wrap',header:'.order-list-table th',cell:'.order-list-table tbody td'}),overviewVisual);
    const sizes=[{width:1440,height:900,columns:2},{width:1280,height:800,columns:2},{width:1024,height:768,columns:2},{width:900,height:700,columns:1}];
    for(const [index,size] of sizes.entries()){
      await page.setViewportSize(size);const row=page.locator('#orders-table-body tr').filter({hasText:responsiveOrderNo});await row.waitFor();const list=await packagedOrderListGeometry(page,row);assert.equal(list.page[0],list.page[1]);assert.equal(list.wrap[0],list.wrap[1]);assert.ok(list.table[0]<=list.table[1]+1);assert.equal(list.headVisible,size.width>=1280);assert.deepEqual(list.labels,['序号','日期','订单编号','客户电话','商品','商品数量','包裹数量','状态','成本','物流','利润']);assert.deepEqual(list.stacks,[0,0,0,0]);await row.focus();await row.click();await page.getByRole('heading',{name:'收件资料'}).waitFor();assert.equal(await page.locator('.recipient-table-row').count(),8);assert.equal(await page.locator('#recipient-editor').isVisible(),false);assert.equal(await page.locator('.recipient-section input:visible').count(),0);assertPackagedDialog(await packagedDialogGeometry(page),size.columns);
      if(index===0)await page.locator('#order-detail-close').click();else if(index===1)await page.keyboard.press('Escape');else if(index===2)await page.mouse.click(4,4);else{await page.getByRole('button',{name:'编辑收件资料'}).click();await page.getByLabel('选择收件资料字段').selectOption('province');await page.getByLabel('省人工值').fill('Unsaved Fictional Province');page.once('dialog',prompt=>prompt.accept());await page.mouse.click(4,4);}await page.waitForFunction(()=>!document.querySelector('#order-detail-dialog').open);assert.equal(await row.evaluate(element=>document.activeElement===element),true);
    }
  }finally{if(database)database.close();if(application)await application.close().catch(()=>{});}
});

test('packaged App将持久化invalid_grant显示为授权失效而不是绿色已连接',async()=>{
  const root=path.join(acceptanceRoot,'google-auth-state'),userData=path.join(root,'user-data'),state=path.join(userData,'state');let application;
  await mkdir(state,{recursive:true});await writeFile(path.join(state,'google-refresh-token.enc'),'fictional-encrypted-token-placeholder\n');await writeFile(path.join(state,'app-state.json'),JSON.stringify({lastSuccessfulSync:null,lastCheck:null,productCount:0,kdocsLoggedIn:false,latest:{ok:false,at:'2026-09-05T13:21:31.638Z',error:{stage:'读取Google表格',code:'GOOGLE_API_FAILED',message:'读取Google表格失败：invalid_grant'}}}));
  try{application=await launch(userData);const page=await application.firstWindow();const status=page.locator('#google-status');await page.getByText('● 授权已失效',{exact:true}).waitFor();assert.equal(await status.getAttribute('data-state'),'error');await page.getByRole('button',{name:'重新连接'}).waitFor();await page.getByText(/GOOGLE_API_FAILED/).waitFor();}
  finally{if(application)await application.close().catch(()=>{});}
});

test('replacing the previously installed packaged App with 0.1.13 preserves the separate order database',{skip:!oldAppPath},async()=>{
  const root=path.join(acceptanceRoot,'release-upgrade'),userData=path.join(root,'user-data'),installed=path.join(root,'install','KDocs 库存同步.app'),previous=path.join(root,'install',`KDocs 库存同步-${oldAppVersion}.app`);let database,application;
  try{
    await mkdir(path.dirname(installed),{recursive:true});await execute('/usr/bin/ditto',[oldAppPath,installed]);const databaseFile=orderDatabasePath(userData);await mkdir(path.dirname(databaseFile),{recursive:true});database=new DatabaseSync(databaseFile);database.exec('PRAGMA foreign_keys=ON');migrateOrderDatabase(database,ORDER_MIGRATIONS.slice(0,12));new OrderService(new OrderRepository(database)).createOrder(manualOrder('PACKAGED-VERSION-UPGRADE'));database.close();database=null;
    application=await launchInstalledVersion(installed,userData,oldAppVersion);let page=await application.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.waitForFunction(()=>document.querySelector('#sum-total')?.textContent==='1');await application.close();application=null;
    await rename(installed,previous);await execute('/usr/bin/ditto',[appPath,installed]);application=await launchInstalledVersion(installed,userData,'0.1.13');page=await application.firstWindow();await page.getByRole('button',{name:'订单管理'}).click();await page.waitForFunction(()=>document.querySelector('#sum-total')?.textContent==='1');await page.getByRole('button',{name:'订单列表'}).click();await page.locator('#orders-table-body tr').filter({hasText:'PACKAGED-VERSION-UPGRADE'}).click();await page.getByText('Fictional Recipient').waitFor();assert.equal(orderDatabasePath(userData).startsWith(installed),false);await application.close();application=null;database=await openOrderDatabase({userDataPath:userData,skipMigrationBackup:true});assert.equal(database.prepare('SELECT count(*) count FROM orders').get().count,1);assert.equal(database.prepare('SELECT fixed_sequence FROM orders').get().fixed_sequence,1);database.close();database=null;
  }finally{if(database)database.close();if(application)await application.close().catch(()=>{});}
});

test.after(async()=>{if(process.env.KEEP_PACKAGED_ACCEPTANCE!=='1')await rm(acceptanceRoot,{recursive:true,force:true});});
