import test from 'node:test';import assert from 'node:assert/strict';
import {buildSyncPlan,validateSyncPlan} from '../src/sync/plan.mjs';
import {buildFirstMappingWizard,applyWizardAnswers,mappingValues} from '../src/mapping/mapping.mjs';
import {buildWriteRequests,validateRequests} from '../src/google/transaction.mjs';
import {oldEvidence,metadata,inventoryHeaders,mappingHeaders} from './helpers.mjs';
async function baseline(){const {snapshot}=await oldEvidence(),w=buildFirstMappingWizard(snapshot.products),mapping=applyWizardAnswers(w,w.rows.map((r,i)=>({sourceKey:r.sourceKey,businessId:String(i+1).padStart(3,'0')})));return {snapshot,mapping};}
test('首次计划只管理库存情况和商品映射',async()=>{const {snapshot,mapping}=await baseline(),meta=metadata(),plan=buildSyncPlan({sourceSnapshot:snapshot,mappingState:mapping,inventoryValues:[inventoryHeaders],mappingValuesBefore:[mappingHeaders],metadata:meta,now:new Date('2026-08-29T01:00:00Z')});assert.equal(plan.counts.total,189);assert.equal(plan.firstSync,true);assert.equal(plan.requiresInput,false);assert.equal(plan.inventoryAfter.length,190);validateSyncPlan(plan);const workbook={metadata:meta,inventorySheet:meta.sheets[1],mappingSheet:meta.sheets[2],inventory:[inventoryHeaders],mapping:[mappingHeaders]};const requests=buildWriteRequests(plan,workbook);validateRequests(requests,new Set([2,3]));assert.doesNotMatch(JSON.stringify(requests),/"sheetId":1/);});
test('首次Google表只有6列时先追加列而不是在边界外插入列',async()=>{const {snapshot,mapping}=await baseline(),meta=metadata();meta.sheets[1].properties.gridProperties.columnCount=6;const plan=buildSyncPlan({sourceSnapshot:snapshot,mappingState:mapping,inventoryValues:[inventoryHeaders],mappingValuesBefore:[mappingHeaders],metadata:meta,now:new Date('2026-08-29T01:00:00Z')});const workbook={metadata:meta,inventorySheet:meta.sheets[1],mappingSheet:meta.sheets[2],inventory:[inventoryHeaders],mapping:[mappingHeaders]},requests=buildWriteRequests(plan,workbook);assert.deepEqual(requests[0],{appendDimension:{sheetId:2,dimension:'COLUMNS',length:4}});});
test('无变化不增加历史版本',async()=>{const {snapshot,mapping}=await baseline(),meta=metadata();const first=buildSyncPlan({sourceSnapshot:snapshot,mappingState:mapping,inventoryValues:[inventoryHeaders],mappingValuesBefore:[mappingHeaders],metadata:meta,now:new Date('2026-08-29T01:00:00Z')});const second=buildSyncPlan({sourceSnapshot:snapshot,mappingState:mapping,inventoryValues:first.inventoryAfter,mappingValuesBefore:first.mappingAfter,metadata:meta,now:new Date('2026-08-29T02:00:00Z')});assert.equal(second.formalChanged,false);assert.deepEqual(second.historyHeaders,[]);assert.equal(second.inventoryAfter[0].length,10);assert.equal(second.inventoryAfter.length,first.inventoryAfter.length);});
test('从未进入库存的已移除映射不会生成幽灵新增记录',()=>{const meta=metadata(),source={capturedAt:'2026-08-31T00:00:00Z',quality:{namedProducts:0},products:[]},mapping={rows:[{businessId:'LYT2',sourceKey:'NAME:狼牙套|IMG:old',sourceName:'狼牙套',status:'来源已移除'}]},before=[mappingHeaders,['LYT2','NAME:狼牙套|IMG:old','狼牙套','正常','']],plan=buildSyncPlan({sourceSnapshot:source,mappingState:mapping,inventoryValues:[inventoryHeaders],mappingValuesBefore:before,metadata:meta,now:new Date('2026-08-31T00:00:00Z')});assert.equal(plan.summary.newProducts,0);assert.equal(plan.summary.removed,0);assert.equal(plan.detail.length,0);});
test('价格库存新增移除名称变化及同名记录不串商品',async()=>{const {snapshot,mapping}=await baseline(),meta=metadata();const first=buildSyncPlan({sourceSnapshot:snapshot,mappingState:mapping,inventoryValues:[inventoryHeaders],mappingValuesBefore:[mappingHeaders],metadata:meta,now:new Date('2026-08-29T01:00:00Z')});const changed=structuredClone(snapshot);const wolf=changed.products.find(r=>r.sourceName==='狼牙套');wolf.suggestedPrice=String(Number(wolf.suggestedPrice)+20);const ky13=changed.products.find(r=>r.sourceName==='KY13');ky13.stock=ky13.stock==='有货'?'无货':'有货';ky13.cost='50.0';ky13.additionalInfo='最后两件';const rename=changed.products.find(r=>r.sourceName.includes('VT006'));rename.sourceName='OG拍打双震棒 新包装（VT006）';const renamedId=mapping.rows.find(r=>r.sourceKey==='MODEL:VT006').businessId;const removed=changed.products.findIndex(r=>r.sourceName==='KY15');changed.products.splice(removed,1);const state={...mapping,rows:mapping.rows.map(r=>r.sourceName==='KY15'?{...r,status:'来源已移除'}:r.sourceKey==='MODEL:VT006'?{...r,sourceName:rename.sourceName}:r)};const plan=buildSyncPlan({sourceSnapshot:changed,mappingState:state,inventoryValues:first.inventoryAfter,mappingValuesBefore:first.mappingAfter,metadata:meta,now:new Date('2026-08-29T07:20:00Z')});assert.equal(plan.formalChanged,true);assert.equal(plan.historyHeaders[0],'8.29 15:20成本');const wolves=plan.inventoryAfter.filter(r=>r[1]==='狼牙套');assert.equal(wolves.length,2);assert.equal(wolves.filter(r=>r[3]).length,1);assert.equal(plan.detail.filter(x=>x.sourceName==='狼牙套').length,1);assert.ok(plan.detail.some(x=>x.kind==='removed'));assert.ok(plan.detail.some(x=>x.businessId===renamedId&&x.changes.some(c=>c.field==='sourceName')));assert.ok(plan.detail.some(x=>x.changes.some(c=>c.field==='additionalInfo')));});
test('异常采集会在生成Google计划前停止',async()=>{const {collection,snapshot}=await oldEvidence();collection.result.rows=collection.result.rows.slice(0,30);collection.result.coverage.recognizedRows=30;const {validateCollection}=await import('../src/source/quality.mjs');assert.throws(()=>validateCollection(collection,snapshot),/采集异常/);});
