import test from 'node:test';import assert from 'node:assert/strict';
import {buildFirstMappingWizard,applyWizardAnswers,mappingValues,reconcileMappings} from '../src/mapping/mapping.mjs';
import {parseMappingRows} from '../src/mapping/mapping.mjs';
import {oldEvidence,mappingHeaders} from './helpers.mjs';
import {buildMergedNameRepair} from '../src/mapping/merged-repair.mjs';
import {buildFirstInventoryBaseline} from '../src/sync/baseline.mjs';
import {assignSourceKeys} from '../src/mapping/source-key.mjs';
test('旧的KDocs证据保留原始行并将同名资料合并为来源商品',async()=>{const {quality,snapshot}=await oldEvidence();assert.equal(quality.endpoint,'S190');assert.equal(quality.rawNamedRows,189);assert.equal(quality.namedProducts,182);assert.equal(quality.totalBusinessRows,189);assert.equal(snapshot.products.length,182);assert.equal(quality.empty.cost,0);assert.equal(quality.empty.suggestedPrice,0);assert.equal(quality.empty.stock,2);assert.equal(quality.inStock+quality.outOfStock+quality.empty.stock,189);const condoms=snapshot.products.find(r=>r.sourceName==='避孕套');assert.deepEqual(condoms.sourceRows.map(r=>r.sourceRow),[177,178,179]);});
test('20条实际来源记录和119-122已知区域保持原值',async()=>{const {collection}=await oldEvidence();const sampled=Array.from({length:20},(_,i)=>collection.result.rows[1+Math.round(i*188/19)]);assert.equal(sampled.length,20);for(const row of sampled)for(const c of ['A','D','E','F'])assert.equal(typeof row.cells[c],'string');const rows=Object.fromEntries(collection.result.rows.slice(118,122).map(r=>[r.row,r.cells]));assert.deepEqual([rows[119].A,rows[119].D,rows[119].E,rows[119].F],['KY13','45.0','220','无货']);assert.deepEqual([rows[120].A,rows[120].D,rows[120].E,rows[120].F],['KY14','50.0','240','无货']);assert.deepEqual([rows[121].A,rows[121].D,rows[121].E,rows[121].F],['KY15','90.0','260-280','无货']);assert.equal(rows[122].A,'KY16');assert.equal(rows[122].D,'180.0');assert.match(rows[122].E,/320/);assert.equal(rows[122].F,'有货');});
test('首次映射按去重后的来源商品建立且不自动编号',async()=>{const {snapshot}=await oldEvidence();const wizard=buildFirstMappingWizard(snapshot.products);assert.equal(wizard.total,182);assert.equal(wizard.automatic,0);assert.equal(wizard.pendingNumber,182);assert.equal(wizard.review.length,182);assert.ok(wizard.rows.every(r=>r.businessId===''&&r.status==='待编号'&&r.note===''));assert.deepEqual(wizard.rows.map(r=>r.sourceRow),[...wizard.rows].map(r=>r.sourceRow).sort((a,b)=>a-b));const model=wizard.rows.find(r=>r.sourceKey==='MODEL:VT006');assert.equal(model.businessId,'');assert.match(model.sourceName,/033 OG拍打双震棒/);const wolves=wizard.rows.filter(r=>r.sourceName==='狼牙套');assert.equal(wolves.length,1);assert.equal(snapshot.products.find(r=>r.sourceName==='狼牙套').sourceRowCount,2);const values=mappingValues(structuredClone(wizard.rows));assert.ok(values.slice(1).every(r=>r[0]===''&&r[3]==='待编号'&&r[4]===''));});
test('候选映射只有明确确认才保存，明确不对应会回到待选择状态',()=>{const wizard={firstRun:false,total:2,automatic:0,needsConfirmation:2,pendingNumber:0,rows:[{sourceKey:'MODEL:A',sourceName:'来源 A',businessId:'SP-A-LOCAL',status:'待确认',note:'自动候选',sourceRow:2},{sourceKey:'MODEL:B',sourceName:'来源 B',businessId:'SP-B-LOCAL',status:'待确认',note:'自动候选',sourceRow:3}]};const onlyA=applyWizardAnswers(wizard,[{sourceKey:'MODEL:A',businessId:'SP-A-LOCAL'}]);assert.deepEqual(onlyA.rows.map(row=>[row.businessId,row.status]),[['SP-A-LOCAL','正常'],['SP-B-LOCAL','待确认']],'未提交的候选不能因保存其它行而被误确认');const rejectB=applyWizardAnswers(wizard,[{sourceKey:'MODEL:B',businessId:''}]);assert.deepEqual(rejectB.rows.map(row=>[row.businessId,row.status]),[['SP-A-LOCAL','待确认'],['','待编号']]);assert.match(rejectB.rows[1].note,/候选已标记不对应/);});
test('人工文本编号原样复用，不因来源行号变化重新编号',async()=>{const {snapshot}=await oldEvidence(),wizard=buildFirstMappingWizard(snapshot.products),confirmed=applyWizardAnswers(wizard,wizard.rows.map((r,i)=>({sourceKey:r.sourceKey,businessId:i===0?'049':String(i+1)})));const values=mappingValues(structuredClone(confirmed.rows)),existing=parseMappingRows(values);const moved=structuredClone(snapshot.products).reverse().map((x,i)=>({...x,sourceRow:500+i}));const state=reconcileMappings(moved,existing);assert.equal(state.pendingNumber,0);assert.equal(state.needsConfirmation,0);assert.equal(state.rows.find(r=>r.sourceKey===confirmed.rows[0].sourceKey).businessId,'049');assert.notEqual(state.rows.find(r=>r.sourceKey===confirmed.rows[1].sourceKey).businessId,'049');assert.equal(state.rows.filter(r=>r.sourceName==='狼牙套').length,1);assert.deepEqual(values[0],mappingHeaders);});
test('KDocs隐藏型号或图片后仍按名称与相对顺序保护人工编号',()=>{const existing=parseMappingRows([mappingHeaders,
  ['033','MODEL:VT004','龙吟舌舔（VT004）','正常',''],['034','MODEL:VT006','033 OG拍打双震棒（VT006）','正常',''],['035','MODEL:VT005','034 OG吸吮双震棒APP（VT005）','正常',''],
  ['LYT','NAME:狼牙套|IMG:SHOT:first','狼牙套','正常',''],['LYT2','NAME:狼牙套|IMG:SHOT:second','狼牙套','正常','']]);
  const current=[{sourceRow:6,sourceName:'033 龙吟舌舔'},{sourceRow:7,sourceName:'034 OG拍打双震棒'},{sourceRow:8,sourceName:'035 OG吸吮双震棒APP'},{sourceRow:50,sourceName:'狼牙套'}],state=reconcileMappings(current,existing);
  assert.deepEqual(state.rows.filter(r=>r.sourceRow).map(r=>r.businessId),['033','034','035','LYT']);assert.equal(state.rows.find(r=>r.businessId==='034').sourceKey,'NAME:og拍打双震棒');assert.equal(state.rows.find(r=>r.businessId==='LYT2').status,'来源已移除');
  const values=mappingValues(state.rows),lyt2=values.find(r=>r[0]==='LYT2');assert.equal(lyt2[3],'来源已移除');});
test('G列附加信息始终按原始显示字符串保存',async()=>{const {collection}=await oldEvidence();collection.result.rows[1].cells.G='3.67';collection.result.rows[2].cells.G='最后两件';collection.result.rows[3].cells.G='';const records=(await import('../src/source/quality.mjs')).sourceRecords(collection.result);assert.equal(records[0].additionalInfo,'3.67');assert.equal(records[1].additionalInfo,'最后两件');assert.equal(records[2].additionalInfo,'');assert.equal(typeof records[0].additionalInfo,'string');});
test('纵向合并名称保留原始行和图片，但只产生一个来源商品候选',async()=>{const {sourceRecords,sourceProducts}=await import('../src/source/quality.mjs');const result={rows:Array.from({length:4},(_,i)=>({row:i+1,cells:i?{A:i===1?'避孕套':'',D:'15.0',E:'35',F:'无货',G:''}:{A:'名称',D:'成本AED',E:'建议售价AED',F:'库存',G:''}})),coverage:{mergeCandidates:[{range:'A2:A4',anchor:'A2'}]},imageFingerprints:{C2:{fingerprint:'SHOT:a'},C3:{fingerprint:'SHOT:b'},C4:{fingerprint:'SHOT:c'}}};const records=sourceRecords(result),products=sourceProducts(records);assert.deepEqual(records.map(r=>[r.sourceRow,r.sourceName,r.imageFingerprint]),[[2,'避孕套','SHOT:a'],[3,'避孕套','SHOT:b'],[4,'避孕套','SHOT:c']]);assert.equal(products.length,1);assert.deepEqual(products[0].sourceRows.map(row=>row.sourceRow),[2,3,4]);assert.deepEqual(products[0].imageFingerprints,['SHOT:a','SHOT:b','SHOT:c']);assert.equal(buildFirstMappingWizard(products).rows.length,1);});
test('生产采集可同时要求原始行数准确并拒绝同名核心资料冲突',async()=>{const {collection}=await oldEvidence();const {validateCollection}=await import('../src/source/quality.mjs'),{SOURCE_RULES}=await import('../src/config.mjs');assert.throws(()=>validateCollection(collection,null,{...SOURCE_RULES,expectedRawRows:199}),/应为199行，实际189行/);assert.throws(()=>validateCollection(collection,null,{...SOURCE_RULES,expectedRawRows:189,rejectConflictingDuplicateNames:true}),/同名来源资料的核心字段不一致/);});
test('同名资料合并后不会按旧行顺序自动挑选网站候选',()=>{const existing=parseMappingRows([mappingHeaders,['A','MODEL:TY17|OCC:1','TY17','待确认','旧建议 A'],['B','MODEL:TY17|OCC:2','TY17','待确认','旧建议 B'],['C','MODEL:TY17|OCC:3','TY17','待确认','旧建议 C']]),current=[{sourceRow:192,sourceName:'TY17',cost:'20.0',suggestedPrice:'50',stock:'有货',sourceRowCount:3}],state=reconcileMappings(current,existing);assert.equal(state.rows.length,1);assert.deepEqual(state.rows[0],{businessId:'',sourceKey:'MODEL:TY17',sourceName:'TY17',status:'待编号',note:'同名来源资料已合并；历史候选不会自动继承，请重新选择网站商品',sourceRow:192});});
test('合并名称修复保留人工文本编号并只插入缺失来源行',()=>{const previous=[{sourceRow:177,sourceName:'避孕套'},{sourceRow:180,sourceName:'男用延时1'}],current=[{sourceRow:177,sourceName:'避孕套',imageFingerprint:'SHOT:a'},{sourceRow:178,sourceName:'避孕套',imageFingerprint:'SHOT:b'},{sourceRow:179,sourceName:'避孕套',imageFingerprint:'SHOT:c'},{sourceRow:180,sourceName:'男用延时1'}],currentValues=[mappingHeaders,['049','NAME:避孕套','避孕套','待编号',''],['50','NAME:男用延时1','男用延时1','待编号','']];const plan=buildMergedNameRepair({currentValues,previousProducts:previous,currentProducts:current});assert.deepEqual(plan.rows.map(r=>[r.sourceRow,r.businessId,r.status]),[[177,'049','正常'],[178,'','待编号'],[179,'','待编号'],[180,'50','正常']]);assert.equal(plan.stats.insertedPending,2);assert.equal(plan.stats.numberedBefore,2);assert.equal(plan.stats.numberedAfter,2);});
test('第一次库存基准只收已编号商品并保持来源顺序和真正空变化列',()=>{const sourceSnapshot={capturedAt:'2026-08-30T00:00:00.000Z',quality:{namedProducts:3},products:[{sourceRow:2,sourceName:'甲',cost:'45.0',suggestedPrice:'220',stock:'无货',additionalInfo:'最后两件'},{sourceRow:3,sourceName:'乙',cost:'50.0',suggestedPrice:'240',stock:'有货',additionalInfo:''},{sourceRow:4,sourceName:'丙',cost:'60',suggestedPrice:'260',stock:'有货',additionalInfo:'3.67'}]};const assigned=buildFirstMappingWizard(sourceSnapshot.products),mappingValues=[mappingHeaders,...assigned.rows.map((row,i)=>[i===0?'049':i===2?'49':'',row.sourceKey,row.sourceName,i===1?'待编号':'正常',''])];const baseline=buildFirstInventoryBaseline({mappingValues,sourceSnapshot,now:new Date('2026-08-30T01:00:00Z')});assert.equal(baseline.counts.numbered,2);assert.equal(baseline.counts.skipped,1);assert.deepEqual(baseline.values[0],['商品编号','来源商品名称','成本变化','建议售价变化','库存变化','附加信息变化','8.30成本','8.30建议售价','8.30库存','8.30附加信息']);assert.deepEqual(baseline.values.slice(1).map(row=>row.slice(0,2)),[['049','甲'],['49','丙']]);assert.ok(baseline.values.slice(1).every(row=>row.slice(2,6).every(value=>value==='')));assert.deepEqual(baseline.values[1].slice(6),['45.0','220','无货','最后两件']);});
test('已编号但当前来源已消失的旧映射可跳过，但所有当前来源必须完整覆盖',()=>{const sourceSnapshot={capturedAt:'2026-08-30T00:00:00.000Z',quality:{namedProducts:1},products:[{sourceRow:2,sourceName:'甲',cost:'1',suggestedPrice:'2',stock:'有货',additionalInfo:''}]};const mappingValues=[mappingHeaders,['A1','NAME:甲','甲','正常',''],['OLD','NAME:已移除','已移除','待编号','']];const baseline=buildFirstInventoryBaseline({mappingValues,sourceSnapshot,skipMissingMappings:true});assert.equal(baseline.counts.numbered,1);assert.equal(baseline.counts.missingMappings,1);assert.equal(baseline.values.length,2);assert.equal(baseline.ignoredMissingMappings[0].businessId,'OLD');});

test('来源名称批量变更保留采集安全门并进入商品映射人工复核',async()=>{const {collection,snapshot}=await oldEvidence(),changed=structuredClone(collection);let renamed=0;for(const row of changed.result.rows){if(row.row===1||!row.cells.A||renamed>=40)continue;row.cells.A=`更新名称-${row.row}`;renamed++;}const {validateCollection,makeSourceSnapshot}=await import('../src/source/quality.mjs'),quality=validateCollection(changed,snapshot);assert.equal(renamed,40);assert.equal(quality.passed,true);assert.match(quality.warnings.join('\n'),/必须在商品映射中人工复核/);const current=makeSourceSnapshot(changed,quality),existing=assignSourceKeys(snapshot.products.filter(row=>row.sourceName)).map((row,index)=>({businessId:`B${index+1}`,sourceKey:row.sourceKey,sourceName:row.sourceName,status:'正常',note:''})),mapping=reconcileMappings(current.products,existing);assert.ok(mapping.pendingNumber>=40);assert.ok(mapping.review.length>=40);});
