import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {openOrderDatabase,orderDatabasePath,migrateOrderDatabase} from '../src/orders/database.mjs';
import {OrderRepository} from '../src/orders/order-repository.mjs';
import {OrderService} from '../src/orders/order-service.mjs';
import {OrderAppService} from '../src/orders/order-app-service.mjs';
import {buildPackageTxt} from '../src/orders/package-report.mjs';
import {createVerifiedBackup,replaceDatabaseAtomically,finalizeDatabaseReplacement} from '../src/orders/order-data-protection.mjs';
import {CURRENT_ORDER_SCHEMA_VERSION,ORDER_MIGRATIONS} from '../src/orders/migrations/index.mjs';

const originalFullName='Full Name Preserved Exactly';
const orderInput=(overrides={})=>({source:'manual',shopplus_order_no:'RECIPIENT-FICTIONAL',currency:'AED',delivery_status:'unshipped',customer_first_name:'Original Name',customer_last_name:'Original Surname',customer_full_name:originalFullName,customer_phone:'+0000000001',customer_email:'fictional@example.invalid',country:'Example Country',province:'Example Province',city:'Example City',street:'Example Street',residence:'Example Residence',items:[{sku_code:'KY02',product_name_snapshot:'Fictional Product',quantity:1,unit_list_price:'10',unit_actual_price:'10',unit_cost_snapshot:'2'}],...overrides});
async function fixture(overrides={}){const directory=await mkdtemp(path.join(os.tmpdir(),'recipient-data-')),database=await openOrderDatabase({userDataPath:directory}),repository=new OrderRepository(database),service=new OrderService(repository),created=service.createOrder(orderInput(overrides)),app=new OrderAppService({database,userDataPath:directory});app.confirmOrder({orderId:created.id});app.recordAddressVerification({orderId:created.id,status:'matched',detailConfirmed:true});return {directory,database,repository,service,created,app,close:async()=>{try{database.close();}catch{}await rm(directory,{recursive:true,force:true});}};}

test('Residence为空仍可生成TXT、保留空行和非阻断警告且Billing address无多余分隔符',async()=>{const f=await fixture({residence:null});try{const report=f.app.previewPackageTxt({packageId:f.created.packages[0].id});assert.equal(report.ok,true);assert.ok(report.warnings.some(value=>value.code==='RESIDENCE_MISSING'));assert.match(report.content,/\nResidence:\n/);assert.match(report.content,/Billing address\nExample Street - Example City\/Example Province\/Example Country\n/);assert.equal(/--|\/\/|\s{2,}-|\/-|-\s+-/.test(report.content.split('Billing address\n')[1].split('\n')[0]),false);}finally{await f.close();}});

test('原始Name优先，Name为空时不能静默使用Full name，明确确认后完整原文生效',async()=>{let f=await fixture();try{let report=f.app.previewPackageTxt({packageId:f.created.packages[0].id});assert.match(report.content,/Name: Original Name\n/);assert.equal(report.content.includes(`Name: ${originalFullName}`),false);}finally{await f.close();}f=await fixture({customer_first_name:null});try{let report=f.app.previewPackageTxt({packageId:f.created.packages[0].id});assert.equal(report.ok,false);assert.ok(report.problems.some(value=>value.code==='FULL_NAME_CONFIRMATION_REQUIRED'));assert.equal(report.content,null);const detail=f.app.confirmFullNameAsName({orderId:f.created.id});assert.equal(detail.customer.firstName,originalFullName);report=f.app.previewPackageTxt({packageId:f.created.packages[0].id});assert.equal(report.ok,true);assert.match(report.content,new RegExp(`Name: ${originalFullName}\\n`));const event=f.database.prepare("SELECT event_time FROM order_events WHERE event_type='recipient_full_name_confirmed'").get(),override=f.database.prepare("SELECT override_value,reason,updated_at FROM order_recipient_overrides WHERE field_name='firstName'").get();assert.equal(override.override_value,originalFullName);assert.equal(override.reason,'确认使用Excel原始Full name');assert.equal(event.event_time,override.updated_at);}finally{await f.close();}});

test('Name和Full name都为空以及Province为空继续阻止，人工补全Province后重新核对地址即可通过',async()=>{let f=await fixture({customer_first_name:null,customer_full_name:null});try{const report=f.app.previewPackageTxt({packageId:f.created.packages[0].id});assert.equal(report.ok,false);assert.ok(report.problems.some(value=>value.field==='customer_first_name'));assert.equal(report.canConfirmFullNameAsName,false);}finally{await f.close();}f=await fixture({province:null});try{let report=f.app.previewPackageTxt({packageId:f.created.packages[0].id});assert.equal(report.ok,false);assert.ok(report.problems.some(value=>value.field==='province'));const detail=f.app.updateRecipient({orderId:f.created.id,field:'province',value:'Manually Confirmed Province',reason:'verified through fictional channel'});assert.equal(detail.recipient.check.problems.length,0);assert.equal(detail.addressVerification.status,'not_configured');f.app.recordAddressVerification({orderId:f.created.id,status:'matched',detailConfirmed:true});report=f.app.previewPackageTxt({packageId:f.created.packages[0].id});assert.equal(report.ok,true);assert.match(report.content,/Province: Manually Confirmed Province/);}finally{await f.close();}});

test('人工资料优先于Excel原值并可恢复，事件不含完整资料',async()=>{const f=await fixture();try{const staleToken=f.app.previewPackageTxt({packageId:f.created.packages[0].id}).token;let detail=f.app.updateRecipient({orderId:f.created.id,field:'street',value:'Manual Fictional Street',reason:'fictional correction'});assert.throws(()=>f.app.reportForSave(staleToken),error=>error.code==='PACKAGE_REPORT_EXPIRED');assert.equal(detail.recipient.fields.find(value=>value.field==='street').original,'Example Street');assert.equal(detail.customer.street,'Manual Fictional Street');assert.equal(f.database.prepare('SELECT street FROM orders WHERE id=?').get(f.created.id).street,'Example Street');assert.equal(f.database.prepare("SELECT reason FROM order_recipient_overrides WHERE field_name='street'").get().reason,'fictional correction');assert.equal(f.app.previewPackageTxt({packageId:f.created.packages[0].id}).ok,false);f.app.recordAddressVerification({orderId:f.created.id,status:'matched',detailConfirmed:true});assert.match(f.app.previewPackageTxt({packageId:f.created.packages[0].id}).content,/Street: Manual Fictional Street/);detail=f.app.restoreRecipient({orderId:f.created.id,field:'street'});assert.equal(detail.customer.street,'Example Street');assert.equal(f.database.prepare("SELECT count(*) count FROM order_recipient_overrides WHERE field_name='street'").get().count,0);const events=f.database.prepare("SELECT event_type,old_value,new_value,note FROM order_events WHERE event_type LIKE 'recipient_%'").all(),serialized=JSON.stringify(events);assert.equal(serialized.includes('Manual Fictional Street'),false);assert.equal(serialized.includes('Example Street'),false);assert.equal(events.length,2);assert.throws(()=>f.app.updateRecipient({orderId:f.created.id,field:'city',value:'',reason:'fictional'}),/不能为空/);}finally{await f.close();}});

test('覆盖值和事件写入处于同一事务，事件失败时全部回滚',async()=>{const f=await fixture();try{f.database.exec("CREATE TRIGGER reject_recipient_event BEFORE INSERT ON order_events WHEN NEW.event_type='recipient_override_saved' BEGIN SELECT RAISE(ABORT,'fictional recipient rollback'); END");assert.throws(()=>f.app.updateRecipient({orderId:f.created.id,field:'city',value:'Changed Fictional City',reason:'fictional correction'}),/fictional recipient rollback/);assert.equal(f.database.prepare("SELECT count(*) count FROM order_recipient_overrides WHERE field_name='city'").get().count,0);assert.equal(f.database.prepare('SELECT city FROM orders WHERE id=?').get(f.created.id).city,'Example City');}finally{await f.close();}});

test('人工覆盖、Full name确认和地址核对结果可备份恢复，地址变更会要求重新核对',async()=>{const f=await fixture({customer_first_name:null});try{f.app.confirmFullNameAsName({orderId:f.created.id});f.app.updateRecipient({orderId:f.created.id,field:'province',value:'Backup Province',reason:'fictional backup value'});let detail=f.app.recordAddressVerification({orderId:f.created.id,status:'matched',detailConfirmed:true});assert.equal(detail.addressVerification.status,'deliverable');const backup=path.join(f.directory,'recipient-backup.sqlite');await createVerifiedBackup(f.database,backup,{maxVersion:CURRENT_ORDER_SCHEMA_VERSION});detail=f.app.updateRecipient({orderId:f.created.id,field:'province',value:'Later Province',reason:'fictional later value'});assert.equal(detail.addressVerification.status,'not_configured');assert.throws(()=>f.app.recordAddressVerification({orderId:f.created.id,status:'automatic'}),/无效/);f.database.close();let replacement=await replaceDatabaseAtomically({databaseFile:orderDatabasePath(f.directory),sourceFile:backup,maxVersion:CURRENT_ORDER_SCHEMA_VERSION});await finalizeDatabaseReplacement(replacement.rollbackFile);f.database=await openOrderDatabase({userDataPath:f.directory,skipMigrationBackup:true});f.app=new OrderAppService({database:f.database,userDataPath:f.directory});detail=f.app.detail({id:f.created.id});assert.equal(detail.customer.firstName,originalFullName);assert.equal(detail.customer.province,'Backup Province');assert.equal(detail.recipient.fields.find(value=>value.field==='firstName').overrideKind,'full_name_confirmation');assert.equal(detail.addressVerification.status,'deliverable');assert.equal(f.app.previewPackageTxt({packageId:f.created.packages[0].id}).ok,true);}finally{await f.close();}});

test('版本7旧订单迁移后保留原始资料且新覆盖表可用',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'recipient-v7-')),file=orderDatabasePath(directory);let database;try{await mkdir(path.dirname(file),{recursive:true});database=new DatabaseSync(file);database.exec('PRAGMA foreign_keys=ON');migrateOrderDatabase(database,ORDER_MIGRATIONS.slice(0,7));const service=new OrderService(new OrderRepository(database)),created=service.createOrder(orderInput());database.close();database=await openOrderDatabase({userDataPath:directory});const original={...database.prepare('SELECT customer_first_name,customer_full_name FROM orders WHERE id=?').get(created.id)};assert.deepEqual(original,{customer_first_name:'Original Name',customer_full_name:originalFullName});assert.equal(database.prepare("SELECT count(*) count FROM schema_migrations WHERE version=8 AND name='recipient_data_completion'").get().count,1);assert.equal(database.prepare('PRAGMA integrity_check').get().integrity_check,'ok');}finally{try{database?.close();}catch{}await rm(directory,{recursive:true,force:true});}});
