import test from 'node:test';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import * as XLSX from 'xlsx';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {openOrderDatabase} from '../src/orders/database.mjs';
import {createCostCatalog,parseInventoryCost} from '../src/orders/cost-catalog.mjs';
import {previewShopPlusExcel,commitShopPlusImport} from '../src/orders/shopplus-import.mjs';
import {readShopPlusWorkbook} from '../src/orders/shopplus-excel.mjs';
import {businessCodeCandidates,excelSerialToSourceTime,leadingBusinessCode} from '../src/orders/shopplus-fields.mjs';

const COLUMNS=[
  ['订单信息基础信息','siteId','站点ID'],['订单信息基础信息','orderNo','订单号'],['订单信息基础信息','orderSequence','订单序号'],['订单信息基础信息','subOrderId','子订单 ID'],['订单信息基础信息','createdAt','创建时间'],['订单信息基础信息','orderStatus','订单状态'],['订单信息基础信息','currency','货币单位'],['订单信息基础信息','orderTotal','订单总价'],['订单信息基础信息','productTotal','商品总价'],['订单信息基础信息','discountAmount','优惠金额'],['订单信息基础信息','customerShippingFee','物流费用'],['订单信息基础信息','taxAmount','税费'],['订单信息基础信息','fixedDiscountAmount','订单一口价优惠'],
  ['收货信息','firstName','名(firstName)'],['收货信息','lastName','姓(lastName)'],['收货信息','fullName','姓名'],['收货信息','phone','联系电话'],['收货信息','email','联系邮箱'],['收货信息','country','国家'],['收货信息','city','城市'],['收货信息','street','街道'],
  ['商品信息','skuId','SKU ID'],['商品信息','spuId','商品SPU'],['商品信息','spuCode','SPU编码'],['商品信息','productSku','商品SKU'],['商品信息','productName','商品名称'],['商品信息','unitPrice','商品售价'],['商品信息','quantity','售出数量'],['商品信息','paymentStatus','商品支付状态'],['商品信息','fulfillmentStatus','商品配送状态'],
  ['物流信息','trackingNumber','物流单号'],['物流信息','logisticsCompany','物流商'],
  ['账单信息','firstName','名(firstName)'],['账单信息','lastName','姓(lastName)'],['账单信息','fullName','姓名'],['账单信息','phone','联系电话'],['账单信息','email','联系邮箱'],['账单信息','country','国家'],['账单信息','city','城市'],['账单信息','street','街道']
];
const fictional=(overrides={})=>({siteId:'SITE-TEST',orderNo:'ORDER-TEST-1',orderSequence:'0001',subOrderId:'SUB-TEST-1',createdAt:46257.5,orderStatus:'待发货',currency:'AED',orderTotal:'100.00',productTotal:'100.00',discountAmount:'0',customerShippingFee:'0',taxAmount:'0',fixedDiscountAmount:'0',firstName:'Test',lastName:'Recipient',fullName:'Test Recipient',phone:'+000000001',email:'recipient@example.invalid',country:'Example Country',city:'Example City',street:'Example Street',skuId:'90000001',spuId:'80000001',spuCode:'',productSku:'KY02',productName:'KY02 Fictional Product',unitPrice:'100.00',quantity:'1',paymentStatus:'paid',fulfillmentStatus:'pending',trackingNumber:'',logisticsCompany:'',billing:{firstName:'Billing',lastName:'Person',fullName:'Billing Person',phone:'000000099',email:'billing@example.invalid',country:'Billing Country',city:'Billing City',street:'Billing Street'},...overrides});

async function writeWorkbook(directory,rows,{formula=false}={}){const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Orders');let start=1;for(const group of [...new Set(COLUMNS.map(column=>column[0]))]){const count=COLUMNS.filter(column=>column[0]===group).length;sheet.mergeCells(1,start,1,start+count-1);sheet.getCell(1,start).value=group;start+=count;}COLUMNS.forEach((column,index)=>sheet.getCell(2,index+1).value=column[2]);for(const [rowIndex,data] of rows.entries())for(const [columnIndex,[group,key]] of COLUMNS.entries()){let value=group==='账单信息'?data.billing?.[key]:data[key];if(formula&&key==='orderTotal')value={formula:'100',result:100};sheet.getCell(rowIndex+3,columnIndex+1).value=value??'';}const file=path.join(directory,'fictional-orders.xlsx');await workbook.xlsx.writeFile(file);return file;}
function portableRows(rows,{flat=false}={}){const dataRows=rows.map(data=>COLUMNS.map(([group,key])=>group==='账单信息'?data.billing?.[key]??'':data[key]??''));if(flat)return [COLUMNS.map(([group,,label])=>`${group}/${label}`),...dataRows];let previous='';const groupRow=COLUMNS.map(([group])=>{const value=group===previous?'':group;previous=group;return value;});return [groupRow,COLUMNS.map(column=>column[2]),...dataRows];}
async function writePortableWorkbook(directory,extension,rows,options={}){const sheet=XLSX.utils.aoa_to_sheet(portableRows(rows,options)),workbook=XLSX.utils.book_new(),file=path.join(directory,`fictional-orders.${extension}`);XLSX.utils.book_append_sheet(workbook,sheet,'Orders');await writeFile(file,XLSX.write(workbook,{bookType:extension,type:'buffer'}));return file;}
async function moveFirstHeaderOutsideGroup(file,header){const workbook=new ExcelJS.Workbook();await workbook.xlsx.readFile(file);const sheet=workbook.getWorksheet('Orders');sheet.unMergeCells('A1:M1');sheet.mergeCells('B1:M1');sheet.getCell('B1').value='订单信息基础信息';sheet.getCell('A1').value=null;sheet.getCell('A2').value=header;await workbook.xlsx.writeFile(file);}
async function context(rows,options={}){const directory=await mkdtemp(path.join(os.tmpdir(),'shopplus-test-')),file=await writeWorkbook(directory,rows,options),database=await openOrderDatabase({databaseFile:path.join(directory,'orders.sqlite')}),costCatalog=createCostCatalog([{businessId:'KY02',sourceName:'KY02 Fictional Product',cost:'20.00'},{businessId:'YB45',sourceName:'YB45 Fictional Product',cost:'30.00'},{businessId:'026',sourceName:'026 Fictional Product',cost:'10.00'},{businessId:'Z01',sourceName:'Z01 Fictional Product',cost:'15.00'}]);return {directory,file,database,costCatalog,close:async()=>{database.close();await rm(directory,{recursive:true,force:true});}};}

test('两层合并表头区分收货和账单重复列，并保留客户原文',async()=>{const c=await context([fictional({fullName:' Test  Recipient '})]);try{const p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:c.costCatalog}),o=p.orders[0];assert.equal(o.shipping.fullName,' Test  Recipient ');assert.equal(o.shipping.phone,'+000000001');assert.equal(o.billing.phone,'000000099');assert.notEqual(o.shipping.phone,o.billing.phone);assert.equal(p.summary.validOrders,1);}finally{await c.close();}});
test('收货字段为空时才使用账单后备并产生warning',async()=>{const c=await context([fictional({phone:''})]);try{const p=await previewShopPlusExcel(c.file,{costCatalog:c.costCatalog}),o=p.orders[0];assert.equal(o.shipping.phone,'000000099');assert.ok(o.warnings.some(w=>w.code==='BILLING_FALLBACK'&&w.field==='phone'));assert.equal(o.customerDataFallback,true);}finally{await c.close();}});
test('顶层分组为空时只识别明确的站点ID表头',async()=>{let c=await context([fictional()]);try{await moveFirstHeaderOutsideGroup(c.file,'站点ID');let parsed=await readShopPlusWorkbook(c.file);assert.equal(parsed.rows[0].order.siteId,'SITE-TEST');}finally{await c.close();}c=await context([fictional()]);try{await moveFirstHeaderOutsideGroup(c.file,'随机无分组字段');const parsed=await readShopPlusWorkbook(c.file);assert.equal(parsed.rows[0].order.siteId,undefined);assert.equal(parsed.rows[0].order.orderNo,'ORDER-TEST-1');}finally{await c.close();}});
test('Excel日期序号不偏移日期且公式只读取缓存值',async()=>{assert.equal(excelSerialToSourceTime(46257.5),'2026-08-23T12:00:00');const c=await context([fictional()],{formula:true});try{const p=await previewShopPlusExcel(c.file,{costCatalog:c.costCatalog});assert.equal(p.orders[0].createdAt,'2026-08-23T12:00:00');assert.ok(p.warnings.some(w=>w.code==='FORMULA_CACHED_VALUE'));}finally{await c.close();}});
test('XLS与两层表头CSV沿用XLSX订单解析和业务校验',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'shopplus-formats-')),costCatalog=createCostCatalog([{businessId:'KY02',cost:'20'}]);try{for(const extension of ['xls','csv']){const file=await writePortableWorkbook(directory,extension,[fictional({orderNo:`FORMAT-${extension.toUpperCase()}`,createdAt:'2026-09-12 12:00:00',street:'Fictional Street, Unit "A"'})]),preview=await previewShopPlusExcel(file,{costCatalog}),order=preview.orders[0];assert.equal(order.orderNo,`FORMAT-${extension.toUpperCase()}`);assert.equal(order.shipping.phone,'+000000001');assert.equal(order.shipping.street,'Fictional Street, Unit "A"');assert.equal(order.items[0].businessCode,'KY02');assert.equal(order.items[0].costFils,2000);assert.equal(preview.summary.validOrders,1);}}finally{await rm(directory,{recursive:true,force:true});}});
test('单层分组表头CSV可以识别收货与账单重复字段',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'shopplus-flat-csv-'));try{const file=await writePortableWorkbook(directory,'csv',[fictional({orderNo:'FLAT-CSV',createdAt:'2026-09-12 12:00:00'})],{flat:true}),parsed=await readShopPlusWorkbook(file);assert.equal(parsed.rows[0].order.orderNo,'FLAT-CSV');assert.equal(parsed.rows[0].shipping.fullName,'Test Recipient');assert.equal(parsed.rows[0].billing.fullName,'Billing Person');assert.equal(parsed.rows[0].product.productName,'KY02 Fictional Product');}finally{await rm(directory,{recursive:true,force:true});}});
test('商品SKU、SPU编码、名称开头按顺序识别，内部SKU ID不参与',()=>{assert.deepEqual(businessCodeCandidates({productSku:'KY02',spuCode:'YB45',productName:'Z01 Name'}).map(x=>x.value),['KY02','YB45','Z01']);assert.equal(leadingBusinessCode('026 Fictional'),'026');assert.equal(leadingBusinessCode('Name YB45'),null);assert.deepEqual(businessCodeCandidates({skuId:'999999',productName:'No Code'}),[]);});
test('一订单多商品正确合并，同系列一包裹、不同系列多包裹',async()=>{const rows=[fictional({subOrderId:'SUB-A',productSku:'KY02',productName:'KY02 Fictional Product',unitPrice:'40',orderTotal:'100',productTotal:'100'}),fictional({subOrderId:'SUB-B',productSku:'KY40',productName:'KY40 Fictional Other',unitPrice:'60',orderTotal:'100',productTotal:'100'})],c=await context(rows);try{let p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:createCostCatalog([{businessId:'KY02',cost:'20'},{businessId:'KY40',cost:'25'}])});assert.equal(p.orders.length,1);assert.equal(p.orders[0].items.length,2);await commitShopPlusImport(p,{database:c.database,confirmReviewOrderNos:['ORDER-TEST-1']});assert.equal(c.database.prepare('SELECT count(*) n FROM packages').get().n,1);
    const c2=await context([rows[0],fictional({...rows[1],productSku:'YB45',productName:'YB45 Fictional Product'})]);try{p=await previewShopPlusExcel(c2.file,{database:c2.database,costCatalog:c2.costCatalog});await commitShopPlusImport(p,{database:c2.database});assert.equal(c2.database.prepare('SELECT count(*) n FROM packages').get().n,2);}finally{await c2.close();}
  }finally{await c.close();}});
test('待发货和已发货只建立跟踪状态，不会自动签收、拒收、运费或最终利润',async()=>{for(const [raw,expected] of [['待发货','unshipped'],['已发货','shipped_pending']]){const c=await context([fictional({orderStatus:raw})]);try{const p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:c.costCatalog});await commitShopPlusImport(p,{database:c.database});const pkg=c.database.prepare('SELECT * FROM packages').get(),order=c.database.prepare('SELECT * FROM orders').get();assert.equal(pkg.package_status,expected);assert.equal(pkg.shipping_fee,null);assert.equal(pkg.shipping_fee_finalized,0);assert.equal(order.realized_profit,null);assert.equal(order.profit_status,'pending');}finally{await c.close();}}});
test('取消和未知状态必须人工确认，不会猜测签收或拒收',async()=>{for(const [raw,code] of [['已取消','CANCEL_STAGE_UNKNOWN'],['mystery','ORDER_STATUS_UNKNOWN']]){const c=await context([fictional({orderStatus:raw})]);try{const p=await previewShopPlusExcel(c.file,{costCatalog:c.costCatalog});assert.equal(p.orders[0].needsReview,true);assert.equal(p.orders[0].packageStatus,'unshipped');assert.ok(p.orders[0].warnings.some(w=>w.code===code));}finally{await c.close();}}});
test('缺少编号或成本使用NULL并标记核对，绝不使用0成本',async()=>{const c=await context([fictional({productSku:'',spuCode:'',productName:'Fictional Product Without Code'})]);try{const p=await previewShopPlusExcel(c.file,{costCatalog:c.costCatalog}),item=p.orders[0].items[0];assert.equal(item.businessCode,null);assert.equal(item.costFils,null);assert.equal(item.needsReview,true);assert.equal(p.summary.missingBusinessCodes,1);assert.equal(p.summary.missingCosts,1);}finally{await c.close();}});
test('订单优惠按原价比例分摊且0.01尾差由最后一条承担',async()=>{const rows=[fictional({subOrderId:'D-A',unitPrice:'33.33',productSku:'KY02',productName:'KY02 Fictional Product',productTotal:'100',orderTotal:'99.99',discountAmount:'0.01'}),fictional({subOrderId:'D-B',unitPrice:'66.67',productSku:'YB45',productName:'YB45 Fictional Product',productTotal:'100',orderTotal:'99.99',discountAmount:'0.01'})],c=await context(rows);try{const p=await previewShopPlusExcel(c.file,{costCatalog:c.costCatalog}),o=p.orders[0];assert.deepEqual(o.items.map(i=>i.allocatedDiscountFils),[0,1]);assert.equal(o.items.reduce((s,i)=>s+i.allocatedDiscountFils,0),1);assert.equal(o.needsReview,true);assert.equal(p.summary.reviewOrders,1);}finally{await c.close();}});
test('商品总价、订单总价或客户资料冲突会明确警告或阻止',async()=>{const rows=[fictional({subOrderId:'C-A',unitPrice:'40',productTotal:'90',orderTotal:'90',phone:'+0001'}),fictional({subOrderId:'C-B',unitPrice:'60',productTotal:'90',orderTotal:'90',phone:'+0002'})],c=await context(rows);try{const p=await previewShopPlusExcel(c.file,{costCatalog:c.costCatalog}),o=p.orders[0];assert.ok(o.warnings.some(w=>w.code==='PRODUCT_TOTAL_MISMATCH'));assert.ok(o.blockingErrors.some(e=>e.code==='SHIPPING_CUSTOMER_CONFLICT'));assert.equal(o.canImport,false);}finally{await c.close();}});
test('相同重复商品行只保留一份，相同子订单不同内容会阻止',async()=>{let c=await context([fictional(),fictional()]);try{let p=await previewShopPlusExcel(c.file,{costCatalog:c.costCatalog});assert.equal(p.orders[0].items.length,1);assert.equal(p.summary.duplicateOrders,1);}finally{await c.close();}c=await context([fictional(),fictional({productName:'KY02 Changed Fictional'})]);try{const p=await previewShopPlusExcel(c.file,{costCatalog:c.costCatalog});assert.ok(p.orders[0].blockingErrors.some(e=>e.code==='SUB_ORDER_CONFLICT'));}finally{await c.close();}});
test('预览不写库，需核对订单未确认不导入，确认后成本快照不随库存改变',async()=>{const c=await context([fictional({discountAmount:'1',orderTotal:'99'})]);try{const p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:c.costCatalog});assert.equal(c.database.prepare('SELECT count(*) n FROM orders').get().n,0);let result=await commitShopPlusImport(p,{database:c.database});assert.equal(result.imported,0);result=await commitShopPlusImport(p,{database:c.database,confirmReviewOrderNos:['ORDER-TEST-1']});assert.equal(result.imported,1);assert.equal(c.database.prepare('SELECT unit_cost_snapshot FROM order_items').get().unit_cost_snapshot,2000);assert.equal(c.database.prepare('SELECT actual_price_confirmed FROM order_items').get().actual_price_confirmed,1);}finally{await c.close();}});
test('同批Excel按创建时间和原始行稳定分配固定序号',async()=>{const rows=[fictional({orderNo:'BATCH-LATER',subOrderId:'BATCH-SUB-3',createdAt:46258}),fictional({orderNo:'BATCH-TIE-FIRST',subOrderId:'BATCH-SUB-1',createdAt:46257}),fictional({orderNo:'BATCH-TIE-SECOND',subOrderId:'BATCH-SUB-2',createdAt:46257})],c=await context(rows);try{const preview=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:c.costCatalog});await commitShopPlusImport(preview,{database:c.database});const stored=c.database.prepare('SELECT shopplus_order_no,fixed_sequence FROM orders ORDER BY fixed_sequence').all();assert.deepEqual(stored.map(row=>[row.shopplus_order_no,row.fixed_sequence]),[['BATCH-TIE-FIRST',1],['BATCH-TIE-SECOND',2],['BATCH-LATER',3]]);}finally{await c.close();}});
test('相同订单和相同文件哈希重新预览会提示并默认跳过',async()=>{const c=await context([fictional()]);try{let p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:c.costCatalog});await commitShopPlusImport(p,{database:c.database});p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:c.costCatalog});assert.equal(p.alreadyImportedFile,true);assert.equal(p.summary.existingOrders,1);const result=await commitShopPlusImport(p,{database:c.database});assert.equal(result.imported,0);}finally{await c.close();}});
test('预览后文件变化会阻止，写入故障整批回滚',async()=>{let c=await context([fictional()]);try{const p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:c.costCatalog});await writeFile(c.file,'changed');await assert.rejects(()=>commitShopPlusImport(p,{database:c.database}),e=>e.code==='SHOPPLUS_FILE_CHANGED');assert.equal(c.database.prepare('SELECT count(*) n FROM orders').get().n,0);}finally{await c.close();}
  c=await context([fictional({orderNo:'ROLLBACK-1',subOrderId:'RB-1'}),fictional({orderNo:'ROLLBACK-2',subOrderId:'RB-2'})]);try{const p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:c.costCatalog});await assert.rejects(()=>commitShopPlusImport(p,{database:c.database,failAfterOrders:1}),/整批回滚/);assert.equal(c.database.prepare('SELECT count(*) n FROM orders').get().n,0);assert.equal(c.database.prepare("SELECT count(*) n FROM import_batches WHERE status='failed'").get().n,1);}finally{await c.close();}});
test('只支持xlsx、xls、csv并拒绝其他扩展名',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'shopplus-invalid-')),file=path.join(directory,'orders.ods');try{await writeFile(file,'not a supported order file');await assert.rejects(()=>previewShopPlusExcel(file),e=>e.code==='SHOPPLUS_FILE_TYPE_UNSUPPORTED');}finally{await rm(directory,{recursive:true,force:true});}});

test('成本20解析为2000 fils',()=>{assert.deepEqual(parseInventoryCost('20'),{status:'valid',costFils:2000,rawText:'20',note:null,annotated:false,notSoldSeparately:false});});
test('成本20.5解析为2050 fils',()=>{assert.equal(parseInventoryCost('20.5').costFils,2050);});
test('成本20(不单卖)保留原文、备注和业务标记',()=>{const result=parseInventoryCost('20(不单卖)');assert.deepEqual(result,{status:'annotated',costFils:2000,rawText:'20(不单卖)',note:'不单卖',annotated:true,notSoldSeparately:true});});
test('成本中文括号备注正确解析',()=>{const result=parseInventoryCost('20（不单卖）');assert.equal(result.costFils,2000);assert.equal(result.note,'不单卖');assert.equal(result.rawText,'20（不单卖）');});
test('数字和成本备注之间允许空格',()=>{const result=parseInventoryCost('20 (不单卖)');assert.equal(result.costFils,2000);assert.equal(result.note,'不单卖');});
test('成本区间20-25不得擅自解析',()=>{assert.equal(parseInventoryCost('20-25').costFils,null);assert.equal(parseInventoryCost('20-25').status,'ambiguous');});
test('组合金额20+5不得擅自解析',()=>{assert.equal(parseInventoryCost('20+5').costFils,null);assert.equal(parseInventoryCost('20+5').status,'ambiguous');});
test('模糊成本约20不得擅自解析',()=>{assert.equal(parseInventoryCost('约20').costFils,null);assert.equal(parseInventoryCost('约20').status,'ambiguous');});
test('一个商品成本异常不中止整份订单预览且不用0代替',async()=>{const rows=[fictional({subOrderId:'BAD-COST',productSku:'KY02',productName:'KY02 Fictional Product',unitPrice:'40',productTotal:'100',orderTotal:'100'}),fictional({subOrderId:'GOOD-COST',productSku:'YB45',productName:'YB45 Fictional Product',unitPrice:'60',productTotal:'100',orderTotal:'100'})],c=await context(rows);try{const catalog=createCostCatalog([{businessId:'KY02',cost:'20-25'},{businessId:'YB45',cost:'30'}]),p=await previewShopPlusExcel(c.file,{costCatalog:catalog});assert.equal(p.summary.validOrders,1);assert.equal(p.orders[0].items[0].costFils,null);assert.equal(p.orders[0].items[1].costFils,3000);assert.ok(p.orders[0].warnings.some(value=>value.code==='COST_FORMAT_AMBIGUOUS'));}finally{await c.close();}});
test('不单卖商品单独下单时需要核对并保存成本原文',async()=>{const c=await context([fictional()]);try{const catalog=createCostCatalog([{businessId:'KY02',cost:'20(不单卖)'}]),p=await previewShopPlusExcel(c.file,{database:c.database,costCatalog:catalog}),order=p.orders[0],item=order.items[0];assert.equal(order.needsReview,true);assert.equal(item.costFils,2000);assert.equal(item.costRawText,'20(不单卖)');assert.equal(item.costNote,'不单卖');assert.ok(order.warnings.some(value=>value.code==='annotated_cost'));assert.ok(order.warnings.some(value=>value.code==='NOT_SOLD_SEPARATELY_SINGLE_PRODUCT'));await commitShopPlusImport(p,{database:c.database,confirmReviewOrderNos:[order.orderNo]});const stored=c.database.prepare('SELECT unit_cost_snapshot,cost_raw_text,cost_note,not_sold_separately FROM order_items').get();assert.deepEqual({...stored},{unit_cost_snapshot:2000,cost_raw_text:'20(不单卖)',cost_note:'不单卖',not_sold_separately:1});}finally{await c.close();}});
test('不单卖商品与其他商品同单时只保留备注而不阻断',async()=>{const rows=[fictional({subOrderId:'BUNDLE-A',productSku:'KY02',productName:'KY02 Fictional Product',unitPrice:'40',productTotal:'100',orderTotal:'100'}),fictional({subOrderId:'BUNDLE-B',productSku:'YB45',productName:'YB45 Fictional Product',unitPrice:'60',productTotal:'100',orderTotal:'100'})],c=await context(rows);try{const catalog=createCostCatalog([{businessId:'KY02',cost:'20(不单卖)'},{businessId:'YB45',cost:'30'}]),p=await previewShopPlusExcel(c.file,{costCatalog:catalog}),order=p.orders[0];assert.equal(order.blockingErrors.length,0);assert.equal(order.warnings.some(value=>value.code==='NOT_SOLD_SEPARATELY_SINGLE_PRODUCT'),false);assert.equal(order.items[0].costNote,'不单卖');}finally{await c.close();}});
test('无法确定的成本为NULL并产生明确目录警告',()=>{const catalog=createCostCatalog([{businessId:'KY02',cost:'无成本'}]),result=catalog.resolve({candidates:[{value:'KY02'}]});assert.equal(result.costFils,null);assert.equal(result.costStatus,'ambiguous');assert.ok(catalog.warnings.some(value=>value.code==='COST_FORMAT_AMBIGUOUS'));});
test('未被当前订单使用的注释成本也不会中止预览且保留脱敏警告',async()=>{const c=await context([fictional()]);try{const catalog=createCostCatalog([{businessId:'KY02',cost:'20'},{businessId:'YB45',cost:'30(不单卖)'}]),p=await previewShopPlusExcel(c.file,{costCatalog:catalog});assert.equal(p.summary.validOrders,1);assert.equal(p.summary.annotatedCostWarnings,1);assert.ok(p.warnings.some(value=>value.code==='annotated_cost'));}finally{await c.close();}});
