export type ReplyTemplate={id:string;label:string;zh:string;en:string;enabled:boolean;imageIds:string[]};
type ImageChoice={id:string;name:string;sku?:string;dataUrl:string};
export const REPLY_KEY='liaodan.reply-templates.v1',ORDER_KEY='liaodan.order-template.v1';
export const defaultReplies:ReplyTemplate[]=[
 ['confirm','确认订单','{订单确认}','{订单确认}'],
 ['address','询问地址','麻烦提供您的姓名、电话、城市和详细收货地址，谢谢。','Could you please share your full name, phone number, city and detailed delivery address?'],
 ['details','补充资料','麻烦补充缺少的资料，以便我为您核对订单。','Could you please provide the missing details so I can check your order?'],
 ['products','确认商品','请确认您需要的商品、规格和数量。','Could you please confirm the product, variant and quantity you would like?'],
 ['delivery','配送说明','我会核对您的地址是否可以配送，并与您确认配送费及时间。','I will check whether delivery is available for your address and confirm the delivery fee and timing with you.'],
 ['followup','礼貌跟进','您好，请问您是否需要继续下单？有任何疑问都可以告诉我。','Hello! Would you like to continue with your order? Please let me know if you have any questions.']
].map(([id,label,zh,en])=>({id,label,zh,en,enabled:true,imageIds:[]}));
export function loadReplies(){const stored=window.localStorage.getItem(REPLY_KEY);if(!stored)return structuredClone(defaultReplies);const value=JSON.parse(stored);if(!Array.isArray(value)||value.some(t=>typeof t.id!=='string'||typeof t.label!=='string'||typeof t.zh!=='string'||typeof t.en!=='string'||!Array.isArray(t.imageIds)))throw new Error('快捷回复设置无法读取，请先在设置中检查。');return value as ReplyTemplate[];}
export function templateDialog(doc:Document,title:string){const d=doc.createElement('dialog');d.className='shared-dialog template-dialog';d.innerHTML='<h2></h2><div class="template-body"></div><output aria-live="polite"></output><footer><button data-close>关闭</button></footer>';d.querySelector('h2')!.textContent=title;doc.body.append(d);d.querySelector<HTMLButtonElement>('[data-close]')!.onclick=()=>d.close();d.onclose=()=>d.remove();return {d,body:d.querySelector<HTMLElement>('.template-body')!,footer:d.querySelector('footer')!,status:d.querySelector('output')!};}
export const fieldNames=['订单号','客户姓名','电话','国家','城市','完整地址','商品清单','配送费','应付金额'];
export function orderFields(doc:Document):Record<string,string>{
 const section=doc.querySelector('#od-customer-title')?.closest('section');
 const fields=Array.from(section?.querySelectorAll('.od-field-value')||[]).map(el=>Array.from(el.childNodes).filter(n=>n.nodeType===3).map(n=>n.textContent).join('').trim());
 const value=(selector:string)=>doc.querySelector(selector)?.textContent?.trim()||'';
 const products=Array.from(doc.querySelectorAll('.od-product-list .od-product')).map(el=>['.od-product-name','.od-qty','.od-price'].map(s=>el.querySelector(s)?.textContent?.trim()||'').filter(Boolean).join(' · '));
 return {'订单号':value('h1'),'客户姓名':fields[0]||'','电话':fields[1]||'','国家':fields[2]||'','城市':fields[3]||'','完整地址':fields[4]||'','商品清单':products.join('\n'),'配送费':value('#od-customer-delivery-display')||value('#od-customer-delivery-fee'),'应付金额':value('#od-payable')};
}
export function fillTemplate(text:string,fields:Record<string,string>){return text.replace(/\{([^{}]+)\}/g,(_,key:string)=>{const v=fields[key];if(!v||/^(—|-|待填写|未填写|待确认)$/.test(v))throw new Error(`缺少或无法调用字段：${key}`);return v;});}
function insertFields(doc:Document,target:HTMLTextAreaElement,names:string[]){const row=doc.createElement('div');row.className='template-fields';for(const name of names){const b=doc.createElement('button');b.type='button';b.textContent=`{${name}}`;b.onclick=()=>{target.setRangeText(`{${name}}`,target.selectionStart,target.selectionEnd,'end');target.dispatchEvent(new Event('input'));target.focus();};row.append(b);}return row;}
export function openReplySettings(doc:Document,onSave:()=>void,images:()=>Promise<ImageChoice[]>){
 const {d,body,footer,status}=templateDialog(doc,'快捷回复设置');let items:ReplyTemplate[];try{items=loadReplies();}catch(e){status.textContent=(e as Error).message;d.showModal();return;}
 let selected=items[0]?.id,dragged='';const layout=doc.createElement('div');layout.className='template-columns';const list=doc.createElement('div');list.className='template-list';const editor=doc.createElement('div');editor.className='template-editor';layout.append(list,editor);body.append(layout);
 const paint=()=>{
  list.replaceChildren();items.forEach((t,index)=>{const row=doc.createElement('div');row.className='template-list-row';row.draggable=true;row.ondragstart=()=>{dragged=t.id;};row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();const from=items.findIndex(x=>x.id===dragged);if(from<0)return;items.splice(index,0,items.splice(from,1)[0]);paint();};const pick=doc.createElement('button');pick.textContent=(t.enabled?'':'隐藏 · ')+t.label;pick.setAttribute('aria-pressed',String(t.id===selected));pick.onclick=()=>{selected=t.id;paint();};row.append(pick);for(const [label,step] of [['上移',-1],['下移',1]] as const){const b=doc.createElement('button');b.textContent=step<0?'↑':'↓';b.setAttribute('aria-label',`${label} ${t.label}`);b.disabled=index+step<0||index+step>=items.length;b.onclick=()=>{items.splice(index+step,0,items.splice(index,1)[0]);paint();};row.append(b);}list.append(row);});
  editor.replaceChildren();const t=items.find(x=>x.id===selected);if(!t){editor.textContent='点击“新增回复”添加模板。';return;}
  editor.innerHTML='<label>按钮名称<input data-name maxlength="20"></label><label class="template-check"><input data-enabled type="checkbox">在快捷回复中显示</label><label>中文内容<textarea data-zh rows="4"></textarea></label><label>英文内容<textarea data-en rows="4"></textarea></label><p>支持换行、空行和表情。动态字段来自当前订单；资料缺失会提示，关联真实聊天后不调用演示订单字段。</p><div class="template-images"></div>';
  const name=editor.querySelector<HTMLInputElement>('[data-name]')!,enabled=editor.querySelector<HTMLInputElement>('[data-enabled]')!,zh=editor.querySelector<HTMLTextAreaElement>('[data-zh]')!,en=editor.querySelector<HTMLTextAreaElement>('[data-en]')!;name.value=t.label;enabled.checked=t.enabled;zh.value=t.zh;en.value=t.en;
  name.oninput=()=>{t.label=name.value;};enabled.onchange=()=>{t.enabled=enabled.checked;};zh.oninput=()=>{t.zh=zh.value;};en.oninput=()=>{t.en=en.value;};zh.after(insertFields(doc,zh,[...fieldNames,'订单确认']));en.after(insertFields(doc,en,[...fieldNames,'订单确认']));
  const imageBox=editor.querySelector<HTMLElement>('.template-images')!;imageBox.textContent='正在读取商品图片…';void images().then(rows=>{if(!imageBox.isConnected)return;imageBox.replaceChildren();const caption=doc.createElement('p');caption.textContent='附带商品图片（最多 6 张，调用后仍可移除）';imageBox.append(caption);for(const id of t.imageIds.filter(id=>!rows.some(p=>p.id===id))){const p=doc.createElement('p');p.textContent='有已失效图片，调用前请重新选择。';imageBox.append(p);const remove=doc.createElement('button');remove.textContent='移除失效图片';remove.onclick=()=>{t.imageIds=t.imageIds.filter(x=>x!==id);paint();};imageBox.append(remove);}if(!rows.length){imageBox.append('暂无商品图片，可先到商品库存添加，或回复时手动上传。');}for(const p of rows){const label=doc.createElement('label');label.className='template-image';const check=doc.createElement('input');check.type='checkbox';check.checked=t.imageIds.includes(p.id);check.onchange=()=>{if(check.checked&&t.imageIds.length>=6){check.checked=false;status.textContent='最多附带 6 张图片';return;}t.imageIds=check.checked?[...t.imageIds,p.id]:t.imageIds.filter(id=>id!==p.id);};const img=doc.createElement('img');img.src=p.dataUrl;img.alt=p.name;label.append(check,img,doc.createTextNode(p.sku||p.name));imageBox.append(label);}}).catch(e=>{imageBox.textContent=(e as Error).message;});
 };
 const button=(label:string,fn:()=>void)=>{const b=doc.createElement('button');b.textContent=label;b.onclick=fn;footer.prepend(b);};
 button('删除当前回复',()=>{items=items.filter(t=>t.id!==selected);selected=items[0]?.id;paint();});button('新增回复',()=>{if(items.length>=50){status.textContent='最多保存 50 条快捷回复';return;}const t={id:crypto.randomUUID(),label:'新回复',zh:'',en:'',enabled:true,imageIds:[]};items.push(t);selected=t.id;paint();});
 button('保存快捷回复',()=>{try{if(items.some(t=>!t.label.trim()||t.enabled&&(!t.zh.trim()||!t.en.trim())))throw new Error('请填写按钮名称，以及已启用回复的中英文内容。');window.localStorage.setItem(REPLY_KEY,JSON.stringify(items));onSave();status.textContent='快捷回复已保存';paint();}catch(e){status.textContent=(e as Error).message;}});paint();d.showModal();
}
const defaultOrder='订单：{订单号}\n客户：{客户姓名}\n电话：{电话}\n国家：{国家}\n城市：{城市}\n地址：{完整地址}\n\n商品：\n{商品清单}\n配送费：{配送费}\n应付金额：{应付金额}';
const sample:Record<string,string>={'订单号':'示例订单 001','客户姓名':'Example Customer','电话':'+971 50 000 0000','国家':'United Arab Emirates','城市':'Dubai','完整地址':'Example Street, Villa 8','商品清单':'KY02 × 2 · AED 150.00','配送费':'AED 0.00','应付金额':'AED 150.00'};
export function openOrderSettings(doc:Document){const {d,body,footer,status}=templateDialog(doc,'订单模板设置');const hint=doc.createElement('p');hint.textContent='设置 TXT 的字段顺序、标签语言、换行和分隔线。下方使用示例订单预览，保存后应用到订单弹窗和导出。';const area=doc.createElement('textarea');area.className='order-template-editor';area.setAttribute('aria-label','订单 TXT 模板');area.rows=10;area.value=window.localStorage.getItem(ORDER_KEY)??defaultOrder;const preview=doc.createElement('pre');preview.className='order-text-content';preview.setAttribute('aria-label','订单模板示例');const paint=()=>{try{preview.textContent=fillTemplate(area.value,sample);status.textContent='';}catch(e){status.textContent=(e as Error).message;preview.textContent='';}};area.oninput=paint;body.append(hint,area,insertFields(doc,area,fieldNames),preview);const save=doc.createElement('button');save.textContent='保存订单模板';save.onclick=()=>{try{if(!area.value.trim())throw new Error('订单模板不能为空');fillTemplate(area.value,sample);window.localStorage.setItem(ORDER_KEY,area.value);status.textContent='订单模板已保存';}catch(e){status.textContent=(e as Error).message;}};footer.prepend(save);paint();d.showModal();}
export function installOrderPreview(doc:Document){
 const generate=doc.querySelector<HTMLButtonElement>('#od-generate');if(!generate)return ()=>{};
 generate.textContent='预览订单 TXT';const pre=doc.querySelector<HTMLElement>('.od-txt-preview');if(pre)pre.hidden=true;
 generate.onclick=()=>{const {d,body,footer,status}=templateDialog(doc,'订单 TXT 预览');const text=doc.createElement('pre');text.className='order-text-content';let content='';try{content=fillTemplate(window.localStorage.getItem(ORDER_KEY)??defaultOrder,orderFields(doc));text.textContent=content;}catch(e){status.textContent=(e as Error).message;}body.append(text);const copy=doc.createElement('button');copy.textContent='复制';copy.disabled=!content;copy.onclick=async()=>{try{await window.navigator.clipboard.writeText(content);status.textContent='已复制';}catch{status.textContent='无法自动复制，请选中文字后复制。';}};const download=doc.createElement('button');download.textContent='导出 TXT';download.disabled=!content;download.onclick=async()=>{const filename=(orderFields(doc)['订单号']||'订单').replace(/[\\/:*?"<>|]/g,'_')+'.txt';const native=(window as Window&{orderTextFiles?:{save:(payload:{filename:string;content:string})=>Promise<{ok:boolean;canceled?:boolean;error?:string}>}}).orderTextFiles;if(native){download.disabled=true;try{const result=await native.save({filename,content});if(!result.ok)throw new Error(result.error||'导出失败');status.textContent=result.canceled?'已取消导出':'订单 TXT 已保存';}catch(e){status.textContent=(e as Error).message;}finally{download.disabled=false;}return;}const url=URL.createObjectURL(new Blob(['\uFEFF'+content.replace(/\r?\n/g,'\r\n')],{type:'text/plain;charset=utf-8'}));const a=doc.createElement('a');a.href=url;a.download=(orderFields(doc)['订单号']||'订单').replace(/[\\/:*?"<>|]/g,'_')+'.txt';doc.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);};const settings=doc.createElement('button');settings.textContent='模板设置';settings.onclick=()=>{d.close();openOrderSettings(doc);};footer.prepend(copy,download,settings);d.showModal();};
 const settings=doc.createElement('button');settings.className='od-button';settings.textContent='模板设置';settings.onclick=()=>openOrderSettings(doc);generate.after(settings);return ()=>{};
}
