type Response<T>={ok:boolean;data?:T;error?:{message?:string}};
type OrderRow={id:string;orderNo:string;sequence:number;source:string;workflowStatus:string;trackingStatus:string;customerName:string;phone:string;createdAt:string;updatedAt:string;amountFils:number|null;products:{code:string;quantity:number}[];itemCount:number;needsReview:boolean};
type PreviewItem={sourceRow:number;businessCode:string|null;productName:string;quantity:number;costFils:number|null;needsReview:boolean};
type PreviewOrder={orderNo:string|null;phoneMasked:string;items:PreviewItem[];canImport:boolean;alreadyExists:boolean;needsReview:boolean;reviewConfirmed:boolean;warnings:{code:string}[];blockingErrors:{code:string}[];amountCheck?:{amountMismatch?:boolean;discountNeedsConfirmation?:boolean}};
type ImportPreview={token:string;filename:string;alreadyImportedFile:boolean;summary:{validOrders:number;directImportOrders:number;reviewOrders:number;blockedOrders:number;existingOrders:number;blockingErrors:number};orders:PreviewOrder[]};
type DraftItem={sku:string;quantity:number;price_fils:number|null;discount_fils:number|null};
type DetailItem={businessCode:string;productName:string;quantity:number;unitActualPriceFils:number|null;costFils:number|null;lineRevenueFils:number|null;lineCostFils?:number|null;manualDiscountFils?:number|null;itemProfitFils?:number|null;needsReview?:boolean};
type DetailPackage={id:string;seriesCode:string;status:string;statusUpdatedAt?:string|null;reportedAt?:string|null;shippingFeeFils:number|null;shippingFeeConfirmed?:boolean;feeNote?:string|null;packageProfitFils?:number|null;profitStatus?:string|null};
type Detail={id:string;orderNo:string|null;sequence:number;source:string;entryState:string;draftRevision:number;trackingStatus:string;orderStatus:string;confirmed?:boolean;confirmedAt?:string|null;confirmationNote?:string|null;amounts:{orderTotal:number|null;productTotal?:number|null;discount?:number|null;customerShippingFee:number|null};customer:{fullName:string|null;firstName:string|null;lastName:string|null;phone:string|null;email:string|null;country:string|null;province:string|null;city:string|null;street:string|null;residence:string|null};draft?:{fields:Record<string,string|null>;items:DraftItem[]}|null;items:DetailItem[];packages:DetailPackage[];report?:{reportedAt:string|null}|null;profitStatus?:string|null;totalProfitFils?:number|null;remittance?:{amountFils:number|null;registeredAt:string|null;completedAt:string|null;status:'received'|'pending'}|null};
type AssistantWorkflow={stageState:{revision:number;values:{nextFollowUpAt?:string|null;history?:{note?:string;action?:string}[]}};reminder:{active:boolean;dueAt:string|null}};
type OrderSyncSchedule={enabled:boolean;intervalMinutes:number};
type SyncAttentionOrder={id:string;orderNo:string;phone:string;createdAt:string;contactStatus:'phone_missing'|'chat_not_bound'|'communicated'|'chat_bound_no_messages';messageCount:number};
type SyncAttention={orders:SyncAttentionOrder[]};
type ShopPlusState={configured:boolean;test:{status:'verified'|'failed';at:string;message:string}|null;sync:{lastSuccessfulAt:string|null;lastFetchedAt:string|null;lastImported:number;lastExisting:number;lastBlocked:number;truncated:boolean};schedule:OrderSyncSchedule};
type ShopPlusSync={result:{fetched:number;imported:number;existing:number;blocked:number;lastSuccessfulAt:string;truncated:boolean};response:{pages:number;totalCount:number|null;truncated:boolean};status:ShopPlusState};

const money=(fils:number|null|undefined)=>fils===null||fils===undefined?'待核对':`AED ${(fils/100).toFixed(2)}`;
const cny=(fen:number|null|undefined)=>fen===null||fen===undefined?'待确认':`CNY ¥${(fen/100).toFixed(2)}`;
const plain=(value:unknown)=>String(value??'').trim()||'—';
const orderStatusLabel=(workflowStatus:string,trackingStatus:string)=>workflowStatus==='draft'?'草稿':({pending:'待确认',unshipped:'待发货',awaiting_report:'待报单',outbound_processing:'出库中',shipped_pending:'待收货',signed:'已签收',refused:'已拒收',unreachable:'联系不上',cancelled_before_outbound:'已取消',cancelled_after_outbound:'已取消'}[trackingStatus]||'状态待核对');
const input=(doc:Document,label:string,value='')=>{const wrap=doc.createElement('label');wrap.className='ob-field';const name=doc.createElement('span');name.textContent=label;const box=doc.createElement('input');box.value=value;wrap.append(name,box);return {wrap,box};};
const button=(doc:Document,label:string,className='btn')=>{const element=doc.createElement('button');element.type='button';element.className=className;element.textContent=label;return element;};
const note=(doc:Document,message:string)=>{const item=doc.createElement('p');item.className='ob-note';item.textContent=message;return item;};
const lucide=(doc:Document,name:string)=>{const icon=doc.createElement('i');icon.dataset.lucide=name;icon.setAttribute('aria-hidden','true');return icon;};
const section=(doc:Document,title:string,iconName?:string)=>{const item=doc.createElement('section');item.className='od-card ob-card';const bar=doc.createElement('div');bar.className='od-card-head';const head=doc.createElement('h2');head.className='od-card-title';if(iconName)head.append(lucide(doc,iconName));head.append(title);bar.append(head);item.append(bar);return item;};
function workbenchStatus(row:OrderRow){
  if(row.workflowStatus==='draft')return {label:'草稿',className:'cw-info',icon:'file-pen-line'};
  if(row.workflowStatus==='pending')return {label:'待确认',className:'cw-confirm',icon:'clipboard-check'};
  const states:Record<string,{label:string;className:string;icon:string}>={
    unshipped:{label:'待发货',className:'cw-confirm',icon:'package'},
    awaiting_report:{label:'待报单',className:'cw-info',icon:'clipboard-list'},
    outbound_processing:{label:'出库中',className:'cw-confirm',icon:'package-check'},
    shipped_pending:{label:'运输中',className:'cw-follow',icon:'truck'},
    signed:{label:'已签收',className:'cw-follow',icon:'badge-check'},
    refused:{label:'已拒收',className:'cw-info',icon:'circle-alert'},
    unreachable:{label:'联系不上',className:'cw-info',icon:'phone-off'},
    cancelled_before_outbound:{label:'已取消',className:'cw-info',icon:'circle-x'},
    cancelled_after_outbound:{label:'已取消',className:'cw-info',icon:'circle-x'}
  };
  return states[row.trackingStatus]||{label:'状态待核对',className:'cw-info',icon:'circle-help'};
}
async function call<T>(name:string,...args:unknown[]):Promise<T>{
  const method=window.inventoryApp?.orders?.[name];if(!method)throw new Error('订单服务尚未就绪，请从桌面 App 重新打开');
  const result=await method(...args) as Response<T>;
  if(!result.ok)throw new Error(result.error?.message||'订单操作失败');
  return result.data as T;
}

export function installWorkbenchOrders(doc:Document,{selectOrder,selectedOrderId}:{selectOrder:(id:string)=>void;selectedOrderId?:string|null}):()=>void{
  const root=doc.querySelector<HTMLElement>('#chat-workbench-aligned')!,list=root.querySelector<HTMLElement>('#cw-task-list')!,count=root.querySelector<HTMLElement>('#cw-result-count')!;
  const title=root.querySelector<HTMLElement>('#cw-queue-title');if(title)title.textContent='近期订单';
  let closed=false,filter='all',rows:OrderRow[]=[],selectedId=selectedOrderId||'';
  const render=()=>{
    if(closed)return;
    for(const [kind,predicate,label] of [
      ['info',(row:OrderRow)=>row.workflowStatus==='draft','待补资料'],
      ['confirm',(row:OrderRow)=>row.workflowStatus==='pending','待确认']
    ] as const){const stat=root.querySelector<HTMLElement>(`.cw-stat[data-filter="${kind}"]`);if(!stat)continue;const amount=rows.filter(predicate).length;stat.querySelector<HTMLElement>('.cw-stat-value')!.textContent=String(amount);stat.querySelector<HTMLElement>('.cw-stat-note')!.textContent=amount?`${amount} 个真实订单`:`暂无${label}订单`;}
    const attention=root.querySelector<HTMLElement>('.cw-tab[data-filter="attention"]');if(attention){const label=doc.createElement('span'),badge=doc.createElement('span');label.textContent='需注意';badge.className='cw-attention-count';badge.textContent=String(rows.filter(row=>row.needsReview).length);attention.replaceChildren(label,badge);}
    const visible=rows.filter(row=>filter==='all'||filter==='info'&&row.workflowStatus==='draft'||filter==='confirm'&&row.workflowStatus==='pending'||filter==='attention'&&row.needsReview||filter==='follow'&&row.trackingStatus==='shipped_pending');
    count.textContent=`${visible.length} 项`;list.replaceChildren();
    if(!visible.length){const empty=doc.createElement('div');empty.className='cw-empty';empty.textContent=rows.length?'当前筛选没有订单':'暂无真实订单。可以导入 ShopPlus 文件，或新建空白订单。';list.append(empty);return;}
    for(const row of visible){const article=doc.createElement('article');article.className='cw-task-row';article.dataset.orderId=row.id;article.dataset.selected=String(row.id===selectedId);
      const main=button(doc,'','cw-row-main cursor-interaction');main.setAttribute('aria-label',`选择${row.orderNo}订单`);main.setAttribute('aria-pressed',String(row.id===selectedId));main.onclick=()=>{selectedId=row.id;selectOrder(row.id);for(const card of list.querySelectorAll<HTMLElement>('.cw-task-row')){const selected=card.dataset.orderId===row.id;card.dataset.selected=String(selected);card.querySelector<HTMLButtonElement>('.cw-row-main')?.setAttribute('aria-pressed',String(selected));}};
      const person=doc.createElement('span');person.className='cw-row-person';const avatar=doc.createElement('span');avatar.className='cw-avatar';avatar.textContent=row.customerName?.[0]||'?';const copy=doc.createElement('span');copy.className='cw-person-copy';const phoneLine=doc.createElement('span');phoneLine.className='cw-phone-line';const phone=doc.createElement('span');phone.className='cw-phone-number';phone.textContent=plain(row.phone);phoneLine.append(phone);const ref=doc.createElement('span');ref.className='cw-order-ref';ref.textContent=row.orderNo;copy.append(phoneLine,ref);person.append(avatar,copy);
      const message=doc.createElement('span');message.className='cw-row-message';const heading=doc.createElement('span');heading.className='cw-message-title';heading.textContent=row.customerName||'客户资料待补';const body=doc.createElement('span');body.className='cw-message-preview';body.textContent=row.products.length?row.products.map(p=>`${p.code} × ${p.quantity}`).join('，'):'商品待补';const source=doc.createElement('span'),sourceIcon=doc.createElement('i');source.className='cw-source';sourceIcon.dataset.lucide=row.source==='manual'?'pen-line':'file-up';source.append(sourceIcon,doc.createTextNode(row.source==='manual'?'手动新建':'ShopPlus 导入'));message.append(heading,body,source);
      const state=doc.createElement('span');state.className='cw-row-status';const status=workbenchStatus(row),badge=doc.createElement('span'),badgeIcon=doc.createElement('i');badge.className=`cw-status-pill ${status.className}`;badgeIcon.dataset.lucide=status.icon;badge.append(badgeIcon,doc.createTextNode(status.label));const time=doc.createElement('span');time.className='cw-status-time';time.textContent=plain(row.updatedAt).slice(0,16);state.append(badge,time);main.append(person,message,state);
      const actions=doc.createElement('span');actions.className='cw-row-actions';const detail=button(doc,'订单详情','cw-open cw-detail cursor-interaction');detail.dataset.openOrderDetail='';actions.append(detail);article.append(main,actions);list.append(article);
    }
    (doc.defaultView as (Window&{lucide?:{createIcons:(options:{nodes:Element[]})=>void}})|null)?.lucide?.createIcons({nodes:[list]});
  };
  const choose=(event:Event)=>{const target=(event.target as Element).closest<HTMLElement>('[data-filter]');if(!target||!root.contains(target))return;event.preventDefault();event.stopImmediatePropagation();filter=target.dataset.filter||'all';for(const tab of root.querySelectorAll<HTMLElement>('.cw-tab'))tab.setAttribute('aria-selected',String(tab.dataset.filter===filter));for(const stat of root.querySelectorAll<HTMLElement>('.cw-stat'))stat.setAttribute('aria-pressed',String(stat.dataset.filter===filter));render();};
  root.addEventListener('click',choose,true);
  void call<OrderRow[]>('list',{sort:'newest'}).then(value=>{rows=value;render();}).catch(error=>{if(!closed){list.replaceChildren(note(doc,(error as Error).message));count.textContent='读取失败';}});
  return ()=>{closed=true;root.removeEventListener('click',choose,true);};
}

export function installOrdersPage(doc:Document,{openOrder,initialAction,openSettings}:{openOrder:(id:string)=>void;initialAction?:'import'|'new';openSettings?:()=>void}):()=>void{
  const root=doc.querySelector<HTMLElement>('#ui040')!,main=root.querySelector<HTMLElement>('.main')!,head=main.querySelector<HTMLElement>('.head')!;
  const connection=root.querySelector<HTMLElement>('.wa');if(connection){connection.textContent='○ WhatsApp · 订单聊天待核对';connection.style.color='#747080';}
  main.replaceChildren(head);
  root.querySelector('#u40-import-dialog')?.remove();root.querySelector('#u40-row-menu')?.remove();root.querySelector('#u40-popover')?.remove();
  const originalImport=head.querySelector<HTMLButtonElement>('#u40-import')!;
  const importButton=originalImport.cloneNode(true) as HTMLButtonElement;
  originalImport.replaceWith(importButton);
  const pageSettings=root.querySelector<HTMLButtonElement>('.up-settings'),layoutDialog=root.querySelector<HTMLDialogElement>('.shared-dialog');
  pageSettings?.remove();
  const layoutApply=layoutDialog?.querySelector<HTMLButtonElement>('[data-close]');if(layoutApply)layoutApply.textContent='应用';
  const title=head.querySelector<HTMLElement>('h1')!,titleRow=doc.createElement('span');titleRow.className='ob-title-row';
  const info=doc.createElement('button');info.type='button';info.className='ob-title-info';info.setAttribute('aria-label','订单管理说明与布局设置');info.textContent='?';
  title.replaceWith(titleRow);titleRow.append(title,info);
  info.onclick=()=>{if(layoutDialog){layoutDialog.querySelector('p')!.textContent='导入、查找和管理订单，以及维护聊单用户档案。可在此调整并应用本屏幕的导航与内容布局。';layoutDialog.showModal();}};
  const workspace=doc.createElement('section');workspace.className='ob-orders';
  workspace.innerHTML='<div class="ob-toolbar"><label>查找订单 <input class="ob-search" type="search" placeholder="订单编号、客户电话或商品编号"></label><label>下单日期 <span class="ob-date-range"><input class="ob-date-from" type="date" aria-label="开始日期"><span>至</span><input class="ob-date-to" type="date" aria-label="结束日期"></span></label><label>订单状态 <select class="ob-status"><option value="all">全部</option><option value="draft">草稿</option><option value="unshipped">待发货</option><option value="shipped_pending">运输中</option><option value="signed">已签收</option></select></label><span class="ob-count" role="status">正在读取订单…</span></div><section class="ob-sync-attention" aria-live="polite" hidden><div class="ob-sync-attention-copy"></div><button type="button" class="ob-sync-attention-ack">已查看这些新订单</button></section><div class="table-wrap"><table><thead><tr><th class="ob-sequence-head">序号</th><th>下单日期</th><th>订单编号</th><th>客户</th><th>商品</th><th>订单总金额</th><th>来源</th><th>状态</th><th>操作</th></tr></thead><tbody class="ob-rows"></tbody></table></div><nav class="ob-pagination" aria-label="订单分页"></nav><p class="ob-feedback" role="status" aria-live="polite"></p>';
  main.append(workspace);
  const search=workspace.querySelector<HTMLInputElement>('.ob-search')!,dateFrom=workspace.querySelector<HTMLInputElement>('.ob-date-from')!,dateTo=workspace.querySelector<HTMLInputElement>('.ob-date-to')!,status=workspace.querySelector<HTMLSelectElement>('.ob-status')!,rows=workspace.querySelector<HTMLElement>('.ob-rows')!,count=workspace.querySelector<HTMLElement>('.ob-count')!,pagination=workspace.querySelector<HTMLElement>('.ob-pagination')!,feedback=workspace.querySelector<HTMLElement>('.ob-feedback')!,attention=workspace.querySelector<HTMLElement>('.ob-sync-attention')!,attentionCopy=workspace.querySelector<HTMLElement>('.ob-sync-attention-copy')!,attentionAck=workspace.querySelector<HTMLButtonElement>('.ob-sync-attention-ack')!;
  const pageSize=10;let all:OrderRow[]=[],page=1,closed=false,preview:ImportPreview|undefined;
  const show=(message:string)=>{feedback.textContent=message;};
  const draftDeleteDialog=doc.createElement('dialog');draftDeleteDialog.className='shared-dialog ob-draft-delete-confirm';root.append(draftDeleteDialog);
  const requestDraftDeletion=(row:OrderRow)=>{draftDeleteDialog.replaceChildren();const heading=doc.createElement('h2');heading.textContent='删除订单草稿';const warning=note(doc,`确定删除“${row.orderNo}”吗？这会删除本机的草稿资料和草稿商品明细，不能恢复；不会删除正式订单或向外部平台发送操作。`);const result=doc.createElement('output');result.className='ob-feedback';result.setAttribute('aria-live','polite');const footer=doc.createElement('footer'),cancel=button(doc,'取消','btn'),confirm=button(doc,'确认删除草稿','btn danger');cancel.onclick=()=>draftDeleteDialog.close();confirm.onclick=async()=>{confirm.disabled=true;result.textContent='正在删除草稿…';try{await call<{id:string;deleted:true}>('deleteDraft',{orderId:row.id,confirmed:true});draftDeleteDialog.close();await refresh();show(`已删除草稿“${row.orderNo}”。`);}catch(error){result.textContent=(error as Error).message;confirm.disabled=false;}};footer.append(cancel,confirm);draftDeleteDialog.append(heading,warning,result,footer);if(!draftDeleteDialog.open)draftDeleteDialog.showModal();};
  const render=()=>{
    const query=search.value.trim().toLowerCase(),filtered=all.filter(row=>{const day=plain(row.createdAt).slice(0,10);return (status.value==='all'||status.value==='draft'&&row.workflowStatus==='draft'||status.value!=='draft'&&row.trackingStatus===status.value)&&(!dateFrom.value||day>=dateFrom.value)&&(!dateTo.value||day<=dateTo.value)&&(!query||[row.orderNo,row.phone,row.customerName,...row.products.map(p=>p.code)].some(value=>String(value||'').toLowerCase().includes(query)));});
    const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,totalPages);const visible=filtered.slice((page-1)*pageSize,page*pageSize);
    count.textContent=`共 ${filtered.length} 个订单`;rows.replaceChildren();pagination.replaceChildren();
    if(!filtered.length){const tr=doc.createElement('tr'),td=doc.createElement('td');td.colSpan=9;td.className='ob-empty';td.textContent=all.length?'没有符合条件的订单':'暂无真实订单。请从聊单工作台核对客户后新建订单，或导入 ShopPlus 文件。';tr.append(td);rows.append(tr);return;}
    for(const row of visible){const tr=doc.createElement('tr');tr.dataset.orderId=row.id;tr.style.setProperty('--ob-product-count',String(Math.max(1,row.products.length)));
      const serial=doc.createElement('td');serial.className='ob-sequence';serial.textContent=String(row.sequence);tr.append(serial);
      const date=doc.createElement('td');date.className='ob-date';const timestamp=plain(row.createdAt),dateLine=doc.createElement('b'),timeLine=doc.createElement('span');dateLine.textContent=timestamp.slice(0,10)||'—';timeLine.textContent=timestamp.slice(11,16)||'—';date.append(dateLine,timeLine);tr.append(date);
      const number=doc.createElement('td');number.className='ob-order-number';number.textContent=row.orderNo;tr.append(number);
      const customer=doc.createElement('td');customer.className='ob-customer';const phone=doc.createElement('b'),name=doc.createElement('span');phone.textContent=plain(row.phone);name.textContent=row.customerName||'资料待补';customer.append(phone,name);tr.append(customer);
      const products=doc.createElement('td');products.className='ob-products';if(row.products.length)for(const product of row.products){const line=doc.createElement('span');line.textContent=`${product.code} × ${product.quantity}`;products.append(line);}else products.textContent='待补商品';tr.append(products);
      const sourceLabel=row.source==='manual'?'聊单创建':row.source==='shopplus_api'?'ShopPlus API 同步':'文件导入';for(const value of [money(row.amountFils),sourceLabel]){const td=doc.createElement('td');td.textContent=value;tr.append(td);}const statusCell=doc.createElement('td'),statusBadge=doc.createElement('span');statusBadge.className=`ob-order-status is-${row.workflowStatus==='draft'?'draft':row.trackingStatus||'unknown'}`;statusBadge.textContent=orderStatusLabel(row.workflowStatus,row.trackingStatus);statusCell.append(statusBadge);tr.append(statusCell);
      const action=doc.createElement('td'),open=button(doc,'订单详情','detail');action.className='ob-row-actions';open.dataset.openOrderDetail='';open.onclick=()=>openOrder(row.id);action.append(open);if(row.workflowStatus==='draft'){const remove=button(doc,'删除草稿','detail ob-delete-draft');remove.onclick=()=>requestDraftDeletion(row);action.append(remove);}tr.append(action);rows.append(tr);
    }
    const previous=button(doc,'上一页','ob-page-button');previous.disabled=page===1;previous.onclick=()=>{page--;render();};const indicator=doc.createElement('span');indicator.textContent=`第 ${page} / ${totalPages} 页`;const next=button(doc,'下一页','ob-page-button');next.disabled=page===totalPages;next.onclick=()=>{page++;render();};pagination.append(previous,indicator,next);
  };
  const contactDescription=(order:SyncAttentionOrder)=>({phone_missing:'电话待核对，暂不能关联 WhatsApp 会话',chat_not_bound:'未发现已核对 WhatsApp 会话',chat_bound_no_messages:'已关联会话，尚未保存本单沟通记录',communicated:`已保存 ${order.messageCount} 条本单沟通记录`}[order.contactStatus]);
  const refreshAttention=async()=>{try{const value=await call<SyncAttention>('shopPlusSyncAttention');if(closed)return;attention.hidden=value.orders.length===0;attentionCopy.replaceChildren();if(!value.orders.length)return;const heading=doc.createElement('strong');heading.textContent=`发现 ${value.orders.length} 个新订单待处理`;const noteText=doc.createElement('span');noteText.textContent='“是否加好友”没有可验证字段；这里只核对已关联会话与本机已保存沟通记录。';const list=doc.createElement('ul');for(const order of value.orders.slice(0,4)){const line=doc.createElement('li');line.textContent=`${order.orderNo} · ${plain(order.phone)} · ${contactDescription(order)}`;list.append(line);}if(value.orders.length>4){const more=doc.createElement('li');more.textContent=`另有 ${value.orders.length-4} 个新订单待核对`;list.append(more);}attentionCopy.append(heading,noteText,list);}catch(error){if(!closed)show((error as Error).message);}};
  attentionAck.onclick=async()=>{attentionAck.disabled=true;try{const current=await call<SyncAttention>('shopPlusSyncAttention');if(current.orders.length)await call<SyncAttention>('acknowledgeShopPlusSyncAttention',{orderIds:current.orders.map(order=>order.id)});await refreshAttention();show('已标记为已查看；订单和沟通记录没有被修改。');}catch(error){show((error as Error).message);}finally{attentionAck.disabled=false;}};
  const refresh=async()=>{try{all=await call<OrderRow[]>('list',{sort:'newest'});if(!closed)render();await refreshAttention();}catch(error){if(!closed)show((error as Error).message);}};
  const resetPage=()=>{page=1;render();};search.oninput=resetPage;status.onchange=resetPage;dateFrom.onchange=resetPage;dateTo.onchange=resetPage;
  importButton.textContent='从文件导入';
  const apiStatus=doc.createElement('button'),scheduleButton=doc.createElement('button'),syncButton=doc.createElement('button');apiStatus.type='button';apiStatus.className='ob-api-status';apiStatus.setAttribute('aria-label','ShopPlus 连接与同步状态');scheduleButton.type='button';scheduleButton.className='ob-schedule-button';scheduleButton.setAttribute('aria-label','设置订单定时更新');syncButton.type='button';syncButton.className='ob-sync-button';syncButton.textContent='同步最新订单';const actions=head.querySelector<HTMLElement>('.head-actions')!;actions.prepend(syncButton);actions.prepend(scheduleButton);actions.prepend(apiStatus);
  let shopPlus:ShopPlusState|undefined,shopPlusNotice='',shopPlusStatusError='';
  const syncDialog=doc.createElement('dialog');syncDialog.className='shared-dialog ob-sync';root.append(syncDialog);
  const displayTime=(value:string|null|undefined)=>value?value.replace('T',' ').slice(0,16):'尚未同步';
  const readableShopPlusError=(error:unknown)=>{const message=(error as Error)?.message||'ShopPlus 同步失败';return /UNIQUE constraint failed:\s*order_items\.shopplus_sub_order_id/i.test(message)?'ShopPlus 返回的商品编号在不同订单中重复。本版本会自动按订单区分；请关闭弹窗后再次同步。':message;};
  const refreshShopPlusStatus=async()=>{try{shopPlus=await call<ShopPlusState>('shopPlusStatus');shopPlusStatusError='';const verified=shopPlus.test?.status==='verified';apiStatus.classList.toggle('is-connected',verified);apiStatus.classList.toggle('is-failed',shopPlus.test?.status==='failed');apiStatus.textContent=verified?'ShopPlus 已连接':shopPlus.configured?'ShopPlus 待验证':'ShopPlus 未配置';apiStatus.title=verified?`${shopPlus.test?.message||'已验证'}；最近同步：${displayTime(shopPlus.sync.lastSuccessfulAt)}`:shopPlus.test?.message||'请在“连接与设置”统一配置 ShopPlus App Key 和 API Secret。';const schedule=shopPlus.schedule||{enabled:false,intervalMinutes:30};scheduleButton.textContent=schedule.enabled?`定时更新：每 ${schedule.intervalMinutes} 分钟`:'定时更新：关闭';scheduleButton.classList.toggle('is-enabled',schedule.enabled);scheduleButton.title=schedule.enabled?'已启用只读 ShopPlus 订单定时更新':'默认关闭；点击后可选择更新间隔';}catch(error){shopPlus=undefined;shopPlusStatusError=readableShopPlusError(error);apiStatus.classList.remove('is-connected');apiStatus.classList.add('is-failed');apiStatus.textContent='ShopPlus 状态不可读取';apiStatus.title=shopPlusStatusError;scheduleButton.textContent='定时更新：不可读取';scheduleButton.classList.remove('is-enabled');}};
  const renderSyncDialog=()=>{
    const state=shopPlus;syncDialog.replaceChildren();const heading=doc.createElement('h2');heading.textContent='同步 ShopPlus 订单';const lead=note(doc,'从店铺后台只读获取订单，写入本机订单管理。相同订单号会跳过，不会覆盖本地订单或修改网站后台。');const card=doc.createElement('section');card.className='ob-sync-status';const stateName=doc.createElement('strong'),stateDetail=doc.createElement('span');const verified=state?.test?.status==='verified';stateName.textContent=shopPlusStatusError?'ShopPlus 配置状态暂不可读取':verified?'ShopPlus 已连接':state?.configured?'ShopPlus 待验证':'ShopPlus 尚未在连接与设置配置';stateDetail.textContent=shopPlusStatusError?`${shopPlusStatusError}。请在“连接与设置”重新读取状态；无需重复录入凭据。`:verified?`${state?.test?.message||'最近一次接口验证通过'} · 最近同步 ${displayTime(state?.sync.lastSuccessfulAt)}`:state?.test?.message||'请前往“连接与设置”统一配置 App Key 和 API Secret；商品读取仍会单独验证。';card.append(stateName,stateDetail);
    const schedule=state?.schedule||{enabled:false,intervalMinutes:30};const scheduleCard=doc.createElement('section');scheduleCard.className='ob-auto-sync';const scheduleTitle=doc.createElement('strong');scheduleTitle.textContent='定时更新';const scheduleDetail=doc.createElement('span');scheduleDetail.textContent='默认关闭。启用后按选定间隔只读同步 ShopPlus 订单；不会修改网站订单。';const scheduleControl=doc.createElement('div');const scheduleSelect=doc.createElement('select');scheduleSelect.setAttribute('aria-label','订单定时更新间隔');for(const [value,label] of [['off','关闭'],['15','每 15 分钟'],['30','每 30 分钟'],['60','每 60 分钟']]){const option=doc.createElement('option');option.value=value;option.textContent=label;scheduleSelect.append(option);}scheduleSelect.value=schedule.enabled?String(schedule.intervalMinutes):'off';const saveSchedule=button(doc,'保存定时更新','btn');saveSchedule.disabled=!state?.configured||Boolean(shopPlusStatusError);saveSchedule.onclick=async()=>{saveSchedule.disabled=true;try{const enabled=scheduleSelect.value!=='off';await call<OrderSyncSchedule>('configureOrderSyncSchedule',{enabled,intervalMinutes:enabled?Number(scheduleSelect.value):schedule.intervalMinutes});await refreshShopPlusStatus();shopPlusNotice=enabled?`已启用每 ${scheduleSelect.value} 分钟定时更新。`:'已关闭定时更新。';renderSyncDialog();}catch(error){shopPlusNotice=(error as Error).message;saveSchedule.disabled=false;}};scheduleControl.append(scheduleSelect,saveSchedule);scheduleCard.append(scheduleTitle,scheduleDetail,scheduleControl);
    const result=doc.createElement('p');result.className='ob-feedback';result.setAttribute('aria-live','polite');result.textContent=shopPlusNotice;const footer=doc.createElement('footer'),close=button(doc,'关闭','btn'),settings=button(doc,'前往连接与设置','btn'),run=button(doc,'同步最新订单','btn primary'),file=button(doc,'从文件导入','btn');close.onclick=()=>syncDialog.close();settings.onclick=()=>{syncDialog.close();if(openSettings)openSettings();else shopPlusNotice='请从左侧“连接与设置”统一配置 ShopPlus API。';};run.disabled=!state?.configured||Boolean(shopPlusStatusError);run.onclick=async()=>{run.disabled=true;settings.disabled=true;result.textContent='正在从 ShopPlus 读取最新订单…';try{const response=await call<ShopPlusSync>('syncShopPlus');shopPlus=response.status;const notice=`已读取 ${response.result.fetched} 单，新加入 ${response.result.imported} 单，重复跳过 ${response.result.existing} 单${response.result.blocked?`，待核对跳过 ${response.result.blocked} 单`:''}。`;shopPlusNotice=response.result.truncated?`${notice} 本次最多读取 1000 单，请再次同步继续获取。`:notice;show(shopPlusNotice);await refresh();await refreshShopPlusStatus();renderSyncDialog();}catch(error){result.textContent=readableShopPlusError(error);await refreshShopPlusStatus();run.disabled=false;settings.disabled=false;}};file.onclick=()=>{syncDialog.close();importButton.click();};footer.append(close,file);if(!state?.configured||shopPlusStatusError)footer.append(settings);footer.append(run);syncDialog.append(heading,lead,card,scheduleCard,result,footer);
  };
  const openSync=async()=>{await refreshShopPlusStatus();renderSyncDialog();if(!syncDialog.open)syncDialog.showModal();};apiStatus.onclick=()=>void openSync();scheduleButton.onclick=()=>void openSync();syncButton.onclick=()=>void openSync();const orderSyncRuntime=window.inventoryApp as (typeof window.inventoryApp&{onOrderSync?:(callback:(value:{automatic?:boolean;result?:{imported?:number}})=>void)=>()=>void});const removeOrderSyncListener=orderSyncRuntime?.onOrderSync?.(value=>{if(!value?.result?.imported||closed)return;show(`${value.automatic?'定时更新':'同步'}发现 ${value.result.imported} 个新订单，请核对会话与沟通记录。`);void refresh();void refreshShopPlusStatus();});const attentionPoll=window.setInterval(()=>{if(!closed)void refreshAttention();},15000);void refreshShopPlusStatus();

  const dialog=doc.createElement('dialog');dialog.className='shared-dialog ob-import';root.append(dialog);
  const renderPreview=()=>{
    if(!preview)return;
    dialog.replaceChildren();const title=doc.createElement('h2');title.textContent=`导入预览 · ${preview.filename}`;dialog.append(title);
    dialog.append(note(doc,`识别 ${preview.summary.validOrders} 单；可直接导入 ${preview.summary.directImportOrders} 单；需人工核对 ${preview.summary.reviewOrders} 单；重复 ${preview.summary.existingOrders} 单；阻断 ${preview.summary.blockedOrders} 单。`));
    if(preview.alreadyImportedFile)dialog.append(note(doc,'这个文件此前已导入。已有订单会自动跳过，请核对后再决定是否提交。'));
    const list=doc.createElement('div');list.className='ob-preview-list';
    for(const order of preview.orders){const card=doc.createElement('section');card.className='ob-preview-order';
      const h=doc.createElement('h3');h.textContent=`${plain(order.orderNo)} · ${plain(order.phoneMasked)}`;card.append(h);
      card.append(note(doc,order.alreadyExists?'已存在，将跳过':!order.canImport?`不能导入：${order.blockingErrors.map(e=>e.code).join('、')}`:order.reviewConfirmed?'已人工核对':order.needsReview?'需要人工核对商品、状态或金额':'可直接导入'));
      if(order.canImport&&order.needsReview){const itemInputs:{sourceRow:number;code:HTMLInputElement;cost:HTMLInputElement}[]=[];
        for(const item of order.items){const row=doc.createElement('div');row.className='ob-review-row';const label=doc.createElement('span');label.textContent=`第 ${item.sourceRow} 行 · ${plain(item.productName)} × ${item.quantity}`;const code=input(doc,'商品编号',item.businessCode||'');const cost=input(doc,'成本 AED',item.costFils===null?'':(item.costFils/100).toFixed(2));row.append(label,code.wrap,cost.wrap);card.append(row);itemInputs.push({sourceRow:item.sourceRow,code:code.box,cost:cost.box});}
        const missing=doc.createElement('label'),missingCheck=doc.createElement('input');missingCheck.type='checkbox';missing.append(missingCheck,' 允许暂缺成本，利润保持待核对');card.append(missing);
        const discount=doc.createElement('label'),discountCheck=doc.createElement('input');discountCheck.type='checkbox';discount.append(discountCheck,' 已核对优惠与订单金额');card.append(discount);
        const confirm=button(doc,order.reviewConfirmed?'重新核对本单':'确认本单资料','btn');confirm.onclick=async()=>{confirm.disabled=true;try{preview=await call<ImportPreview>('reviewImport',{token:preview!.token,orderNo:order.orderNo,items:itemInputs.map(item=>({sourceRow:item.sourceRow,...(item.code.value.trim()?{businessCode:item.code.value.trim()}:{}),...(item.cost.value.trim()?{costAed:item.cost.value.trim()}:{} )})),confirmed:true,missingCostConfirmed:missingCheck.checked,discountConfirmed:discountCheck.checked});renderPreview();}catch(error){const output=card.querySelector<HTMLElement>('.ob-review-error')||doc.createElement('p');output.className='ob-review-error';output.textContent=(error as Error).message;card.append(output);confirm.disabled=false;}};card.append(confirm);
      }
      list.append(card);
    }
    dialog.append(list);const footer=doc.createElement('footer');const cancel=button(doc,'取消','btn'),commit=button(doc,'确认导入','btn primary');
    cancel.onclick=()=>dialog.close();commit.disabled=preview.summary.blockingErrors>0||preview.orders.every(o=>!o.canImport)||preview.orders.some(o=>o.canImport&&!o.alreadyExists&&o.needsReview&&!o.reviewConfirmed);
    commit.onclick=async()=>{commit.disabled=true;try{const result=await call<{imported:number;skipped:number}>('commitImport',preview!.token);dialog.close();show(`已导入 ${result.imported} 单，跳过 ${result.skipped} 单。`);preview=undefined;await refresh();}catch(error){dialog.append(note(doc,(error as Error).message));commit.disabled=false;}};
    footer.append(cancel,commit);dialog.append(footer);
  };
  importButton.onclick=async()=>{importButton.disabled=true;show('正在选择文件…');try{const selection=await call<{canceled:boolean;token:string;filename:string}>('selectExcel');if(selection.canceled){show('已取消选择文件');return;}preview=await call<ImportPreview>('previewImport',selection.token);renderPreview();dialog.showModal();show('文件已预览，尚未写入订单。');}catch(error){show((error as Error).message);}finally{importButton.disabled=false;}};
  void refresh();if(initialAction==='import')queueMicrotask(()=>{if(!closed)importButton.click();});
  return ()=>{closed=true;window.clearInterval(attentionPoll);removeOrderSyncListener?.();dialog.remove();syncDialog.remove();draftDeleteDialog.remove();};
}

export function installOrderDetail(doc:Document,orderId:string):()=>void{
  const root=doc.querySelector<HTMLElement>('#ui008-order-detail')!,content=root.querySelector<HTMLElement>('.od-content')!,heading=root.querySelector<HTMLElement>('.od-heading-copy h1')!,status=root.querySelector<HTMLElement>('.od-status-actions')!;
  const previewLabel=root.querySelector<HTMLElement>('.od-preview-label');if(previewLabel)previewLabel.textContent='UI-028 · 订单详情';
  let closed=false,detail:Detail|undefined;
  const trackingLabel=(value:Detail)=>{
    if(value.entryState==='draft')return '草稿';
    const states:Record<string,string>={pending:'待确认',unshipped:'待发货',awaiting_report:'待报单',outbound_processing:'出库中',shipped_pending:'运输中',signed:'已签收',refused:'已拒收',unreachable:'联系不上',cancelled_before_outbound:'已取消',cancelled_after_outbound:'已取消'};
    return states[value.trackingStatus]||states[value.orderStatus]||'状态待核对';
  };
  const sourceLabel=(value:Detail)=>value.source==='manual'?'手动新建':value.source==='shopplus_api'?'ShopPlus API 同步':'ShopPlus 文件导入';
  const refreshIcons=()=>{const view=doc.defaultView as Window&{lucide?:{createIcons:(options:{nodes:Element[]})=>void}};view.lucide?.createIcons({nodes:[content,status]});};
  const stageCard=(value:Detail,name:string)=>{
    const card=doc.createElement('section');card.className='od-card od-stage-card ob-stage-card';card.setAttribute('aria-label','订单阶段');
    const top=doc.createElement('div');top.className='od-stage-top';const current=doc.createElement('div');current.className='od-current-order';const label=doc.createElement('span');label.className='od-order-label';label.textContent='当前订单';const orderName=doc.createElement('span');orderName.className='od-order-name';orderName.textContent=value.orderNo||`草稿 #${value.sequence}`;current.append(label,orderName);const badge=doc.createElement('span');badge.className='od-badge';badge.textContent=trackingLabel(value);top.append(current,badge);card.append(top);
    const hasItems=value.entryState==='draft'?Boolean(value.draft?.items.length):value.items.length>0,hasAddress=Boolean(value.customer.phone&&value.customer.country&&value.customer.city&&(value.customer.street||value.customer.residence)),hasDelivery=value.packages.length>0||['outbound_processing','shipped_pending','signed','refused'].includes(value.trackingStatus),hasConfirmedOrder=value.entryState!=='draft';
    const facts=[hasItems,hasAddress,hasDelivery,hasConfirmedOrder],labels=['明确商品与数量','收齐收货资料','核对配送范围','客户确认订单'];let active=facts.findIndex(done=>!done);if(active<0)active=3;
    const stages=doc.createElement('div');stages.className='od-stages';stages.setAttribute('aria-label','订单推进步骤');labels.forEach((text,index)=>{const step=doc.createElement('span');step.className=`od-stage${index<active&&facts[index]?' is-done':''}${index===active?' is-current':''}`;const number=doc.createElement('span');number.className='od-stage-number';if(index<active&&facts[index])number.append(lucide(doc,'check'));else number.textContent=String(index+1);const copy=doc.createElement('span');copy.textContent=text;step.append(number,copy);stages.append(step);if(index<labels.length-1){const arrow=lucide(doc,'arrow-right');arrow.classList.add('od-stage-arrow');stages.append(arrow);}});card.append(stages);
    const objectives=['核对商品编号、数量和价格。','补全并核对客户的收货资料。','核对完整地址与配送范围。','核对订单资料并继续履约。'];const objective=doc.createElement('div');objective.className='od-objective';objective.append('当前目标：');const strong=doc.createElement('strong');strong.textContent=objectives[active];objective.append(strong);const meta=doc.createElement('span');meta.className='ob-stage-meta';meta.textContent=`${sourceLabel(value)} · ${name||'客户资料待补'} · ${money(value.amounts.orderTotal)}`;objective.append(meta);card.append(objective);return card;
  };
  const parcelStatusLabel=(status:string)=>({unshipped:'待发货',awaiting_report:'待报单',outbound_processing:'出库中',shipped_pending:'运输中',signed:'已签收',refused:'已拒收',unreachable:'联系不上',cancelled_before_outbound:'已取消',cancelled_after_outbound:'已取消',partial_complete:'部分完成',completed_mixed:'已完成'}[status]||'状态待核对');
  const totalIfKnown=(values:(number|null|undefined)[])=>values.length&&values.every(value=>typeof value==='number')?values.reduce((sum,value)=>sum+(value as number),0):null;
  const shortDate=(value:string|null|undefined)=>value?.slice(0,10)||'待确认';
  const profitCard=(value:Detail)=>{
    const card=section(doc,'履约与回款／利润核算','chart-no-axes-combined');card.classList.add('ob-profit-card');card.dataset.orderProfitCard='true';card.setAttribute('aria-label','履约与回款／利润核算');
    const itemCosts=value.items.map(item=>item.lineCostFils??(item.costFils===null||item.costFils===undefined?null:item.costFils*item.quantity));
    const revenue=totalIfKnown(value.items.map(item=>item.lineRevenueFils)),cost=totalIfKnown(itemCosts),confirmedPackages=value.packages.filter(parcel=>parcel.shippingFeeConfirmed===true),confirmedShipping=totalIfKnown(confirmedPackages.map(parcel=>parcel.shippingFeeFils)),allShippingConfirmed=value.packages.length>0&&confirmedPackages.length===value.packages.length,missingCost=value.items.length===0||cost===null,finalProfit=value.profitStatus==='final'?value.totalProfitFils??null:null,hasSigned=value.packages.some(parcel=>parcel.status==='signed'),hasIncomplete=value.profitStatus==='incomplete'||missingCost;
    const remittance=value.remittance||null,hasRemittance=remittance?.status==='received'&&remittance.amountFils!==null&&remittance.amountFils!==undefined;
    const settlementLabel=value.entryState==='draft'?'草稿待补资料':hasIncomplete?'利润待核对':!allShippingConfirmed?'待确认物流费':hasSigned&&!hasRemittance?'已签收 · 待回款':finalProfit!==null?'已完成核算':'待确认';
    const badge=doc.createElement('span');badge.className=`od-badge ob-profit-badge${hasIncomplete?' is-review':''}${hasRemittance?' is-complete':''}`;badge.textContent=settlementLabel;card.querySelector('.od-card-head')!.append(badge);
    if(value.entryState==='draft'){
      const draftNote=doc.createElement('div');draftNote.className='ob-profit-notice is-waiting';draftNote.append(lucide(doc,'clock-3'));const copy=doc.createElement('div'),title=doc.createElement('strong'),message=doc.createElement('p');title.textContent='草稿订单尚未进入利润核算';message.textContent='补齐商品、成本、配送结果和回款资料后，系统才会显示真实核算结果。';copy.append(title,message);draftNote.append(copy);card.append(draftNote);return card;
    }
    const statusList=doc.createElement('div');statusList.className='ob-profit-package-status';statusList.setAttribute('aria-label','包裹履约结果');
    if(!value.packages.length){const empty=doc.createElement('span');empty.className='ob-profit-status';empty.textContent='暂无包裹记录';statusList.append(empty);}else for(const parcel of value.packages){const status=doc.createElement('span');status.className=`ob-profit-status${['signed','refused','cancelled_before_outbound','cancelled_after_outbound'].includes(parcel.status)?' is-final':''}`;status.textContent=`${plain(parcel.seriesCode)} · ${parcelStatusLabel(parcel.status)}`;statusList.append(status);}card.append(statusList);
    const panels=doc.createElement('div');panels.className='ob-profit-panels';
    const panel=(title:string,icon:string)=>{const item=doc.createElement('section');item.className='ob-profit-panel';const heading=doc.createElement('h3');heading.append(lucide(doc,icon),doc.createTextNode(title));item.append(heading);return item;};
    const detailRow=(label:string,text:string)=>{const row=doc.createElement('div');row.className='ob-profit-detail-row';const name=doc.createElement('span'),result=doc.createElement('strong');name.textContent=label;result.textContent=text;row.append(name,result);return row;};
    const deliveryPanel=panel('配送结果与运输费用','route');const latestPackageDate=value.packages.map(parcel=>parcel.statusUpdatedAt).filter((date):date is string=>Boolean(date)).sort().at(-1);deliveryPanel.append(detailRow('包裹结果',value.packages.length?`${value.packages.length} 个包裹 · ${value.packages.map(parcel=>parcelStatusLabel(parcel.status)).join('、')}`:'待确认'),detailRow('结果日期',shortDate(latestPackageDate)),detailRow('已确认实际物流费',confirmedShipping===null?'待确认':allShippingConfirmed?money(confirmedShipping):`${money(confirmedShipping)}（另 ${value.packages.length-confirmedPackages.length} 包待确认）`));
    const settlementPanel=panel('回款与利润核算','badge-dollar-sign');settlementPanel.append(detailRow('已登记净回款（CNY）',hasRemittance?cny(remittance?.amountFils):'待回款'),detailRow('回款登记日',hasRemittance?shortDate(remittance?.registeredAt):'待回款'),detailRow('订单利润状态',hasIncomplete?'待核对':finalProfit!==null?'已核算':'待确认'));
    panels.append(deliveryPanel,settlementPanel);card.append(panels);
    const metrics=doc.createElement('div');metrics.className='ob-profit-metrics';const metric=(key:string,label:string,text:string,review=false)=>{const item=doc.createElement('div');item.className=`ob-profit-metric${review?' is-review':''}`;item.dataset.profitMetric=key;const name=doc.createElement('span'),amount=doc.createElement('strong');name.textContent=label;amount.textContent=text;item.append(name,amount);metrics.append(item);};
    metric('revenue','商品成交额',money(revenue));metric('cost','商品成本',money(cost),missingCost);metric('shipping','已确认物流费',confirmedShipping===null?'待确认':allShippingConfirmed?money(confirmedShipping):`${money(confirmedShipping)}（未全确认）`,!allShippingConfirmed);metric('profit','订单利润',finalProfit===null?'待确认':money(finalProfit),finalProfit===null);card.append(metrics);
    const notice=doc.createElement('div');notice.className=`ob-profit-notice${hasIncomplete||!allShippingConfirmed||hasSigned&&!hasRemittance?' is-waiting':''}`;notice.append(lucide(doc,hasIncomplete?'circle-alert':finalProfit!==null&&(!hasSigned||hasRemittance)?'circle-check':'clock-3'));const copy=doc.createElement('div'),title=doc.createElement('strong'),message=doc.createElement('p');
    if(hasIncomplete){title.textContent='暂不能形成订单利润';message.textContent='商品成本或核算资料缺失，请核对后再计算。';}else if(!allShippingConfirmed){title.textContent='实际物流费待确认';message.textContent='只显示已确认的物流费用；未确认包裹不会按零费用计入订单利润。';}else if(hasSigned&&!hasRemittance){title.textContent='暂不计入每日回款核算';message.textContent='订单利润已按已确认费用核算；收到并登记净回款后，才按回款日期计入每日回款核算。';}else if(finalProfit!==null){title.textContent=hasRemittance?'已登记净回款并完成核算':'已完成订单利润核算';message.textContent=hasRemittance?`已于 ${shortDate(remittance?.registeredAt)} 登记净回款；金额单位与 AED 订单利润分别显示。`:'配送结果和实际物流费已确认，订单利润可供核对。';}else{title.textContent='等待履约结果与费用确认';message.textContent='尚未形成实际运输与回款数据，当前不显示假设利润。';}
    copy.append(title,message);notice.append(copy);card.append(notice);return card;
  };
  const requestOrderConfirmation=(value:Detail)=>{
    const dialog=doc.createElement('dialog');dialog.className='shared-dialog ob-fulfillment-dialog';const title=doc.createElement('h2');title.textContent='确认客户订单';const basis=input(doc,'客户确认依据或备注');const result=doc.createElement('output');result.className='ob-feedback';result.setAttribute('aria-live','polite');const footer=doc.createElement('footer'),cancel=button(doc,'取消','btn'),confirm=button(doc,'确认客户订单','btn primary');
    cancel.onclick=()=>dialog.close();confirm.onclick=async()=>{confirm.disabled=true;result.textContent='正在保存确认…';try{const updated=await call<Detail>('confirmOrder',{orderId:value.id,note:basis.box.value.trim()});dialog.close();if(!closed)render(updated);}catch(error){result.textContent=(error as Error).message;confirm.disabled=false;}};
    footer.append(cancel,confirm);dialog.append(title,note(doc,'请仅在客户已明确确认商品、数量、价格和收货资料后保存。本操作只更新本机订单状态，不会发送外部消息。'),basis.wrap,result,footer);root.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();
  };
  const render=(value:Detail)=>{
    detail=value;heading.textContent=value.orderNo||`草稿 #${value.sequence}`;
    const name=value.customer.fullName||[value.customer.lastName,value.customer.firstName].filter(Boolean).join(' '),phone=value.customer.phone;
    const setText=(selector:string,text:string)=>{const element=root.querySelector<HTMLElement>(selector);if(element)element.textContent=text;};
    setText('.od-contact strong',phone||'未关联客户');setText('.od-contact small',`${name||'客户资料待补'} · ${heading.textContent}`);setText('.od-avatar',name?.[0]||'?');
    status.replaceChildren();status.hidden=false;
    if(value.entryState==='draft'){const draft=doc.createElement('span');draft.className='od-status-button ob-status-summary ob-status-complete';draft.textContent='草稿';status.append(draft);}else{
      const hasStartedDelivery=value.packages.some(parcel=>parcel.status!=='unshipped'),transporting=value.packages.some(parcel=>['outbound_processing','shipped_pending'].includes(parcel.status)),hasException=value.packages.some(parcel=>['refused','unreachable','cancelled_after_outbound'].includes(parcel.status)),allReceived=value.packages.length>0&&value.packages.every(parcel=>parcel.status==='signed'),reported=Boolean(value.report?.reportedAt)||hasStartedDelivery;
      const addSummary=(label:string,kind:'complete'|'current'|'future'|'action',onClick?:()=>void)=>{const state=onClick?button(doc,label,'od-status-button ob-status-summary ob-status-action cursor-interaction'):doc.createElement('span');if(!onClick)state.className='od-status-button ob-status-summary';state.classList.add(`ob-status-${kind}`);if(!onClick)state.textContent=label;state.setAttribute('aria-current',String(kind==='current'));if(onClick)state.onclick=onClick;status.append(state);};
      addSummary(value.confirmed?'已确认':'待确认',value.confirmed?'complete':'action',value.confirmed?undefined:()=>requestOrderConfirmation(value));
      addSummary(reported?'已报单':'待报单',reported?'complete':'future');
      addSummary(allReceived?'已收货':hasException?'已拒收':transporting?'运输中':'待运输',allReceived||hasException?'complete':transporting?'current':'future');
      if(hasException)addSummary('待跟进','action',()=>doc.querySelector<HTMLElement>('[data-order-followup]')?.scrollIntoView({behavior:'smooth',block:'center'}));
    }
    content.replaceChildren(stageCard(value,name));
    if(value.entryState==='draft'){const form=doc.createElement('form');form.className='ob-draft';const customer=section(doc,'客户与收货资料','user-round'),grid=doc.createElement('div');grid.className='ob-field-grid';const fields:Record<string,HTMLInputElement>={};
      for(const [key,label] of Object.entries({fullName:'客户姓名',phone:'联系电话',email:'邮箱',country:'国家／地区',province:'省／州',city:'城市',street:'街道和门牌',residence:'楼栋／房号'})){const field=input(doc,label,value.draft?.fields[key]||'');field.box.name=key;fields[key]=field.box;grid.append(field.wrap);}customer.append(grid);form.append(customer);
      const products=section(doc,'商品与金额','package'),itemList=doc.createElement('div');itemList.className='ob-draft-items';const itemRows:{sku:HTMLInputElement;quantity:HTMLInputElement;price:HTMLInputElement;discount:HTMLInputElement;row:HTMLElement}[]=[];
      const addItem=(item?:DraftItem)=>{const row=doc.createElement('div');row.className='ob-draft-item';const sku=input(doc,'商品编号',item?.sku||''),quantity=input(doc,'数量',item?String(item.quantity):'1'),price=input(doc,'成交单价 AED',item?.price_fils===null||item===undefined?'':(item.price_fils/100).toFixed(2)),discount=input(doc,'单件优惠 AED',item?.discount_fils===null||item===undefined?'':(item.discount_fils/100).toFixed(2));quantity.box.type='number';quantity.box.min='1';quantity.box.step='1';const remove=button(doc,'移除','btn');remove.onclick=()=>{row.remove();const at=itemRows.findIndex(value=>value.row===row);if(at>=0)itemRows.splice(at,1);};row.append(sku.wrap,quantity.wrap,price.wrap,discount.wrap,remove);itemList.append(row);itemRows.push({sku:sku.box,quantity:quantity.box,price:price.box,discount:discount.box,row});};
      for(const item of value.draft?.items||[])addItem(item);products.append(itemList);const add=button(doc,'添加商品','btn');add.onclick=()=>addItem();products.append(add);form.append(products);
      const actions=doc.createElement('div');actions.className='ob-actions';const save=button(doc,'保存草稿','btn primary'),result=doc.createElement('output');save.type='submit';result.className='ob-feedback';result.setAttribute('aria-live','polite');actions.append(save,result);form.append(actions);content.append(form,profitCard(value));
      form.onsubmit=async event=>{event.preventDefault();save.disabled=true;result.textContent='正在保存…';try{const fieldsPayload=Object.fromEntries(Object.entries(fields).map(([key,element])=>[key,element.value.trim()]));const items=itemRows.map(row=>({sku:row.sku.value.trim(),quantity:Number(row.quantity.value),price:row.price.value.trim(),discount:row.discount.value.trim()}));const updated=await call<Detail>('saveDraft',{orderId:value.id,revision:value.draftRevision,fields:fieldsPayload,items});if(!closed)render(updated);}catch(error){result.textContent=(error as Error).message;save.disabled=false;}};
    }else{
      const pair=doc.createElement('div');pair.className='od-two-cards ob-detail-pair';const customer=section(doc,'客户信息','user-round'),grid=doc.createElement('div');grid.className='od-fields ob-read-grid';for(const [label,data,wide] of [['客户姓名',name,false],['联系电话',phone,false],['邮箱',value.customer.email,false],['国家／地区',value.customer.country,false],['省／州',value.customer.province,false],['城市',value.customer.city,false],['详细收货地址',[value.customer.street,value.customer.residence].filter(Boolean).join(' · '),true]] as [string,unknown,boolean][]){const field=doc.createElement('div');field.className=`od-field${wide?' od-field-wide':''}`;const key=doc.createElement('span'),text=doc.createElement('span');key.className='od-field-label';text.className='od-field-value';key.textContent=label;text.textContent=plain(data);field.append(key,text);grid.append(field);}customer.append(grid);
      const editPhone=button(doc,'','od-text-button cursor-interaction');editPhone.replaceChildren(lucide(doc,'pencil'),doc.createTextNode('核对电话'));customer.querySelector('.od-card-head')!.append(editPhone);editPhone.onclick=()=>{const dialog=doc.createElement('dialog');dialog.className='shared-dialog ob-phone-dialog';const title=doc.createElement('h2');title.textContent='更正订单联系电话';const phoneInput=input(doc,'完整电话（含国家区号）',phone||'');const reason=input(doc,'修改依据或备注');const output=doc.createElement('output');output.className='ob-feedback';const actions=doc.createElement('footer'),cancel=button(doc,'取消','btn'),save=button(doc,'保存更正','btn primary');cancel.onclick=()=>dialog.close();save.onclick=async()=>{save.disabled=true;try{const updated=await call<Detail>('updateRecipient',{orderId:value.id,field:'phone',value:phoneInput.box.value.trim(),reason:reason.box.value.trim()});dialog.close();if(!closed)render(updated);}catch(error){output.textContent=(error as Error).message;save.disabled=false;}};actions.append(cancel,save);dialog.append(title,note(doc,'仅在核对真实资料后更正。原始导入记录仍保留。'),phoneInput.wrap,reason.wrap,output,actions);root.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();};
      const products=section(doc,'商品与金额','package');const productList=doc.createElement('div');productList.className='ob-order-products';if(!value.items.length)productList.append(note(doc,'该订单没有商品明细。'));for(const item of value.items){const row=doc.createElement('div');row.className='od-product ob-order-product';const picture=doc.createElement('span');picture.className='od-product-image';picture.append(lucide(doc,'box'));const copy=doc.createElement('div');const title=doc.createElement('div');title.className='od-product-name';title.textContent=plain(item.businessCode);const itemDetail=doc.createElement('div');itemDetail.className='od-product-meta';itemDetail.textContent=`${plain(item.productName)} · 成本 ${money(item.costFils)}`;copy.append(title,itemDetail);const quantity=doc.createElement('span');quantity.className='od-qty';quantity.textContent=`× ${item.quantity}`;const price=doc.createElement('span');price.className='od-price';price.textContent=money(item.unitActualPriceFils);row.append(picture,copy,quantity,price);productList.append(row);}products.append(productList);const total=doc.createElement('div');total.className='od-total';const totalLabel=doc.createElement('span');totalLabel.textContent='订单商品合计';const totalValue=doc.createElement('strong');totalValue.textContent=money(value.amounts.orderTotal);total.append(totalLabel,totalValue);products.append(total);const shipping=doc.createElement('div');shipping.className='ob-shipping-total';shipping.textContent=`客户运费：${money(value.amounts.customerShippingFee)}`;products.append(shipping);pair.append(customer,products);content.append(pair);
      const delivery=section(doc,'配送与包裹','map-pinned'),deliveryBody=doc.createElement('div');deliveryBody.className='od-delivery ob-delivery';const map=doc.createElement('div');map.className='od-map';const pin=doc.createElement('span');pin.append(lucide(doc,'map-pin'));map.append(pin);const deliveryCopy=doc.createElement('div');const location=doc.createElement('strong');location.textContent=[value.customer.city,value.customer.province,value.customer.country].filter(Boolean).join(' · ')||'地址待补全';const address=doc.createElement('p');address.textContent=[value.customer.street,value.customer.residence].filter(Boolean).join(' · ')||'尚未提供详细收货地址。';const deliveryState=doc.createElement('span');deliveryState.className='od-delivery-state';deliveryState.append(lucide(doc,value.packages.length?'circle-check':'clock-3'),doc.createTextNode(value.packages.length?`已有 ${value.packages.length} 个包裹记录`:'暂无包裹记录，待核对'));deliveryCopy.append(location,address,deliveryState);
      const packages=doc.createElement('div');packages.className='ob-package-list';const operationFeedback=doc.createElement('output');operationFeedback.className='ob-feedback';operationFeedback.setAttribute('aria-live','polite');
      const showDialog=(titleText:string,message:string,onConfirm:()=>Promise<Detail>,fields:HTMLElement[]=[] )=>{const dialog=doc.createElement('dialog');dialog.className='shared-dialog ob-fulfillment-dialog';const title=doc.createElement('h2');title.textContent=titleText;const result=doc.createElement('output');result.className='ob-feedback';result.setAttribute('aria-live','polite');const footer=doc.createElement('footer'),cancel=button(doc,'取消','btn'),confirm=button(doc,'确认','btn primary');cancel.onclick=()=>dialog.close();confirm.onclick=async()=>{confirm.disabled=true;result.textContent='正在保存…';try{const updated=await onConfirm();dialog.close();if(!closed)render(updated);}catch(error){result.textContent=(error as Error).message;confirm.disabled=false;}};footer.append(cancel,confirm);dialog.append(title,note(doc,message),...fields,result,footer);root.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();};
      const updateStatus=async(parcel:DetailPackage,next:string)=>{operationFeedback.textContent='正在更新包裹状态…';try{const updated=await call<Detail>('updatePackageStatus',{packageId:parcel.id,status:next});if(!closed)render(updated);}catch(error){operationFeedback.textContent=(error as Error).message;}};
      const feeDialog=(parcel:DetailPackage)=>{const amount=input(doc,'实际物流费（AED）',parcel.shippingFeeFils===null?'':(parcel.shippingFeeFils/100).toFixed(2)),reason=input(doc,parcel.shippingFeeConfirmed?'更正来源或原因（必填）':'费用来源或备注（选填）',parcel.feeNote||'');amount.box.inputMode='decimal';showDialog(parcel.shippingFeeConfirmed?'更正实际物流费':'登记实际物流费','只登记本机核对过的物流实际费用，不会写入外部平台。',()=>call<Detail>('confirmPackageFee',{packageId:parcel.id,amountAed:amount.box.value.trim(),reason:reason.box.value.trim()}),[amount.wrap,reason.wrap]);};
      for(const parcel of value.packages){const row=doc.createElement('div');row.className='ob-package-row';const copy=doc.createElement('div');copy.className='ob-package-copy';const label=doc.createElement('strong');label.textContent=plain(parcel.seriesCode);const state=doc.createElement('span');state.textContent=`${parcelStatusLabel(parcel.status)} · 实际物流费 ${parcel.shippingFeeConfirmed?money(parcel.shippingFeeFils):'待登记'}`;copy.append(label,state);const actions=doc.createElement('div');actions.className='ob-package-actions';const action=(text:string,handler:()=>void)=>{const control=button(doc,text,'btn ob-package-action');control.onclick=handler;actions.append(control);};if(parcel.status==='unshipped')action('标记出库中',()=>void updateStatus(parcel,'outbound_processing'));else if(parcel.status==='outbound_processing')action('标记运输中',()=>void updateStatus(parcel,'shipped_pending'));else if(parcel.status==='shipped_pending'){action('确认已收货',()=>showDialog('确认已收货','请仅在客户已确认收货后继续。本机包裹状态将改为“已签收”，不会写入 ShopPlus 或发送外部消息。',()=>call<Detail>('updatePackageStatus',{packageId:parcel.id,status:'signed'})));action('登记拒收／拒单',()=>{const reason=input(doc,'拒收／拒单原因（必填）');showDialog('登记拒收／拒单','请仅在已核对客户明确拒收、拒单或无法继续配送时登记。本机包裹状态将改为“已拒收”，不会发送外部消息。',()=>call<Detail>('updatePackageStatus',{packageId:parcel.id,status:'refused',note:reason.box.value.trim()}),[reason.wrap]);});}else if(['signed','refused','cancelled_after_outbound'].includes(parcel.status))action(parcel.shippingFeeConfirmed?'更正实际物流费':'登记实际物流费',()=>feeDialog(parcel));row.append(copy,actions);packages.append(row);}
      deliveryCopy.append(packages,operationFeedback);deliveryBody.append(map,deliveryCopy);delivery.append(deliveryBody);content.append(delivery);
      if(value.packages.some(parcel=>['refused','unreachable','cancelled_after_outbound'].includes(parcel.status))){const followup=section(doc,'待跟进','message-circle-more');followup.classList.add('ob-followup-card');followup.dataset.orderFollowup='true';const summary=note(doc,'此处只安排本机提醒，不会向客户发送消息、赠品资料或新货通知。请在实际处理后再自行完成联系或发送。');const scheduleState=doc.createElement('p');scheduleState.className='ob-followup-state';scheduleState.textContent='正在读取本机跟进安排…';const actions=doc.createElement('div');actions.className='ob-followup-actions';
        const openFollowup=(kind:string)=>{const dialog=doc.createElement('dialog');dialog.className='shared-dialog ob-fulfillment-dialog';const title=doc.createElement('h2');title.textContent=`安排${kind}`;const at=input(doc,'下次跟进时间',new Date(Date.now()+86400000).toISOString().slice(0,16));at.box.type='datetime-local';const detailNote=input(doc,'跟进备注或依据（必填）',kind);const result=doc.createElement('output');result.className='ob-feedback';result.setAttribute('aria-live','polite');const footer=doc.createElement('footer'),cancel=button(doc,'取消','btn'),save=button(doc,'保存本机提醒','btn primary');cancel.onclick=()=>dialog.close();save.onclick=async()=>{save.disabled=true;result.textContent='正在保存提醒…';try{const workflow=await call<AssistantWorkflow>('assistantWorkflow',{orderId:value.id});const updated=await call<AssistantWorkflow>('saveAssistantStage',{orderId:value.id,revision:workflow.stageState.revision,action:'followup',at:at.box.value,note:detailNote.box.value.trim()}),due=updated.stageState.values.nextFollowUpAt; scheduleState.textContent=due?`已安排下次跟进：${due.slice(0,16).replace('T',' ')} · ${detailNote.box.value.trim()}`:'已保存本机跟进安排。';dialog.close();}catch(error){result.textContent=(error as Error).message;save.disabled=false;}};footer.append(cancel,save);dialog.append(title,note(doc,'保存后只在本机记录提醒时间和依据；不会自动联系客户或触发任何外部操作。'),at.wrap,detailNote.wrap,result,footer);root.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();};
        for(const kind of ['拒单询问','赠品资料发送','新货到店提醒','自定义跟进']){const control=button(doc,kind,'btn ob-followup-action');control.onclick=()=>openFollowup(kind);actions.append(control);}followup.append(summary,scheduleState,actions);content.append(followup);void call<AssistantWorkflow>('assistantWorkflow',{orderId:value.id}).then(workflow=>{if(closed||!followup.isConnected)return;const due=workflow.stageState.values.nextFollowUpAt;const last=workflow.stageState.values.history?.at(-1);scheduleState.textContent=due?`已安排下次跟进：${due.slice(0,16).replace('T',' ')}${last?.note?` · ${last.note}`:''}`:'尚未安排本机跟进提醒。';}).catch(error=>{if(!closed&&followup.isConnected)scheduleState.textContent=`无法读取跟进安排：${(error as Error).message}`;});}
      if(value.packages.some(parcel=>parcel.status==='signed')){const settlement=section(doc,'收货与结算','badge-dollar-sign');settlement.classList.add('ob-settlement-card');const remittance=value.remittance;const summary=doc.createElement('p');summary.className='ob-note';summary.textContent=remittance?.status==='received'&&remittance.amountFils!==null?`已登记净回款：${cny(remittance.amountFils)} · ${shortDate(remittance.registeredAt)}`:'已有已签收包裹，可在收到款项后登记本机净回款。';const action=button(doc,remittance?.status==='received'?'已登记净回款':'登记净回款','btn primary ob-settlement-action');action.disabled=remittance?.status==='received';action.onclick=()=>{const amount=input(doc,'净回款（CNY）'),date=input(doc,'回款日期',new Date().toISOString().slice(0,10));date.box.type='date';amount.box.inputMode='decimal';showDialog('登记净回款','只记录本机收到的人民币净回款与日期，不会写入外部平台。',()=>call<Detail>('recordRemittance',{orderId:value.id,amountCny:amount.box.value.trim(),registeredAt:date.box.value}),[amount.wrap,date.wrap]);};settlement.append(summary,action);content.append(settlement);}
      content.append(profitCard(value));
    }
    refreshIcons();
  };
  void call<Detail|null>('detail',orderId).then(value=>{if(closed)return;if(!value){content.replaceChildren(note(doc,'找不到所选订单，请返回订单管理重新选择。'));return;}render(value);}).catch(error=>{if(!closed)content.replaceChildren(note(doc,(error as Error).message));});
  return ()=>{closed=true;};
}
