type Response<T>={ok:boolean;data?:T;error?:{message?:string}};
type OrderRow={id:string;orderNo:string;sequence:number;source:string;workflowStatus:string;trackingStatus:string;customerName:string;phone:string;createdAt:string;updatedAt:string;amountFils:number|null;products:{code:string;quantity:number}[];itemCount:number;needsReview:boolean};
type PreviewItem={sourceRow:number;businessCode:string|null;productName:string;quantity:number;costFils:number|null;needsReview:boolean};
type PreviewOrder={orderNo:string|null;phoneMasked:string;items:PreviewItem[];canImport:boolean;alreadyExists:boolean;needsReview:boolean;reviewConfirmed:boolean;warnings:{code:string}[];blockingErrors:{code:string}[];amountCheck?:{amountMismatch?:boolean;discountNeedsConfirmation?:boolean}};
type ImportPreview={token:string;filename:string;alreadyImportedFile:boolean;summary:{validOrders:number;directImportOrders:number;reviewOrders:number;blockedOrders:number;existingOrders:number;blockingErrors:number};orders:PreviewOrder[]};
type DraftItem={sku:string;quantity:number;price_fils:number|null;discount_fils:number|null};
type Detail={id:string;orderNo:string|null;sequence:number;source:string;entryState:string;draftRevision:number;trackingStatus:string;orderStatus:string;amounts:{orderTotal:number|null;customerShippingFee:number|null};customer:{fullName:string|null;firstName:string|null;lastName:string|null;phone:string|null;email:string|null;country:string|null;province:string|null;city:string|null;street:string|null;residence:string|null};draft?:{fields:Record<string,string|null>;items:DraftItem[]}|null;items:{businessCode:string;productName:string;quantity:number;unitActualPriceFils:number|null;costFils:number|null;lineRevenueFils:number|null}[];packages:{seriesCode:string;status:string;shippingFeeFils:number|null}[]};
type ShopPlusState={configured:boolean;test:{status:'verified'|'failed';at:string;message:string}|null;sync:{lastSuccessfulAt:string|null;lastFetchedAt:string|null;lastImported:number;lastExisting:number;lastBlocked:number;truncated:boolean}};
type ShopPlusSync={result:{fetched:number;imported:number;existing:number;blocked:number;lastSuccessfulAt:string;truncated:boolean};response:{pages:number;totalCount:number|null;truncated:boolean};status:ShopPlusState};

const money=(fils:number|null|undefined)=>fils===null||fils===undefined?'待核对':`AED ${(fils/100).toFixed(2)}`;
const plain=(value:unknown)=>String(value??'').trim()||'—';
const input=(doc:Document,label:string,value='')=>{const wrap=doc.createElement('label');wrap.className='ob-field';const name=doc.createElement('span');name.textContent=label;const box=doc.createElement('input');box.value=value;wrap.append(name,box);return {wrap,box};};
const button=(doc:Document,label:string,className='btn')=>{const element=doc.createElement('button');element.type='button';element.className=className;element.textContent=label;return element;};
const note=(doc:Document,message:string)=>{const item=doc.createElement('p');item.className='ob-note';item.textContent=message;return item;};
const lucide=(doc:Document,name:string)=>{const icon=doc.createElement('i');icon.dataset.lucide=name;icon.setAttribute('aria-hidden','true');return icon;};
const section=(doc:Document,title:string,iconName?:string)=>{const item=doc.createElement('section');item.className='od-card ob-card';const bar=doc.createElement('div');bar.className='od-card-head';const head=doc.createElement('h2');head.className='od-card-title';if(iconName)head.append(lucide(doc,iconName));head.append(title);bar.append(head);item.append(bar);return item;};
function workbenchStatus(row:OrderRow){
  if(row.workflowStatus==='draft')return {label:'草稿',className:'cw-info',icon:'file-pen-line'};
  if(row.workflowStatus==='pending')return {label:'待确认',className:'cw-confirm',icon:'clipboard-check'};
  const states:Record<string,{label:string;className:string;icon:string}>={
    unshipped:{label:'待发货',className:'cw-confirm',icon:'package'},
    awaiting_report:{label:'待报单',className:'cw-info',icon:'clipboard-list'},
    outbound_processing:{label:'出库中',className:'cw-confirm',icon:'package-check'},
    shipped_pending:{label:'运输中',className:'cw-follow',icon:'truck'},
    signed:{label:'已签收',className:'cw-follow',icon:'badge-check'},
    refused:{label:'已拒收',className:'cw-info',icon:'circle-alert'},
    unreachable:{label:'联系不上',className:'cw-info',icon:'phone-off'},
    cancelled_before_outbound:{label:'已取消',className:'cw-info',icon:'circle-x'},
    cancelled_after_outbound:{label:'已取消',className:'cw-info',icon:'circle-x'}
  };
  return states[row.trackingStatus]||{label:'状态待核对',className:'cw-info',icon:'circle-help'};
}
async function call<T>(name:string,...args:unknown[]):Promise<T>{
  const method=window.inventoryApp?.orders?.[name];if(!method)throw new Error('订单服务尚未就绪，请从桌面 App 重新打开');
  const result=await method(...args) as Response<T>;
  if(!result.ok)throw new Error(result.error?.message||'订单操作失败');
  return result.data as T;
}

export function installWorkbenchOrders(doc:Document,{selectOrder,selectedOrderId}:{selectOrder:(id:string)=>void;selectedOrderId?:string|null}):()=>void{
  const root=doc.querySelector<HTMLElement>('#chat-workbench-aligned')!,list=root.querySelector<HTMLElement>('#cw-task-list')!,count=root.querySelector<HTMLElement>('#cw-result-count')!;
  const title=root.querySelector<HTMLElement>('#cw-queue-title');if(title)title.textContent='近期订单';
  let closed=false,filter='all',rows:OrderRow[]=[],selectedId=selectedOrderId||'';
  const render=()=>{
    if(closed)return;
    for(const [kind,predicate,label] of [
      ['info',(row:OrderRow)=>row.workflowStatus==='draft','待补资料'],
      ['confirm',(row:OrderRow)=>row.workflowStatus==='pending','待确认']
    ] as const){const stat=root.querySelector<HTMLElement>(`.cw-stat[data-filter="${kind}"]`);if(!stat)continue;const amount=rows.filter(predicate).length;stat.querySelector<HTMLElement>('.cw-stat-value')!.textContent=String(amount);stat.querySelector<HTMLElement>('.cw-stat-note')!.textContent=amount?`${amount} 个真实订单`:`暂无${label}订单`;}
    const attention=root.querySelector<HTMLElement>('.cw-tab[data-filter="attention"]');if(attention){const label=doc.createElement('span'),badge=doc.createElement('span');label.textContent='需注意';badge.className='cw-attention-count';badge.textContent=String(rows.filter(row=>row.needsReview).length);attention.replaceChildren(label,badge);}
    const visible=rows.filter(row=>filter==='all'||filter==='info'&&row.workflowStatus==='draft'||filter==='confirm'&&row.workflowStatus==='pending'||filter==='attention'&&row.needsReview||filter==='follow'&&row.trackingStatus==='shipped_pending');
    count.textContent=`${visible.length} 项`;list.replaceChildren();
    if(!visible.length){const empty=doc.createElement('div');empty.className='cw-empty';empty.textContent=rows.length?'当前筛选没有订单':'暂无真实订单。可以导入 ShopPlus 文件，或新建空白订单。';list.append(empty);return;}
    for(const row of visible){const article=doc.createElement('article');article.className='cw-task-row';article.dataset.orderId=row.id;article.dataset.selected=String(row.id===selectedId);
      const main=button(doc,'','cw-row-main cursor-interaction');main.setAttribute('aria-label',`选择${row.orderNo}订单`);main.setAttribute('aria-pressed',String(row.id===selectedId));main.onclick=()=>{selectedId=row.id;selectOrder(row.id);for(const card of list.querySelectorAll<HTMLElement>('.cw-task-row')){const selected=card.dataset.orderId===row.id;card.dataset.selected=String(selected);card.querySelector<HTMLButtonElement>('.cw-row-main')?.setAttribute('aria-pressed',String(selected));}};
      const person=doc.createElement('span');person.className='cw-row-person';const avatar=doc.createElement('span');avatar.className='cw-avatar';avatar.textContent=row.customerName?.[0]||'?';const copy=doc.createElement('span');copy.className='cw-person-copy';const phoneLine=doc.createElement('span');phoneLine.className='cw-phone-line';const phone=doc.createElement('span');phone.className='cw-phone-number';phone.textContent=plain(row.phone);phoneLine.append(phone);const ref=doc.createElement('span');ref.className='cw-order-ref';ref.textContent=row.orderNo;copy.append(phoneLine,ref);person.append(avatar,copy);
      const message=doc.createElement('span');message.className='cw-row-message';const heading=doc.createElement('span');heading.className='cw-message-title';heading.textContent=row.customerName||'客户资料待补';const body=doc.createElement('span');body.className='cw-message-preview';body.textContent=row.products.length?row.products.map(p=>`${p.code} × ${p.quantity}`).join('，'):'商品待补';const source=doc.createElement('span'),sourceIcon=doc.createElement('i');source.className='cw-source';sourceIcon.dataset.lucide=row.source==='manual'?'pen-line':'file-up';source.append(sourceIcon,doc.createTextNode(row.source==='manual'?'手动新建':'ShopPlus 导入'));message.append(heading,body,source);
      const state=doc.createElement('span');state.className='cw-row-status';const status=workbenchStatus(row),badge=doc.createElement('span'),badgeIcon=doc.createElement('i');badge.className=`cw-status-pill ${status.className}`;badgeIcon.dataset.lucide=status.icon;badge.append(badgeIcon,doc.createTextNode(status.label));const time=doc.createElement('span');time.className='cw-status-time';time.textContent=plain(row.updatedAt).slice(0,16);state.append(badge,time);main.append(person,message,state);
      const actions=doc.createElement('span');actions.className='cw-row-actions';const detail=button(doc,'订单详情','cw-open cw-detail cursor-interaction');detail.dataset.openOrderDetail='';actions.append(detail);article.append(main,actions);list.append(article);
    }
    (doc.defaultView as (Window&{lucide?:{createIcons:(options:{nodes:Element[]})=>void}})|null)?.lucide?.createIcons({nodes:[list]});
  };
  const choose=(event:Event)=>{const target=(event.target as Element).closest<HTMLElement>('[data-filter]');if(!target||!root.contains(target))return;event.preventDefault();event.stopImmediatePropagation();filter=target.dataset.filter||'all';for(const tab of root.querySelectorAll<HTMLElement>('.cw-tab'))tab.setAttribute('aria-selected',String(tab.dataset.filter===filter));for(const stat of root.querySelectorAll<HTMLElement>('.cw-stat'))stat.setAttribute('aria-pressed',String(stat.dataset.filter===filter));render();};
  root.addEventListener('click',choose,true);
  void call<OrderRow[]>('list',{sort:'newest'}).then(value=>{rows=value;render();}).catch(error=>{if(!closed){list.replaceChildren(note(doc,(error as Error).message));count.textContent='读取失败';}});
  return ()=>{closed=true;root.removeEventListener('click',choose,true);};
}

export function installOrdersPage(doc:Document,{openOrder,initialAction}:{openOrder:(id:string)=>void;initialAction?:'import'|'new'}):()=>void{
  const root=doc.querySelector<HTMLElement>('#ui040')!,main=root.querySelector<HTMLElement>('.main')!,head=main.querySelector<HTMLElement>('.head')!;
  const connection=root.querySelector<HTMLElement>('.wa');if(connection){connection.textContent='○ WhatsApp · 订单聊天待核对';connection.style.color='#747080';}
  main.replaceChildren(head);
  root.querySelector('#u40-import-dialog')?.remove();root.querySelector('#u40-row-menu')?.remove();root.querySelector('#u40-popover')?.remove();
  const originalImport=head.querySelector<HTMLButtonElement>('#u40-import')!;
  const importButton=originalImport.cloneNode(true) as HTMLButtonElement;
  originalImport.replaceWith(importButton);
  const pageSettings=root.querySelector<HTMLButtonElement>('.up-settings'),layoutDialog=root.querySelector<HTMLDialogElement>('.shared-dialog');
  pageSettings?.remove();
  const layoutApply=layoutDialog?.querySelector<HTMLButtonElement>('[data-close]');if(layoutApply)layoutApply.textContent='应用';
  const title=head.querySelector<HTMLElement>('h1')!,titleRow=doc.createElement('span');titleRow.className='ob-title-row';
  const info=doc.createElement('button');info.type='button';info.className='ob-title-info';info.setAttribute('aria-label','订单管理说明与布局设置');info.textContent='?';
  title.replaceWith(titleRow);titleRow.append(title,info);
  info.onclick=()=>{if(layoutDialog){layoutDialog.querySelector('p')!.textContent='导入、查找和管理订单，以及维护聊单用户档案。可在此调整并应用本屏幕的导航与内容布局。';layoutDialog.showModal();}};
  const workspace=doc.createElement('section');workspace.className='ob-orders';
  workspace.innerHTML='<div class="ob-toolbar"><label>查找订单 <input class="ob-search" type="search" placeholder="订单编号、客户电话或商品编号"></label><label>下单日期 <span class="ob-date-range"><input class="ob-date-from" type="date" aria-label="开始日期"><span>至</span><input class="ob-date-to" type="date" aria-label="结束日期"></span></label><label>订单状态 <select class="ob-status"><option value="all">全部</option><option value="draft">草稿</option><option value="unshipped">待发货</option><option value="shipped_pending">运输中</option><option value="signed">已签收</option></select></label><span class="ob-count" role="status">正在读取订单…</span></div><div class="table-wrap"><table><thead><tr><th class="ob-sequence-head">序号</th><th>下单日期</th><th>订单编号</th><th>客户</th><th>商品</th><th>订单总金额</th><th>来源</th><th>状态</th><th>操作</th></tr></thead><tbody class="ob-rows"></tbody></table></div><nav class="ob-pagination" aria-label="订单分页"></nav><p class="ob-feedback" role="status" aria-live="polite"></p>';
  main.append(workspace);
  const search=workspace.querySelector<HTMLInputElement>('.ob-search')!,dateFrom=workspace.querySelector<HTMLInputElement>('.ob-date-from')!,dateTo=workspace.querySelector<HTMLInputElement>('.ob-date-to')!,status=workspace.querySelector<HTMLSelectElement>('.ob-status')!,rows=workspace.querySelector<HTMLElement>('.ob-rows')!,count=workspace.querySelector<HTMLElement>('.ob-count')!,pagination=workspace.querySelector<HTMLElement>('.ob-pagination')!,feedback=workspace.querySelector<HTMLElement>('.ob-feedback')!;
  const pageSize=10;let all:OrderRow[]=[],page=1,closed=false,preview:ImportPreview|undefined;
  const show=(message:string)=>{feedback.textContent=message;};
  const render=()=>{
    const query=search.value.trim().toLowerCase(),filtered=all.filter(row=>{const day=plain(row.createdAt).slice(0,10);return (status.value==='all'||status.value==='draft'&&row.workflowStatus==='draft'||status.value!=='draft'&&row.trackingStatus===status.value)&&(!dateFrom.value||day>=dateFrom.value)&&(!dateTo.value||day<=dateTo.value)&&(!query||[row.orderNo,row.phone,row.customerName,...row.products.map(p=>p.code)].some(value=>String(value||'').toLowerCase().includes(query)));});
    const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,totalPages);const visible=filtered.slice((page-1)*pageSize,page*pageSize);
    count.textContent=`共 ${filtered.length} 个订单`;rows.replaceChildren();pagination.replaceChildren();
    if(!filtered.length){const tr=doc.createElement('tr'),td=doc.createElement('td');td.colSpan=9;td.className='ob-empty';td.textContent=all.length?'没有符合条件的订单':'暂无真实订单。请从聊单工作台核对客户后新建订单，或导入 ShopPlus 文件。';tr.append(td);rows.append(tr);return;}
    for(const row of visible){const tr=doc.createElement('tr');tr.dataset.orderId=row.id;tr.style.setProperty('--ob-product-count',String(Math.max(1,row.products.length)));
      const serial=doc.createElement('td');serial.className='ob-sequence';serial.textContent=String(row.sequence);tr.append(serial);
      const date=doc.createElement('td');date.className='ob-date';const timestamp=plain(row.createdAt),dateLine=doc.createElement('b'),timeLine=doc.createElement('span');dateLine.textContent=timestamp.slice(0,10)||'—';timeLine.textContent=timestamp.slice(11,16)||'—';date.append(dateLine,timeLine);tr.append(date);
      const number=doc.createElement('td');number.className='ob-order-number';number.textContent=row.orderNo;tr.append(number);
      const customer=doc.createElement('td');customer.className='ob-customer';const phone=doc.createElement('b'),name=doc.createElement('span');phone.textContent=plain(row.phone);name.textContent=row.customerName||'资料待补';customer.append(phone,name);tr.append(customer);
      const products=doc.createElement('td');products.className='ob-products';if(row.products.length)for(const product of row.products){const line=doc.createElement('span');line.textContent=`${product.code} × ${product.quantity}`;products.append(line);}else products.textContent='待补商品';tr.append(products);
      const sourceLabel=row.source==='manual'?'聊单创建':row.source==='shopplus_api'?'ShopPlus API 同步':'文件导入';for(const value of [money(row.amountFils),sourceLabel,row.workflowStatus==='draft'?'草稿':plain(row.trackingStatus)]){const td=doc.createElement('td');td.textContent=value;tr.append(td);}
      const action=doc.createElement('td'),open=button(doc,'订单详情','detail');open.dataset.openOrderDetail='';open.onclick=()=>openOrder(row.id);action.append(open);tr.append(action);rows.append(tr);
    }
    const previous=button(doc,'上一页','ob-page-button');previous.disabled=page===1;previous.onclick=()=>{page--;render();};const indicator=doc.createElement('span');indicator.textContent=`第 ${page} / ${totalPages} 页`;const next=button(doc,'下一页','ob-page-button');next.disabled=page===totalPages;next.onclick=()=>{page++;render();};pagination.append(previous,indicator,next);
  };
  const refresh=async()=>{try{all=await call<OrderRow[]>('list',{sort:'newest'});if(!closed)render();}catch(error){if(!closed)show((error as Error).message);}};
  const resetPage=()=>{page=1;render();};search.oninput=resetPage;status.onchange=resetPage;dateFrom.onchange=resetPage;dateTo.onchange=resetPage;
  importButton.textContent='从文件导入';
  const apiStatus=doc.createElement('button'),syncButton=doc.createElement('button');apiStatus.type='button';apiStatus.className='ob-api-status';apiStatus.setAttribute('aria-label','ShopPlus 连接与同步状态');syncButton.type='button';syncButton.className='ob-sync-button';syncButton.textContent='同步最新订单';const actions=head.querySelector<HTMLElement>('.head-actions')!;actions.prepend(syncButton);actions.prepend(apiStatus);
  let shopPlus:ShopPlusState|undefined,shopPlusNotice='';
  const syncDialog=doc.createElement('dialog');syncDialog.className='shared-dialog ob-sync';root.append(syncDialog);
  const displayTime=(value:string|null|undefined)=>value?value.replace('T',' ').slice(0,16):'尚未同步';
  const readableShopPlusError=(error:unknown)=>{const message=(error as Error)?.message||'ShopPlus 同步失败';return /UNIQUE constraint failed:\s*order_items\.shopplus_sub_order_id/i.test(message)?'ShopPlus 返回的商品编号在不同订单中重复。本版本会自动按订单区分；请关闭弹窗后再次同步。':message;};
  const refreshShopPlusStatus=async()=>{try{shopPlus=await call<ShopPlusState>('shopPlusStatus');const verified=shopPlus.test?.status==='verified';apiStatus.classList.toggle('is-connected',verified);apiStatus.classList.toggle('is-failed',shopPlus.test?.status==='failed');apiStatus.textContent=verified?'ShopPlus 已连接':shopPlus.configured?'ShopPlus 待验证':'ShopPlus 未配置';apiStatus.title=verified?`${shopPlus.test?.message||'已验证'}；最近同步：${displayTime(shopPlus.sync.lastSuccessfulAt)}`:shopPlus.test?.message||'配置 ShopPlus App Key 和 API Secret 后即可同步订单';}catch{apiStatus.classList.remove('is-connected','is-failed');apiStatus.textContent='ShopPlus 状态不可读取';apiStatus.title='暂时无法读取 ShopPlus 状态';}};
  const renderSyncDialog=()=>{
    const state=shopPlus;syncDialog.replaceChildren();const heading=doc.createElement('h2');heading.textContent='同步 ShopPlus 订单';const lead=note(doc,'从店铺后台只读获取订单，写入本机订单管理。相同订单号会跳过，不会覆盖本地订单或修改网站后台。');const card=doc.createElement('section');card.className='ob-sync-status';const stateName=doc.createElement('strong'),stateDetail=doc.createElement('span');const verified=state?.test?.status==='verified';stateName.textContent=verified?'ShopPlus 已连接':state?.configured?'ShopPlus 待验证':'尚未配置 ShopPlus API';stateDetail.textContent=verified?`${state?.test?.message||'最近一次接口验证通过'} · 最近同步 ${displayTime(state?.sync.lastSuccessfulAt)}`:state?.test?.message||'请先安全录入 App Key 和 API Secret。';card.append(stateName,stateDetail);
    const result=doc.createElement('p');result.className='ob-feedback';result.setAttribute('aria-live','polite');result.textContent=shopPlusNotice;const footer=doc.createElement('footer'),close=button(doc,'关闭','btn'),configure=button(doc,state?.configured?'更新 ShopPlus API':'配置 ShopPlus API','btn'),run=button(doc,'同步最新订单','btn primary'),file=button(doc,'从文件导入','btn');close.onclick=()=>syncDialog.close();configure.onclick=async()=>{configure.disabled=true;result.textContent='请在系统安全输入窗口依次录入 App Key 和 API Secret…';try{const response=await call<{canceled:boolean;state:ShopPlusState}>('configureShopPlus');if(response.canceled){shopPlusNotice='已取消配置，原有凭据未改变。';renderSyncDialog();}else{shopPlus=response.state;shopPlusNotice='ShopPlus 已验证，可以开始同步。';await refreshShopPlusStatus();renderSyncDialog();}}catch(error){result.textContent=readableShopPlusError(error);await refreshShopPlusStatus();}finally{configure.disabled=false;}};run.disabled=!state?.configured;run.onclick=async()=>{run.disabled=true;configure.disabled=true;result.textContent='正在从 ShopPlus 读取最新订单…';try{const response=await call<ShopPlusSync>('syncShopPlus');shopPlus=response.status;const notice=`已读取 ${response.result.fetched} 单，新加入 ${response.result.imported} 单，重复跳过 ${response.result.existing} 单${response.result.blocked?`，待核对跳过 ${response.result.blocked} 单`:''}。`;shopPlusNotice=response.result.truncated?`${notice} 本次最多读取 1000 单，请再次同步继续获取。`:notice;show(shopPlusNotice);await refresh();await refreshShopPlusStatus();renderSyncDialog();}catch(error){result.textContent=readableShopPlusError(error);await refreshShopPlusStatus();run.disabled=false;configure.disabled=false;}};file.onclick=()=>{syncDialog.close();importButton.click();};footer.append(close,file,configure,run);syncDialog.append(heading,lead,card,result,footer);
  };
  const openSync=async()=>{await refreshShopPlusStatus();renderSyncDialog();if(!syncDialog.open)syncDialog.showModal();};apiStatus.onclick=()=>void openSync();syncButton.onclick=()=>void openSync();void refreshShopPlusStatus();

  const dialog=doc.createElement('dialog');dialog.className='shared-dialog ob-import';root.append(dialog);
  const renderPreview=()=>{
    if(!preview)return;
    dialog.replaceChildren();const title=doc.createElement('h2');title.textContent=`导入预览 · ${preview.filename}`;dialog.append(title);
    dialog.append(note(doc,`识别 ${preview.summary.validOrders} 单；可直接导入 ${preview.summary.directImportOrders} 单；需人工核对 ${preview.summary.reviewOrders} 单；重复 ${preview.summary.existingOrders} 单；阻断 ${preview.summary.blockedOrders} 单。`));
    if(preview.alreadyImportedFile)dialog.append(note(doc,'这个文件此前已导入。已有订单会自动跳过，请核对后再决定是否提交。'));
    const list=doc.createElement('div');list.className='ob-preview-list';
    for(const order of preview.orders){const card=doc.createElement('section');card.className='ob-preview-order';
      const h=doc.createElement('h3');h.textContent=`${plain(order.orderNo)} · ${plain(order.phoneMasked)}`;card.append(h);
      card.append(note(doc,order.alreadyExists?'已存在，将跳过':!order.canImport?`不能导入：${order.blockingErrors.map(e=>e.code).join('、')}`:order.reviewConfirmed?'已人工核对':order.needsReview?'需要人工核对商品、状态或金额':'可直接导入'));
      if(order.canImport&&order.needsReview){const itemInputs:{sourceRow:number;code:HTMLInputElement;cost:HTMLInputElement}[]=[];
        for(const item of order.items){const row=doc.createElement('div');row.className='ob-review-row';const label=doc.createElement('span');label.textContent=`第 ${item.sourceRow} 行 · ${plain(item.productName)} × ${item.quantity}`;const code=input(doc,'商品编号',item.businessCode||'');const cost=input(doc,'成本 AED',item.costFils===null?'':(item.costFils/100).toFixed(2));row.append(label,code.wrap,cost.wrap);card.append(row);itemInputs.push({sourceRow:item.sourceRow,code:code.box,cost:cost.box});}
        const missing=doc.createElement('label'),missingCheck=doc.createElement('input');missingCheck.type='checkbox';missing.append(missingCheck,' 允许暂缺成本，利润保持待核对');card.append(missing);
        const discount=doc.createElement('label'),discountCheck=doc.createElement('input');discountCheck.type='checkbox';discount.append(discountCheck,' 已核对优惠与订单金额');card.append(discount);
        const confirm=button(doc,order.reviewConfirmed?'重新核对本单':'确认本单资料','btn');confirm.onclick=async()=>{confirm.disabled=true;try{preview=await call<ImportPreview>('reviewImport',{token:preview!.token,orderNo:order.orderNo,items:itemInputs.map(item=>({sourceRow:item.sourceRow,...(item.code.value.trim()?{businessCode:item.code.value.trim()}:{}),...(item.cost.value.trim()?{costAed:item.cost.value.trim()}:{} )})),confirmed:true,missingCostConfirmed:missingCheck.checked,discountConfirmed:discountCheck.checked});renderPreview();}catch(error){const output=card.querySelector<HTMLElement>('.ob-review-error')||doc.createElement('p');output.className='ob-review-error';output.textContent=(error as Error).message;card.append(output);confirm.disabled=false;}};card.append(confirm);
      }
      list.append(card);
    }
    dialog.append(list);const footer=doc.createElement('footer');const cancel=button(doc,'取消','btn'),commit=button(doc,'确认导入','btn primary');
    cancel.onclick=()=>dialog.close();commit.disabled=preview.summary.blockingErrors>0||preview.orders.every(o=>!o.canImport)||preview.orders.some(o=>o.canImport&&!o.alreadyExists&&o.needsReview&&!o.reviewConfirmed);
    commit.onclick=async()=>{commit.disabled=true;try{const result=await call<{imported:number;skipped:number}>('commitImport',preview!.token);dialog.close();show(`已导入 ${result.imported} 单，跳过 ${result.skipped} 单。`);preview=undefined;await refresh();}catch(error){dialog.append(note(doc,(error as Error).message));commit.disabled=false;}};
    footer.append(cancel,commit);dialog.append(footer);
  };
  importButton.onclick=async()=>{importButton.disabled=true;show('正在选择文件…');try{const selection=await call<{canceled:boolean;token:string;filename:string}>('selectExcel');if(selection.canceled){show('已取消选择文件');return;}preview=await call<ImportPreview>('previewImport',selection.token);renderPreview();dialog.showModal();show('文件已预览，尚未写入订单。');}catch(error){show((error as Error).message);}finally{importButton.disabled=false;}};
  void refresh();if(initialAction==='import')queueMicrotask(()=>{if(!closed)importButton.click();});
  return ()=>{closed=true;dialog.remove();syncDialog.remove();};
}

export function installOrderDetail(doc:Document,orderId:string):()=>void{
  const root=doc.querySelector<HTMLElement>('#ui008-order-detail')!,content=root.querySelector<HTMLElement>('.od-content')!,heading=root.querySelector<HTMLElement>('.od-heading-copy h1')!,status=root.querySelector<HTMLElement>('.od-status-actions')!;
  const previewLabel=root.querySelector<HTMLElement>('.od-preview-label');if(previewLabel)previewLabel.textContent='UI-028 · 订单详情';
  let closed=false,detail:Detail|undefined;
  const trackingLabel=(value:Detail)=>{
    if(value.entryState==='draft')return '草稿';
    const states:Record<string,string>={pending:'待确认',unshipped:'待发货',awaiting_report:'待报单',outbound_processing:'出库中',shipped_pending:'运输中',signed:'已签收',refused:'已拒收',unreachable:'联系不上',cancelled_before_outbound:'已取消',cancelled_after_outbound:'已取消'};
    return states[value.trackingStatus]||states[value.orderStatus]||'状态待核对';
  };
  const sourceLabel=(value:Detail)=>value.source==='manual'?'手动新建':value.source==='shopplus_api'?'ShopPlus API 同步':'ShopPlus 文件导入';
  const refreshIcons=()=>{const view=doc.defaultView as Window&{lucide?:{createIcons:(options:{nodes:Element[]})=>void}};view.lucide?.createIcons({nodes:[content,status]});};
  const stageCard=(value:Detail,name:string)=>{
    const card=doc.createElement('section');card.className='od-card od-stage-card ob-stage-card';card.setAttribute('aria-label','订单阶段');
    const top=doc.createElement('div');top.className='od-stage-top';const current=doc.createElement('div');current.className='od-current-order';const label=doc.createElement('span');label.className='od-order-label';label.textContent='当前订单';const orderName=doc.createElement('span');orderName.className='od-order-name';orderName.textContent=value.orderNo||`草稿 #${value.sequence}`;current.append(label,orderName);const badge=doc.createElement('span');badge.className='od-badge';badge.textContent=trackingLabel(value);top.append(current,badge);card.append(top);
    const hasItems=value.entryState==='draft'?Boolean(value.draft?.items.length):value.items.length>0,hasAddress=Boolean(value.customer.phone&&value.customer.country&&value.customer.city&&(value.customer.street||value.customer.residence)),hasDelivery=value.packages.length>0||['outbound_processing','shipped_pending','signed','refused'].includes(value.trackingStatus),hasConfirmedOrder=value.entryState!=='draft';
    const facts=[hasItems,hasAddress,hasDelivery,hasConfirmedOrder],labels=['明确商品与数量','收齐收货资料','核对配送范围','客户确认订单'];let active=facts.findIndex(done=>!done);if(active<0)active=3;
    const stages=doc.createElement('div');stages.className='od-stages';stages.setAttribute('aria-label','订单推进步骤');labels.forEach((text,index)=>{const step=doc.createElement('span');step.className=`od-stage${index<active&&facts[index]?' is-done':''}${index===active?' is-current':''}`;const number=doc.createElement('span');number.className='od-stage-number';if(index<active&&facts[index])number.append(lucide(doc,'check'));else number.textContent=String(index+1);const copy=doc.createElement('span');copy.textContent=text;step.append(number,copy);stages.append(step);if(index<labels.length-1){const arrow=lucide(doc,'arrow-right');arrow.classList.add('od-stage-arrow');stages.append(arrow);}});card.append(stages);
    const objectives=['核对商品编号、数量和价格。','补全并核对客户的收货资料。','核对完整地址与配送范围。','核对订单资料并继续履约。'];const objective=doc.createElement('div');objective.className='od-objective';objective.append('当前目标：');const strong=doc.createElement('strong');strong.textContent=objectives[active];objective.append(strong);const meta=doc.createElement('span');meta.className='ob-stage-meta';meta.textContent=`${sourceLabel(value)} · ${name||'客户资料待补'} · ${money(value.amounts.orderTotal)}`;objective.append(meta);card.append(objective);return card;
  };
  const render=(value:Detail)=>{
    detail=value;heading.textContent=value.orderNo||`草稿 #${value.sequence}`;
    const name=value.customer.fullName||[value.customer.lastName,value.customer.firstName].filter(Boolean).join(' '),phone=value.customer.phone;
    const setText=(selector:string,text:string)=>{const element=root.querySelector<HTMLElement>(selector);if(element)element.textContent=text;};
    setText('.od-contact strong',phone||'未关联客户');setText('.od-contact small',`${name||'客户资料待补'} · ${heading.textContent}`);setText('.od-avatar',name?.[0]||'?');
    status.replaceChildren();status.hidden=false;const currentStatus=trackingLabel(value),statusNames=value.entryState==='draft'?['草稿']:['待确认','待报单','待收货','拒单','联系不上'];if(!statusNames.includes(currentStatus))statusNames.push(currentStatus);for(const label of statusNames){const state=button(doc,label,'od-status-button ob-status-readonly');state.setAttribute('aria-pressed',String(label===currentStatus));state.setAttribute('aria-disabled','true');state.tabIndex=-1;status.append(state);}
    content.replaceChildren(stageCard(value,name));
    if(value.entryState==='draft'){const form=doc.createElement('form');form.className='ob-draft';const customer=section(doc,'客户与收货资料','user-round'),grid=doc.createElement('div');grid.className='ob-field-grid';const fields:Record<string,HTMLInputElement>={};
      for(const [key,label] of Object.entries({fullName:'客户姓名',phone:'联系电话',email:'邮箱',country:'国家／地区',province:'省／州',city:'城市',street:'街道和门牌',residence:'楼栋／房号'})){const field=input(doc,label,value.draft?.fields[key]||'');field.box.name=key;fields[key]=field.box;grid.append(field.wrap);}customer.append(grid);form.append(customer);
      const products=section(doc,'商品与金额','package'),itemList=doc.createElement('div');itemList.className='ob-draft-items';const itemRows:{sku:HTMLInputElement;quantity:HTMLInputElement;price:HTMLInputElement;discount:HTMLInputElement;row:HTMLElement}[]=[];
      const addItem=(item?:DraftItem)=>{const row=doc.createElement('div');row.className='ob-draft-item';const sku=input(doc,'商品编号',item?.sku||''),quantity=input(doc,'数量',item?String(item.quantity):'1'),price=input(doc,'成交单价 AED',item?.price_fils===null||item===undefined?'':(item.price_fils/100).toFixed(2)),discount=input(doc,'单件优惠 AED',item?.discount_fils===null||item===undefined?'':(item.discount_fils/100).toFixed(2));quantity.box.type='number';quantity.box.min='1';quantity.box.step='1';const remove=button(doc,'移除','btn');remove.onclick=()=>{row.remove();const at=itemRows.findIndex(value=>value.row===row);if(at>=0)itemRows.splice(at,1);};row.append(sku.wrap,quantity.wrap,price.wrap,discount.wrap,remove);itemList.append(row);itemRows.push({sku:sku.box,quantity:quantity.box,price:price.box,discount:discount.box,row});};
      for(const item of value.draft?.items||[])addItem(item);products.append(itemList);const add=button(doc,'添加商品','btn');add.onclick=()=>addItem();products.append(add);form.append(products);
      const actions=doc.createElement('div');actions.className='ob-actions';const save=button(doc,'保存草稿','btn primary'),result=doc.createElement('output');save.type='submit';result.className='ob-feedback';result.setAttribute('aria-live','polite');actions.append(save,result);form.append(actions);content.append(form);
      form.onsubmit=async event=>{event.preventDefault();save.disabled=true;result.textContent='正在保存…';try{const fieldsPayload=Object.fromEntries(Object.entries(fields).map(([key,element])=>[key,element.value.trim()]));const items=itemRows.map(row=>({sku:row.sku.value.trim(),quantity:Number(row.quantity.value),price:row.price.value.trim(),discount:row.discount.value.trim()}));const updated=await call<Detail>('saveDraft',{orderId:value.id,revision:value.draftRevision,fields:fieldsPayload,items});if(!closed)render(updated);}catch(error){result.textContent=(error as Error).message;save.disabled=false;}};
    }else{
      const pair=doc.createElement('div');pair.className='od-two-cards ob-detail-pair';const customer=section(doc,'客户信息','user-round'),grid=doc.createElement('div');grid.className='od-fields ob-read-grid';for(const [label,data,wide] of [['客户姓名',name,false],['联系电话',phone,false],['邮箱',value.customer.email,false],['国家／地区',value.customer.country,false],['省／州',value.customer.province,false],['城市',value.customer.city,false],['详细收货地址',[value.customer.street,value.customer.residence].filter(Boolean).join(' · '),true]] as [string,unknown,boolean][]){const field=doc.createElement('div');field.className=`od-field${wide?' od-field-wide':''}`;const key=doc.createElement('span'),text=doc.createElement('span');key.className='od-field-label';text.className='od-field-value';key.textContent=label;text.textContent=plain(data);field.append(key,text);grid.append(field);}customer.append(grid);
      const editPhone=button(doc,'','od-text-button cursor-interaction');editPhone.replaceChildren(lucide(doc,'pencil'),doc.createTextNode('核对电话'));customer.querySelector('.od-card-head')!.append(editPhone);editPhone.onclick=()=>{const dialog=doc.createElement('dialog');dialog.className='shared-dialog ob-phone-dialog';const title=doc.createElement('h2');title.textContent='更正订单联系电话';const phoneInput=input(doc,'完整电话（含国家区号）',phone||'');const reason=input(doc,'修改依据或备注');const output=doc.createElement('output');output.className='ob-feedback';const actions=doc.createElement('footer'),cancel=button(doc,'取消','btn'),save=button(doc,'保存更正','btn primary');cancel.onclick=()=>dialog.close();save.onclick=async()=>{save.disabled=true;try{const updated=await call<Detail>('updateRecipient',{orderId:value.id,field:'phone',value:phoneInput.box.value.trim(),reason:reason.box.value.trim()});dialog.close();if(!closed)render(updated);}catch(error){output.textContent=(error as Error).message;save.disabled=false;}};actions.append(cancel,save);dialog.append(title,note(doc,'仅在核对真实资料后更正。原始导入记录仍保留。'),phoneInput.wrap,reason.wrap,output,actions);root.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();};
      const products=section(doc,'商品与金额','package');const productList=doc.createElement('div');productList.className='ob-order-products';if(!value.items.length)productList.append(note(doc,'该订单没有商品明细。'));for(const item of value.items){const row=doc.createElement('div');row.className='od-product ob-order-product';const picture=doc.createElement('span');picture.className='od-product-image';picture.append(lucide(doc,'box'));const copy=doc.createElement('div');const title=doc.createElement('div');title.className='od-product-name';title.textContent=plain(item.businessCode);const itemDetail=doc.createElement('div');itemDetail.className='od-product-meta';itemDetail.textContent=`${plain(item.productName)} · 成本 ${money(item.costFils)}`;copy.append(title,itemDetail);const quantity=doc.createElement('span');quantity.className='od-qty';quantity.textContent=`× ${item.quantity}`;const price=doc.createElement('span');price.className='od-price';price.textContent=money(item.unitActualPriceFils);row.append(picture,copy,quantity,price);productList.append(row);}products.append(productList);const total=doc.createElement('div');total.className='od-total';const totalLabel=doc.createElement('span');totalLabel.textContent='订单商品合计';const totalValue=doc.createElement('strong');totalValue.textContent=money(value.amounts.orderTotal);total.append(totalLabel,totalValue);products.append(total);const shipping=doc.createElement('div');shipping.className='ob-shipping-total';shipping.textContent=`客户运费：${money(value.amounts.customerShippingFee)}`;products.append(shipping);pair.append(customer,products);content.append(pair);
      const delivery=section(doc,'配送与包裹','map-pinned'),deliveryBody=doc.createElement('div');deliveryBody.className='od-delivery ob-delivery';const map=doc.createElement('div');map.className='od-map';const pin=doc.createElement('span');pin.append(lucide(doc,'map-pin'));map.append(pin);const deliveryCopy=doc.createElement('div');const location=doc.createElement('strong');location.textContent=[value.customer.city,value.customer.province,value.customer.country].filter(Boolean).join(' · ')||'地址待补全';const address=doc.createElement('p');address.textContent=[value.customer.street,value.customer.residence].filter(Boolean).join(' · ')||'尚未提供详细收货地址。';const deliveryState=doc.createElement('span');deliveryState.className='od-delivery-state';deliveryState.append(lucide(doc,value.packages.length?'circle-check':'clock-3'),doc.createTextNode(value.packages.length?`已有 ${value.packages.length} 个包裹记录`:'暂无包裹记录，待核对'));deliveryCopy.append(location,address,deliveryState);const packages=doc.createElement('div');packages.className='ob-package-list';for(const parcel of value.packages){const row=doc.createElement('div');row.className='ob-package-row';const label=doc.createElement('span');label.textContent=plain(parcel.seriesCode);const state=doc.createElement('strong');const parcelState:Record<string,string>={unshipped:'待发货',awaiting_report:'待报单',outbound_processing:'出库中',shipped_pending:'运输中',signed:'已签收',refused:'已拒收'};state.textContent=`${parcelState[parcel.status]||'状态待核对'} · 运费 ${money(parcel.shippingFeeFils)}`;row.append(label,state);packages.append(row);}deliveryCopy.append(packages);deliveryBody.append(map,deliveryCopy);delivery.append(deliveryBody);content.append(delivery);
    }
    refreshIcons();
  };
  void call<Detail|null>('detail',orderId).then(value=>{if(closed)return;if(!value){content.replaceChildren(note(doc,'找不到所选订单，请返回订单管理重新选择。'));return;}render(value);}).catch(error=>{if(!closed)content.replaceChildren(note(doc,(error as Error).message));});
  return ()=>{closed=true;};
}
