import {version} from '../../package.json';
type Page='inventory'|'profit'|'assistant'|'settings'|'product'|'profit-detail';
type Reply<T>={ok:boolean;data?:T;error?:{message?:string}};
type Profile={businessId:string;displayName?:string|null;category?:string|null;websiteUrl?:string|null;actualPriceFils?:number|null;pendingPriceFils?:number|null;sourceCost?:string|null;suggestedPrice?:string|null;inventoryStatus?:string|null;chatEnabled?:boolean;imagePaths?:string[];updatedAt?:string|null};
type Inventory={current?:{savedAt?:string;products?:Array<{businessId:string;sourceName?:string;cost?:string;suggestedPrice?:string;stock?:string}>}|null;updatedAt?:string|null};
type ProfitRow={day:string;orders:number;remittanceCnyFen:number;adUsdCents:number;usdCnyRateScaled:number;adCostCnyFen:number;accountCostCnyFen:number;shippingAedFils:number;shippingCnyFen:number;realProfitCnyFen:number;signedOrders:number;refusedOrders:number;pendingRemittanceOrders:number};
type Profit={rows:ProfitRow[];summary:{remittanceCnyFen:number;sharedCostCnyFen:number;shippingCnyFen:number;realProfitCnyFen:number};aedCnyRate:number};
type Options={openProduct:(id:string)=>void;openDay:(day:string)=>void;openOrder:(id:string)=>void;productId?:string;day?:string};

async function call<T>(fn:(()=>Promise<Reply<unknown>>)|undefined,label:string):Promise<T>{
  if(!fn)throw new Error(`${label}暂不可用，请从桌面 App 重新打开`);
  const result=await fn();if(!result.ok)throw new Error(result.error?.message||`${label}失败`);return result.data as T;
}
const service=(name:string,payload?:unknown)=>call<any>(window.inventoryApp?.orders?.[name]?()=>window.inventoryApp!.orders![name](payload):undefined,name);
const get=<T extends Element=HTMLElement>(doc:Document,selector:string)=>doc.querySelector<T>(selector)!;
const set=(doc:Document,selector:string,value:unknown)=>{const node=doc.querySelector<HTMLElement>(selector);if(node)node.textContent=String(value??'—');};
const money=(value:number|undefined|null)=>value===null||value===undefined?'—':`¥${(value/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const aed=(value:number|undefined|null)=>value===null||value===undefined?'—':`AED ${(value/100).toFixed(2)}`;
const decimal=(value:string|undefined|null)=>value?String(value):'—';
const today=()=>new Date().toLocaleDateString('sv-SE');
function feedback(doc:Document,selector:string,message:string){const target=doc.querySelector<HTMLElement>(selector);if(!target)return;target.textContent=message;target.hidden=false;target.setAttribute('role','status');}
function status(doc:Document,main:Element,message:string){let line=main.querySelector<HTMLElement>('.live-page-status');if(!line){line=doc.createElement('p');line.className='live-page-status';main.prepend(line);}line.textContent=message;}
function empty(doc:Document,message:string){const row=doc.createElement('tr'),cell=doc.createElement('td');cell.colSpan=8;cell.className='live-table-empty';cell.textContent=message;row.append(cell);return row;}
function tabs(doc:Document){const buttons=[...doc.querySelectorAll<HTMLButtonElement>('.main .tabs .tab')],panels=[...doc.querySelectorAll<HTMLElement>('.main .tab-panel')];for(const button of buttons)button.onclick=()=>{for(const tab of buttons){tab.classList.toggle('active',tab===button);tab.classList.toggle('on',tab===button);tab.setAttribute('aria-selected',String(tab===button));}for(const panel of panels)panel.hidden=panel.dataset.panel!==button.dataset.tab;};}
function forbid(button:HTMLButtonElement|null|undefined,reason:string){if(!button)return;button.disabled=true;button.title=reason;button.setAttribute('aria-label',`${button.textContent?.trim()||'操作'}：${reason}`);}
function field(doc:Document,label:string,value:string){const row=doc.createElement('label');row.className='live-dialog-field';row.textContent=label;const input=doc.createElement('input');input.value=value;row.append(input);return {row,input};}
function dialog(doc:Document,title:string){const box=doc.createElement('dialog');box.className='shared-dialog live-dialog';const heading=doc.createElement('h2');heading.textContent=title;const result=doc.createElement('output');result.setAttribute('aria-live','polite');box.append(heading,result);doc.body.append(box);box.onclose=()=>box.remove();return {box,result};}

function inventory(doc:Document,win:Window,options:Options){
  const root=get(doc,'#ui011-inventory'),main=get(root.ownerDocument,'.main'),rows=get<HTMLTableSectionElement>(doc,'#ui011-rows'),search=get<HTMLInputElement>(doc,'#ui011-search'),filter=get<HTMLSelectElement>(doc,'#ui011-status');
  let products:Array<{id:string;name:string;stock:string;cost:string;suggested:string;profile?:Profile}>=[],selected='',quick='all',closed=false;
  const source=()=>products.find(p=>p.id===selected);
  const overview=()=>{const p=source();set(doc,'#ui011-overview-name',p?.id||'—');set(doc,'#ui011-cost',p?.cost||'—');set(doc,'#ui011-suggested',p?.suggested||'—');set(doc,'#ui011-price',p?aed(p.profile?.actualPriceFils):'—');set(doc,'#ui011-stock-value',p?.stock||'—');set(doc,'#ui011-overview-stock',p?.stock||'未同步');const badge=get(doc,'#ui011-overview-stock');badge.className=`badge ${p?.stock==='有货'?'is-in':'is-out'}`;set(doc,'#ui011-chat-state',p?.stock==='有货'?'有货 · 请人工核对实际售价后推荐':p?.stock==='无货'?'无货 · 暂不可发货':'库存未核实 · 请先同步');get<HTMLButtonElement>(doc,'#ui011-edit').disabled=!p;get<HTMLButtonElement>(doc,'#ui011-full-details').disabled=!p;const picture=doc.querySelector<HTMLButtonElement>('#ui011-inventory .product-images-button');if(picture)picture.disabled=!p;};
  const render=()=>{if(closed)return;set(doc,'#ui011-total',products.length);set(doc,'#ui011-in',products.filter(p=>p.stock==='有货').length);set(doc,'#ui011-out',products.filter(p=>p.stock==='无货').length);const q=search.value.trim().toLowerCase(),mode=filter.value!=='all'?filter.value:quick,visible=products.filter(p=>(!q||`${p.name} ${p.id}`.toLowerCase().includes(q))&&(mode==='all'||mode==='in'&&p.stock==='有货'||mode==='out'&&p.stock==='无货'));set(doc,'#ui011-result-count',`共 ${visible.length} 个商品 · ${products.length?'真实资料':'暂无真实商品'}`);rows.replaceChildren();for(const p of visible){const tr=doc.createElement('tr');tr.dataset.key=p.id;tr.setAttribute('aria-selected',String(p.id===selected));for(const value of [p.name, aed(p.profile?.actualPriceFils),p.stock]){const td=doc.createElement('td');td.textContent=value;tr.append(td);}tr.onclick=()=>{selected=p.id;render();};rows.append(tr);}get(doc,'#ui011-empty').hidden=visible.length>0;if(!visible.length)set(doc,'#ui011-empty',products.length?'没有符合条件的商品。':'暂无真实商品；订单或库存同步后会显示在这里。');overview();};
  const refresh=async()=>{try{const [view,profiles]=await Promise.all([call<Inventory>(window.inventoryApp?.localInventory,'库存读取'),service('productProfiles') as Promise<Profile[]>]);if(closed)return;const byId=new Map<string,Profile>(profiles.map(p=>[p.businessId,p])),bySource=new Map((view.current?.products||[]).map(p=>[p.businessId.toUpperCase(),p]));const ids=new Set([...byId.keys(),...bySource.keys()]);products=[...ids].sort().map(id=>{const p=byId.get(id),s=bySource.get(id);return {id,name:p?.displayName||s?.sourceName||id,stock:p?.inventoryStatus||s?.stock||'未同步',cost:p?.sourceCost||s?.cost||'',suggested:p?.suggestedPrice||s?.suggestedPrice||'',profile:p};});if(!products.some(p=>p.id===selected))selected=products[0]?.id||'';const connected=Boolean(view.current?.savedAt||view.updatedAt);set(doc,'#ui011-connection > span',connected?'库存有本地同步记录':'库存尚未同步');set(doc,'#ui011-popover .popover-meta',connected?`上次本地同步：${view.updatedAt||'时间未记录'}`:'尚无本地库存同步记录');get(doc,'#ui011-popover .change-list').replaceChildren();get(doc,'#ui011-popover .order-impact').hidden=true;status(doc,main,connected?'数据来自本机已同步库存和商品档案；网站售价由人工核对。':'暂无已同步库存。可使用原有同步入口，商品档案也会显示在此页。');render();}catch(error){status(doc,main,`库存读取失败：${(error as Error).message}`);}};
  search.oninput=render;filter.onchange=()=>{quick='all';render();};for(const button of root.querySelectorAll<HTMLButtonElement>('.stat'))button.onclick=()=>{quick=button.dataset.filter||'all';filter.value='all';for(const other of root.querySelectorAll('.stat'))other.setAttribute('aria-pressed',String(other===button));render();};
  get<HTMLButtonElement>(doc,'#ui011-connection').onclick=()=>{const el=get(doc,'#ui011-popover');el.hidden=!el.hidden;};get<HTMLButtonElement>(doc,'#ui011-close-popover').onclick=()=>get(doc,'#ui011-popover').hidden=true;
  get<HTMLButtonElement>(doc,'#ui011-overview-help').onclick=()=>{const el=get(doc,'#ui011-overview-info');el.hidden=!el.hidden;};
  get<HTMLButtonElement>(doc,'#ui011-open-source').onclick=async()=>{try{if(!window.inventoryApp?.openKdocs)throw new Error('库存来源入口暂不可用');await window.inventoryApp.openKdocs();}catch(error){feedback(doc,'#ui011-toast',(error as Error).message);}};
  get<HTMLButtonElement>(doc,'#ui011-sync').onclick=async event=>{const button=event.currentTarget as HTMLButtonElement;button.disabled=true;status(doc,main,'正在读取库存，请等待实际同步结果…');try{if(!window.inventoryApp?.sync)throw new Error('库存同步入口暂不可用');const result=await window.inventoryApp.sync() as Reply<unknown>;if(!result?.ok)throw new Error(result?.error?.message||'同步未完成');await refresh();}catch(error){status(doc,main,`同步未完成：${(error as Error).message}`);}finally{button.disabled=false;}};
  get<HTMLButtonElement>(doc,'#ui011-edit').onclick=()=>{const p=source();if(!p)return;const d=dialog(doc,`编辑 ${p.id} 商品档案`),name=field(doc,'商品名称',p.profile?.displayName||p.name),category=field(doc,'分类',p.profile?.category||''),url=field(doc,'网站商品链接',p.profile?.websiteUrl||''),price=field(doc,'人工核对的实际售价（AED）',p.profile?.actualPriceFils===null||p.profile?.actualPriceFils===undefined?'':(p.profile.actualPriceFils/100).toFixed(2));const foot=doc.createElement('footer'),cancel=doc.createElement('button'),save=doc.createElement('button');cancel.textContent='取消';save.textContent='保存商品资料';save.className='primary';cancel.onclick=()=>d.box.close();save.onclick=async()=>{save.disabled=true;try{await service('saveProductProfile',{businessId:p.id,displayName:name.input.value.trim(),category:category.input.value.trim(),websiteUrl:url.input.value.trim(),actualPrice:price.input.value.trim(),chatEnabled:p.profile?.chatEnabled!==false,imagePaths:p.profile?.imagePaths||[]});d.box.close();await refresh();}catch(error){d.result.textContent=(error as Error).message;save.disabled=false;}};foot.append(cancel,save);d.box.append(name.row,category.row,url.row,price.row,foot);d.box.showModal();};
  get<HTMLButtonElement>(doc,'#ui011-full-details').dataset.restoredAction='true';get<HTMLButtonElement>(doc,'#ui011-full-details').onclick=()=>{if(selected)options.openProduct(selected);};
  get<HTMLButtonElement>(doc,'#ui011-help').onclick=()=>{const el=get(doc,'#ui011-overview-info');el.hidden=!el.hidden;};
  get(doc,'#ui011-popover .change-list').replaceChildren();get(doc,'#ui011-popover .order-impact').hidden=true;set(doc,'#ui011-change-count','');get(doc,'#ui011-empty').hidden=false;overview();void refresh();return()=>{closed=true;};
}

function profit(doc:Document,options:Options){
  const main=get(doc,'#ui034 .main'),table=get<HTMLTableSectionElement>(doc,'#ui034 tbody'),range=get<HTMLSelectElement>(doc,'#u34-range'),date=get<HTMLInputElement>(doc,'#u34-date'),statusFilter=get<HTMLSelectElement>(doc,'#ui034 .table-card .tools select');let state:Profit={rows:[],summary:{remittanceCnyFen:0,sharedCostCnyFen:0,shippingCnyFen:0,realProfitCnyFen:0},aedCnyRate:1.8},closed=false;
  const draw=()=>{if(closed)return;const all=state.rows,period=range.selectedIndex===2?all.filter(row=>row.day.slice(0,7)===today().slice(0,7)):all,rows=period.filter(row=>statusFilter.selectedIndex===0||statusFilter.selectedIndex===1&&row.pendingRemittanceOrders===0||statusFilter.selectedIndex===2&&row.pendingRemittanceOrders>0);
    const summary=rows.reduce((a,r)=>({remittanceCnyFen:a.remittanceCnyFen+r.remittanceCnyFen,sharedCostCnyFen:a.sharedCostCnyFen+r.adCostCnyFen+r.accountCostCnyFen,shippingCnyFen:a.shippingCnyFen+r.shippingCnyFen,realProfitCnyFen:a.realProfitCnyFen+r.realProfitCnyFen}),{remittanceCnyFen:0,sharedCostCnyFen:0,shippingCnyFen:0,realProfitCnyFen:0});
    const stats=[...main.querySelectorAll<HTMLElement>('.stats .stat strong')];for(const [index,value] of [summary.remittanceCnyFen,rows.reduce((a,r)=>a+r.adUsdCents,0),summary.sharedCostCnyFen+summary.shippingCnyFen,summary.realProfitCnyFen].entries())if(stats[index])stats[index].textContent=rows.length?(index===1?`$${(value/100).toFixed(2)}`:money(value)):'—';
    const notes=[...main.querySelectorAll<HTMLElement>('.stats .stat small')];if(notes[1])notes[1].textContent=rows.length?`折合人民币 ${money(rows.reduce((a,r)=>a+r.adCostCnyFen,0))}`:'暂无投流记录';
    const chart=get(doc,'#ui034 .chart'),breakdown=get(doc,'#ui034 .breakdown');chart.replaceChildren();breakdown.replaceChildren();if(rows.length){const visible=rows.slice(0,7).reverse(),limit=Math.max(1,...visible.map(r=>Math.abs(r.realProfitCnyFen)));for(const row of visible){const bar=doc.createElement('div');bar.className='bar-wrap';const value=doc.createElement('div');value.className='bar';value.style.setProperty('--h',`${Math.max(3,Math.round(Math.abs(row.realProfitCnyFen)/limit*95))}%`);value.title=`${row.day}：${money(row.realProfitCnyFen)}`;const label=doc.createElement('span');label.textContent=row.day.slice(5);bar.append(value,label);chart.append(bar);}for(const [label,value] of [['本期运费支出',aed(rows.reduce((a,r)=>a+r.shippingAedFils,0))],['账号购买',money(rows.reduce((a,r)=>a+r.accountCostCnyFen,0))],['已回款订单',`${rows.reduce((a,r)=>a+r.signedOrders,0)} 单`],['拒收 / 待回款',`${rows.reduce((a,r)=>a+r.refusedOrders,0)} / ${rows.reduce((a,r)=>a+r.pendingRemittanceOrders,0)} 单`]]){const chip=doc.createElement('div');chip.className='chip';const heading=doc.createElement('span'),strong=doc.createElement('b');heading.textContent=label;strong.textContent=value;chip.append(heading,strong);breakdown.append(chip);}}else{const hint=doc.createElement('p');hint.className='live-empty-inline';hint.textContent='暂无真实核算记录；保存当天成本或导入并结算订单后显示。';chart.append(hint);}
    table.replaceChildren();if(!rows.length)table.append(empty(doc,'暂无真实每日利润记录。'));for(const row of rows){const tr=doc.createElement('tr');for(const value of [row.day,money(row.remittanceCnyFen),`$${(row.adUsdCents/100).toFixed(2)}`,money(row.accountCostCnyFen),aed(row.shippingAedFils),money(row.adCostCnyFen+row.accountCostCnyFen+row.shippingCnyFen),money(row.realProfitCnyFen)]){const td=doc.createElement('td');td.textContent=value;tr.append(td);}const action=doc.createElement('td'),button=doc.createElement('button');button.className='link';button.dataset.restoredAction='true';button.textContent='查看详情';button.onclick=()=>options.openDay(row.day);action.append(button);tr.append(action);table.append(tr);}status(doc,main,rows.length?`已读取 ${rows.length} 天的本机真实订单与成本记录。`:'利润列表目前没有可核算的真实数据；金额不使用演示值。');
    const chosen=state.rows.find(row=>row.day===date.value);get<HTMLInputElement>(doc,'#u34-orders').value=chosen?String(chosen.orders):'';get<HTMLInputElement>(doc,'#u34-ad').value=chosen?String(chosen.adUsdCents/100):'';get<HTMLInputElement>(doc,'#u34-usd-rate').value=chosen?String(chosen.usdCnyRateScaled/1e6):'';get<HTMLInputElement>(doc,'#u34-account').value=chosen?String(chosen.accountCostCnyFen/100):'';get<HTMLInputElement>(doc,'#u34-aed-rate').value=String(state.aedCnyRate);set(doc,'#u34-total',chosen?money(chosen.adCostCnyFen+chosen.accountCostCnyFen):'—');set(doc,'#u34-average',chosen&&chosen.orders?money(Math.round((chosen.adCostCnyFen+chosen.accountCostCnyFen)/chosen.orders)):'—');
  };
  const refresh=async()=>{try{state=await service('profitDashboard',{range:range.selectedIndex===0?'7':range.selectedIndex===1?'30':undefined}) as Profit;draw();}catch(error){status(doc,main,`利润读取失败：${(error as Error).message}`);}};
  table.replaceChildren(empty(doc,'正在读取真实利润数据…'));main.querySelector('.stats')!.querySelectorAll('strong').forEach(node=>node.textContent='—');get(doc,'#ui034 .chart').replaceChildren();get(doc,'#ui034 .breakdown').replaceChildren();date.value=today();range.onchange=()=>void refresh();statusFilter.onchange=draw;date.onchange=draw;get<HTMLInputElement>(doc,'#u34-orders').readOnly=true;
  get<HTMLButtonElement>(doc,'#u34-save').onclick=async event=>{const button=event.currentTarget as HTMLButtonElement,ad=get<HTMLInputElement>(doc,'#u34-ad').value,rate=get<HTMLInputElement>(doc,'#u34-usd-rate').value,account=get<HTMLInputElement>(doc,'#u34-account').value;if(!ad||!rate||!account){status(doc,main,'请填写当天投流（可填 0）、USD 汇率和账号购买（可填 0）后保存。');return;}button.disabled=true;try{await service('saveDailyCosts',{day:date.value,adUsd:ad,usdCnyRate:rate,accountCostCny:account});await refresh();status(doc,main,`${date.value} 的成本已保存并重新核算。`);}catch(error){status(doc,main,`保存失败：${(error as Error).message}`);}finally{button.disabled=false;}};
  get<HTMLButtonElement>(doc,'#u34-export').onclick=async event=>{const button=event.currentTarget as HTMLButtonElement;button.disabled=true;try{const result=await service('exportProfit',{filters:{},includePending:false});status(doc,main,result.canceled?'已取消导出':`已导出利润文件：${result.filename}`);}catch(error){status(doc,main,`导出失败：${(error as Error).message}`);}finally{button.disabled=false;}};
  for(const [selector,message] of [['#u34-currency-help','美元投流按对应日期汇率折算；AED 运费以 1.80 的固定汇率核算。'],['#u34-account-help','账号成本以人民币填写，仅计入购买当日。'],['#u34-freight-help','订单实际运费按固定 AED 汇率折算。']] as const)get<HTMLButtonElement>(doc,selector).onclick=()=>status(doc,main,message);
  void refresh();return()=>{closed=true;};
}

function dailyProfit(doc:Document,options:Options){
  const main=get(doc,'#ui035 .main'),table=get<HTMLTableSectionElement>(doc,'#ui035 tbody');let day=options.day||today(),days:string[]=[],closed=false;
  const load=async()=>{const requestedDay=day;try{const result=await service('dailyProfit',{day:requestedDay}),daily=result.daily as ProfitRow,orders=result.orders as Array<{id:string;orderNo:string;customerName:string;orderAedFils:number;remittanceCnyFen:number;shippingAedFils:number;contributionCnyFen:number}>;if(closed||requestedDay!==day)return;set(doc,'#u35-date',day);const costs=daily.adCostCnyFen+daily.accountCostCnyFen+daily.shippingCnyFen,stat=[...main.querySelectorAll<HTMLElement>('.stats .stat strong')];for(const [index,value] of [money(daily.remittanceCnyFen),money(costs),money(daily.realProfitCnyFen),daily.remittanceCnyFen?`${(daily.realProfitCnyFen/daily.remittanceCnyFen*100).toFixed(1)}%`:'—'].entries())if(stat[index])stat[index].textContent=value;const amounts=[...main.querySelectorAll<HTMLElement>('.tiles b')];for(const [index,value] of [`$${(daily.adUsdCents/100).toFixed(2)}`,money(daily.accountCostCnyFen),daily.orders?money(Math.round((daily.adCostCnyFen+daily.accountCostCnyFen)/daily.orders)):'—',money(daily.remittanceCnyFen),money(costs),money(daily.realProfitCnyFen)].entries())if(amounts[index])amounts[index].textContent=value;const note=main.querySelector<HTMLElement>('.tiles .tile small');if(note)note.textContent=`≈ ${money(daily.adCostCnyFen)}`;const meta=[...main.querySelectorAll<HTMLElement>('.day-meta span')];for(const [index,value] of [`${daily.orders} 个订单`,`已签收 ${daily.signedOrders} 单`,`拒收 ${daily.refusedOrders} 单`,`待回款 ${daily.pendingRemittanceOrders} 单`].entries())if(meta[index])meta[index].textContent=value;table.replaceChildren();if(!orders.length)table.append(empty(doc,'该日期没有真实订单。'));for(const order of orders){const tr=doc.createElement('tr');for(const text of [order.orderNo,order.customerName||'—',aed(order.orderAedFils),'真实订单',money(order.remittanceCnyFen),aed(order.shippingAedFils),money(order.contributionCnyFen)]){const td=doc.createElement('td');td.textContent=text;tr.append(td);}const cell=doc.createElement('td'),button=doc.createElement('button');button.className='link';button.dataset.restoredAction='true';button.textContent='订单详情';button.onclick=()=>options.openOrder(order.id);cell.append(button);tr.append(cell);table.append(tr);}status(doc,main,orders.length?`${day}：${orders.length} 个真实订单。`:`${day} 暂无订单，显示真实空状态。`);}catch(error){status(doc,main,`每日利润读取失败：${(error as Error).message}`);}};
  table.replaceChildren(empty(doc,'正在读取真实每日利润…'));main.querySelectorAll('.stats .stat strong,.tiles b').forEach(node=>node.textContent='—');main.querySelectorAll<HTMLElement>('.source-grid strong,.cost-grid strong,.breakdown strong').forEach(node=>node.textContent='—');main.querySelectorAll('.day-meta span').forEach(node=>node.textContent='读取中…');const initialNote=main.querySelector<HTMLElement>('.tiles .tile small');if(initialNote)initialNote.textContent='—';
  void service('profitDashboard',{}).then((value:Profit)=>{days=value.rows.map(row=>row.day);if(!options.day&&days.length){day=days[0];void load();}}).catch(()=>{});void load();
  get<HTMLButtonElement>(doc,'#u35-prev').onclick=()=>{const index=days.indexOf(day);day=days[index+1]||new Date(Date.parse(day+'T00:00:00')-86400000).toISOString().slice(0,10);void load();};get<HTMLButtonElement>(doc,'#u35-next').onclick=()=>{const index=days.indexOf(day);day=days[index-1]||new Date(Date.parse(day+'T00:00:00')+86400000).toISOString().slice(0,10);void load();};
  get<HTMLButtonElement>(doc,'#u35-date').onclick=()=>{const input=doc.createElement('input');input.type='date';input.value=day;input.className='live-day-picker';get(doc,'#u35-date').after(input);input.focus();input.onchange=()=>{if(input.value){day=input.value;void load();}input.remove();};input.onblur=()=>setTimeout(()=>input.remove(),100);};
  get<HTMLButtonElement>(doc,'#u35-export').onclick=async()=>{try{const value=await service('exportProfit',{filters:{day},includePending:false});status(doc,main,value.canceled?'已取消导出':`已导出：${value.filename}`);}catch(error){status(doc,main,(error as Error).message);}};
  for(const name of ['#u35-cost-help','#u35-profit-help'])get<HTMLButtonElement>(doc,name).onclick=()=>status(doc,main,'利润使用已登记回款和真实成本核算，未结算订单可能仍需人工核对。');
  const filters=[...main.querySelectorAll<HTMLSelectElement>('select')];for(const filter of filters){filter.disabled=true;filter.title='订单状态明细尚未接入筛选；请在订单详情核对实际履约状态';}return()=>{closed=true;};
}

function product(doc:Document,options:Options){
  const main=get(doc,'#ui032 .main'),gallery=get(doc,'#u32-hero'),thumbs=get(doc,'#ui032 .thumbs'),addPhoto=get<HTMLButtonElement>(doc,'#u32-add-photo');let current:Profile|undefined,closed=false;
  const show=async()=>{try{const profiles=await service('productProfiles',{}) as Profile[],view=await call<Inventory>(window.inventoryApp?.localInventory,'库存读取');if(closed)return;current=profiles.find(p=>p.businessId===options.productId)||profiles[0];if(!current){set(doc,'#ui032 .page-head h1','尚未选择商品');set(doc,'#ui032 .left-info .info-line:first-child strong','—');set(doc,'#ui032 .left-info .info-line:nth-child(2) strong','—');set(doc,'#ui032 .workspace > div:first-child .card-head .source-note','暂无图片');set(doc,'#ui032 .stack .card-head .source-note','库存未同步');set(doc,'#ui032 .stock-badge','未同步');for(const node of doc.querySelectorAll<HTMLElement>('#ui032 .source-grid strong'))node.textContent='—';const select=get<HTMLSelectElement>(doc,'#u32-details select');select.replaceChildren(new Option('未分类',''));select.disabled=true;set(doc,'#ui032 .availability-main strong','库存尚未核实');set(doc,'#ui032 .availability-main p','请先在订单中录入真实商品，或同步真实库存。');get<HTMLButtonElement>(doc,'#u32-edit').disabled=true;get<HTMLButtonElement>(doc,'#u32-add-photo').disabled=true;gallery.textContent='暂无真实商品图片';const picture=doc.querySelector<HTMLButtonElement>('#ui032 .product-images-button');if(picture)picture.disabled=true;status(doc,main,'产品详情尚无可展示的真实商品；原有商品资料、图片和来源区域保留。');return;}
    const source=view.current?.products?.find(p=>p.businessId.toUpperCase()===current!.businessId),fields=[...doc.querySelectorAll<HTMLInputElement>('#u32-details .form-grid input')],name=current.displayName||source?.sourceName||current.businessId,stock=current.inventoryStatus||source?.stock||'未同步';
    set(doc,'#ui032 .page-head h1',name);set(doc,'#ui032 .left-info .info-line:first-child strong',current.businessId);set(doc,'#ui032 .left-info .info-line:nth-child(2) strong',current.updatedAt||'未记录');
    if(fields[0]){fields[0].value=name;fields[0].readOnly=true;}if(fields[1])fields[1].value=decimal(current.sourceCost||source?.cost);if(fields[2])fields[2].value=decimal(current.suggestedPrice||source?.suggestedPrice);if(fields[3])fields[3].value=current.actualPriceFils===null||current.actualPriceFils===undefined?'':(current.actualPriceFils/100).toFixed(2);if(fields[4])fields[4].value=stock;
    const select=get<HTMLSelectElement>(doc,'#u32-details select');select.replaceChildren();const option=doc.createElement('option');option.value=current.category||'';option.textContent=current.category||'未分类';select.append(option);select.disabled=true;get<HTMLTextAreaElement>(doc,'#u32-details textarea').value=current.websiteUrl?`网站链接：${current.websiteUrl}`:'尚未填写网站商品链接';
    set(doc,'#ui032 .stock-badge',stock);const parts=[...doc.querySelectorAll<HTMLElement>('#ui032 .source-grid strong')];for(const [index,value] of [decimal(current.sourceCost||source?.cost),decimal(current.suggestedPrice||source?.suggestedPrice),stock].entries())if(parts[index])parts[index].textContent=value;
    set(doc,'#ui032 .stack .card-head .source-note',view.updatedAt?`上次同步：${view.updatedAt}`:'库存未同步');set(doc,'#ui032 .availability-main strong',stock==='有货'&&current.chatEnabled!==false?'有货 · 可供人工核对':'暂不可自动推荐');set(doc,'#ui032 .availability-main p',stock==='有货'?'请核对实际售价和客户需求。':'库存尚未确认为有货，不可承诺发货。');const toggle=get<HTMLButtonElement>(doc,'#ui032 .availability .switch');toggle.setAttribute('aria-checked',String(current.chatEnabled!==false&&stock==='有货'));toggle.disabled=true;
    thumbs.replaceChildren(addPhoto);gallery.replaceChildren();const placeholder=doc.createElement('span');placeholder.textContent='商品图片请在下方的“商品图片”入口查看或添加';gallery.append(placeholder);set(doc,'#ui032 .workspace > div:first-child .card-head .source-note',`${current.imagePaths?.length||0} 张已归档`);const picture=doc.querySelector<HTMLButtonElement>('#ui032 .product-images-button');if(picture)picture.disabled=false;status(doc,main,`当前显示本机商品档案 ${current.businessId}；成本和库存状态只能由真实库存同步更新。`);
  }catch(error){status(doc,main,`商品读取失败：${(error as Error).message}`);}};
  set(doc,'#ui032 .page-head h1','读取商品中…');for(const input of doc.querySelectorAll<HTMLInputElement>('#u32-details input'))input.value='';get<HTMLTextAreaElement>(doc,'#u32-details textarea').value='';thumbs.replaceChildren(addPhoto);gallery.replaceChildren();
  get<HTMLButtonElement>(doc,'#u32-edit').onclick=()=>{if(!current)return;const d=dialog(doc,`编辑 ${current.businessId} 商品资料`),name=field(doc,'商品名称',current.displayName||''),category=field(doc,'分类',current.category||''),url=field(doc,'网站商品链接',current.websiteUrl||''),price=field(doc,'实际售价（AED）',current.actualPriceFils===null||current.actualPriceFils===undefined?'':(current.actualPriceFils/100).toFixed(2));const foot=doc.createElement('footer'),cancel=doc.createElement('button'),save=doc.createElement('button');cancel.textContent='取消';save.textContent='保存';save.className='primary';cancel.onclick=()=>d.box.close();save.onclick=async()=>{save.disabled=true;try{await service('saveProductProfile',{businessId:current!.businessId,displayName:name.input.value.trim(),category:category.input.value.trim(),websiteUrl:url.input.value.trim(),actualPrice:price.input.value.trim(),chatEnabled:current!.chatEnabled!==false,imagePaths:current!.imagePaths||[]});d.box.close();await show();}catch(error){d.result.textContent=(error as Error).message;save.disabled=false;}};foot.append(cancel,save);d.box.append(name.row,category.row,url.row,price.row,foot);d.box.showModal();};
  addPhoto.onclick=()=>doc.querySelector<HTMLButtonElement>('.product-images-button')?.click();get<HTMLButtonElement>(doc,'#u32-help').onclick=()=>{const el=get(doc,'#u32-help-pop');el.hidden=!el.hidden;};
  void show();return()=>{closed=true;};
}

function assistant(doc:Document){
  const main=get(doc,'#ui041 .main');tabs(doc);const state=get(doc,'#ui041 .state');state.textContent='AI 自动发送未启用';
  status(doc,main,'保留原有助手说明与页签；自动发送尚未启用，历史演示“保存”不代表真实配置。');
  set(doc,'#ui041 .mode.auto p','自动发送尚未启用；聊天与订单操作继续由人工确认。');set(doc,'#ui041 .scope.allowed h3','规划能力 · 当前不自动发送');for(const badge of main.querySelectorAll<HTMLElement>('.fixed'))if(badge.textContent?.includes('已启用'))badge.textContent='规则说明';
  forbid(get<HTMLButtonElement>(doc,'#u41-save'),'此页原按钮仅为演示保存；尚未开放 AI 自动策略修改');
  get<HTMLButtonElement>(doc,'#u41-records').onclick=async()=>{const d=dialog(doc,'实际 AI 调用记录');try{const result=await call<any>(window.inventoryApp?.assistantSettings?.get,'助手设置读取'),entries=result.ledger||[];d.result.textContent=entries.length?entries.map((row:{purpose:string;at:string;status:string})=>`${row.at} · ${row.purpose} · ${row.status}`).join('\n'):'暂无真实 AI 调用记录。';}catch(error){d.result.textContent=(error as Error).message;}const close=doc.createElement('button');close.textContent='关闭';close.onclick=()=>d.box.close();d.box.append(close);d.box.showModal();};
  void call<any>(window.inventoryApp?.assistantSettings?.get,'助手设置读取').then(value=>{const provider=value.providers?.[value.activeProvider];state.textContent=provider?.hasApiKey?`已配置 ${provider.label}；AI 自动发送未启用`:'尚未配置 AI 服务；自动发送未启用';}).catch(error=>status(doc,main,`助手配置状态暂不可读取：${(error as Error).message}`));
  return()=>{};
}

function settings(doc:Document){
  const main=get(doc,'#ui036 .main');tabs(doc);const key=get<HTMLInputElement>(doc,'#u36-key'),aiCard=get(doc,'#u36-ai-status').closest('.card')!,waCard=get(doc,'#u36-manage-wa').closest('.card')!,sheetCard=waCard.nextElementSibling as HTMLElement;
  const aiStatus=get(doc,'#u36-ai-status'),waStatus=waCard.querySelector<HTMLElement>('.status')!,sheetStatus=sheetCard.querySelector<HTMLElement>('.status')!;
  key.value='';key.type='text';key.placeholder='点击右侧按钮安全输入密钥';key.readOnly=true;key.tabIndex=-1;const keyButton=get<HTMLButtonElement>(doc,'#u36-key-toggle');keyButton.title='安全输入密钥';keyButton.setAttribute('aria-label','安全输入密钥');keyButton.replaceChildren();const keyIcon=doc.createElement('i');keyIcon.dataset.lucide='key-round';keyButton.append(keyIcon);const paintKeyState=(provider:{hasApiKey?:boolean}|undefined)=>{const saved=Boolean(provider?.hasApiKey);key.value=saved?'密钥已安全保存':'';key.placeholder=saved?'':'点击右侧按钮安全输入密钥';key.classList.toggle('key-saved',saved);key.setAttribute('aria-label',saved?'API Key 已安全保存在本机':'API Key 尚未设置');keyButton.title=saved?'更换 API Key':'安全输入密钥';keyButton.setAttribute('aria-label',saved?'更换 API Key':'安全输入密钥');};
  const select=aiCard.querySelector('select')!,model=aiCard.querySelectorAll<HTMLInputElement>('.ai-grid input')[2],url=aiCard.querySelectorAll<HTMLInputElement>('.ai-grid input')[0];select.replaceChildren();for(const [value,label] of [['deepseek','DeepSeek'],['openai','OpenAI / GPT']]){const option=doc.createElement('option');option.value=value;option.textContent=label;select.append(option);}url.readOnly=true;
  const account=waCard.querySelector<HTMLElement>('.account-main b')!,accountLabel=waCard.querySelector<HTMLElement>('.account-main span:last-child')!,online=waCard.querySelector<HTMLElement>('.online')!;account.textContent='尚未核对账号';accountLabel.textContent='登录后在工作台统一读取会话';online.textContent='● 待核对';waCard.querySelector<HTMLElement>('.avatar')!.textContent='?';for(const node of waCard.querySelectorAll<HTMLElement>('.meta-grid b'))node.textContent='待核对';
  const initialStatuses=[...main.querySelectorAll<HTMLElement>('.tab-panel .card .status')];for(const badge of initialStatuses)if(!badge.textContent?.includes('固定规则'))badge.textContent='待核对';
  for(const el of main.querySelectorAll<HTMLInputElement>('.tab-panel input'))if(el!==key&&el!==model&&el!==url&&!el.readOnly)el.value='';
  for(const button of main.querySelectorAll<HTMLButtonElement>('.switch')){button.setAttribute('aria-checked','false');forbid(button,'原稿仅有演示开关，当前没有持久设置接口');}
  let ai:any;
  const readAI=async()=>{ai=await call<any>(window.inventoryApp?.assistantSettings?.get,'AI 设置读取');select.value=ai.activeProvider;const provider=ai.providers?.[ai.activeProvider];url.value=provider?.baseUrl||'';model.value=provider?.model||'';aiStatus.textContent=provider?.hasApiKey?(provider?.test?.status==='verified'?'已验证':'已配置 · 未验证'):'未设置密钥';paintKeyState(provider);};
  void readAI().catch(error=>{aiStatus.textContent='不可用';status(doc,main,`AI 设置读取失败：${(error as Error).message}`);});
  select.onchange=()=>{const p=ai?.providers?.[select.value];url.value=p?.baseUrl||'';model.value=p?.model||'';aiStatus.textContent=p?.hasApiKey?'已配置 · 未验证':'未设置密钥';paintKeyState(p);};
  get<HTMLButtonElement>(doc,'#u36-key-toggle').onclick=async()=>{if(!ai)return;try{const result=await window.inventoryApp?.assistantSettings?.changeKey({provider:select.value,revision:ai.revision});if(!result?.ok)throw new Error(result?.error?.message||'密钥保存失败');await readAI();status(doc,main,'安全密钥操作已结束；应用不会显示密钥原文。');}catch(error){status(doc,main,(error as Error).message);}};
  get<HTMLButtonElement>(doc,'#u36-ai-save').onclick=async event=>{const button=event.currentTarget as HTMLButtonElement;if(!ai)return;button.disabled=true;try{const result=await window.inventoryApp?.assistantSettings?.save({provider:select.value,revision:ai.revision,model:model.value.trim()});if(!result?.ok)throw new Error(result?.error?.message||'AI 设置保存失败');await readAI();status(doc,main,'服务商和模型设置已保存；未自动启用 AI 回复。');}catch(error){status(doc,main,(error as Error).message);}finally{button.disabled=false;}};
  get<HTMLButtonElement>(doc,'#u36-ai-test').onclick=async event=>{const button=event.currentTarget as HTMLButtonElement;if(!ai)return;button.disabled=true;try{const result=await window.inventoryApp?.assistantSettings?.test({provider:select.value,revision:ai.revision});if(!result?.ok)throw new Error(result?.error?.message||'连接验证失败');await readAI();status(doc,main,'已使用虚构资料完成一次真实接口验证；没有读取客户消息。');}catch(error){status(doc,main,(error as Error).message);await readAI().catch(()=>{});}finally{button.disabled=false;}};
  const readWhatsApp=async()=>{const value=await service('assistantConnection',{});const connected=value.status==='online';waStatus.textContent=connected?'已登录':'未登录';account.textContent=connected?(value.accountPhone||value.accountId||'已登录账号'):'尚未核对账号';accountLabel.textContent=connected?'工作台将统一读取真实会话':'请使用手机扫码连接';online.textContent=connected?'● 在线':'● 未在线';return value;};
  void readWhatsApp().catch(error=>status(doc,main,`WhatsApp 状态暂不可读取：${(error as Error).message}`));
  const openWhatsAppLogin=()=>{let timer:ReturnType<typeof setInterval>|undefined;const dialog=doc.createElement('dialog');dialog.className='live-dialog wa-login-dialog';dialog.innerHTML='<h2>WhatsApp 登录</h2><p class="wa-login-hint">请使用手机 WhatsApp 的“已关联设备”扫描二维码。登录成功后，聊单工作台会统一读取真实会话。</p><output aria-live="polite">正在准备登录…</output><img class="wa-login-qr" hidden alt="WhatsApp 登录二维码"><div class="wa-login-account" hidden></div><footer><button type="button" data-retry>重新获取二维码</button><button type="button" data-close>关闭</button></footer>';
    const output=dialog.querySelector<HTMLOutputElement>('output')!,qr=dialog.querySelector<HTMLImageElement>('.wa-login-qr')!,accountBox=dialog.querySelector<HTMLElement>('.wa-login-account')!,retry=dialog.querySelector<HTMLButtonElement>('[data-retry]')!;
    const paint=async()=>{try{const value=await readWhatsApp();output.textContent=value.message||'正在检查连接状态…';if(value.qr){qr.src=value.qr;qr.hidden=false;}else {qr.removeAttribute('src');qr.hidden=true;}if(value.status==='online'){accountBox.hidden=false;accountBox.textContent=`已登录：${value.accountPhone||value.accountId||'账号已核对'}；工作台现在可读取真实会话。`;retry.hidden=true;if(timer)clearInterval(timer);}else {accountBox.hidden=true;retry.hidden=false;}}catch(error){output.textContent=(error as Error).message;}};
    const begin=async()=>{retry.disabled=true;output.textContent='正在连接 WhatsApp…';try{await service('openWhatsApp',{});}catch(error){output.textContent=(error as Error).message;}finally{retry.disabled=false;await paint();}};
    retry.onclick=()=>void begin();dialog.querySelector<HTMLButtonElement>('[data-close]')!.onclick=()=>dialog.close();dialog.onclose=()=>{if(timer)clearInterval(timer);dialog.remove();};doc.body.append(dialog);dialog.showModal();timer=setInterval(()=>void paint(),800);void begin();};
  get<HTMLButtonElement>(doc,'#u36-manage-wa').onclick=openWhatsAppLogin;
  waCard.querySelector<HTMLButtonElement>('[data-test]')!.onclick=async event=>{const button=event.currentTarget as HTMLButtonElement,original=button.textContent||'检测连接';button.disabled=true;button.textContent='检测中…';try{const value=await readWhatsApp();button.textContent=value.status==='online'?'已连接':'未连接';status(doc,main,value.status==='online'?'已重新读取实际 WhatsApp 连接状态：账号在线。':'已重新读取实际 WhatsApp 连接状态：尚未在线。');}catch(error){button.textContent='检测失败';status(doc,main,(error as Error).message);}finally{window.setTimeout(()=>{button.textContent=original;button.disabled=false;},1600);}};
  const readSheet=async()=>{const value=await call<any>(window.inventoryApp?.status,'连接状态读取');const connected=Boolean(value.google?.connected);sheetStatus.textContent=connected?'已授权':'未授权';sheetCard.querySelector<HTMLElement>('.card-head .desc')!.textContent=connected?'已授权 Google 表格':'尚未核对库存表授权';};sheetCard.querySelector<HTMLElement>('.card-head .desc')!.textContent='库存表授权待核对';
  void readSheet().catch(error=>{sheetStatus.textContent='不可用';status(doc,main,(error as Error).message);});
  sheetCard.querySelector<HTMLButtonElement>('[data-test]')!.onclick=async()=>{try{await readSheet();status(doc,main,'已读取实际库存表授权状态；尚未执行同步。');}catch(error){status(doc,main,(error as Error).message);}};
  const changeSheet=[...sheetCard.querySelectorAll<HTMLButtonElement>('button')].find(button=>button.textContent?.includes('更换表格'));forbid(changeSheet,'库存来源是项目固定配置；更换地址尚未开放');
  const business=get(doc,'#ui036 [data-panel="business"]');business.querySelector<HTMLInputElement>('.rates input:not([readonly])')!.readOnly=true;forbid(business.querySelector<HTMLButtonElement>('[data-save]'),'默认汇率设置尚无独立保存接口；可在利润核算页保存指定日期汇率');
  const dataPanel=get(doc,'#ui036 [data-panel="data"]'),dataCards=[...dataPanel.querySelectorAll<HTMLElement>('.data-card')];dataCards[0].querySelector<HTMLElement>('.card-head .desc')!.textContent='手动备份订单数据库';dataCards[0].querySelectorAll<HTMLElement>('.meta b')[1].textContent='由保存窗口选择';dataCards[1].querySelector<HTMLElement>('.card-head .desc')!.textContent='自动清理规则尚未接入';for(const node of dataCards[1].querySelectorAll<HTMLElement>('.retention strong'))node.textContent='尚未配置';
  const backupStatus=get(doc,'#ui036 [data-panel="data"] .data-card .meta b');backupStatus.textContent='读取中…';void service('dataStatus',{}).then(value=>backupStatus.textContent=value.lastManualBackupAt||'尚未进行手动备份').catch(()=>backupStatus.textContent='无法读取');
  get<HTMLButtonElement>(doc,'#u36-backup').onclick=async event=>{const button=event.currentTarget as HTMLButtonElement;button.disabled=true;try{const value=await service('createBackup',{});status(doc,main,value.canceled?'已取消备份':`已验证并保存备份：${value.filename}`);if(!value.canceled)backupStatus.textContent=value.createdAt;}catch(error){status(doc,main,`备份失败：${(error as Error).message}`);}finally{button.disabled=false;}};
  get<HTMLButtonElement>(doc,'#u36-restore').onclick=async()=>{try{const candidate=await service('selectRestore',{});if(candidate.canceled)return;const d=dialog(doc,'确认恢复订单资料');const text=doc.createElement('p');text.textContent=`所选文件：${candidate.filename}；版本 ${candidate.schemaVersion}；${candidate.orderCount} 单。恢复会替换当前订单数据库，系统会先备份现有数据。请确认已核对文件。`;const foot=doc.createElement('footer'),cancel=doc.createElement('button'),confirm=doc.createElement('button');cancel.textContent='取消';confirm.textContent='确认恢复订单数据库';confirm.className='danger';cancel.onclick=()=>d.box.close();confirm.onclick=async()=>{confirm.disabled=true;try{await service('restoreBackup',candidate.token);d.box.close();status(doc,main,'订单数据库恢复完成，请重新打开订单管理核对。');}catch(error){d.result.textContent=(error as Error).message;confirm.disabled=false;}};foot.append(cancel,confirm);d.box.append(text,foot);d.box.showModal();}catch(error){status(doc,main,`无法选择备份：${(error as Error).message}`);}};
  forbid(get<HTMLButtonElement>(doc,'#u36-clear'),'当前没有可单独核对的缓存清理入口');const data=get(doc,'#ui036 [data-panel="data"]');for(const button of data.querySelectorAll<HTMLButtonElement>('[data-export]'))if(button.dataset.export==='利润核算')button.onclick=async()=>{try{const result=await service('exportProfit',{filters:{},includePending:false});status(doc,main,result.canceled?'已取消导出':`已导出利润：${result.filename}`);}catch(error){status(doc,main,(error as Error).message);}};else forbid(button,'当前未提供这一类 XLSX 导出');
  data.querySelector<HTMLElement>('.version-row strong')!.textContent=version;get(doc,'#u36-login').remove();status(doc,main,'连接状态以实际服务为准；未核对时不会显示虚构账号、密钥或在线状态。');return()=>{};
}

export function installRestoredPage(doc:Document,win:Window,page:Page,options:Options):()=>void{
  const side=doc.querySelector<HTMLElement>('.connection,.wa');if(side)side.textContent='● WhatsApp · 请在订单详情核对';
  if(page==='inventory')return inventory(doc,win,options);
  if(page==='profit')return profit(doc,options);
  if(page==='product')return product(doc,options);
  if(page==='profit-detail')return dailyProfit(doc,options);
  if(page==='assistant')return assistant(doc);
  return settings(doc);
}
