export const migration001=Object.freeze({
  version:1,
  name:'initial_order_schema',
  statements:[
    `CREATE TABLE IF NOT EXISTS orders (
      id TEXT PRIMARY KEY,
      source TEXT NOT NULL CHECK (source IN ('shopplus_api','shopplus_excel','manual')),
      shopplus_order_no TEXT,
      order_sequence INTEGER,
      currency TEXT NOT NULL DEFAULT 'AED',
      order_status TEXT NOT NULL DEFAULT 'new',
      payment_status TEXT NOT NULL DEFAULT 'unknown',
      fulfillment_status TEXT NOT NULL DEFAULT 'unfulfilled',
      delivery_status TEXT NOT NULL DEFAULT 'unshipped',
      customer_first_name TEXT,
      customer_last_name TEXT,
      customer_full_name TEXT,
      customer_phone TEXT,
      customer_email TEXT,
      country TEXT,
      province TEXT,
      city TEXT,
      street TEXT,
      residence TEXT,
      postal_code TEXT,
      order_total INTEGER,
      product_total INTEGER,
      discount_amount INTEGER NOT NULL DEFAULT 0,
      buyer_note TEXT,
      order_note TEXT,
      shopplus_created_at TEXT,
      shopplus_paid_at TEXT,
      shopplus_shipped_at TEXT,
      shopplus_cancelled_at TEXT,
      profit_status TEXT NOT NULL DEFAULT 'pending' CHECK (profit_status IN ('final','pending','incomplete')),
      total_profit INTEGER,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS orders_shopplus_order_no_unique
      ON orders(shopplus_order_no)
      WHERE shopplus_order_no IS NOT NULL AND trim(shopplus_order_no) <> ''`,
    `CREATE TABLE IF NOT EXISTS packages (
      id TEXT PRIMARY KEY,
      order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      series_code TEXT NOT NULL,
      package_status TEXT NOT NULL CHECK (package_status IN ('unshipped','shipped_pending','signed','refused','cancelled_before_shipping')),
      shipping_fee INTEGER NOT NULL DEFAULT 0,
      shipping_fee_finalized INTEGER NOT NULL DEFAULT 0 CHECK (shipping_fee_finalized IN (0,1)),
      tracking_number TEXT,
      logistics_company TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(order_id,series_code)
    )`,
    `CREATE TABLE IF NOT EXISTS order_items (
      id TEXT PRIMARY KEY,
      order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      shopplus_sub_order_id TEXT,
      sku_code TEXT,
      product_name_snapshot TEXT NOT NULL,
      quantity INTEGER NOT NULL CHECK (quantity > 0),
      unit_list_price INTEGER NOT NULL CHECK (unit_list_price >= 0),
      unit_actual_price INTEGER NOT NULL CHECK (unit_actual_price >= 0),
      unit_cost_snapshot INTEGER CHECK (unit_cost_snapshot IS NULL OR unit_cost_snapshot >= 0),
      package_id TEXT NOT NULL REFERENCES packages(id) ON DELETE RESTRICT,
      allocated_shipping_fee INTEGER NOT NULL DEFAULT 0 CHECK (allocated_shipping_fee >= 0),
      line_revenue INTEGER NOT NULL CHECK (line_revenue >= 0),
      line_cost INTEGER CHECK (line_cost IS NULL OR line_cost >= 0),
      line_profit INTEGER,
      cost_source TEXT,
      needs_review INTEGER NOT NULL DEFAULT 0 CHECK (needs_review IN (0,1)),
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS order_items_order_id_index ON order_items(order_id)`,
    `CREATE INDEX IF NOT EXISTS packages_order_id_index ON packages(order_id)`,
    `CREATE TABLE IF NOT EXISTS order_events (
      id TEXT PRIMARY KEY,
      order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      package_id TEXT REFERENCES packages(id) ON DELETE CASCADE,
      event_type TEXT NOT NULL,
      old_value TEXT,
      new_value TEXT,
      event_time TEXT NOT NULL,
      note TEXT
    )`,
    `CREATE INDEX IF NOT EXISTS order_events_order_id_index ON order_events(order_id,event_time)`
  ]
});
