import {createHash} from 'node:crypto';
import {draftError} from './draft-orders.mjs';
import {structuredUpgrade} from './assistant-message-upgrade.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
export function validateMedia(value=[]){if(!Array.isArray(value)||value.length>4)throw draftError('图片数量无效');return value.map(m=>{if(!m||m.type!=='image'||!['cached','unavailable'].includes(m.status))throw draftError('图片状态无效');if(m.status==='cached'&&(typeof m.dataUrl!=='string'||m.dataUrl.length>1400000||!/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/]+=*$/.test(m.dataUrl)))throw draftError('图片格式无效或过大');return {type:'image',status:m.status,...(m.status==='cached'?{dataUrl:m.dataUrl}:{}),...(m.source==='attachment'?{source:'attachment'}:{}),note:m.status==='unavailable'?'图片未能下载或超过缓存限制；请在WhatsApp查看原图。':m.source==='attachment'?'已缓存聊天图片':'本地缩略图'};});}
export function parseTranscript(text,{dateOrder='dmy',timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone}={}){
 if(typeof text!=='string'||Buffer.byteLength(text)>5*1024*1024||!['dmy','mdy'].includes(dateOrder))throw draftError('聊天文件应小于5MB，请选择正确日期顺序');
 const entries=[];for(const line of text.replace(/[\u200e\u200f\u202a-\u202e\u2066-\u2069]/g,'').split(/\r?\n/)){const m=line.match(/^(?:\[)?(\d{1,4})[/.\-](\d{1,2})[/.\-](\d{1,4}),?\s+(\d{1,2}):(\d{2})(?::\d{2})?\s*(AM|PM)?(?:\]\s*|\s*-\s*)([^:]+):\s*(.*)$/i);if(m){let [,a,b,c,h,min,ap,sender,body]=m;let y=Number(c),month=Number(dateOrder==='dmy'?b:a),day=Number(dateOrder==='dmy'?a:b);if(a.length===4){y=Number(a);month=Number(b);day=Number(c);}if(y<100)y+=2000;h=Number(h);if(ap)h=h%12+(/pm/i.test(ap)?12:0);if(h>23||Number(min)>59||month<1||month>12||day<1||day>31)throw draftError('聊天文件中存在无效日期');
   const local=Date.UTC(y,month-1,day,h,Number(min));let utc=local;const f=new Intl.DateTimeFormat('en-CA',{timeZone,hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});for(let n=0;n<3;n++){const p=Object.fromEntries(f.formatToParts(new Date(utc)).map(p=>[p.type,Number(p.value)]));utc+=local-Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute);}const p=Object.fromEntries(f.formatToParts(new Date(utc)).map(p=>[p.type,Number(p.value)]));if(p.year!==y||p.month!==month||p.day!==day)throw draftError('聊天文件日期或时区无法核对');entries.push({sender:sender.trim(),sentAt:new Date(utc).toISOString(),text:body});
  }else if(entries.length)entries.at(-1).text+='\n'+line;
 }
 if(!entries.length||entries.length>50000||entries.some(e=>e.text.length>16000))throw draftError('没有识别到聊天记录，或文件超出50000条/单条16000字限制');return entries;
}
export class AssistantHistory{
 constructor(app,assistant){this.app=app;this.assistant=assistant;this.db=app.database;this.busy=new Set();this.cancelled=new Set();}
 target(orderId){const b=this.assistant.row(orderId);if(!b.account_id||!b.chat_id)throw draftError('请先关联并核对当前聊天');return b;}
 progress(b){return this.db.prepare('SELECT * FROM assistant_chat_progress WHERE account_id=? AND chat_id=?').get(b.account_id,b.chat_id)||{revision:0,payload:'{}'};}
 state({orderId,before=null,limit=80,query=''}){const b=this.target(orderId);if(!Number.isSafeInteger(limit)||limit<1||limit>200||typeof query!=='string'||query.length>200)throw draftError('历史查看参数无效');let clause='',args=[b.account_id,b.chat_id];if(before){if(typeof before.sentAt!=='string'||typeof before.id!=='string')throw draftError('历史分页位置无效');clause+=' AND (sent_at<? OR (sent_at=? AND message_id<?))';args.push(before.sentAt,before.sentAt,before.id);}if(query){clause+=" AND instr(body,?)>0";args.push(query);}const rows=this.db.prepare(`SELECT message_id id,direction,sent_at sentAt,body text,metadata FROM assistant_chat_archive WHERE account_id=? AND chat_id=?${clause} ORDER BY sent_at DESC,message_id DESC LIMIT ?`).all(...args,limit+1),messages=rows.slice(0,limit).reverse().map(({metadata,...m})=>({...m,media:JSON.parse(metadata||'{}').media||[],incomplete:Boolean(JSON.parse(metadata||'{}').incomplete),syncNote:JSON.parse(metadata||'{}').note||null})),first=messages[0];return {messages,hasOlder:rows.length>limit,before:rows.length>limit?{id:first.id,sentAt:first.sentAt}:null,count:Number(this.db.prepare('SELECT count(*) n FROM assistant_chat_archive WHERE account_id=? AND chat_id=?').get(b.account_id,b.chat_id).n),progress:JSON.parse(this.progress(b).payload),note:'历史查看不扩大本单提取范围。网页历史能否读全取决于页面实际提供的记录；不能据此保证从第一条开始。'};}
 save(b,messages,progress){if(!Array.isArray(messages)||messages.length>50000||Buffer.byteLength(JSON.stringify(messages))>20*1024*1024)throw draftError('历史批次超过大小限制');const p=this.progress(b);return this.app.drafts.repo.transaction(()=>{if(this.assistant.row(b.order_id).binding_revision!==b.binding_revision)throw draftError('读取期间关联已改变，结果未保存');if(this.progress(b).revision!==p.revision)throw draftError('另一个订单已更新同客历史，请重新同步');let added=0;for(const m of messages){if(!m||m.accountId!==undefined&&m.accountId!==b.account_id||m.chatId!==undefined&&m.chatId!==b.chat_id||typeof m.id!=='string'||!m.id||m.id.length>200||!['customer','merchant'].includes(m.direction)||!Number.isFinite(Date.parse(m.sentAt))||typeof m.text!=='string'||m.text.length>16000)throw draftError('历史消息校验失败');const metadata={source:m.metadata?.source||'whatsapp-web',timePrecision:m.metadata?.timePrecision||'minute',...(['whatsapp-structured','whatsapp-wwebjs'].includes(m.metadata?.source)?{messageType:m.metadata.messageType}:{}),mediaCachedAt:this.app.now().toISOString(),media:validateMedia(m.metadata?.media),incomplete:Boolean(m.metadata?.incomplete),note:m.metadata?.incomplete?String(m.metadata.note||'未完整同步的消息内容，请在 WhatsApp 核对。').slice(0,300):null};const old=this.db.prepare('SELECT * FROM assistant_chat_archive WHERE account_id=? AND chat_id=? AND message_id=?').get(b.account_id,b.chat_id,m.id);const correction=old?structuredUpgrade(old,m):null;if(old&&!correction.allowed)throw draftError('历史消息已编辑，原记录保留，请在原聊天核对');if(old){const previous=JSON.parse(old.metadata||'{}'),upgrade=metadata.media.some(m=>m.status==='cached')&&(!previous.media?.some(m=>m.status==='cached')||metadata.media.some(m=>m.status==='cached'&&m.source==='attachment')&&!previous.media?.some(m=>m.status==='cached'&&m.source==='attachment'));if(upgrade||metadata.incomplete&&!previous.incomplete||correction.changed||correction.decrypted)this.db.prepare('UPDATE assistant_chat_archive SET body=?,sent_at=?,metadata=? WHERE account_id=? AND chat_id=? AND message_id=?').run(m.text,m.sentAt,JSON.stringify({...previous,...metadata,media:upgrade?metadata.media:previous.media||metadata.media,incomplete:correction.decrypted?false:Boolean(previous.incomplete||metadata.incomplete),note:correction.decrypted?null:metadata.note||previous.note||null}),b.account_id,b.chat_id,m.id);}added+=Number(this.db.prepare('INSERT OR IGNORE INTO assistant_chat_archive VALUES(?,?,?,?,?,?,?)').run(b.account_id,b.chat_id,m.id,m.direction,m.sentAt,m.text,JSON.stringify(metadata)).changes);}this.db.prepare('INSERT INTO assistant_chat_progress VALUES(?,?,?,1) ON CONFLICT(account_id,chat_id) DO UPDATE SET payload=excluded.payload,revision=revision+1').run(b.account_id,b.chat_id,JSON.stringify(progress));return added;});}
 cancel({orderId}){this.cancelled.add(orderId);return {cancelRequested:true};}
 async sync({orderId,direction='latest',historyConsent=false,initial=false}){const b=this.target(orderId);if(this.busy.has(orderId))throw draftError('历史正在同步');if(!this.assistant.chat?.readHistory)throw draftError('此聊天渠道尚不支持历史读取，可导入WhatsApp导出的TXT');if(this.assistant.chat.mode==='browser'&&!historyConsent&&!JSON.parse(this.progress(b).payload).historyConsent)throw draftError('首次补齐客户历史需要确认读取范围；原订单未修改');this.busy.add(orderId);this.cancelled.delete(orderId);this.assistant.invalidateRead(orderId,b.binding_revision,'聊天正在同步，请完成本轮同步后再提取或拟回复；人工草稿保留。',b.read_revision);let batches=0,added=0;
  try{await this.assistant.chat.readHistory({accountId:b.account_id,chatId:b.chat_id,binding:JSON.parse(b.browser_binding||'null'),direction,initial,progress:JSON.parse(this.progress(b).payload),cancelled:()=>this.cancelled.has(orderId),mediaLookup:async id=>{const old=this.db.prepare('SELECT metadata FROM assistant_chat_archive WHERE account_id=? AND chat_id=? AND message_id=?').get(b.account_id,b.chat_id,id);return JSON.parse(old?.metadata||'{}').media?.find(m=>m.status==='cached'&&m.source==='attachment');},onBatch:async(messages,progress)=>{added+=this.save(b,messages,{...JSON.parse(this.progress(b).payload),...progress,historyConsent:historyConsent||JSON.parse(this.progress(b).payload).historyConsent||false,batches:++batches,updatedAt:this.app.now().toISOString(),source:'web'});this.assistant.policy.cleanupMedia();}});return {...this.state({orderId}),added};}catch(error){if(this.assistant.row(orderId).binding_revision===b.binding_revision){const old=JSON.parse(this.progress(b).payload);this.save(b,[],{...old,complete:false,status:'failed',note:'本轮同步未完成，成功批次已保留；'+String(error.message).slice(0,300)});this.assistant.invalidateRead(orderId,b.binding_revision,'聊天同步未完成；已保存记录和草稿保留，暂不使用旧上下文提取或拟回复。',this.assistant.row(orderId).read_revision);}throw error;}finally{this.busy.delete(orderId);this.cancelled.delete(orderId);}
 }
 async refresh({orderId,historyConsent=false,direction='latest',initial=false}){
  const b=this.target(orderId),chat=this.assistant.chat;
  if(!['latest','older'].includes(direction))throw draftError('聊天同步方向无效');
  if(!chat?.readHistory||chat.restriction){const result=await this.assistant.read({orderId});return {...result,syncNotice:'已更新本单授权范围；此连接不支持或未授权完整历史读取。'};}
  const previous=JSON.parse(this.progress(b).payload);
  if(chat.mode==='browser'&&!previous.historyConsent&&!historyConsent)throw draftError('首次补齐客户历史需要确认读取范围；原订单未修改');
  await this.sync({orderId,direction,initial,historyConsent:historyConsent||previous.historyConsent});
  await this.apply({orderId,bindingRevision:b.binding_revision});
  const state=this.state({orderId});return {...this.assistant.status({orderId}),syncNotice:`已保存客户聊天 ${state.count} 条；`+(state.progress.note||'历史覆盖尚未确认。'),history:state};
 }
 import({orderId,text,ownSender,dateOrder,timeZone}){if(this.busy.has(orderId))throw draftError('历史正在同步，请结束后再导入');const b=this.target(orderId);if(typeof ownSender!=='string'||!ownSender.trim()||ownSender.length>200)throw draftError('请填写导出聊天中我方的准确名称');const entries=parseTranscript(text,{dateOrder,timeZone}),senders=[...new Set(entries.map(e=>e.sender))];if(senders.length>2||!senders.includes(ownSender)||senders.length<2)throw draftError('仅支持已核对的一对一聊天；我方名称必须与文件一致');const occurrences=new Map(),messages=entries.map(e=>{const key=JSON.stringify(e),occurrence=(occurrences.get(key)||0)+1;occurrences.set(key,occurrence);return {id:'export:'+hash(key+':'+occurrence),direction:e.sender===ownSender?'merchant':'customer',sentAt:e.sentAt,text:e.text,metadata:{source:'whatsapp-export',timePrecision:'minute'}};});const added=this.save(b,messages,{source:'export',complete:false,fileComplete:true,earliest:messages[0].sentAt,latest:messages.at(-1).sentAt,note:'已导入文件全部记录；无法证明该文件包含账号全部历史。附件需在原聊天查看。',updatedAt:this.app.now().toISOString()});return {...this.state({orderId}),added};}
 async apply({orderId,bindingRevision}){if(this.busy.has(orderId))throw draftError('历史正在同步，请结束后再应用至本单');const b=this.target(orderId);if(bindingRevision!==undefined&&bindingRevision!==b.binding_revision)throw draftError('读取期间关联已改变，未写入本单');const from=b.scope_start,to=b.scope_end_mode==='latest'?this.app.now().toISOString():b.scope_end;const rows=this.db.prepare('SELECT message_id id,direction,sent_at sentAt,body text,metadata FROM assistant_chat_archive WHERE account_id=? AND chat_id=? AND sent_at>=? AND sent_at<=? ORDER BY sent_at,message_id').all(b.account_id,b.chat_id,from,to);if(rows.length>5000)throw draftError('本单范围超过5000条，请缩小订单范围；历史仍可查看');let added=0,corrected=0;const p=JSON.parse(this.progress(b).payload),unfinished=p.reader==='structured'&&(['running','paused','cancelled','failed'].includes(p.status)||!(p.boundary?.noEarlierMsgs&&(p.boundary?.endOfHistoryTransfer||p.boundary?.webTopLoaded))&&(!p.earliest||p.earliest>from));const issue=unfinished?'本单范围尚未完整同步；成功批次与草稿保留，请人工继续同步后再提取或拟回复。':rows.some(m=>JSON.parse(m.metadata||'{}').incomplete)?'本单含未完整同步的非文字、引用或编辑内容；请在 WhatsApp 核对，暂不使用这些记录自动拟回复或提取。':null;this.app.drafts.repo.transaction(()=>{for(const m of rows){const old=this.db.prepare('SELECT * FROM order_chat_messages WHERE order_id=? AND binding_revision=? AND message_id=?').get(orderId,b.binding_revision,m.id);const correction=old?structuredUpgrade(old,{...m,metadata:JSON.parse(m.metadata||'{}')}):null;if(old&&!correction.allowed)throw draftError('本单消息与历史版本冲突，未写入');if(old&&(correction.changed||correction.decrypted)){corrected++;this.db.prepare('UPDATE order_chat_messages SET body=?,sent_at=?,metadata=? WHERE order_id=? AND binding_revision=? AND message_id=?').run(m.text,m.sentAt,m.metadata,orderId,b.binding_revision,m.id);}added+=Number(this.db.prepare('INSERT OR IGNORE INTO order_chat_messages VALUES(?,?,?,?,?,?,?)').run(orderId,b.binding_revision,m.id,m.direction,m.sentAt,m.text,m.metadata).changes);if(JSON.parse(m.metadata||'{}').incomplete)this.db.prepare('UPDATE order_chat_messages SET metadata=? WHERE order_id=? AND binding_revision=? AND message_id=?').run(m.metadata,orderId,b.binding_revision,m.id);}const changed=added>0||corrected>0||issue!==b.read_issue;this.db.prepare('UPDATE order_assistant SET scope_end=?,last_read_at=?,read_issue=?,read_revision=read_revision+?,result=CASE WHEN ? THEN NULL ELSE result END WHERE order_id=?').run(to,this.app.now().toISOString(),issue,changed?1:0,changed?1:0,orderId);});return this.assistant.status({orderId});}
}
