import {effectiveRecipientOrder} from './order-recipient.mjs';
import {randomUUID} from 'node:crypto';
import {OrderRepository} from './order-repository.mjs';
import {OrderService} from './order-service.mjs';
import {classifySeries} from './series-classifier.mjs';
import {validateRecipientForTxt} from './package-report.mjs';
export const DRAFT_FIELDS={fullName:'customer_full_name',phone:'customer_phone',email:'customer_email',country:'country',province:'province',city:'city',street:'street',residence:'residence'};
export const draftError=message=>Object.assign(new Error(message),{code:'DRAFT_VALIDATION',stage:'聊单草稿'});
export const nullableMoney=value=>{if(value===null||value===undefined||value==='')return null;if(typeof value!=='string'||!/^\d+(?:\.\d{1,2})?$/.test(value))throw draftError('金额必须为非负金额，最多两位小数');const [whole,fraction='']=value.split('.'),n=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'));if(n>BigInt(Number.MAX_SAFE_INTEGER))throw draftError('金额超出范围');return Number(n);};
export const asMoney=value=>value===null?'':`${Math.floor(value/100)}.${String(value%100).padStart(2,'0')}`;
export function insertRecord(db,table,record){const keys=Object.keys(record);db.prepare(`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).run(...keys.map(k=>record[k]??null));}
export class DraftOrders{
 constructor(app){this.app=app;this.db=app.database;this.repo=new OrderRepository(this.db);}
 order(id){const row=this.db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!row)throw draftError('找不到订单');return row;}
 assertDraft(id,revision){const row=this.order(id);if(row.entry_state!=='draft'||row.order_confirmed)throw draftError('已确认订单只能生成建议，不能自动补全');if(revision!==undefined&&revision!==row.draft_revision)throw draftError('资料已改变，请重新打开后核对');return row;}
 items(id){return this.db.prepare('SELECT * FROM order_draft_items WHERE order_id=? ORDER BY position').all(id);}
 state(id){const stored=this.order(id),order=stored.entry_state==='active'?effectiveRecipientOrder(stored,this.repo.recipientOverrides(id)):stored;return {fields:Object.fromEntries(Object.entries(DRAFT_FIELDS).map(([key,column])=>[key,order[column]])),items:this.items(id),sources:this.db.prepare('SELECT * FROM order_field_sources WHERE order_id=?').all(id)};}
 event(id,type){this.db.prepare('INSERT INTO order_events(id,order_id,event_type,event_time) VALUES(?,?,?,?)').run(randomUUID(),id,type,this.app.now().toISOString());}
 create({requestId}={}){if(typeof requestId!=='string'||!/^[\w-]{8,100}$/.test(requestId))throw draftError('新建请求标识无效');return this.repo.transaction(()=>{const old=this.db.prepare('SELECT id FROM orders WHERE draft_request_id=?').get(requestId);if(old)return this.app.detail({id:old.id});const id=randomUUID(),at=this.app.now().toISOString(),report=this.repo.allocateOrderReport(at);insertRecord(this.db,'orders',{id,source:'manual',entry_state:'draft',draft_request_id:requestId,fixed_sequence:this.repo.allocateFixedSequence(),order_status:'draft',created_at:at,updated_at:at,...report});this.db.prepare('INSERT INTO order_assistant(order_id) VALUES(?)').run(id);this.event(id,'draft_created');return this.app.detail({id});});}
 source(id,field,source,evidence=null){this.db.prepare('INSERT INTO order_field_sources(order_id,field,source,evidence,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(order_id,field) DO UPDATE SET source=excluded.source,evidence=excluded.evidence,updated_at=excluded.updated_at').run(id,field,source,evidence?JSON.stringify(evidence):null,this.app.now().toISOString());}
 invalidate(id){this.db.prepare('DELETE FROM order_address_verifications WHERE order_id=?').run(id);this.db.prepare('DELETE FROM order_delivery_verifications WHERE order_id=?').run(id);this.app.invalidateReport(id);}
 async prepareItems(id,items,source='manual'){
  if(!Array.isArray(items)||items.length>100)throw draftError('商品明细无效');const previous=this.items(id),catalog=await this.app.costCatalogLoader(this.app.userDataPath),seen=new Set();return items.map((item,position)=>{const sku=String(item.sku??'').trim().toUpperCase();if(!/^(?:\d+|[A-Z]+[A-Z0-9-]*)$/.test(sku)||sku.length>80||classifySeries(sku).needsReview||seen.has(sku))throw draftError('商品编号无效或重复；同商品请修改数量');seen.add(sku);if(!Number.isSafeInteger(item.quantity)||item.quantity<=0||item.quantity>100000)throw draftError('数量必须为正整数');const price=nullableMoney(item.price),discount=nullableMoney(item.discount),old=previous.find(row=>row.sku===sku),cost=old||catalog.resolve({candidates:[{value:sku}]});if(price!==null&&(!Number.isSafeInteger(price*item.quantity)||!Number.isSafeInteger((price+(discount??0))*item.quantity)))throw draftError('商品金额超出范围');return {id:old?.id||randomUUID(),order_id:id,position,sku,quantity:item.quantity,price_fils:price,discount_fils:discount,cost_fils:old?old.cost_fils:cost.status==='matched'?cost.costFils:null,cost_source:old?old.cost_source:cost.status==='matched'?cost.costSource:null,source};});
 }
 write(id,fields,items,{source='manual',evidence={}}={}){
  for(const [field,value] of Object.entries(fields)){if(!Object.hasOwn(DRAFT_FIELDS,field)||value!==null&&typeof value!=='string'||String(value??'').length>500)throw draftError('客户字段无效');const normalized=value===''?null:value;if(this.order(id)[DRAFT_FIELDS[field]]===normalized)continue;this.db.prepare(`UPDATE orders SET ${DRAFT_FIELDS[field]}=? WHERE id=?`).run(normalized,id);this.source(id,field,source,evidence[field]);}
  if(items){this.db.prepare('DELETE FROM order_draft_items WHERE order_id=?').run(id);for(const item of items)insertRecord(this.db,'order_draft_items',item);this.source(id,'items',source,evidence.items);}
  const rows=this.items(id),total=rows.length&&rows.every(row=>row.price_fils!==null)?rows.reduce((n,row)=>n+row.price_fils*row.quantity,0):null;if(total!==null&&!Number.isSafeInteger(total))throw draftError('订单金额超出范围');this.db.prepare('UPDATE orders SET order_total=?,product_total=?,draft_revision=draft_revision+1,updated_at=? WHERE id=?').run(total,total,this.app.now().toISOString(),id);this.invalidate(id);
 }
 async save({orderId,revision,fields={},items}={}){const initial=this.assertDraft(orderId,revision);revision??=initial.draft_revision;const prepared=items===undefined?undefined:await this.prepareItems(orderId,items);return this.repo.transaction(()=>{this.assertDraft(orderId,revision);this.write(orderId,fields,prepared);this.event(orderId,'draft_manually_saved');return this.app.detail({id:orderId});});}
 async matchCosts({orderId,revision}){this.assertDraft(orderId,revision);const catalog=await this.app.costCatalogLoader(this.app.userDataPath);return this.repo.transaction(()=>{this.assertDraft(orderId,revision);const items=this.items(orderId).map(item=>{if(item.cost_fils!==null)return item;const match=catalog.resolve({candidates:[{value:item.sku}]});return match.status==='matched'?{...item,cost_fils:match.costFils,cost_source:match.costSource}:item;});this.write(orderId,{},items);this.event(orderId,'draft_missing_costs_matched');return this.app.detail({id:orderId});});}
 activate({orderId,note}={}){return this.repo.transaction(()=>{const row=this.assertDraft(orderId),items=this.items(orderId),recipient=validateRecipientForTxt(row);if(recipient.problems.length)throw draftError(recipient.problems.map(p=>p.label).join('；'));if(!items.length||items.some(i=>i.price_fils===null||i.cost_fils===null))throw draftError('请补全商品、成交单价及成本快照');if(!String(note??'').trim())throw draftError('请记录客户确认依据');
  // Build with the existing series, cost and fee rules; keep the original order identity.
  const capture=new OrderRepository(this.db);let graph;capture.insertOrderGraph=value=>{graph=value;return value.order;};new OrderService(capture,{clock:()=>this.app.now()}).createOrder({...row,order_total:asMoney(row.order_total),product_total:asMoney(row.product_total),discount_amount:'0',items:items.map(i=>({sku_code:i.sku,product_name_snapshot:i.sku,quantity:i.quantity,unit_list_price:asMoney(i.price_fils+(i.discount_fils??0)),unit_actual_price:asMoney(i.price_fils),unit_cost_snapshot:asMoney(i.cost_fils),cost_source:i.cost_source}))});
  for(const p of graph.packages)insertRecord(this.db,'packages',{...p,order_id:orderId});for(const i of graph.items){const draft=items.find(row=>row.sku===i.sku_code),discount=draft.discount_fils===null?null:draft.discount_fils*draft.quantity;insertRecord(this.db,'order_items',{...i,order_id:orderId,manual_discount:discount,discount_input_value:discount??0});}this.db.prepare('UPDATE orders SET discount_amount=? WHERE id=?').run(items.every(i=>i.discount_fils!==null)?items.reduce((sum,i)=>sum+i.discount_fils*i.quantity,0):null,orderId);const keep=['profit_status','total_profit','projected_profit','realized_profit','profit_review_required','exchange_rate_rule_id','exchange_rate_version','exchange_rate_scaled','exchange_rate_scale','projected_rmb_settlement','realized_rmb_settlement','rmb_settlement_status'];this.db.prepare(`UPDATE orders SET ${keep.map(k=>k+'=?').join(',')},entry_state='active',order_status='new',draft_revision=draft_revision+1 WHERE id=?`).run(...keep.map(k=>graph.order[k]),orderId);this.repo.confirmOrder({orderId,confirmedAt:this.app.now().toISOString(),note,eventId:randomUUID()});this.event(orderId,'draft_activated');this.app.reports.clear();return this.app.detail({id:orderId});});}
}
