import {randomUUID} from 'node:crypto';
import {groupItemsBySeries} from './series-classifier.mjs';
import {classifyDeliveryZone} from './delivery-zone-classifier.mjs';
import {calculatePackage,calculateOrder,moneyToFils} from './profit-calculation.mjs';
import {FinancialRuleRepository,feeSnapshot} from './financial-rules.mjs';
import {isRealizedPackageStatus} from './shipping-calculation.mjs';
import {validateOrderInput,validatePackageStatus} from './order-validation.mjs';

function integer(value,label){if(value===null||value===undefined)return null;const amount=BigInt(value);if(amount>BigInt(Number.MAX_SAFE_INTEGER)||amount<BigInt(Number.MIN_SAFE_INTEGER))throw new RangeError(`${label}超出SQLite安全整数范围`);return Number(amount);}
const optional=value=>value===undefined||value===null||value===''?null:value;
const bigintOrNull=value=>value===null||value===undefined?null:BigInt(value);
const optionalMoney=value=>value===undefined||value===null||value===''?null:moneyToFils(value);
const terminalStatuses=new Set(['signed','refused','cancelled_before_outbound','cancelled_after_outbound']);
export function aggregateOrderDeliveryStatus(packages=[]){const statuses=packages.map(value=>value.package_status),unique=[...new Set(statuses)];if(!unique.length)return 'unshipped';if(unique.length===1)return unique[0];const terminal=statuses.filter(value=>terminalStatuses.has(value)).length;if(terminal===statuses.length)return 'completed_mixed';if(terminal>0)return 'partial_complete';if(statuses.includes('shipped_pending')||statuses.includes('outbound_processing'))return 'outbound_processing';return 'unshipped';}
export function allocatePackageDiscount(items,totalDiscount){
  const discount=BigInt(totalDiscount),rows=items.map(item=>({quantity:BigInt(item.quantity),gross:BigInt(item.line_gross)})),grossTotal=rows.reduce((sum,row)=>sum+row.gross,0n);if(discount<0n||discount>grossTotal)throw new RangeError('包裹优惠必须在0和商品金额之间');if(!rows.length)throw new TypeError('包裹没有商品');
  for(let lastIndex=0;lastIndex<rows.length;lastIndex++){
    const allocated=rows.map((row,index)=>index===lastIndex?0n:((grossTotal?discount*row.gross/grossTotal:0n)/row.quantity)*row.quantity),sum=allocated.reduce((value,row)=>value+row,0n),last=discount-sum,lastRow=rows[lastIndex];if(last>=0n&&last<=lastRow.gross&&last%lastRow.quantity===0n){allocated[lastIndex]=last;return allocated;}
    for(let adjustIndex=0;adjustIndex<rows.length;adjustIndex++){if(adjustIndex===lastIndex)continue;const row=rows[adjustIndex],base=allocated[adjustIndex];for(let step=-256;step<=256;step++){const adjusted=base+BigInt(step)*row.quantity;if(adjusted<0n||adjusted>row.gross)continue;const candidateLast=discount-(sum-base+adjusted);if(candidateLast>=0n&&candidateLast<=lastRow.gross&&candidateLast%lastRow.quantity===0n){allocated[adjustIndex]=adjusted;allocated[lastIndex]=candidateLast;return allocated;}}}
  }throw new RangeError('包裹优惠无法按商品数量精确分摊到分，请调整优惠金额');
}

export class OrderService {
  constructor(repository,{clock=()=>new Date(),idFactory=randomUUID,rules=new FinancialRuleRepository(repository.database)}={}){this.repository=repository;this.clock=clock;this.idFactory=idFactory;this.rules=rules;}
  ruleContext(at,ruleSetId=null){
    const ruleSet=ruleSetId?this.rules.feeRuleSet(ruleSetId):this.rules.activeFeeRuleSet(at),exchangeRate=this.rules.activeExchangeRate(at);
    if(!ruleSet)throw new Error('没有可用的运输费用规则');return {ruleSet,exchangeRate};
  }
  feesFor({ruleSetId,zone,status,projectedFeeSnapshot=null,manualFee=null,includeDisabled=false}){
    const ruleSet=this.rules.feeRuleSet(ruleSetId),manualActual=ruleSet?.fee_mode==='manual_actual',projectedRule=manualActual?null:this.rules.feeRule({ruleSetId,zone,status:'signed',includeDisabled}),projectedFee=manualActual?null:projectedFeeSnapshot===null?feeSnapshot(projectedRule):{totalFeeFils:BigInt(projectedFeeSnapshot)};
    if(manualFee)return {projectedRule,projectedFee,realizedRule:null,realizedFee:manualFee,finalized:true};
    const automaticZero=manualActual&&status==='cancelled_before_outbound',realizedRule=isRealizedPackageStatus(status)&&(automaticZero||!manualActual)?this.rules.feeRule({ruleSetId,zone,status,includeDisabled}):null,realizedFee=feeSnapshot(realizedRule);
    return {projectedRule,projectedFee,realizedRule,realizedFee,finalized:Boolean(realizedFee)};
  }
  createOrder(input){
    validateOrderInput(input);const now=this.clock().toISOString(),orderId=this.idFactory(),groups=groupItemsBySeries(input.items),zone=classifyDeliveryZone({city:input.city,province:input.province,state:input.state,override:input.delivery_zone_override}),{ruleSet,exchangeRate}=this.ruleContext(now),packages=[],items=[];
    const calculatedPackages=groups.map(group=>{
      const explicitStatuses=new Set(group.items.map(item=>item.package_status).filter(Boolean));if(explicitStatuses.size>1)throw new TypeError(`同一${group.seriesCode}包裹不能有多个状态`);
      const status=[...explicitStatuses][0]||input.delivery_status||'unshipped',fees=this.feesFor({ruleSetId:ruleSet.id,zone:zone.zone,status}),fixedZoneRequired=ruleSet.fee_mode!=='manual_actual'&&!status.startsWith('cancelled_'),calculated=calculatePackage({items:group.items,status,projectedFee:fees.projectedFee,realizedFee:fees.realizedFee,feeFinalized:fees.finalized,
        packageNeedsReview:group.needsReview||(zone.zone==='unclassified'&&fixedZoneRequired)}),packageId=this.idFactory();
      packages.push({id:packageId,order_id:orderId,series_code:group.seriesCode,package_status:status,delivery_zone:zone.zone,projected_shipping_fee:integer(calculated.projectedFeeFils,'预计运费'),
        shipping_fee:integer(calculated.realizedFeeFils,'实际运费'),delivery_fee:integer(fees.realizedFee?.deliveryFeeFils??0n,'派送费'),handling_fee:integer(fees.realizedFee?.handlingFeeFils??0n,'出库费'),
        shipping_fee_finalized:calculated.shippingFeeFinalized?1:0,fee_rule_set_id:ruleSet.id,fee_rule_version:ruleSet.version,fee_rule_id:fees.realizedRule?.id||null,fee_overridden:0,fee_override_reason:null,
        fee_overridden_at:null,fee_confirmation_source:null,fee_confirmed_at:null,fee_confirmation_note:null,fee_dispute_note:status==='fee_dispute'?optional(input.fee_dispute_note):null,legacy_shipping_fee:null,tracking_number:optional(input.tracking_number),logistics_company:optional(input.logistics_company),status_updated_at:now,created_at:now,updated_at:now});
      calculated.items.forEach(item=>items.push(this.itemRecord({item,orderId,packageId,now,itemSequence:item.sourceIndex+1,groupNeedsReview:group.needsReview})));
      return calculated;
    });
    const result=calculateOrder(calculatedPackages,{exchangeRate}),productTotal=input.product_total===undefined||input.product_total===null?calculatedPackages.flatMap(value=>value.items).reduce((sum,item)=>sum+item.lineRevenueFils,0n):moneyToFils(input.product_total),orderTotal=input.order_total===undefined||input.order_total===null?productTotal:moneyToFils(input.order_total),discount=moneyToFils(input.discount_amount??'0');
    const order={id:orderId,source:input.source,shopplus_order_no:optional(input.shopplus_order_no?.trim()),order_sequence:input.order_sequence??null,currency:input.currency||'AED',order_status:input.order_status||'new',payment_status:input.payment_status||'unknown',fulfillment_status:input.fulfillment_status||'unfulfilled',delivery_status:aggregateOrderDeliveryStatus(packages),
      customer_first_name:optional(input.customer_first_name),customer_last_name:optional(input.customer_last_name),customer_full_name:optional(input.customer_full_name),customer_phone:optional(input.customer_phone),customer_email:optional(input.customer_email),country:optional(input.country),province:optional(input.province),city:optional(input.city),street:optional(input.street),residence:optional(input.residence),postal_code:optional(input.postal_code),
      order_total:integer(orderTotal,'订单总额'),product_total:integer(productTotal,'商品总额'),discount_amount:integer(discount,'优惠金额'),buyer_note:optional(input.buyer_note),order_note:optional(input.order_note),shopplus_created_at:optional(input.shopplus_created_at),shopplus_paid_at:optional(input.shopplus_paid_at),shopplus_shipped_at:optional(input.shopplus_shipped_at),shopplus_cancelled_at:optional(input.shopplus_cancelled_at),
      profit_status:result.profitStatus,total_profit:integer(result.realizedProfitFils,'实际利润'),projected_profit:integer(result.projectedProfitFils,'预计利润'),realized_profit:integer(result.realizedProfitFils,'实际利润'),legacy_total_profit:null,profit_review_required:result.profitStatus==='incomplete'?1:0,
      exchange_rate_rule_id:exchangeRate?.id||null,exchange_rate_version:exchangeRate?.version||null,exchange_rate_scaled:exchangeRate?.rate_scaled??null,exchange_rate_scale:exchangeRate?.scale??null,projected_rmb_settlement:integer(result.projectedRmbFen,'预计人民币结算'),realized_rmb_settlement:integer(result.realizedRmbFen,'实际人民币结算'),rmb_settlement_status:result.rmbSettlementStatus,
      import_batch_id:optional(input.import_batch_id),source_file_name:optional(input.source_file_name),source_file_sha256:optional(input.source_file_sha256),imported_at:optional(input.imported_at),shopplus_site_id:optional(input.shopplus_site_id),shopplus_order_sequence_text:optional(input.shopplus_order_sequence_text),
      aftersale_status:optional(input.aftersale_status),repaid_status:optional(input.repaid_status),channel_source:optional(input.channel_source),payment_method:optional(input.payment_method),website_domain:optional(input.website_domain),customer_shipping_fee:integer(optionalMoney(input.customer_shipping_fee),'客户物流费'),tax_amount:integer(optionalMoney(input.tax_amount),'税费'),shipping_insurance:integer(optionalMoney(input.shipping_insurance),'运费险'),tip_amount:integer(optionalMoney(input.tip_amount),'小费'),fixed_discount_amount:integer(optionalMoney(input.fixed_discount_amount),'一口价优惠'),door_number:optional(input.door_number),customer_data_fallback:input.customer_data_fallback?1:0,
      billing_first_name:optional(input.billing_first_name),billing_last_name:optional(input.billing_last_name),billing_full_name:optional(input.billing_full_name),billing_phone:optional(input.billing_phone),billing_email:optional(input.billing_email),billing_country:optional(input.billing_country),billing_province:optional(input.billing_province),billing_city:optional(input.billing_city),billing_street:optional(input.billing_street),billing_residence:optional(input.billing_residence),billing_postal_code:optional(input.billing_postal_code),billing_door_number:optional(input.billing_door_number),order_confirmed:0,order_confirmed_at:null,order_confirmation_note:null,net_remittance:null,remittance_registered_at:null,workflow_completed_at:null,created_at:now,updated_at:now};
    const events=[{id:this.idFactory(),order_id:orderId,package_id:null,event_type:'order_created',old_value:null,new_value:order.order_status,event_time:now,note:null},...packages.map(value=>({id:this.idFactory(),order_id:orderId,package_id:value.id,event_type:'package_created',old_value:null,new_value:value.package_status,event_time:now,note:null})),
      ...(input.delivery_zone_override?packages.map(value=>({id:this.idFactory(),order_id:orderId,package_id:value.id,event_type:'delivery_zone_overridden',old_value:null,new_value:zone.zone,event_time:now,note:'manual delivery zone override'})):[]),
      ...(input.source==='shopplus_excel'?[{id:this.idFactory(),order_id:orderId,package_id:null,event_type:'shopplus_excel_imported',old_value:null,new_value:input.shopplus_order_no||null,event_time:now,note:input.source_file_sha256?`file_sha256:${input.source_file_sha256}`:null}]:[])];
    return this.repository.insertOrderGraph({order,packages,items,events});
  }
  itemRecord({item,orderId,packageId,now,itemSequence=item.item_sequence,groupNeedsReview=false}){
    return {id:item.id||this.idFactory(),order_id:orderId,item_sequence:itemSequence,shopplus_sub_order_id:optional(item.shopplus_sub_order_id),sku_code:optional(item.normalizedSku||item.sku_code),product_name_snapshot:item.product_name_snapshot,quantity:item.quantity,
      unit_list_price:integer(item.unitListPriceFils,'标价'),unit_actual_price:integer(item.unitActualPriceFils,'实付价'),unit_cost_snapshot:integer(item.unitCostFils,'成本'),package_id:packageId,
      allocated_shipping_fee:integer(item.realizedAllocatedShippingFeeFils??0n,'实际分摊运费'),line_revenue:integer(item.lineRevenueFils,'计划商品收入'),line_cost:integer(item.lineCostFils,'成本快照合计'),line_profit:integer(item.realizedLineProfitFils,'实际商品利润'),
      projected_allocated_shipping_fee:integer(item.projectedAllocatedShippingFeeFils,'预计分摊运费'),realized_allocated_shipping_fee:integer(item.realizedAllocatedShippingFeeFils,'实际分摊运费'),projected_line_profit:integer(item.projectedLineProfitFils,'预计商品利润'),
      realized_line_revenue:integer(item.realizedLineRevenueFils,'实际收入'),realized_line_cost:integer(item.realizedLineCostFils,'实际销售成本'),realized_line_profit:integer(item.realizedLineProfitFils,'实际商品利润'),legacy_allocated_shipping_fee:null,legacy_line_profit:null,
      cost_source:optional(item.cost_source),needs_review:item.needsReview||groupNeedsReview?1:0,source_excel_row:item.source_excel_row??null,source_sku_id:optional(item.source_sku_id),source_spu_id:optional(item.source_spu_id),source_spu_code:optional(item.source_spu_code),product_attribute_1:optional(item.product_attribute_1),product_attribute_2:optional(item.product_attribute_2),product_attribute_3:optional(item.product_attribute_3),sku_custom_attribute:optional(item.sku_custom_attribute),source_payment_status:optional(item.source_payment_status),source_fulfillment_status:optional(item.source_fulfillment_status),virtual_product:optional(item.virtual_product),line_gross:integer(item.lineGrossFils??item.unitListPriceFils*BigInt(item.quantity),'商品原价小计'),actual_price_confirmed:item.actual_price_confirmed===false?0:1,cost_raw_text:optional(item.cost_raw_text),cost_note:optional(item.cost_note),not_sold_separately:item.not_sold_separately?1:0,source_line_revenue:integer(item.source_line_revenue??item.lineRevenueFils,'网站成交金额'),manual_discount:integer(item.manual_discount,'人工优惠'),discount_input_type:item.discount_input_type||'AED',discount_input_value:integer(item.discount_input_value??item.manual_discount??0n,'优惠输入'),created_at:item.created_at||now,updated_at:now};
  }
  storedItemInput(item){return {id:item.id,item_sequence:item.item_sequence,sku_code:item.sku_code,product_name_snapshot:item.product_name_snapshot,quantity:Number(item.quantity),unit_list_price:BigInt(item.unit_list_price),unit_actual_price:BigInt(item.unit_actual_price),line_actual_revenue:BigInt(item.line_revenue),unit_cost_snapshot:bigintOrNull(item.unit_cost_snapshot),needs_review:Boolean(item.needs_review),cost_source:item.cost_source,source_excel_row:item.source_excel_row,source_sku_id:item.source_sku_id,source_spu_id:item.source_spu_id,source_spu_code:item.source_spu_code,product_attribute_1:item.product_attribute_1,product_attribute_2:item.product_attribute_2,product_attribute_3:item.product_attribute_3,sku_custom_attribute:item.sku_custom_attribute,source_payment_status:item.source_payment_status,source_fulfillment_status:item.source_fulfillment_status,virtual_product:item.virtual_product,line_gross:item.line_gross,actual_price_confirmed:Boolean(item.actual_price_confirmed),cost_raw_text:item.cost_raw_text,cost_note:item.cost_note,not_sold_separately:Boolean(item.not_sold_separately),source_line_revenue:item.source_line_revenue,manual_discount:item.manual_discount,discount_input_type:item.discount_input_type||'AED',discount_input_value:item.discount_input_value,created_at:item.created_at};}
  updateItemDiscount(itemId,discount,{reason=null,inputType='AED',inputValue=null,maximumType=null,maximumValue=null}={}){
    const current=this.repository.database.prepare('SELECT * FROM order_items WHERE id=?').get(itemId);if(!current)throw new Error('找不到商品');
    const amount=moneyToFils(discount),gross=BigInt(current.line_gross),quantity=BigInt(current.quantity);if(amount<0n||amount>gross)throw new RangeError('优惠必须在0和商品金额之间');const revenue=gross-amount;if(revenue%quantity!==0n)throw new RangeError('优惠后成交金额无法按商品数量精确计算到分，请调整优惠金额');
    return this.repository.transaction(()=>{const now=this.clock().toISOString(),storedInput=inputValue===null?amount:BigInt(inputValue),sql=this.repository.hasDiscountInputColumns()?'UPDATE order_items SET line_revenue=?,unit_actual_price=?,manual_discount=?,discount_input_type=?,discount_input_value=?,actual_price_confirmed=1,updated_at=? WHERE id=?':'UPDATE order_items SET line_revenue=?,unit_actual_price=?,manual_discount=?,actual_price_confirmed=1,updated_at=? WHERE id=?',args=this.repository.hasDiscountInputColumns()?[integer(revenue,'成交金额'),integer(revenue/quantity,'成交单价'),integer(amount,'优惠金额'),inputType,integer(storedInput,'优惠输入'),now,itemId]:[integer(revenue,'成交金额'),integer(revenue/quantity,'成交单价'),integer(amount,'优惠金额'),now,itemId];this.repository.database.prepare(sql).run(...args);if(maximumType&&maximumValue!==null)this.repository.saveProductDiscountLimit({skuCode:current.sku_code,type:maximumType,value:integer(maximumValue,'极限优惠'),at:now});return this.recalculatePackage(current.package_id,{status:this.repository.getPackage(current.package_id).package_status,note:reason,eventType:'item_discount_updated',eventOldValue:String(current.manual_discount??(BigInt(current.line_gross)-BigInt(current.line_revenue))),eventValue:String(amount)});});
  }
  updatePackageDiscount(packageId,discount,{reason}){
    const current=this.repository.getPackage(packageId);if(!current)throw new Error('找不到包裹');if(typeof reason!=='string'||!reason.trim())throw new TypeError('包裹优惠必须填写修改原因');const items=this.repository.itemsForPackage(packageId),amount=moneyToFils(discount),allocated=allocatePackageDiscount(items,amount),oldAmount=items.reduce((sum,item)=>sum+BigInt(item.line_gross)-BigInt(item.line_revenue),0n);
    return this.repository.transaction(()=>{const now=this.clock().toISOString(),statement=this.repository.database.prepare('UPDATE order_items SET line_revenue=?,unit_actual_price=?,manual_discount=?,actual_price_confirmed=1,updated_at=? WHERE id=?');for(let index=0;index<items.length;index++){const item=items[index],lineRevenue=BigInt(item.line_gross)-allocated[index],quantity=BigInt(item.quantity);statement.run(integer(lineRevenue,'成交金额'),integer(lineRevenue/quantity,'成交单价'),integer(allocated[index],'优惠金额'),now,item.id);}return this.recalculatePackage(packageId,{status:current.package_status,note:reason,eventType:'package_discount_updated',eventOldValue:String(oldAmount),eventValue:String(amount)});});
  }
  updatePackageStatus(packageId,status,{note=null,contactOutcome=null,eventValue=null}={}){validatePackageStatus(status);return this.recalculatePackage(packageId,{status,note,contactOutcome,eventValue,eventType:'package_status_changed'});}
  correctPackageStatus(packageId,status,{note}){validatePackageStatus(status);if(typeof note!=='string'||!note.trim())throw new TypeError('更正状态必须填写原因');return this.recalculatePackage(packageId,{status,note,contactOutcome:null,eventValue:status,eventType:'package_status_corrected'});}
  confirmPackageFee(packageId,{actual_fee,reason,resolution_status,delivery_fee=null,handling_fee=null}){
    return this.recordActualPackageFee(packageId,{actual_fee,reason,resolution_status,delivery_fee,handling_fee,source:'courier',eventType:'package_fee_confirmed'});
  }
  overridePackageFee(packageId,{actual_fee,reason,resolution_status,delivery_fee=null,handling_fee=null}){
    return this.recordActualPackageFee(packageId,{actual_fee,reason,resolution_status,delivery_fee,handling_fee,source:'manual_adjustment',eventType:'package_fee_overridden'});
  }
  recordActualPackageFee(packageId,{actual_fee,reason,resolution_status,delivery_fee=null,handling_fee=null,source,eventType}){
    validatePackageStatus(resolution_status);if(!isRealizedPackageStatus(resolution_status))throw new TypeError('实际费用必须指定签收、拒签或取消结果');if(typeof reason!=='string'||!reason.trim())throw new TypeError('实际费用必须填写确认依据');
    const total=moneyToFils(actual_fee),delivery=delivery_fee===null?total:moneyToFils(delivery_fee),handling=handling_fee===null?0n:moneyToFils(handling_fee);if(total<0n||delivery<0n||handling<0n)throw new TypeError('实际费用不能为负数');if(delivery+handling!==total)throw new TypeError('实际费用组成之和必须等于实际总费用');
    return this.recalculatePackage(packageId,{status:resolution_status,note:reason,eventType,feeConfirmation:{source},manualFee:{totalFeeFils:total,deliveryFeeFils:delivery,handlingFeeFils:handling,finalized:true,overridden:source==='manual_adjustment'}});
  }
  recalculatePackage(packageId,{status,note,eventType,manualFee=null,feeConfirmation=null,contactOutcome=undefined,eventValue=null,eventOldValue=null}){
    const current=this.repository.getPackage(packageId);if(!current)throw new Error('找不到包裹');if(!current.fee_rule_set_id)throw new Error('旧版包裹缺少费用规则快照，必须人工核对');
    const order=this.repository.getOrder(current.order_id),ruleSet=this.rules.feeRuleSet(current.fee_rule_set_id),fees=this.feesFor({ruleSetId:current.fee_rule_set_id,zone:current.delivery_zone,status,projectedFeeSnapshot:current.projected_shipping_fee,manualFee,includeDisabled:true}),sourceItems=this.repository.itemsForPackage(packageId).map(item=>this.storedItemInput(item)),fixedZoneRequired=ruleSet?.fee_mode!=='manual_actual'&&!status.startsWith('cancelled_'),calculated=calculatePackage({items:sourceItems,status,projectedFee:fees.projectedFee,realizedFee:fees.realizedFee,feeFinalized:fees.finalized,packageNeedsReview:current.delivery_zone==='unclassified'&&fixedZoneRequired&&!manualFee}),now=this.clock().toISOString();
    const resolvedContact=contactOutcome===undefined?current.contact_outcome:contactOutcome,isOverride=feeConfirmation?.source==='manual_adjustment',updatedPackage={...current,package_status:status,contact_outcome:resolvedContact,shipping_fee:integer(calculated.realizedFeeFils,'实际运费'),delivery_fee:integer(fees.realizedFee?.deliveryFeeFils??0n,'派送费'),handling_fee:integer(fees.realizedFee?.handlingFeeFils??0n,'出库费'),shipping_fee_finalized:fees.finalized?1:0,
      fee_rule_id:manualFee?null:fees.realizedRule?.id||null,fee_overridden:isOverride?1:0,fee_override_reason:isOverride?note:null,fee_overridden_at:isOverride?now:null,fee_confirmation_source:feeConfirmation?.source||null,fee_confirmed_at:feeConfirmation?now:null,fee_confirmation_note:feeConfirmation?note:null,
      fee_dispute_note:status==='fee_dispute'?note:null,status_updated_at:current.package_status===status&&current.contact_outcome===resolvedContact?current.status_updated_at||current.updated_at:now,updated_at:now};
    const otherPackages=this.repository.listPackages(current.order_id).filter(value=>value.id!==packageId),otherItems=this.repository.listItems(current.order_id).filter(value=>value.package_id!==packageId),summaries=[calculated,...otherPackages.map(value=>this.storedPackageSummary(value,otherItems.filter(item=>item.package_id===value.id)))],exchangeRate=order.exchange_rate_scaled?{rate_scaled:order.exchange_rate_scaled,scale:order.exchange_rate_scale}:null,orderResult=calculateOrder(summaries,{exchangeRate});
    const updatedItems=calculated.items.map(item=>this.itemRecord({item,orderId:current.order_id,packageId,now})),discountAmount=this.repository.database.prepare('SELECT COALESCE(SUM(line_gross-line_revenue),0) amount FROM order_items WHERE order_id=?').get(current.order_id).amount,updatedOrder={id:current.order_id,delivery_status:aggregateOrderDeliveryStatus([updatedPackage,...otherPackages]),discount_amount:discountAmount,profit_status:orderResult.profitStatus,total_profit:integer(orderResult.realizedProfitFils,'实际利润'),projected_profit:integer(orderResult.projectedProfitFils,'预计利润'),realized_profit:integer(orderResult.realizedProfitFils,'实际利润'),profit_review_required:orderResult.profitStatus==='incomplete'?1:0,
      projected_rmb_settlement:integer(orderResult.projectedRmbFen,'预计人民币结算'),realized_rmb_settlement:integer(orderResult.realizedRmbFen,'实际人民币结算'),rmb_settlement_status:orderResult.rmbSettlementStatus,updated_at:now},feeEvent=eventType==='package_fee_overridden'||eventType==='package_fee_confirmed',event={id:this.idFactory(),order_id:current.order_id,package_id:packageId,event_type:eventType,old_value:feeEvent?String(current.shipping_fee):(eventOldValue??current.contact_outcome??current.package_status),new_value:feeEvent?String(updatedPackage.shipping_fee):eventValue||status,event_time:now,note};
    return this.repository.updatePackageFinancials({package:updatedPackage,items:updatedItems,order:updatedOrder,event});
  }
  storedPackageSummary(packageRow,items){
    const mapped=items.map(item=>({lineRevenueFils:BigInt(item.line_revenue),lineCostFils:bigintOrNull(item.line_cost),projectedLineProfitFils:bigintOrNull(item.projected_line_profit),realizedLineProfitFils:bigintOrNull(item.realized_line_profit)}));
    return {status:packageRow.package_status,projectedProfitFils:mapped.every(item=>item.projectedLineProfitFils!==null)?mapped.reduce((sum,item)=>sum+item.projectedLineProfitFils,0n):null,
      realizedProfitFils:mapped.every(item=>item.realizedLineProfitFils!==null)?mapped.reduce((sum,item)=>sum+item.realizedLineProfitFils,0n):null,profitStatus:packageRow.shipping_fee_finalized&&mapped.every(item=>item.realizedLineProfitFils!==null)?'final':items.some(item=>item.needs_review)?'incomplete':'pending',items:mapped};
  }
}
