import ExcelJS from 'exceljs';

const money=value=>value===null||value===undefined?null:Number(value)/100;
const date=value=>{if(!value)return null;const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed;};
const resultLabels={unshipped:'待发货',outbound_processing:'出库中',shipped_pending:'已发货待结果',unreachable:'联系不上',signed:'已签收',refused:'已拒单',cancelled_before_outbound:'出库前取消',cancelled_after_outbound:'出库后取消'};
const profitLabels={final:'最终',waiting_remittance:'等待回款登记',waiting_fee:'等待物流费用',incomplete_cost:'成本不完整',pending_result:'等待包裹结果'};

export function summarizeProfitRows(rows){const unique=status=>new Set(rows.filter(status).map(row=>row.packageId)).size;return {signed:unique(row=>row.packageResult==='signed'),refused:unique(row=>row.packageResult==='refused'),finalProfitFils:rows.filter(row=>row.profitStatus==='final').reduce((sum,row)=>sum+(row.itemProfitFils||0),0),waitingFee:unique(row=>row.profitStatus==='waiting_fee'),incompleteCost:rows.filter(row=>row.profitStatus==='incomplete_cost').length};}

export async function buildProfitWorkbook({report,includePending=false}={}){
  if(!report||!Array.isArray(report.rows))throw new TypeError('利润导出数据无效');const rows=includePending?report.rows:report.rows.filter(row=>row.profitStatus==='final'),summary=summarizeProfitRows(rows),workbook=new ExcelJS.Workbook();workbook.creator='KDocs Inventory Sync';workbook.created=new Date();workbook.modified=new Date();workbook.calcProperties.fullCalcOnLoad=true;
  const detail=workbook.addWorksheet('利润明细',{views:[{state:'frozen',ySplit:1,activeCell:'A2'}]}),headers=['序号','日期','ShopPlus订单号','客户电话（脱敏）','商品编号','商品名称','数量','成本快照AED','实际售价AED','优惠AED','分摊物流费AED','包裹系列','包裹结果','利润状态','商品利润AED','订单确认时间','状态更新时间'];detail.addRow(headers);
  for(const row of rows)detail.addRow([row.sequence,date(row.date),row.orderNo,row.phoneMasked,row.businessCode,row.productName,row.quantity,money(row.costFils),money(row.actualPriceFils),money(row.discountFils),money(row.allocatedShippingFils),row.seriesCode,resultLabels[row.packageResult]||row.packageResult,profitLabels[row.profitStatus]||row.profitStatus,money(row.itemProfitFils),date(row.orderConfirmedAt),date(row.statusUpdatedAt)]);
  detail.autoFilter={from:'A1',to:'Q1'};detail.getRow(1).height=28;detail.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};detail.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1769E0'}};detail.getRow(1).alignment={vertical:'middle',horizontal:'center',wrapText:true};detail.getRow(1).border={bottom:{style:'medium',color:{argb:'FF0E4FAD'}}};
  const widths=[10,13,24,20,16,42,10,16,16,13,18,13,18,18,18,22,22];detail.columns.forEach((column,index)=>{column.width=widths[index];});for(const column of ['B','P','Q'])detail.getColumn(column).numFmt='yyyy-mm-dd hh:mm:ss';for(const column of ['H','I','J','K','O']){detail.getColumn(column).numFmt='0.00';detail.getColumn(column).alignment={horizontal:'right'};}detail.getColumn('F').alignment={wrapText:true,vertical:'top'};detail.eachRow((row,index)=>{if(index>1){row.height=22;if(index%2===0)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF5F8FC'}};}});detail.views=[{state:'frozen',ySplit:1,activeCell:'A2',showGridLines:false}];
  const summarySheet=workbook.addWorksheet('汇总',{views:[{showGridLines:false}]});summarySheet.mergeCells('A1:B1');summarySheet.getCell('A1').value='利润导出汇总';summarySheet.getCell('A1').font={bold:true,size:18,color:{argb:'FFFFFFFF'}};summarySheet.getCell('A1').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1769E0'}};summarySheet.getCell('A1').alignment={vertical:'middle'};summarySheet.getRow(1).height=34;summarySheet.addRows([[],['指标','筛选结果'],['签收数量',summary.signed],['拒单数量',summary.refused],['最终利润AED',money(summary.finalProfitFils)],['等待物流费用数量',summary.waitingFee],['成本不完整数量',summary.incompleteCost],['导出范围',includePending?'包含待确认记录':'仅最终利润'],['明细行数',rows.length]]);summarySheet.getRow(3).font={bold:true,color:{argb:'FFFFFFFF'}};summarySheet.getRow(3).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF344054'}};summarySheet.getColumn('A').width=26;summarySheet.getColumn('B').width=24;summarySheet.getCell('B6').numFmt='0.00';for(let row=4;row<=10;row++)for(let column=1;column<=2;column++)summarySheet.getCell(row,column).border={bottom:{style:'thin',color:{argb:'FFD0D5DD'}}};
  return {workbook,rows,summary};
}

export async function buildProfitWorkbookBuffer(options){const result=await buildProfitWorkbook(options),buffer=await result.workbook.xlsx.writeBuffer();return {...result,buffer};}
