import {createHash,randomUUID} from 'node:crypto';
import {readShopPlusWorkbook,hashShopPlusFile} from './shopplus-excel.mjs';
import {amountToFils,businessCodeCandidates,integerQuantity,mapShopPlusStatus} from './shopplus-fields.mjs';
import {allocateShippingFee} from './profit-calculation.mjs';
import {createCostCatalog} from './cost-catalog.mjs';
import {OrderRepository} from './order-repository.mjs';
import {OrderService} from './order-service.mjs';

const present=value=>value!==undefined&&value!==null&&String(value).trim()!=='';
const string=value=>present(value)?String(value):null;
const issue=(code,details={})=>({code,...details});
const digest=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const signaturePayload=preview=>({fileSha256:preview.fileSha256,sheetName:preview.sheetName,totalRows:preview.totalRows,orders:preview.orders});
const orderExists=(database,orderNo)=>{if(!database)return false;try{return Boolean(database.prepare('SELECT 1 FROM orders WHERE shopplus_order_no=?').get(orderNo));}catch{return false;}};
const subOrderExists=(database,value)=>{if(!database||!value)return false;try{return Boolean(database.prepare('SELECT 1 FROM order_items WHERE shopplus_sub_order_id=?').get(value));}catch{return false;}};
const fileSeen=(database,hash)=>{if(!database)return false;try{return Boolean(database.prepare("SELECT 1 FROM import_batches WHERE file_sha256=? AND status='completed'").get(hash));}catch{return false;}};

function consistent(rows,group,field,{required=false,conflict='warning'}={}){
  const values=rows.map(row=>row[group]?.[field]).filter(present),unique=[...new Set(values.map(value=>String(value)))];
  return {value:values[0]??null,missing:required&&!values.length,conflict:unique.length>1,severity:conflict};
}
function money(rows,field,warnings,blockingErrors){const result=consistent(rows,'order',field,{conflict:'blocking'});if(result.conflict)blockingErrors.push(issue('ORDER_AMOUNT_CONFLICT',{field,rows:rows.map(row=>row.sourceRow)}));if(!present(result.value))return null;try{return amountToFils(result.value);}catch{blockingErrors.push(issue('AMOUNT_INVALID',{field,rows:rows.map(row=>row.sourceRow)}));return null;}}
function customer(rows,warnings,blockingErrors){
  const fields=['firstName','lastName','fullName','phone','email','country','province','city','street','residence','postalCode','doorNumber'],shipping={},billing={};let fallback=false;
  for(const field of fields){const ship=consistent(rows,'shipping',field,{conflict:'blocking'}),bill=consistent(rows,'billing',field,{conflict:'blocking'});if(ship.conflict)blockingErrors.push(issue('SHIPPING_CUSTOMER_CONFLICT',{field,rows:rows.map(row=>row.sourceRow)}));if(bill.conflict)warnings.push(issue('BILLING_CUSTOMER_CONFLICT',{field}));billing[field]=string(bill.value);if(present(ship.value))shipping[field]=String(ship.value);else if(present(bill.value)){shipping[field]=String(bill.value);fallback=true;warnings.push(issue('BILLING_FALLBACK',{field}));}else shipping[field]=null;}
  return {shipping,billing,fallback};
}
function parseItem(row,costCatalog,warnings,blockingErrors){
  const name=String(row.product.productName??'');if(!name.trim())blockingErrors.push(issue('PRODUCT_NAME_MISSING',{row:row.sourceRow}));let quantity=null,unitListPriceFils=null;
  try{quantity=integerQuantity(row.product.quantity);}catch{blockingErrors.push(issue('QUANTITY_INVALID',{row:row.sourceRow}));}
  try{unitListPriceFils=amountToFils(row.product.unitPrice,{allowNull:false});}catch{blockingErrors.push(issue('PRODUCT_PRICE_INVALID',{row:row.sourceRow}));}
  const candidates=businessCodeCandidates(row.product),cost=costCatalog.resolve({candidates,productName:name});let businessCode=cost.businessCode||candidates[0]?.value||null,needsReview=false;
  if(!businessCode){warnings.push(issue('BUSINESS_CODE_MISSING',{row:row.sourceRow}));needsReview=true;}
  if(cost.status==='conflict'){blockingErrors.push(issue('COST_MAPPING_CONFLICT',{row:row.sourceRow,businessCode}));needsReview=true;}
  else if(cost.costFils===null){warnings.push(issue(cost.costStatus==='ambiguous'?'COST_FORMAT_AMBIGUOUS':'COST_MISSING',{row:row.sourceRow,businessCode}));needsReview=true;}
  if(cost.annotatedCost)warnings.push(issue('annotated_cost',{row:row.sourceRow,businessCode}));
  return {sourceRow:row.sourceRow,shopplusSubOrderId:string(row.order.subOrderId),businessCode,codeSource:candidates.find(value=>value.value===businessCode)?.source||(cost.businessCode?'confirmed_mapping':null),productName:name,quantity,unitListPriceFils,costFils:cost.costFils,costSource:cost.costSource,costRawText:cost.costRawText,costNote:cost.costNote,annotatedCost:Boolean(cost.annotatedCost),notSoldSeparately:Boolean(cost.notSoldSeparately),businessRuleNeedsReview:false,
    sourceSkuId:string(row.product.skuId),sourceSpuId:string(row.product.spuId),sourceSpuCode:string(row.product.spuCode),productSku:string(row.product.productSku),attribute1:string(row.product.attribute1),attribute2:string(row.product.attribute2),attribute3:string(row.product.attribute3),skuCustomAttribute:string(row.product.skuCustomAttribute),sourcePaymentStatus:string(row.product.paymentStatus),sourceFulfillmentStatus:string(row.product.fulfillmentStatus),virtualProduct:string(row.product.virtualProduct),identityNeedsReview:needsReview,needsReview};
}
function applyAmounts(order,warnings,blockingErrors){
  const grossAvailable=order.items.every(item=>item.quantity&&item.unitListPriceFils!==null);if(!grossAvailable)return {amountMismatch:true,discountNeedsConfirmation:false};
  for(const item of order.items)item.lineGrossFils=item.unitListPriceFils*item.quantity;
  const gross=order.items.reduce((sum,item)=>sum+item.lineGrossFils,0),productTotal=order.amounts.productTotal;
  let amountMismatch=false;if(productTotal===null||gross!==productTotal){warnings.push(issue('PRODUCT_TOTAL_MISMATCH',{grossFils:gross,productTotalFils:productTotal}));amountMismatch=true;}
  const charges=['customerShippingFee','taxAmount','shippingInsurance','tipAmount'].reduce((sum,key)=>sum+(order.amounts[key]||0),0),standard=order.amounts.discountAmount||0,fixed=order.amounts.fixedDiscountAmount||0,orderTotal=order.amounts.orderTotal;
  const discountCandidates=[0,standard,fixed,standard+fixed].filter((value,index,array)=>array.indexOf(value)===index),matching=orderTotal===null||productTotal===null?[]:discountCandidates.filter(value=>productTotal-value+charges===orderTotal);
  let selectedDiscount=0,discountNeedsConfirmation=false;
  if(matching.length===1){selectedDiscount=matching[0];discountNeedsConfirmation=selectedDiscount>0;}else if(matching.length>1){selectedDiscount=matching[0];if(standard||fixed){warnings.push(issue('DISCOUNT_SEMANTICS_AMBIGUOUS'));discountNeedsConfirmation=true;}}else{warnings.push(issue('ORDER_TOTAL_MISMATCH'));amountMismatch=true;discountNeedsConfirmation=Boolean(standard||fixed);selectedDiscount=Math.min(standard+fixed,gross);}
  if(selectedDiscount<0||selectedDiscount>gross){blockingErrors.push(issue('DISCOUNT_OUT_OF_RANGE'));return {amountMismatch:true,discountNeedsConfirmation:true};}
  const shares=allocateShippingFee(order.items.map(item=>({lineRevenueFils:BigInt(item.lineGrossFils)})),BigInt(selectedDiscount));
  order.items.forEach((item,index)=>{item.allocatedDiscountFils=Number(shares[index]);item.lineActualRevenueFils=item.lineGrossFils-item.allocatedDiscountFils;if(item.lineActualRevenueFils%item.quantity!==0){blockingErrors.push(issue('UNIT_ACTUAL_PRICE_NOT_DIVISIBLE',{row:item.sourceRow}));item.unitActualPriceFils=null;}else item.unitActualPriceFils=item.lineActualRevenueFils/item.quantity;item.actualPriceConfirmed=!discountNeedsConfirmation&&!amountMismatch;item.priceNeedsReview=!item.actualPriceConfirmed;item.needsReview=item.identityNeedsReview||item.businessRuleNeedsReview||item.priceNeedsReview;});
  return {amountMismatch,discountNeedsConfirmation,selectedDiscountFils:selectedDiscount,grossFils:gross,chargesFils:charges};
}

function orderPreview(orderNo,rows,{costCatalog,database,globalSubOrders}){
  const warnings=[],blockingErrors=[],statusValue=consistent(rows,'order','orderStatus').value,status=mapShopPlusStatus(statusValue);if(status.warning)warnings.push(issue(status.warning));
  const customers=customer(rows,warnings,blockingErrors),items=[],localSubOrders=new Map();let duplicateRows=0;
  for(const row of rows){const sub=String(row.order.subOrderId??'').trim(),fingerprint=digest({order:orderNo,sub,product:row.product});if(sub&&localSubOrders.has(sub)){if(localSubOrders.get(sub)===fingerprint){warnings.push(issue('DUPLICATE_ITEM_ROW_SKIPPED',{row:row.sourceRow}));duplicateRows++;continue;}blockingErrors.push(issue('SUB_ORDER_CONFLICT',{row:row.sourceRow}));continue;}if(sub)localSubOrders.set(sub,fingerprint);
    if(sub&&globalSubOrders.has(sub)&&globalSubOrders.get(sub)!==orderNo)blockingErrors.push(issue('SUB_ORDER_USED_BY_MULTIPLE_ORDERS',{row:row.sourceRow}));if(sub)globalSubOrders.set(sub,orderNo);if(subOrderExists(database,sub))blockingErrors.push(issue('SUB_ORDER_ALREADY_EXISTS',{row:row.sourceRow}));items.push(parseItem(row,costCatalog,warnings,blockingErrors));}
  const distinctBusinessCodes=new Set(items.map(item=>item.businessCode).filter(Boolean));if(distinctBusinessCodes.size===1){for(const item of items.filter(value=>value.notSoldSeparately)){item.businessRuleNeedsReview=true;item.needsReview=true;warnings.push(issue('NOT_SOLD_SEPARATELY_SINGLE_PRODUCT',{row:item.sourceRow,businessCode:item.businessCode}));}}
  const amounts={orderTotal:money(rows,'orderTotal',warnings,blockingErrors),productTotal:money(rows,'productTotal',warnings,blockingErrors),discountAmount:money(rows,'discountAmount',warnings,blockingErrors)??0,customerShippingFee:money(rows,'customerShippingFee',warnings,blockingErrors)??0,taxAmount:money(rows,'taxAmount',warnings,blockingErrors)??0,shippingInsurance:money(rows,'shippingInsurance',warnings,blockingErrors)??0,tipAmount:money(rows,'tipAmount',warnings,blockingErrors)??0,fixedDiscountAmount:money(rows,'fixedDiscountAmount',warnings,blockingErrors)??0};
  const order={orderNo,sourceRows:rows.map(row=>row.sourceRow),siteId:string(consistent(rows,'order','siteId').value),orderSequence:string(consistent(rows,'order','orderSequence').value),createdAt:string(consistent(rows,'order','createdAt').value),paidAt:string(consistent(rows,'order','paidAt').value),shippedAt:string(consistent(rows,'order','shippedAt').value),cancelledAt:string(consistent(rows,'order','cancelledAt').value),rawOrderStatus:string(statusValue),packageStatus:status.packageStatus,statusNeedsReview:status.needsReview,aftersaleStatus:string(consistent(rows,'order','aftersaleStatus').value),repaidStatus:string(consistent(rows,'order','repaidStatus').value),channelSource:string(consistent(rows,'order','channelSource').value),paymentMethod:string(consistent(rows,'order','paymentMethod').value),currency:string(consistent(rows,'order','currency').value)||'AED',buyerNote:string(consistent(rows,'order','buyerNote').value),orderNote:string(consistent(rows,'order','orderNote').value),websiteDomain:string(consistent(rows,'order','websiteDomain').value),trackingNumber:string(consistent(rows,'logistics','trackingNumber').value),logisticsCompany:string(consistent(rows,'logistics','logisticsCompany').value),shipping:customers.shipping,billing:customers.billing,customerDataFallback:customers.fallback,amounts,items,warnings,blockingErrors,duplicateRows,alreadyExists:orderExists(database,orderNo)};
  if(order.alreadyExists)warnings.push(issue('ORDER_ALREADY_EXISTS'));const amountResult=applyAmounts(order,warnings,blockingErrors);order.amountCheck=amountResult;
  order.needsReview=status.needsReview||customers.fallback||items.some(item=>item.needsReview)||amountResult.amountMismatch||amountResult.discountNeedsConfirmation;order.canImport=!blockingErrors.length&&!order.alreadyExists;return order;
}

export async function previewShopPlusExcel(filePath,{database=null,costCatalog=createCostCatalog([]),limits}={}){
  const workbook=await readShopPlusWorkbook(filePath,{limits}),groups=new Map(),missingOrders=[];for(const row of workbook.rows){const orderNo=String(row.order.orderNo??'').trim();if(!orderNo){missingOrders.push(row);continue;}if(!groups.has(orderNo))groups.set(orderNo,[]);groups.get(orderNo).push(row);}
  const globalSubOrders=new Map(),orders=[...groups].map(([orderNo,rows])=>orderPreview(orderNo,rows,{costCatalog,database,globalSubOrders}));for(const row of missingOrders)orders.push({orderNo:null,sourceRows:[row.sourceRow],items:[],warnings:[],blockingErrors:[issue('ORDER_NUMBER_MISSING',{row:row.sourceRow})],needsReview:true,canImport:false,alreadyExists:false,duplicateRows:0});
  const orderWarnings=orders.flatMap(order=>order.warnings),catalogWarnings=(costCatalog.warnings||[]).filter(catalogWarning=>!orderWarnings.some(orderWarning=>orderWarning.code===catalogWarning.code&&orderWarning.businessCode===catalogWarning.businessCode)),allWarnings=[...workbook.warnings,...catalogWarnings,...orderWarnings],allBlocking=orders.flatMap(order=>order.blockingErrors),allItems=orders.flatMap(order=>order.items),amountWarningCodes=new Set(['PRODUCT_TOTAL_MISMATCH','ORDER_TOTAL_MISMATCH','DISCOUNT_SEMANTICS_AMBIGUOUS']),summary={totalRows:workbook.totalRows,validOrders:orders.filter(order=>order.orderNo).length,itemRows:allItems.length,multiItemOrders:orders.filter(order=>order.items.length>1).length,duplicateOrders:orders.reduce((sum,order)=>sum+order.duplicateRows,0),existingOrders:orders.filter(order=>order.alreadyExists).length,directImportOrders:orders.filter(order=>order.canImport&&!order.needsReview).length,reviewOrders:orders.filter(order=>order.canImport&&order.needsReview).length,blockedOrders:orders.filter(order=>!order.canImport&&!order.alreadyExists).length,recognizedBusinessCodes:allItems.filter(item=>Boolean(item.businessCode)).length,missingBusinessCodes:allItems.filter(item=>!item.businessCode).length,matchedCosts:allItems.filter(item=>item.costFils!==null).length,missingCosts:allItems.filter(item=>item.costFils===null).length,annotatedCosts:allItems.filter(item=>item.annotatedCost).length,annotatedCostWarnings:allWarnings.filter(warning=>warning.code==='annotated_cost').length,notSoldSeparatelyReviews:allItems.filter(item=>item.businessRuleNeedsReview).length,amountWarnings:allWarnings.filter(warning=>amountWarningCodes.has(warning.code)).length,amountMismatches:orders.filter(order=>order.amountCheck?.amountMismatch).length,customerConflicts:orders.filter(order=>order.blockingErrors.some(error=>error.code==='SHIPPING_CUSTOMER_CONFLICT')).length,unknownStatuses:orders.filter(order=>order.warnings.some(warning=>warning.code==='ORDER_STATUS_UNKNOWN')).length,blockingErrors:allBlocking.length};
  const preview={schemaVersion:1,filePath:workbook.filePath,filename:workbook.filename,fileSha256:workbook.fileSha256,sheetName:workbook.sheetName,totalRows:workbook.totalRows,alreadyImportedFile:fileSeen(database,workbook.fileSha256),summary,orders,warnings:allWarnings,blockingErrors:allBlocking,createdAt:new Date().toISOString()};preview.previewSignature=digest(signaturePayload(preview));return preview;
}

function checkPreview(preview){if(!preview||preview.schemaVersion!==1||preview.previewSignature!==digest(signaturePayload(preview)))throw Object.assign(new Error('导入预览已被修改，请重新预览'),{code:'SHOPPLUS_PREVIEW_INVALID'});}

export function applyShopPlusReviewEdits(preview,{orderNo,items=[]}={}){
  checkPreview(preview);const next=structuredClone(preview),order=next.orders.find(value=>value.orderNo===orderNo);if(!order)throw Object.assign(new Error('找不到需要核对的订单'),{code:'SHOPPLUS_REVIEW_ORDER_NOT_FOUND'});if(!Array.isArray(items))throw new TypeError('商品核对内容必须是数组');
  for(const edit of items){const sourceRow=Number(edit?.sourceRow),item=order.items.find(value=>value.sourceRow===sourceRow);if(!item)throw Object.assign(new Error('找不到需要核对的商品'),{code:'SHOPPLUS_REVIEW_ITEM_NOT_FOUND'});
    if(edit.businessCode!==undefined){const value=String(edit.businessCode).trim().toUpperCase();if(!value||value.length>80||!/^[A-Z0-9][A-Z0-9._-]*$/u.test(value))throw new TypeError('业务商品编号格式无效');item.businessCode=value;item.codeSource='manual_review';}
    if(edit.costAed!==undefined&&String(edit.costAed).trim()!==''){const raw=String(edit.costAed).trim();const cost=amountToFils(raw,{allowNull:false});if(!Number.isSafeInteger(cost)||cost<0)throw new TypeError('成本必须是安全范围内的非负AED金额');if(item.costFils===null||cost!==item.costFils){item.costFils=cost;item.costSource='manual_review';item.costRawText=raw;item.costNote=null;item.annotatedCost=false;item.notSoldSeparately=false;}}
    item.identityNeedsReview=!item.businessCode||item.costFils===null;item.needsReview=item.identityNeedsReview||item.businessRuleNeedsReview||item.priceNeedsReview;
  }
  order.needsReview=order.statusNeedsReview||order.customerDataFallback||order.items.some(item=>item.needsReview)||order.amountCheck?.amountMismatch||order.amountCheck?.discountNeedsConfirmation;next.previewSignature=digest(signaturePayload(next));return next;
}

export async function commitShopPlusImport(preview,{database,confirmReviewOrderNos=[],clock=()=>new Date(),idFactory=randomUUID,failAfterOrders=null}={}){
  if(!database)throw new TypeError('确认导入必须提供订单数据库');checkPreview(preview);if(await hashShopPlusFile(preview.filePath)!==preview.fileSha256)throw Object.assign(new Error('Excel文件在预览后已改变'),{code:'SHOPPLUS_FILE_CHANGED'});
  const confirmed=new Set(confirmReviewOrderNos),repository=new OrderRepository(database),service=new OrderService(repository,{clock,idFactory}),eligible=preview.orders.filter(order=>order.canImport&&!order.alreadyExists&&(!order.needsReview||confirmed.has(order.orderNo))).sort((left,right)=>String(left.createdAt||'').localeCompare(String(right.createdAt||''))||(Math.min(...left.sourceRows)-Math.min(...right.sourceRows))||String(left.orderNo||'').localeCompare(String(right.orderNo||''))),skipped=preview.orders.length-eligible.length,batchId=idFactory(),now=clock().toISOString();
  try{return repository.transaction(()=>{database.prepare(`INSERT INTO import_batches(id,source,original_filename,file_sha256,status,total_rows,valid_orders,imported_orders,skipped_orders,failed_orders,warning_count,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(batchId,'shopplus_excel',preview.filename,preview.fileSha256,'processing',preview.totalRows,preview.summary.validOrders,0,skipped,0,preview.warnings.length,now);
      const imported=[];for(const order of eligible){const reviewConfirmed=confirmed.has(order.orderNo),items=order.items.map(item=>({shopplus_sub_order_id:item.shopplusSubOrderId,sku_code:item.businessCode,product_name_snapshot:item.productName,quantity:item.quantity,unit_list_price:BigInt(item.unitListPriceFils),unit_actual_price:BigInt(item.unitActualPriceFils),line_actual_revenue:BigInt(item.lineActualRevenueFils),unit_cost_snapshot:item.costFils===null?null:BigInt(item.costFils),cost_source:item.costSource,cost_raw_text:item.costRawText,cost_note:item.costNote,not_sold_separately:item.notSoldSeparately,needs_review:item.identityNeedsReview||item.businessRuleNeedsReview||order.statusNeedsReview,package_status:order.packageStatus,source_excel_row:item.sourceRow,source_sku_id:item.sourceSkuId,source_spu_id:item.sourceSpuId,source_spu_code:item.sourceSpuCode,product_attribute_1:item.attribute1,product_attribute_2:item.attribute2,product_attribute_3:item.attribute3,sku_custom_attribute:item.skuCustomAttribute,source_payment_status:item.sourcePaymentStatus,source_fulfillment_status:item.sourceFulfillmentStatus,virtual_product:item.virtualProduct,lineGrossFils:BigInt(item.lineGrossFils),actual_price_confirmed:item.actualPriceConfirmed||reviewConfirmed}));
        const record=service.createOrder({source:'shopplus_excel',shopplus_order_no:order.orderNo,order_sequence:/^\d+$/.test(order.orderSequence||'')&&Number.isSafeInteger(Number(order.orderSequence))?Number(order.orderSequence):null,shopplus_order_sequence_text:order.orderSequence,currency:order.currency,order_status:order.rawOrderStatus||'unknown',payment_status:order.items[0]?.sourcePaymentStatus||'unknown',fulfillment_status:order.items[0]?.sourceFulfillmentStatus||'unknown',delivery_status:order.packageStatus,customer_first_name:order.shipping.firstName,customer_last_name:order.shipping.lastName,customer_full_name:order.shipping.fullName,customer_phone:order.shipping.phone,customer_email:order.shipping.email,country:order.shipping.country,province:order.shipping.province,city:order.shipping.city,street:order.shipping.street,residence:order.shipping.residence,postal_code:order.shipping.postalCode,door_number:order.shipping.doorNumber,buyer_note:order.buyerNote,order_note:order.orderNote,shopplus_created_at:order.createdAt,shopplus_paid_at:order.paidAt,shopplus_shipped_at:order.shippedAt,shopplus_cancelled_at:order.cancelledAt,order_total:order.amounts.orderTotal===null?null:BigInt(order.amounts.orderTotal),product_total:order.amounts.productTotal===null?null:BigInt(order.amounts.productTotal),discount_amount:BigInt(order.amounts.discountAmount),customer_shipping_fee:BigInt(order.amounts.customerShippingFee),tax_amount:BigInt(order.amounts.taxAmount),shipping_insurance:BigInt(order.amounts.shippingInsurance),tip_amount:BigInt(order.amounts.tipAmount),fixed_discount_amount:BigInt(order.amounts.fixedDiscountAmount),import_batch_id:batchId,source_file_name:preview.filename,source_file_sha256:preview.fileSha256,imported_at:now,shopplus_site_id:order.siteId,aftersale_status:order.aftersaleStatus,repaid_status:order.repaidStatus,channel_source:order.channelSource,payment_method:order.paymentMethod,website_domain:order.websiteDomain,customer_data_fallback:order.customerDataFallback,billing_first_name:order.billing.firstName,billing_last_name:order.billing.lastName,billing_full_name:order.billing.fullName,billing_phone:order.billing.phone,billing_email:order.billing.email,billing_country:order.billing.country,billing_province:order.billing.province,billing_city:order.billing.city,billing_street:order.billing.street,billing_residence:order.billing.residence,billing_postal_code:order.billing.postalCode,billing_door_number:order.billing.doorNumber,tracking_number:order.trackingNumber,logistics_company:order.logisticsCompany,items});
        imported.push(record.id);if(failAfterOrders!==null&&imported.length>=failAfterOrders)throw new Error('测试注入的整批回滚故障');}
      database.prepare("UPDATE import_batches SET status='completed',imported_orders=?,completed_at=? WHERE id=?").run(imported.length,clock().toISOString(),batchId);return {batchId,status:'completed',imported:imported.length,skipped,blocked:preview.summary.blockedOrders,needsReview:preview.orders.filter(order=>order.canImport&&order.needsReview&&!confirmed.has(order.orderNo)).length,failed:0};});
  }catch(error){try{database.prepare(`INSERT INTO import_batches(id,source,original_filename,file_sha256,status,total_rows,valid_orders,imported_orders,skipped_orders,failed_orders,warning_count,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(idFactory(),'shopplus_excel',preview.filename,preview.fileSha256,'failed',preview.totalRows,preview.summary.validOrders,0,skipped,eligible.length,preview.warnings.length,now,clock().toISOString());}catch{}throw error;}
}
